// packages/survey-react-ui/src/buttongroup-dropdown.tsx
import * as React from "react";
import { QuestionButtonGroupModel, RendererFactory } from "survey-core";
import { SurveyQuestionDropdownBase } from "./dropdown-base";
import { ReactQuestionFactory } from "./reactquestion_factory";

export class SurveyQuestionButtonGroupDropdown extends SurveyQuestionDropdownBase<QuestionButtonGroupModel> {
  constructor(props: any) {
    super(props);
  }
  protected renderElement(): React.JSX.Element {
    const cssClasses = this.question.cssClasses;
    const select = this.renderSelect(cssClasses);
    return (
      <div className={this.question.cssClasses.rootDropdown}>
        {select}
      </div>
    );
  }
}
ReactQuestionFactory.Instance.registerQuestion(
  "sv-buttongroup-dropdown",
  (props) => {
    return React.createElement(SurveyQuestionButtonGroupDropdown, props);
  }
);

RendererFactory.Instance.registerRenderer(
  "buttongroup",
  "dropdown",
  "sv-buttongroup-dropdown"
);

// packages/survey-vue3-ui/src/buttongroup/ButtonGroupDropdown.vue
<template>
    <div :class="question.cssClasses.rootDropdown" ref="root">
      <SvComponent :is="'sv-dropdown'" :question="question"></SvComponent>
    </div>
  </template>
  
  <script lang="ts" setup>
  import SvComponent from "@/SvComponent.vue";
  import { ref } from "vue";
  import { useQuestion } from "../base";
  defineOptions({ inheritAttrs: false });
  const props = defineProps<{ question: QuestionButtonGroupModel }>();
  const root = ref(null);
  useQuestion(props, root);
  </script>
  
  <script lang="ts">
  import { QuestionButtonGroupModel, RendererFactory } from "survey-core";
  RendererFactory.Instance.registerRenderer(
    "buttongroup",
    "dropdown",
    "sv-buttongroup-dropdown"
  );
  </script>
