// packages/survey-react-ui/src/components/scroll.tsx
import * as React from "react";
import { ReactElementFactory } from "../element-factory";
import { ScrollViewModel } from "survey-core";

interface IScrollComponentProps {
  children: React.ReactNode;
  disabled?: boolean;
  keyboardReachable?: boolean;
  onInnerHeightChanged?: (hasScroll: boolean) => void;
}
export class Scroll extends React.Component<IScrollComponentProps, any> {
  private model: ScrollViewModel;
  private rootRef: React.RefObject<HTMLDivElement>;
  constructor(props: any) {
    super(props);
    this.rootRef = React.createRef();
    this.model = new ScrollViewModel();
    this.model.onInnerHeightChanged = (hasScroll: boolean) => {
      if (!!this.props.onInnerHeightChanged) {
        this.props.onInnerHeightChanged(hasScroll);
      }
    };
  }
  componentDidMount() {
    const container = this.rootRef.current;
    if (!container) return;
    this.model.setRootElement(container);
  }
  componentWillUnmount() {
    this.model.unsubscribeRootElement();
    this.model.setRootElement(undefined);
  }

  render(): React.JSX.Element {
    return this.props.disabled ?
      <>{this.props.children}</> :
      <div ref={this.rootRef} className="sv-scroll__wrapper">
        <div className="sv-scroll__scroller sv-drag-target-skipped" tabIndex={this.props.keyboardReachable ? 0 : undefined} onScroll={() => this.model.onScrollContainer()}>
          <div className="sv-scroll__container">
            {this.props.children}
          </div>
        </div>
        <div className="sv-scroll__scrollbar" onScroll={() => this.model.onScrollScrollbar()}>
          <div className="sv-scroll__scrollbar-sizer">
          </div>
        </div>
      </div>;
  }
}
ReactElementFactory.Instance.registerElement("svc-scroll", (props) => {
  return React.createElement(
    Scroll,
    props as IScrollComponentProps
  );
});

// packages/survey-vue3-ui/src/components/Scroll.vue
<template>
  <slot v-if="!!props.disabled" />
  <div ref="root" class="sv-scroll__wrapper" v-else>
    <div
      class="sv-scroll__scroller sv-drag-target-skipped"
      :tabindex="props.keyboardReachable ? 0 : undefined"
      @scroll="() => model.onScrollContainer()"
    >
      <div class="sv-scroll__container">
        <slot />
      </div>
    </div>
    <div class="sv-scroll__scrollbar" @scroll="() => model.onScrollScrollbar()">
      <div class="sv-scroll__scrollbar-sizer"></div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { ScrollViewModel } from "survey-core";
import { onMounted, onUnmounted, ref } from "vue";
const props = defineProps<{ disabled: any, keyboardReachable?: boolean, onInnerHeightChanged?: (hasScroll: boolean) => void }>();
const model = new ScrollViewModel();
model.onInnerHeightChanged = (hasScroll: boolean) => {
  if (props.onInnerHeightChanged) {
    props.onInnerHeightChanged(hasScroll);
  }
};

const root = ref<HTMLDivElement>();
onMounted(() => {
  model.setRootElement(root.value as HTMLDivElement);
});
onUnmounted(() => {
  model.setRootElement(undefined as any);
  model.unsubscribeRootElement();
});
</script>
