// packages/survey-angular-ui/src/components/text-area/text-area.component.ts
import { Component, Input } from "@angular/core";
import { TextAreaModel } from "survey-core";
import { AngularComponentFactory } from "../../component-factory";
import { EmbeddedViewContentComponent } from "../../embedded-view-content.component";

@Component({
  selector: "sv-text-area",
  templateUrl: "./text-area.component.html"
})
export class TextAreaComponent extends EmbeddedViewContentComponent {
  @Input() model!: TextAreaModel;

  get value() {
    return this.model.getTextValue();
  }
}

AngularComponentFactory.Instance.registerComponent("sv-text-area", TextAreaComponent);
<ng-template #template>
<div [class]="model.getCssClasses().root" (click)="onContainerClick($event)">
    <textarea
    [readonly]="model.isReadOnlyAttr"
    [disabled]="model.isDisabledAttr"
    [id]="model.id"
    [attr.maxlength]="model.maxLength"
    [attr.cols]="model.cols"
    [attr.rows]="model.rows"
    [attr.placeholder]="model.placeholder"
    [class]="model.getCssClasses().control"
    [value]="value"
    (input)="model.onTextAreaInput($event)"
    (keydown)="model.onTextAreaKeyDown($event)"
    (focus)="model.onTextAreaFocus($event)"
    (blur)="model.onTextAreaBlur($event)"
    (change)="model.onTextAreaChange($event)"
    [attr.aria-required]="model.ariaRequired"
    [attr.aria-label]="model.ariaLabel"
    [attr.aria-labelledby]="model.ariaLabelledBy"
    [attr.aria-describedby]="model.ariaDescribedBy"
    [attr.aria-invalid]="model.ariaInvalid"
    [attr.aria-errormessage]="model.ariaErrormessage"
    [style.resize]="'none'"
    #contentElement></textarea>
    <div *ngIf="model.characterCounter" :class="cssClasses.group">
      <sv-ng-character-counter
        [counter]="model.characterCounter"
        [remainingCharacterCounter]="$any(model.getCssClasses().characterCounter)">
      </sv-ng-character-counter>
    </div>
    <div *ngIf="model.question.resizeStyle !== 'none'" [class]="model.getCssClasses().grip" #anchorRef>
      <svg [iconName]="$any(model.getCssClasses().gripIconId)" [size]="'auto'" sv-ng-svg-icon></svg>
    </div>
</div>
</ng-template>

// packages/survey-vue3-ui/src/components/TextArea.vue
<template>
  <div :class="cssClasses.root" @click="onContainerClick" :ref="(el)=>getRef(el as HTMLTextAreaElement)">
    <textarea
      ref="inputRef"
      :readonly="model.isReadOnlyAttr"
      :disabled="model.isDisabledAttr"
      :value="value"
      :id="model.id"
      :maxlength="model.maxLength"
      :cols="model.cols"
      :rows="model.rows"
      :placeholder="model.placeholder"
      :class="cssClasses.control"
      @blur="
        (e) => {
          model.onTextAreaBlur(e);
        }
      "
      @focus="
        (e) => {
          model.onTextAreaFocus(e);
        }
      "
      @change="
        (e) => {
          model.onTextAreaChange(e);
        }
      "
      @input="
        (e) => {
          model.onTextAreaInput(e);
        }
      "
      @keydown="
        (e) => {
          model.onTextAreaKeyDown(e);
        }
      "
      :aria-required="model.ariaRequired"
      :aria-label="model.ariaLabel"
      :aria-labelledby="model.ariaLabelledBy"
      :aria-describedby="model.ariaDescribedBy"
      :aria-invalid="model.ariaInvalid"
      :aria-errormessage="model.ariaErrormessage"
      :style="{ resize: 'none' }"
    ></textarea>
    <div v-if="model.characterCounter" :class="cssClasses.group">
      <SvComponent :is="'sv-character-counter'"
        :counter="model.characterCounter"
        :remainingCharacterCounter="cssClasses.characterCounter">
      </SvComponent>
    </div>
    <div v-if="model.question.resizeStyle !== 'none'" :class="cssClasses.grip" ref="anchorRef">
      <SvComponent :is="'sv-svg-icon'" :iconName="cssClasses.gripIconId" :size="'auto'"></SvComponent>
    </div>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { ResizeManager, type TextAreaModel } from "survey-core";
import { computed, onMounted, onUpdated, onUnmounted, ref } from "vue";

const props = defineProps<{ model: TextAreaModel, getRef?: (element: HTMLElement) => void }>();
const anchorRef = ref<HTMLDivElement>();
const inputRef = ref<HTMLTextAreaElement>();
const getRef = function (element: HTMLTextAreaElement) {
  if (props.getRef) props.getRef(element);
};
const value = computed(() => props.model.getTextValue() || "");
const cssClasses = computed(() => {
  return props.model.getCssClasses()
});
const onContainerClick = () => {
  inputRef.value?.focus();
} 
let resizeManager: ResizeManager;
onMounted(() => {
  if (anchorRef.value && inputRef.value && props.model.question.resizeStyle !== "none") {
      resizeManager = new ResizeManager(anchorRef.value, inputRef.value, props.model.question.resizeStyle);
  }
  if(inputRef.value) {
    props.model.setElement(inputRef.value);
  }
});
onUpdated(() => {
  if(inputRef.value) {
    props.model.setElement(inputRef.value);
  }
});
onUnmounted(() => {
  props.model.resetElement();
  resizeManager?.dispose();
});
</script>
