// packages/survey-vue3-ui/src/components/SingleInputSummary.vue
<template>
    <div v-if="!summary.isEmpty()" :class="css.summary">
      <div v-for="(item, index) in summary.items" :key="index" :class="css.summaryRow">
        <div :class="css.summaryRowContent">
          <SvComponent :is="'survey-string'" :locString="item.locText" />
        </div>
        <div :class="css.summaryRowActions">
          <button
            v-if="item.btnEdit"
            :class="css.summaryRowActionEdit"
            @click="item.btnEdit.action()"
            :title="item.btnEdit.title"
          >
            <SvComponent :is="'sv-svg-icon'" iconName="icon-editsmall-16x16" size="auto" />
          </button>
          <button
            v-if="item.showRemove && item.btnRemove"
            :class="css.summaryRowActionDelete"
            @click="item.btnRemove.action()"
            :title="item.btnRemove.title"
          >
            <SvComponent :is="'sv-svg-icon'" iconName="icon-delete-16x16" size="auto" />
          </button>
        </div>
      </div>
    </div>
    <div v-else>
      <SvComponent
        v-if="true"
        :is="'survey-placeholder-' + summary.question.getTemplate()"
        :cssClasses="css"
        :question="summary.question"
      />
      <div v-else>
        <SvComponent :is="'survey-string'" :locString="summary.noEntry" />
      </div>
    </div>
</template>

<script lang="ts" setup>
import { QuestionSingleInputSummary } from "survey-core";
import SvComponent from "@/SvComponent.vue";

defineProps<{
  summary: QuestionSingleInputSummary;
  css: any;
}>();
</script>

// packages/survey-angular-ui/src/components/single-input-summary/single-input-summary.component.ts
import { Component, Input } from '@angular/core';
import { BaseAngular } from '../../base-angular';
import { QuestionSingleInputSummary } from 'survey-core';

@Component({
  selector: 'sv-single-input-summary',
  templateUrl: './single-input-summary.component.html'
})
export class SingleInputSummaryComponent extends BaseAngular<any> {
  @Input() summary!: QuestionSingleInputSummary;
  @Input() css!: any;

  protected getModel(): any {
    return this.summary;
  }
} 
<div *ngIf="!summary.isEmpty()" [class]="css.summary">
  <div *ngFor="let item of summary.items; let index = index" [class]="css.summaryRow">
    <div [class]="css.summaryRowContent">
      <sv-ng-string [model]="item.locText"></sv-ng-string>
    </div>
    <div [class]="css.summaryRowActions">
      <button
        *ngIf="item.btnEdit"
        [class]="css.summaryRowActionEdit"
        (click)="item.btnEdit.action()"
        [title]="item.btnEdit.title"
      >
        <svg [iconName]="'icon-editsmall-16x16'" [size]="'auto'" sv-ng-svg-icon></svg>
      </button>
      <button
        *ngIf="item.showRemove && item.btnRemove"
        [class]="css.summaryRowActionDelete"
        (click)="item.btnRemove.action()"
        [title]="item.btnRemove.title"
      >
        <svg [iconName]="'icon-delete-16x16'" [size]="'auto'" sv-ng-svg-icon></svg>
      </button>
    </div>
  </div>
</div>
<div *ngIf="summary.isEmpty()">
  <!--<sv-placeholder
    *ngIf="true"
    [question]="summary.question"
    [cssClasses]="css"
  ></sv-placeholder>-->
  <div>
    <sv-ng-string [model]="summary.noEntry"></sv-ng-string>
  </div>
</div>
