// packages/survey-vue3-ui/src/ElementHeader.vue
<template>
  <div :class="element.cssHeader" @click="clickTitleFunction" :style="getStyle()">
    <survey-element-title :element="element" :css="css" />
    <div v-if="element.hasDescriptionUnderTitle" v-show="element.hasDescription" :class="element.cssDescription"
      :id="element.ariaDescriptionId">
      <survey-string :locString="element.locDescription" />
    </div>
    <sv-action-bar v-if="element.hasAdditionalTitleToolbar" :model="element.additionalTitleToolbar"></sv-action-bar>
  </div>
</template>

<script lang="ts" setup>
import type { Question, PanelModel } from "survey-core";

const props = defineProps<{ element: Question | PanelModel; css?: any }>();
const clickTitleFunction = (e: any) => {
  if (typeof props.element.clickTitleFunction === "function") {
    props.element.clickTitleFunction(e);
  }
};
const getStyle = () => {
  const headerStyle = { width: undefined };
  if("titleWidth" in props.element) {
    headerStyle.width = props.element.titleWidth;
  }
  return headerStyle;
};
</script>

// packages/survey-angular-ui/src/components/element-header/element-header.component.ts
import { Component, HostBinding, HostListener, Input } from "@angular/core";

@Component({
  selector: "'[sv-ng-element-header]'",
  templateUrl: "./element-header.component.html"
})
export class ElementHeaderComponent {
  @Input() element: any;
  constructor() {
  }
  @HostBinding("class") get rootClass(): string {
    return this.element.cssHeader;
  }
  @HostBinding("style.width") get width(): string {
    return this.element.titleWidth;
  }
  @HostListener("click", ["$event"]) click(e: MouseEvent): void {
    if (this.element.clickTitleFunction !== undefined) {
      this.element.clickTitleFunction(e);
    }
  }
}
<sv-ng-element-title [element]="element"></sv-ng-element-title>
<div *ngIf="element.hasDescriptionUnderTitle" [class]="element.cssDescription" [model]="element.locDescription" [attr.id]="element.ariaDescriptionId" [style.display]="element.hasDescription ? '': 'none' " sv-ng-string></div>
<ng-container *ngIf="element.hasAdditionalTitleToolbar">
<sv-ng-action-bar [model]="element.additionalTitleToolbar"></sv-ng-action-bar>
</ng-container>
