// src/vue/components/header/header-mobile.vue
<template>
  <div class="sv-header--mobile">
    <div v-if="model.survey.hasLogo" class="sv-header__logo">
    <div :class="model.survey.logoClassNames">
      <img
        :class="model.survey.css.logoImage"
        :src="model.survey.locLogo.renderedHtml"
        :width="model.survey.renderedLogoWidth"
        :height="model.survey.renderedLogoHeight"
        :alt="model.survey.locTitle.renderedHtml"
        :style="{ 'objectFit': model.survey.logoFit, 'width': model.survey.renderedStyleLogoWidth, 'height': model.survey.renderedStyleLogoHeight }"
      />
    </div>
    </div>
    <div v-if="model.survey.hasTitle" class="sv-header__title" :style="{ 'maxWidth': model.textAreaWidth }">
      <survey-element-title :element="model.survey" :css="model.survey.css" />
    </div>
    <div v-if="model.survey.renderedHasDescription" class="sv-header__description" :style="{ 'maxWidth': model.textAreaWidth }">
      <h5 v-if="model.survey.renderedHasDescription" :class="model.survey.css.description">
        <survey-string :locString="model.survey.locDescription" />
      </h5>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Prop, Component } from "vue-property-decorator";
import { Base, SurveyModel, Cover, CoverCell } from "survey-core";
import BaseVue from "../../base";

@Component
export class HeaderMobileViewModel extends Vue {
  @Prop() model: Cover;
  constructor(props: any) {
    super(props);
  }
}

Vue.component("sv-header-mobile", HeaderMobileViewModel);
export default HeaderMobileViewModel;
</script>

// packages/survey-angular-ui/src/components/header/header-mobile.component.ts
import { Component, Input, ViewChild, ViewContainerRef } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { EmbeddedViewContentComponent } from "../../embedded-view-content.component";
import { AngularComponentFactory } from "../../component-factory";
import { Cover, CoverCell, SurveyModel } from "survey-core";

@Component({
  selector: "sv-ng-header-mobile",
  templateUrl: "./header-mobile.component.html",
  styles: [":host { display: none; }"],
})
export class HeaderMobileComponent extends EmbeddedViewContentComponent {
  @Input() model!: SurveyModel;
  @ViewChild("actionContent", { read: ViewContainerRef, static: true }) actionContent!: ViewContainerRef;
}

AngularComponentFactory.Instance.registerComponent("sv-header-cell", HeaderMobileComponent);

<ng-template #template>
  <div class="sv-header--mobile">
    <div *ngIf="model.hasLogo" class="sv-header__logo">
      <div [class]="model.logoClassNames">
        <ng-template [component]="{ name: model.getElementWrapperComponentName(model, 'logo-image'), data: { data: model.getElementWrapperComponentData(model, 'logo-image') } }"></ng-template>
      </div>
    </div>
    <div *ngIf="model.hasTitle" class="sv-header__title" [style]="{ maxWidth: model['header'].textAreaWidth }">
      <sv-ng-element-title [element]="model.survey"></sv-ng-element-title>
    </div>
    <div *ngIf="model.renderedHasDescription" class="sv-header__description" [style]="{ maxWidth: model['header'].textAreaWidth }">
      <h5 *ngIf="model.renderedHasDescription" [class]="model.css.description" [model]="model.locDescription" sv-ng-string></h5>
    </div>
  </div>
</ng-template>
