// packages/survey-vue3-ui/src/components/QuestionError.vue
<template>
  <div>
    <span
      :class="
        cssClasses ? cssClasses.error.icon || undefined : 'panel-error-icon'
      "
      aria-hidden="true"
    ></span>
    <span
      :class="
        cssClasses ? cssClasses.error.item || undefined : 'panel-error-item'
      "
    >
      <SvComponent :is="'survey-string'" :locString="error.locText" />
    </span>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { SurveyError } from "survey-core";
defineProps<{
  error: SurveyError;
  cssClasses: any;
  element: any;
}>();
</script>

// packages/survey-angular-ui/src/components/question-error/question-error.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { SurveyError } from "survey-core";

@Component({
  selector: "sv-question-error",
  templateUrl: "./question-error.component.html"
})
export class QuestionErrorComponent {
  @Input() error!: SurveyError;
  @Input() cssClasses?: any;
  @Input() element: any;
}
AngularComponentFactory.Instance.registerComponent("sv-question-error", QuestionErrorComponent);
<div>
  <span
    [class]="cssClasses ? cssClasses.error.icon : 'panel-error-icon'"
    aria-hidden="true"
  ></span>
  <span [class]="cssClasses ? cssClasses.error.item : 'panel-error-item'" [model]="error.locText" sv-ng-string>
  </span>
</div>
