// packages/survey-angular-ui/src/components/survey-header/survey-header.component.ts
import { AfterViewInit, ChangeDetectorRef, Component, Input, OnDestroy, ViewContainerRef } from "@angular/core";
import { SurveyModel } from "survey-core";

@Component({
  selector: "'[sv-ng-survey-header]'",
  templateUrl: "survey-header.component.html"
})
export class SurveyHeaderComponent implements AfterViewInit, OnDestroy {
  @Input() survey!: SurveyModel;
  constructor(private viewContainerRef: ViewContainerRef, private changeDetectorRef: ChangeDetectorRef) {}
  ngAfterViewInit(): void {
    this.survey.afterRenderHeader(this.viewContainerRef.element.nativeElement);
    this.survey.locLogo.onChanged = () => {
      this.changeDetectorRef.detectChanges();
    };
  }
  ngOnDestroy(): void {
    this.survey.locLogo.onChanged = () => {};
  }
}
<div *ngIf="survey.isLogoBefore" [class]="survey.logoClassNames">
  <ng-template [component]="{ name: survey.getElementWrapperComponentName(survey, 'logo-image'), data: { data: survey.getElementWrapperComponentData(survey, 'logo-image') } }"></ng-template>
</div>
<div
  *ngIf="survey.renderedHasTitle"
  [class]="survey.css.headerText"
  [style.maxWidth]="survey.titleMaxWidth"
>
  <sv-ng-element-title [element]="survey"></sv-ng-element-title>
  <h5 *ngIf="survey.renderedHasDescription" [class]="survey.css.description" [model]="survey.locDescription" sv-ng-string></h5>
</div>

<div *ngIf="survey.isLogoAfter" [class]="survey.logoClassNames">
  <ng-template [component]="{ name: survey.getElementWrapperComponentName(survey, 'logo-image'), data: { data: survey.getElementWrapperComponentData(survey, 'logo-image') } }"></ng-template>
</div>
<div [class]="survey.css.headerClose"></div>

// packages/survey-react-ui/src/components/survey-header/survey-header.tsx
import * as React from "react";
import { SurveyModel } from "survey-core";
import { SurveyElementBase } from "../../reactquestion_element";
import { ReactElementFactory } from "../../element-factory";
import { TitleElement } from "../title/title-element";

interface ISurveyHeaderProps {
  survey: SurveyModel;
}

export class SurveyHeader extends React.Component<ISurveyHeaderProps, any> {
  constructor(props: ISurveyHeaderProps) {
    super(props);
    this.state = { changed: 0 };
    this.rootRef = React.createRef();
  }

  private get survey(): SurveyModel {
    return this.props.survey;
  }
  private get css(): any {
    return this.survey.css;
  }
  private rootRef: React.RefObject<HTMLDivElement>;

  componentDidMount() {
    const self: SurveyHeader = this;
    this.survey.afterRenderHeader(this.rootRef.current as HTMLDivElement);
    this.survey.locLogo.onChanged = function () {
      self.setState({ changed: self.state.changed + 1 });
    };
  }
  componentWillUnmount() {
    this.survey.locLogo.onChanged = function () { };
  }

  private renderTitle(): React.JSX.Element | null {
    if(!this.survey.renderedHasTitle) return null;
    const description = SurveyElementBase.renderLocString(
      this.survey.locDescription
    );
    return (
      <div
        className={this.css.headerText}
        style={{ maxWidth: this.survey.titleMaxWidth }}
      >
        <TitleElement element={this.survey}></TitleElement>
        {this.survey.renderedHasDescription ? <div className={this.css.description}>{description}</div> : null}
      </div>
    );
  }

  private renderLogoImage(isRender: boolean): React.JSX.Element | null {
    if(!isRender) return null;
    const componentName: string = this.survey.getElementWrapperComponentName(
      this.survey,
      "logo-image"
    );
    const componentData: any = this.survey.getElementWrapperComponentData(
      this.survey,
      "logo-image"
    );
    return ReactElementFactory.Instance.createElement(componentName, {
      data: componentData,
    });
  }
  public render(): React.JSX.Element | null {
    if(!this.survey.renderedHasHeader) return null;
    return (
      <div className={this.css.header} ref={this.rootRef}>
        {this.renderLogoImage(this.survey.isLogoBefore)}
        {this.renderTitle()}
        {this.renderLogoImage(this.survey.isLogoAfter)}
        <div className={this.css.headerClose}></div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "survey-header",
  (props: ISurveyHeaderProps) => {
    return React.createElement(SurveyHeader, props);
  }
);
