// packages/survey-angular-ui/src/components/slider/slider-label-item.component.ts
import { Component, Input } from "@angular/core";
import { QuestionSliderModel, SliderLabelItemValue } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-slider-label-item",
  templateUrl: "./slider-label-item.component.html"
})

export class SliderLabelItemComponent extends BaseAngular {
  @Input() model!: QuestionSliderModel;
  @Input() item!: SliderLabelItemValue;

  // onClick(event: any): void {
  //   this.model.setValueFromClick(event.target.value);
  //   event.stopPropagation();
  // }

  getModel() {
    return this.item;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-slider-label-item", SliderLabelItemComponent);
<ng-template #template>
    <div [class]="model.getLabelCss(item.locText)"
      [style]="{ left: model.getPercent(item.value) + '%', maxWidth: model.getLabelMaxWidth(item) }"
      (pointerup)="model.handleLabelPointerUp($any($event), item.value)">
        <div [class]="model.cssClasses.labelTick"></div>
        <div [class]="model.cssClasses.labelTextContainer">
          <div *ngIf="!item.showValue" [class]="model.cssClasses.labelText" [title]="item.locText.renderedHtml" [model]="item.locText" sv-ng-string></div>
          <div *ngIf="item.showValue" [class]="model.cssClasses.labelText" [title]="'' + item.value">{{ item.value }}</div>
          <div *ngIf="item.showValue" [class]="model.cssClasses.labelTextSecondaryMode" [title]="item.locText.renderedHtml" [model]="item.locText" sv-ng-string></div>
        </div>
    </div>
</ng-template>

// packages/survey-vue3-ui/src/components/slider/SliderLabelItem.vue
<template>
    <div :class="question.getLabelCss(item.locText)"
    :style="{ left: question.getPercent(item.value) + '%', maxWidth: question.getLabelMaxWidth(item) }" @pointerup="(e)=>{question.handleLabelPointerUp(e, item.value )}">
        <div :class="question.cssClasses.labelTick"></div>
        <div :class="question.cssClasses.labelTextContainer">
            <div :class="question.cssClasses.labelText" :title="item.locText.renderedHtml" v-if="!item.showValue">
                <SvComponent
                :is="'survey-string'"
                :locString="item.locText"
                />
            </div>
            <div :class="question.cssClasses.labelText" :title="''+item.value" v-if="item.showValue">
                {{item.value}}
            </div>
            <div :class="question.cssClasses.labelTextSecondaryMode" :title="item.locText.renderedHtml" v-if="item.showValue">
                <SvComponent
                :is="'survey-string'"
                :locString="item.locText"
                />
            </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { ISliderItemProps } from "./slider";
import { useBase } from "@/base";

const props = defineProps<ISliderItemProps>();

useBase(() => props.item);
</script>
