// src/vue/components/button-group/button-group-item.vue
<template>
  <label :class="model.css.label" v-bind:title="model.caption.renderedHtml">
    <input
      type="radio"
      v-bind:name="model.name"
      v-bind:id="model.id"
      v-bind:aria-required="model.isRequired"
      v-bind:aria-label="model.caption.renderedHtml"
      role="radio"
      v-bind:aria-invalid="model.hasErrors"
      v-bind:aria-describedby="model.describeBy"
      :value="model.value"
      v-model="model.question.renderedValue"
      :disabled="model.readOnly"
      :class="model.css.control"
    />
    <div :class="model.css.decorator">
      <sv-svg-icon
        v-if="!!model.iconName"
        :class="model.css.icon"
        :iconName="model.iconName"
        :size="model.iconSize"
      ></sv-svg-icon>
      <span v-if="model.showCaption" :class="model.css.caption">
        <survey-string :locString="model.caption" />
      </span>
    </div>
  </label>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";
import Vue from "vue";
import {
  ButtonGroupItemModel,
  ItemValue,
  QuestionSelectBase,
} from "survey-core";
import { BaseVue } from "src/vue/base";
@Component
export class ButtonGroupItemViewModel extends BaseVue {
  @Prop() item: ItemValue;
  @Prop() question: QuestionSelectBase;
  @Prop() index: number;
  public model: ButtonGroupItemModel;

  constructor(props: any) {
    super(props);
    this.model = new ButtonGroupItemModel(this.question, this.item, this.index);
  }
  getModel(): ItemValue {
    return this.item;
  }
}

Vue.component("sv-button-group-item", ButtonGroupItemViewModel);
export default ButtonGroupItemViewModel;
</script>

// src/react/components/button-group/button-group-item.tsx
import React from "react";
import { ReactElementFactory } from "../../element-factory";
import { SurveyElementBase } from "../../reactquestion_element";
import { SvgIcon } from "../svg-icon/svg-icon";
import {
  ButtonGroupItemModel,
  QuestionSelectBase,
  ItemValue,
} from "survey-core";

export class SurveyButtonGroupItem extends SurveyElementBase<any, any> {
  public model: ButtonGroupItemModel;
  constructor(props: any) {
    super(props);
    this.model = new ButtonGroupItemModel(this.question, this.item, this.index);
  }
  get index(): number {
    return this.props.index;
  }
  get question(): QuestionSelectBase {
    return this.props.question;
  }
  get item(): ItemValue {
    return this.props.item;
  }
  getStateElement() {
    return this.item;
  }
  public render() {
    const icon = this.renderIcon();
    const input = this.renderInput();
    const caption = this.renderCaption();
    return (
      <label
        className={this.model.css.label}
        title={this.model.caption.renderedHtml}
      >
        {input}
        <div className={this.model.css.decorator}>
          {icon}
          {caption}
        </div>
      </label>
    );
  }
  protected renderIcon() {
    if (!!this.model.iconName) {
      return (
        <SvgIcon
          className={this.model.css.icon}
          iconName={this.model.iconName}
          size={this.model.iconSize || 24}
        ></SvgIcon>
      );
    }
    return null;
  }
  protected renderInput() {
    return (
      <input
        className={this.model.css.control}
        id={this.model.id}
        type="radio"
        name={this.model.name}
        checked={this.model.selected}
        value={this.model.value}
        disabled={this.model.readOnly}
        onChange={() => {
          this.model.onChange();
        }}
        aria-required={this.model.isRequired}
        aria-label={this.model.caption.renderedHtml}
        aria-invalid={this.model.hasErrors}
        aria-describedby={this.model.describedBy}
        role="radio"
      />
    );
  }
  protected renderCaption() {
    if (!this.model.showCaption) return null;
    let caption = this.renderLocString(this.model.caption);
    return (
      <span
        className={this.model.css.caption}
        title={this.model.caption.renderedHtml}
      >
        {caption}
      </span>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-button-group-item",
  (props) => {
    return React.createElement(SurveyButtonGroupItem, props);
  }
);
