// packages/survey-vue3-ui/src/components/rating/RatingDropdownItem.vue
<template>
  <div class="sd-rating-dropdown-item">
    <span class="sd-rating-dropdown-item_text">{{ item.title }}</span>
    <div v-if="!!item.description" class="sd-rating-dropdown-item_description">
      <SvComponent :is="'survey-string'" :locString="item.description" />
    </div>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useBase } from "@/base";

const props = defineProps<{ item: any; model: any }>();

useBase(() => props.item);
</script>

// packages/survey-angular-ui/src/components/renderAs/rating-dropdown/rating-dropdown-item.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../../../base-angular";
import { AngularComponentFactory } from "../../../component-factory";

@Component({
  selector: "sv-ng-rating-dropdown-item, '[sv-ng-rating-dropdown-item]'",
  templateUrl: "./rating-dropdown-item.component.html",
  styleUrls: ["../../../hide-host.scss"],
})

export class RatingDropdownItemComponent extends BaseAngular {
  @Input() element: any;
  @Input() model!: any;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-rating-dropdown-item", RatingDropdownItemComponent);
<ng-template #template>
  <div class="sd-rating-dropdown-item">
    <span class="sd-rating-dropdown-item_text">{{model.title}}</span>
    <ng-container *ngIf="!!model.description">
    <div class="sd-rating-dropdown-item_description">
      <sv-ng-string [model]="model.description"></sv-ng-string>
    </div>
    </ng-container>
  </div>
</ng-template>
