// packages/survey-vue3-ui/src/TimerPanel.vue
<template>
  <div v-if="model.isRunning && model.showTimerAsClock" :class="model.rootCss">
    <svg
      v-if="model.showProgress"
      :class="model.getProgressCss()"
      :style="{ strokeDasharray: circleRadius, strokeDashoffset: progress }"
    >
      <use :xlink:href="'#icon-timercircle'"></use>
    </svg>
    <div :class="model.textContainerCss">
      <span :class="model.majorTextCss">{{ model.clockMajorText }}</span>
      <span v-if="!!model.clockMinorText" :class="model.minorTextCss">{{
        model.clockMinorText
      }}</span>
    </div>
  </div>
  <div
    v-else
    v-show="model.isRunning && !model.showTimerAsClock"
    :class="model.survey.getCss().timerRoot"
  >
    {{ text }}
  </div>
</template>

<script lang="ts" setup>
import type { SurveyTimerModel } from "survey-core";
import { useBase } from "./base";
import { computed } from "vue";

const props = defineProps<{
  model: SurveyTimerModel;
  css?: any;
}>();
const circleRadius: number = 440;
const progress = computed(() => circleRadius * props.model.progress);
const text = computed(() => props.model.text);

useBase(() => props.model);
</script>

// packages/survey-angular-ui/src/components/timer-panel/timer-panel.component.ts
import { Component, Input } from "@angular/core";
import { Base, SurveyTimerModel } from "survey-core";
import { BaseAngular } from "../../base-angular";

@Component(
  {
    selector: "sv-timer-panel",
    template: "<div class='model.survey.getCss().timerRoot'>{{model.text}}</div>"
  }
)

export class TimerPanelComponent extends BaseAngular<SurveyTimerModel> {
  @Input() model!: SurveyTimerModel;

  protected getStateElement(): Base {
    return this.model;
  }
  protected getModel(): SurveyTimerModel {
    return this.model;
  }
}

<div *ngIf="model.isRunning && model.showTimerAsClock" [class]="model.rootCss">
    <svg *ngIf="model.showProgress" [class]="model.getProgressCss()" [style.stroke-dasharray]="circleLength" [style.stroke-dashoffset]="progress" [size]="'auto'" [iconName]="'icon-timercircle'" sv-ng-svg-icon></svg>
    <div [class]="model.textContainerCss">
        <span [class]="model.majorTextCss">{{ model.clockMajorText }}</span>
        <span *ngIf="model.clockMinorText" [class]="model.minorTextCss">{{ model.clockMinorText }}</span>
    </div>
</div>
<div *ngIf="model.isRunning && !model.showTimerAsClock" [class]='model.survey.getCss().timerRoot'>{{model.text}}</div>
