// packages/survey-vue3-ui/src/components/action-bar/ActionBar.vue
<template>
  <div
    v-if="model.hasActions"
    ref="root"
    :style="model.getRootStyle()"
    :class="model.getRootCss()"
    @click="onClick"
  >
    <SvComponent
      :is="'sv-action'"
      v-for="item in model.renderedActions"
      :key="item.renderedId"
      :item="item"
    ></SvComponent>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { ActionContainer } from "survey-core";
import { useBase } from "@/base";
import { onMounted, onUpdated, ref } from "vue";

const props = withDefaults(
  defineProps<{
    model: ActionContainer;
    container?: string;
    handleClick?: boolean;
  }>(),
  {
    handleClick: true,
  }
);
const root = ref<HTMLDivElement>(null as any as HTMLDivElement);

const onClick = (event: MouseEvent) => {
  if (props.handleClick) {
    event.stopPropagation();
  }
};

useBase(() => props.model, undefined, (value) => {
  value.resetResponsivityManager();
});
function initResponsivityManager() {
  if (!props.model.hasVisibleActions) return;
  props.model.initResponsivityManager(root.value);
} 
onUpdated(() => {
  initResponsivityManager();
})

onMounted(() => {
  initResponsivityManager();
});
</script>

// packages/survey-angular-ui/src/components/action-bar/action-bar.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { BaseAngular } from "../../base-angular";
import { Action, ActionContainer } from "survey-core";

@Component({
  selector: "sv-action-bar, sv-ng-action-bar",
  templateUrl: "./action-bar.component.html",
  styles: [":host { display: none }"]
})
export class ActionBarComponent extends BaseAngular<ActionContainer> {
  @Input() model!: ActionContainer;
  @Input() handleClick: any;
  @ViewChild("container") container!: ElementRef<HTMLDivElement>;
  getModel(): ActionContainer {
    return this.model;
  }
  trackActionBy(_: number, action: Action) {
    return action.renderedId;
  }
  get allowOnClick(): boolean {
    return this.handleClick !== undefined ? this.handleClick : true;
  }

  protected override onModelChanged() {
    super.onModelChanged();
    this.previousModel?.resetResponsivityManager();
    if (!!this.model.hasActions && !!this.container && !!this.container.nativeElement) {
      this.model.initResponsivityManager(this.container.nativeElement);
    }
  }

  onClick(event: Event): void {
    if (this.allowOnClick) {
      event.stopPropagation();
    }
  }
  ngAfterViewInit() {
    if (!!this.model.hasActions) {
      this.model.initResponsivityManager(this.container.nativeElement);
    }
  }
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    this.model.resetResponsivityManager();
  }
}

AngularComponentFactory.Instance.registerComponent("sv-action-bar", ActionBarComponent);
<ng-template #template>
  <div *ngIf="model.hasVisibleActions" [class]="model.getRootCss()" (click)="onClick($event)" #container [style]="model.getRootStyle()">
    <ng-container *ngFor="let action of model.renderedActions; trackBy: trackActionBy">
      <sv-ng-action [model]="action"></sv-ng-action>
    </ng-container>
  </div>
</ng-template>
