// packages/survey-vue-ui/src/components/action-bar/ActionBarItemDropdown.vue
<template>
  <button
    type="button"
    :class="item.getActionBarItemCss()"
    v-on:click="
      () => {
        item.action();
      }
    "
    v-on:keyup="
      (evt) => {
        evt.stopPropagation();
      }
    "
    v-bind:disabled="item.enabled !== undefined && item.enabled"
    v-bind:title="item.tooltip || item.title"
    v-bind:role="item.ariaRole"
    v-bind:tabindex="item.disableTabStop ? -1 : 0"
  >
    <sv-svg-icon
      v-if="item.iconName"
      :class="item.cssClasses.itemIcon"
      :iconName="item.iconName"
      :size="item.iconSize"
      :title="item.tooltip || item.title"
    ></sv-svg-icon>

    <span
      v-if="item.hasTitle"
      :class="item.getActionBarItemTitleCss()"
      >{{ item.title }}</span
    >
    <sv-popup :model="item.popupModel"></sv-popup>
  </button>
</template>

<script lang="ts">
import { Action, ActionDropdownViewModel } from "survey-core";
import { defineSurveyComponent } from "../../base";

export default defineSurveyComponent({
  // eslint-disable-next-line
  name: "sv-action-bar-item-dropdown",
  props: {
    item: Action,
  },
  beforeCreate() {
    this.viewModel = new ActionDropdownViewModel(this.item);
  },
  beforeUnmount() {
    this.viewModel.dispose();
  },
  data: (vm: any) => {
    return {
      getModel: () => {
        return vm.item;
      },
    };
  },
});
</script>

// packages/survey-angular-ui/src/components/action-bar/action-bar-item-dropdown.component.ts
import { Component, Input } from "@angular/core";
import { ActionDropdownViewModel } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-action-bar-item-dropdown",
  templateUrl: "./action-bar-item-dropdown.component.html"
})
export class ActionBarItemDropdownComponent extends BaseAngular {
  @Input() model: any
  protected viewModel!: ActionDropdownViewModel;

  protected getModel() {
    return this.model;
  }
  override ngOnInit(): void {
    super.ngOnInit();
    this.viewModel = new ActionDropdownViewModel(this.model);
  }
  override ngOnDestroy(): void {
    this.viewModel.dispose();
    super.ngOnDestroy();
  }
}

AngularComponentFactory.Instance.registerComponent("sv-action-bar-item-dropdown", ActionBarItemDropdownComponent);
<button class="sv-action-bar-item-dropdown" type="button" (click)="model.action()" [key2click]="{ processEsc: false }" [class]="model.getActionBarItemCss()" [title]="model.tooltip || model.title" [disabled]="model.disabled">
    <!-- ko if: $data.iconName -->
    <!-- ko component: { name: 'sv-svg-icon', params: { css: $data.cssClasses.itemIcon, iconName: iconName, size: iconSize } } --><!-- /ko -->
    <!-- /ko -->
    <svg *ngIf="model.iconName" [iconName]="model.iconName" [size]="model.iconSize" [title]="model.tooltip || model.title" sv-ng-svg-icon></svg>
    <span *ngIf="model.hasTitle" [class]="model.getActionBarItemTitleCss()">{{ model.title }}</span>
    <sv-ng-popup [popupModel]="model.popupModel"></sv-ng-popup>
</button>
