// packages/survey-vue3-ui/src/components/breadcrumbs/Breadcrumbs.vue
<template>
  <div v-if="model.actions && model.actions.length" :class="css.breadcrumbsRoot">
    <template v-for="(item, itemIndex) in model.actions" :key="item.uniqueId">
      <SvComponent
        v-if="itemIndex"
        :is="'sv-svg-icon'"
        :class="css.breadcrumbsSeparator"
        iconName="arrowright-16x16"
        size="auto"
      />
      <SvComponent :is="'sv-action'" :item="item" />
    </template>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { ActionContainer } from "survey-core";
import { useBase } from "./../../base";
defineOptions({ inheritAttrs: false });
const props = defineProps<{
  model: ActionContainer;
  css: any;
}>();
useBase(() => props.model);
</script>

// packages/survey-angular-ui/src/components/breadcrumbs/breadcrumbs.component.ts
import { Component, Input } from "@angular/core";
import { ActionContainer } from "survey-core";
import { BaseAngular } from "../../base-angular";
@Component({
  selector: "sv-breadcrumbs",
  templateUrl: "./breadcrumbs.component.html",
  //styles: [":host { display: none; }"],
})
export class BreadcrumbsComponent extends BaseAngular {
  @Input() model!: ActionContainer;
  @Input() css!: any;

  getModel() {
    return this.model;
  }
}
<div *ngIf="model.actions && model.actions.length" [class]="css.breadcrumbsRoot">
  <ng-container *ngFor="let item of model.actions; let itemIndex = index">
    <svg
      *ngIf="itemIndex"
      [class]="css.breadcrumbsSeparator"
      [iconName]="'arrowright-16x16'"
      [size]="'auto'"
      sv-ng-svg-icon
    ></svg>
    <sv-ng-action [model]="item"></sv-ng-action>
  </ng-container>
</div>
