// packages/survey-vue3-ui/src/ElementHeader.vue
<template>
  <div :class="element.cssHeader" @click="clickTitleFunction" :style="getStyle()">
    <survey-element-title :element="element" :css="css" />
    <div v-if="element.hasDescriptionUnderTitle" v-show="element.hasDescription" :class="element.cssDescription"
      :id="element.ariaDescriptionId">
      <survey-string :locString="element.locDescription" />
    </div>
    <sv-action-bar v-if="element.hasAdditionalTitleToolbar" :model="element.additionalTitleToolbar"></sv-action-bar>
  </div>
</template>

<script lang="ts" setup>
import type { Question, PanelModel } from "survey-core";

const props = defineProps<{ element: Question | PanelModel; css?: any }>();
const clickTitleFunction = (e: any) => {
  if (typeof props.element.clickTitleFunction === "function") {
    props.element.clickTitleFunction(e);
  }
};
const getStyle = () => {
  const headerStyle = { width: undefined };
  if("titleWidth" in props.element) {
    headerStyle.width = props.element.titleWidth;
  }
  return headerStyle;
};
</script>

// packages/survey-react-ui/src/element-header.tsx
import React from "react";
import { Question, PanelModel, QuestionPanelDynamicModel } from "survey-core";
import { SurveyActionBar } from "./components/action-bar/action-bar";
import { TitleElement } from "./components/title/title-element";
import { SurveyElementBase } from "./reactquestion_element";

export class SurveyElementHeader extends React.Component<any, any> {
  private get element(): Question | PanelModel {
    return this.props.element;
  }
  public render(): JSX.Element {
    const element = this.element;
    const title = element.hasTitle ? (
      <TitleElement element={element}></TitleElement>
    ) : null;
    const description = element.hasDescriptionUnderTitle
      ? SurveyElementBase.renderQuestionDescription(this.element)
      : null;

    const additionalTitleToolbarElement = element.hasAdditionalTitleToolbar ? <SurveyActionBar model={element.additionalTitleToolbar}></SurveyActionBar> : null;

    const headerStyle: any = { width: undefined };
    if(element instanceof Question) {
      headerStyle.width = element.titleWidth;
    }

    return (
      <div className={element.cssHeader} onClick={(e) => element.clickTitleFunction && element.clickTitleFunction(e.nativeEvent)} style={headerStyle}>
        {title}
        {description}
        {additionalTitleToolbarElement}
      </div>
    );
  }
}
