// packages/survey-vue-ui/src/components/matrix-actions/detail-button/DetailButton.vue
<template>
  <button
    type="button"
    :class="question.getDetailPanelButtonCss(row)"
    @click="() => row.showHideDetailPanelClick()"
    v-bind:aria-expanded="
      question.getIsDetailPanelShowing(row) ? 'true' : 'false'
    "
    :aria-controls="
      question.getIsDetailPanelShowing(row) ? row.detailPanelId : null
    "
  >
  <sv-svg-icon
    :class="this.question.getDetailPanelIconCss(this.row)"
    :iconName="this.question.getDetailPanelIconId(this.row)"
    size="auto"
  >
  </sv-svg-icon>
  </button>
</template>

<script lang="ts">
import { BaseVue } from "../../../base";
import { Action, Base } from "survey-core";
import { defineComponent, type PropType } from "vue";

export default defineComponent({
  // eslint-disable-next-line
  mixins: [BaseVue],
  name: "sv-matrix-detail-button",
  props: {
    item: Object as PropType<Action>,
  },
  methods: {
    getModel(): Base {
      return this.item;
    },
  },
  computed: {
    // readonly
    question(): any {
      return this.item.data.question;
    },
    row() {
      return this.item.data.row;
    },
  },
});
</script>

// packages/survey-angular-ui/src/components/matrix-actions/detail-button/detail-button.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { Action } from "survey-core";
import { Base } from "survey-core";

@Component({
  selector: "sv-ng-matrix-detail-btn",
  templateUrl: "./detail-button.component.html"
})
export class MatrixDetailButtonComponent {
  @Input() public model!: Action;

  get question() {
    return this.model.data.question;
  }

  get row() {
    return this.model.data.row;
  }

  getModel(): Base {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-matrix-detail-button", MatrixDetailButtonComponent);

<button type="button" [class]="question.getDetailPanelButtonCss(row)" (click)="row.showHideDetailPanelClick()"
  [attr.title]="model.title" [attr.aria-expanded]="question.getIsDetailPanelShowing(row) ? 'true' : 'false'"
  [attr.aria-controls]="question.getIsDetailPanelShowing(row) ? row.detailPanelId : null">
  <svg [class]="this.question.getDetailPanelIconCss(this.row)" 
    [iconName]="this.question.getDetailPanelIconId(this.row)" [size]="'auto'" sv-ng-svg-icon>
  </svg>
</button>
