// packages/survey-angular-ui/src/components/matrix-actions/detail-button/detail-button.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { Action } from "survey-core";
import { Base } from "survey-core";

@Component({
  selector: "sv-ng-matrix-detail-btn",
  templateUrl: "./detail-button.component.html"
})
export class MatrixDetailButtonComponent {
  @Input() public model!: Action;

  get question() {
    return this.model.data.question;
  }

  get row() {
    return this.model.data.row;
  }

  getModel(): Base {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-matrix-detail-button", MatrixDetailButtonComponent);

<button type="button" [class]="question.getDetailPanelButtonCss(row)" (click)="row.showHideDetailPanelClick()"
  [attr.title]="model.title" [attr.aria-expanded]="question.getIsDetailPanelShowing(row) ? 'true' : 'false'"
  [attr.aria-controls]="question.getIsDetailPanelShowing(row) ? row.detailPanelId : null">
  <svg [class]="this.question.getDetailPanelIconCss(this.row)" 
    [iconName]="this.question.getDetailPanelIconId(this.row)" [size]="'auto'" sv-ng-svg-icon>
  </svg>
</button>

// packages/survey-vue3-ui/src/components/matrix-actions/detail-button/DetailButton.vue
<template>
  <button
    type="button"
    :class="question.getDetailPanelButtonCss(row)"
    @click="() => row.showHideDetailPanelClick()"
    :title="item.title"
    v-bind:aria-expanded="
      question.getIsDetailPanelShowing(row) ? 'true' : 'false'
    "
    :aria-controls="
      question.getIsDetailPanelShowing(row) ? row.detailPanelId : null
    "
  >
    <SvComponent
      :is="'sv-svg-icon'"
      :class="question.getDetailPanelIconCss(row)"
      :iconName="question.getDetailPanelIconId(row)"
      size="auto"
    >
    </SvComponent>
  </button>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { Action } from "survey-core";
import { useMatrixAction } from "../matrix-action";
const props = defineProps<{ item: Action }>();
const { question, row } = useMatrixAction(props);
</script>
