// packages/survey-vue3-ui/src/components/list/ListItemContent.vue
<template>
  <SvComponent
    :is="'sv-svg-icon'"
    v-if="item.iconName"
    v-bind:class="model.cssClasses.itemIcon"
    :iconName="item.iconName"
    :size="item.iconSize"
  ></SvComponent>
  <SvComponent :is="'survey-string'" :locString="item.locTitle" />
  <SvComponent
    :is="'sv-svg-icon'"
    v-if="item.markerIconName"
    v-bind:class="item.cssClasses.itemMarkerIcon"
    :iconName="item.markerIconName"
    :size="item.markerIconSize"
  ></SvComponent>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useBase } from "@/base";
import type { ListModel, Action } from "survey-core";

const props = defineProps<{ model: ListModel; item: Action }>();

useBase(() => props.item);
</script>

// packages/survey-angular-ui/src/components/list/list-item-content.component.ts
import { Component, Input } from "@angular/core";
import { ListModel, Action } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-list-item-content, '[sv-ng-list-item-content]'",
  templateUrl: "./list-item-content.component.html",
  styleUrls: ["../../hide-host.scss"],
})

export class ListItemContentComponent extends BaseAngular {
  @Input() element: any;
  @Input() model!: Action;
  @Input() listModel!: ListModel;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-list-item-content", ListItemContentComponent);
<ng-template #template>
<svg *ngIf="model.iconName" [class]="listModel.cssClasses.itemIcon" [iconName]="model.iconName" [size]="model.iconSize"
  sv-ng-svg-icon></svg>
<sv-ng-string [model]="model.locTitle"></sv-ng-string>
<svg *ngIf="model.markerIconName" [class]="model.cssClasses.itemMarkerIcon" [iconName]="model.markerIconName" [size]="model.markerIconSize"
  sv-ng-svg-icon></svg>
</ng-template>
