// packages/survey-vue3-ui/src/components/list/List.vue
<template>
  <div v-bind:class="model.cssClasses.root" ref="listContainerElement">
    <div v-bind:class="model.cssClasses.filter" v-if="model.showFilter">
      <div v-bind:class="model.cssClasses.filterIcon">
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="'icon-search'"
          :size="'auto'"
        >
        </SvComponent>
      </div>
      <input
        type="text"
        v-bind:class="model.cssClasses.filterInput"
        :aria-label="model.filterStringPlaceholder"
        :placeholder="model.filterStringPlaceholder"
        :value="model.filterString"
        @change="change"
        @keyup="keyup"
      />
      <button
        v-if="model.showSearchClearButton && !!model.filterString"
        v-on:click="
          (event) => {
            model.onClickSearchClearButton(event);
          }
        "
        v-bind:class="model.cssClasses.searchClearButtonIcon"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          :iconName="'icon-searchclear'"
          :size="'auto'"
        ></SvComponent>
      </button>
    </div>
    <div v-bind:class="model.cssClasses.emptyContainer" v-show="model.isEmpty">
      <div
        v-bind:class="model.cssClasses.emptyText"
        :aria-label="model.emptyMessage"
      >
        {{ model.emptyMessage }}
      </div>
    </div>
    <ul
      v-if="model.renderElements"
      v-bind:class="model.getListClass()"
      v-show="!model.isEmpty"
      :role="model.listRole"
      :aria-label="model.a11yInputAriaLabel"
      :id="model.elementId"
      @mousedown="
        (event) => {
          event.preventDefault();
        }
      "
      @mousemove="mouseMove"
      v-on:keydown="
        (event) => {
          model.onKeyDown(event);
        }
      "
    >
      <SvComponent
        :is="'sv-list-item'"
        v-for="item in renderedActions"
        :item="item"
        :model="model"
        :key="item.id"
      >
      </SvComponent>
    </ul>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useBase, useComputedArray } from "@/base";
import type { ListModel } from "survey-core";
import { onMounted, ref, onUnmounted } from "vue";

const props = defineProps<{ model: ListModel }>();
const listContainerElement = ref<HTMLElement>(null as any);

const change = (event: any) => {
  const model = props.model;
  model.filterString = event.target.value;
};
const keyup = (event: any) => {
  const model = props.model;
  model.filterString = event.target.value;
  props.model.goToItems(event);
};
const mouseMove = (event: any) => {
  props.model.onMouseMove(event);
};
const renderedActions = useComputedArray(() => props.model.renderedActions);

useBase(() => props.model);

onMounted(() => {
  props.model.initListContainerHtmlElement(listContainerElement.value);
});
onUnmounted(() => {
  if (props.model) {
    props.model.removeScrollEventListener();
    props.model.initListContainerHtmlElement(undefined as any);
  }
});
</script>

// packages/survey-angular-ui/src/components/list/list.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-list, '[sv-ng-list]'",
  templateUrl: "./list.component.html",
  styleUrls: ["../../hide-host.scss"]
})
export class ListComponent extends BaseAngular {
  @Input() model: any;

  getModel() {
    return this.model;
  }
  onGoToItems(event: Event): void {
    this.model.goToItems(event);
  }
  onMouseDown(event: Event): void {
    event.preventDefault();
  }
  onKeyDown(event: Event): void {
    this.model.onKeyDown(event);
  }
  onMouseMove(event: Event): void {
    this.model.onMouseMove(event);
  }
}

AngularComponentFactory.Instance.registerComponent("sv-list", ListComponent);
<ng-template #template>
    <div [class]="model.cssClasses.root" #listContainerElement>
        <div *ngIf="model.showFilter" [class]="model.cssClasses.filter">
            <div [class]="model.cssClasses.filterIcon">
                <svg [iconName]="'icon-search'" [size]="'auto'" sv-ng-svg-icon></svg>
            </div>
            <input type="text" [class]="model.cssClasses.filterInput" [(ngModel)]="model.filterString"
                [attr.aria-label]="model.filterStringPlaceholder || ''"
                [attr.placeholder]="model.filterStringPlaceholder || ''" 
                (keyup)="onGoToItems($event)" />
                <button *ngIf="model.showSearchClearButton && !!model.filterString" (click)="model.onClickSearchClearButton($event)" [class]="model.cssClasses.searchClearButtonIcon">
                    <svg [iconName]="'icon-searchclear'" [size]="'auto'" sv-ng-svg-icon></svg>
                </button>
        </div>
        <div [class]="model.cssClasses.emptyContainer" [visible]="model.isEmpty">
            <div [class]="model.cssClasses.emptyText" [attr.aria-label]="model.emptyMessage || ''">{{ model.emptyMessage }}</div>
        </div>
        <ul *ngIf="model.renderElements" [class]="model.getListClass()" [attr.role]="model.listRole" [attr.aria-label]="model.a11yInputAriaLabel" [attr.id]="model.elementId" [visible]="!model.isEmpty" (mousedown)="onMouseDown($event)" (keydown)="onKeyDown($event)" (mousemove)="onMouseMove($event)">
            <sv-ng-list-item *ngFor="let item of model.renderedActions; trackBy: trackItemBy" [listModel]="model" [model]="item"></sv-ng-list-item>
            <!--ko foreach: model.renderedActions -->
            <!-- ko component: { name: 'sv-list-item', params: { item: $data, model: $parent.model } } -->
            <!-- /ko -->
            <!-- /ko -->
        </ul>
    </div>
</ng-template>
