// packages/survey-vue3-ui/src/components/tagbox/TagboxItem.vue
<template>
  <div :class="question.cssClasses.tagItem" :key="item.key">
    <div :class="question.cssClasses.tagItemText">
      <SvComponent :is="'survey-string'" :locString="item.locText" />
    </div>
    <div v-bind:class="question.cssClasses.cleanItem">
      <div
        tabindex="0"
        v-bind:class="question.cssClasses.cleanItemButton"
        v-key2click
        v-on:click="removeItem"
      >
        <SvComponent
          :is="'sv-svg-icon'"
          v-bind:class="question.cssClasses.cleanItemButtonSvg"
          :iconName="question.cssClasses.cleanItemButtonIconId"
          :size="'auto'"
        ></SvComponent>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useBase } from "@/base";
import type { ItemValue, QuestionTagboxModel } from "survey-core";

const props = defineProps<{ question: QuestionTagboxModel; item: ItemValue }>();
const removeItem = (event: any) => {
  props.question.dropdownListModel.deselectItem(props.item.value);
  event.stopPropagation();
};

useBase(() => props.item);
</script>

// packages/survey-angular-ui/src/components/tagbox/tagbox-item.component.ts
import { Component, Input } from "@angular/core";
import { ItemValue, QuestionTagboxModel } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-tagbox-item, '[sv-tagbox-item]'",
  templateUrl: "./tagbox-item.component.html"
})
export class TagboxItemComponent extends BaseAngular {
  @Input() item!: ItemValue;
  @Input() question!: QuestionTagboxModel;

  removeItem(event: any) {
    this.question.dropdownListModel.deselectItem(this.item.value);
    event.stopPropagation();
  }

  getModel() {
    return this.item;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-tagbox-item", TagboxItemComponent);
<ng-template #template>
<div [class]="question.cssClasses.tagItem">
  <div [class]="question.cssClasses.tagItemText" [model]="item.locText" sv-ng-string></div>  
  <div [class]="question.cssClasses.cleanItem">
    <div tabindex="0" [class]="question.cssClasses.cleanItemButton" [key2click] (click)="removeItem($event)">
      <svg [iconName]="question.cssClasses.cleanItemButtonIconId" [partCss]="question.cssClasses.cleanItemButtonSvg" [size]="'auto'" sv-ng-svg-icon></svg>
    </div>
  </div>
</div>
</ng-template>
