// packages/survey-vue3-ui/src/components/tagbox/Tagbox.vue
<template>
  <div :class="question.cssClasses.selectWrapper" @click="click">
    <div
      v-if="!question.isReadOnly"
      :id="question.inputId"
      :tabindex="model.noTabIndex ? undefined : 0"
      v-bind:disabled="question.isDisabledAttr ? true : null"
      @keydown="keyhandler"
      @blur="blur"
      :class="question.getControlClass()"
      :role="question.ariaRole"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-errormessage="question.ariaErrormessage"
      :aria-expanded="question.ariaExpanded"
      :aria-controls="model.listElementId"
      :aria-activedescendant="model.ariaActivedescendant"
      :required="question.isRequired ? true : null"
    >
      <div :class="question.cssClasses.controlValue">
        <SvComponent
          :name="'sv-tagbox-item'"
          v-for="(item, index) in selectedChoices"
          :item="item"
          :question="question"
          :key="'item' + index"
        ></SvComponent>
        <SvComponent
          :name="'sv-tagbox-filter'"
          :model="model"
          :question="question"
        ></SvComponent>
      </div>
      <div
        :class="question.cssClasses.cleanButton"
        v-if="question.allowClear && question.cssClasses.cleanButtonIconId"
        v-show="question.showClearButton"
        @click="clear"
        aria-hidden="true"
      >
        <SvComponent
          :name="'sv-svg-icon'"
          :class="question.cssClasses.cleanButtonSvg"
          :iconName="question.cssClasses.cleanButtonIconId"
          :title="question.clearCaption"
          size="auto"
        >
        </SvComponent>
      </div>
    </div>
    <SvComponent
      :name="'sv-popup'"
      v-if="!question.isReadOnly"
      :model="model.popupModel"
    ></SvComponent>
    <div
      v-else
      :id="question.inputId"
      :aria-label="question.a11y_input_ariaLabel"
      :aria-labelledby="question.a11y_input_ariaLabelledBy"
      :aria-describedby="question.a11y_input_ariaDescribedBy"
      :tabindex="question.isDisabledAttr ? undefined : 0"
      :class="question.getControlClass()"
    >
      <SvComponent
        :name="'survey-string'"
        v-if="question.locReadOnlyText"
        :locString="question.locReadOnlyText"
      />
    </div>
    <div
      :class="question.cssClasses.chevronButton"
      v-on:pointerdown="chevronPointerDown"
      v-if="question.cssClasses.chevronButtonIconId"
      aria-hidden="true"
    >
      <SvComponent
        :name="'sv-svg-icon'"
        :class="question.cssClasses.chevronButtonSvg"
        :iconName="question.cssClasses.chevronButtonIconId"
        size="auto"
      >
      </SvComponent>
    </div>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useBase, useComputedArray } from "@/base";
import { DropdownMultiSelectListModel, QuestionTagboxModel } from "survey-core";
import { computed } from "vue";

const props = defineProps<{ question: QuestionTagboxModel }>();
const model = computed(() => {
  const question = props.question;
  if (!question.dropdownListModel) {
    question.dropdownListModel = new DropdownMultiSelectListModel(question);
  }
  return props.question.dropdownListModel;
});
const click = (event: any) => {
  model.value?.onClick(event);
};
const chevronPointerDown = (event: any) => {
  model.value?.chevronPointerDown(event);
};
const clear = (event: any) => {
  model.value?.onClear(event);
};
const keyhandler = (event: any) => {
  model.value?.keyHandler(event);
};
const blur = (event: any) => {
  model.value?.onBlur(event);
};
const selectedChoices = useComputedArray(() => props.question.selectedChoices);

useBase(() => model.value);
</script>

// packages/survey-angular-ui/src/components/tagbox/tagbox.component.ts
import { Component, Input, OnInit } from "@angular/core";
import { DropdownMultiSelectListModel } from "survey-core";

@Component({
  selector: "sv-ng-tagbox, '[sv-ng-tagbox]'",
  templateUrl: "./tagbox.component.html"
})
export class TagboxComponent implements OnInit {
    @Input() model: any;

    get dropdownModel(): DropdownMultiSelectListModel {
      return this.model?.dropdownListModel;
    }

    getModel() {
      return this.model;
    }

    ngOnInit(): void {
      if(!this.model.dropdownListModel) {
        this.model.dropdownListModel = new DropdownMultiSelectListModel(this.model);
      }
    }

    click(event: any) {
      this.dropdownModel?.onClick(event);
    }
    chevronPointerDown(event: any) {
      this.dropdownModel?.chevronPointerDown(event);
    }
    clear(event: any) {
      this.dropdownModel?.onClear(event);
    }
    keyhandler(event: any) {
      this.dropdownModel?.keyHandler(event);
    }
    blur(event: any) {
      this.model?.onBlur(event);
    }
    focus(event: any) {
      this.model?.onFocus(event);
    }
}
<div [class]="model.cssClasses.selectWrapper" (click)="click($event)">
    <div *ngIf="!model.isReadOnly" [attr.tabindex]="dropdownModel.noTabIndex ? null : 0"
        [class]="model.getControlClass()" [attr.disabled]="model.isDisabledAttr ? true : null" (blur)="blur($event)"
        (keydown)="keyhandler($event)" [attr.id]="model.inputId" [attr.role]="dropdownModel.ariaQuestionRole"
        [attr.aria-required]="dropdownModel.ariaQuestionRequired" [attr.aria-label]="dropdownModel.ariaQuestionLabel"
        [attr.aria-labelledby]="dropdownModel.ariaQuestionLabelledby"
        [attr.aria-describedby]="dropdownModel.ariaQuestionDescribedby"
        [attr.aria-invalid]="dropdownModel.ariaQuestionInvalid"
        [attr.aria-errormessage]="dropdownModel.ariaQuestionErrorMessage"
        [attr.aria-controls]="dropdownModel.ariaQuestionControls"
        [attr.aria-expanded]="dropdownModel.ariaQuestionExpanded"
        [attr.aria-activedescendant]="dropdownModel.ariaQuestionActivedescendant">
        <div [class]="model.cssClasses.controlValue">
            <ng-container *ngIf="!model.isEmpty()">
                <sv-ng-tagbox-item *ngFor="let item of model.selectedChoices" [item]="item" [question]="model">
                </sv-ng-tagbox-item>
            </ng-container>
            <ng-template
                [component]="{ name: 'sv-tagbox-filter', data: { model: dropdownModel, question: model } }"></ng-template>
        </div>
        <div *ngIf="(model.allowClear && model.cssClasses.cleanButtonIconId)" [class]="model.cssClasses.cleanButton"
            (click)="clear($event)" [visible]="model.showClearButton" aria-hidden="true">
            <!-- ko component: { name: 'sv-svg-icon', params: { css: model.cssClasses.cleanButtonSvg, iconName: model.cssClasses.cleanButtonIconId, size: 'auto' } } -->
            <!-- /ko -->
            <svg [iconName]="model.cssClasses.cleanButtonIconId" [partCss]="model.cssClasses.cleanButtonSvg"
                [title]="model.clearCaption" [size]="'auto'" sv-ng-svg-icon></svg>
        </div>
    </div>
    <sv-ng-popup *ngIf="!model.isReadOnly" [popupModel]="model.popupModel"></sv-ng-popup>
    <div *ngIf="model.isReadOnly" [class]="model.getControlClass()" [attr.id]="model.inputId"
        [attr.tabindex]="model.isDisabledAttr ? null : 0" [attr.disabled]="model.isDisabledAttr ? true : null"
        [attr.role]="dropdownModel?.ariaQuestionRole" [attr.aria-label]="dropdownModel?.ariaQuestionLabel"
        [attr.aria-labelledby]="dropdownModel?.ariaQuestionLabelledby"
        [attr.aria-describedby]="dropdownModel?.ariaQuestionDescribedby" [attr.aria-expanded]="false"
        [attr.aria-readonly]="true" [attr.aria-disabled]="true">
        <sv-ng-string *ngIf="model.locReadOnlyText" [model]="model.locReadOnlyText"></sv-ng-string>
    </div>
    <div *ngIf="model.cssClasses.chevronButtonIconId" [class]="model.cssClasses.chevronButton"
        (pointerdown)="chevronPointerDown($event)" aria-hidden="true">
        <svg [iconName]="model.cssClasses.chevronButtonIconId" [partCss]="model.cssClasses.chevronButtonSvg"
            [size]="'auto'" sv-ng-svg-icon></svg>
    </div>
</div>
