// packages/survey-angular-ui/src/components/list/list-item-content.component.ts
import { Component, Input } from "@angular/core";
import { ListModel, Action } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-list-item-content, '[sv-ng-list-item-content]'",
  templateUrl: "./list-item-content.component.html",
  styleUrls: ["../../hide-host.scss"],
})

export class ListItemContentComponent extends BaseAngular {
  @Input() element: any;
  @Input() model!: Action;
  @Input() listModel!: ListModel;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-list-item-content", ListItemContentComponent);
<ng-template #template>
<svg *ngIf="model.iconName" [class]="listModel.cssClasses.itemIcon" [iconName]="model.iconName" [size]="model.iconSize"
  sv-ng-svg-icon></svg>
<sv-ng-string [model]="model.locTitle"></sv-ng-string>
<svg *ngIf="model.markerIconName" [class]="model.cssClasses.itemMarkerIcon" [iconName]="model.markerIconName" [size]="model.markerIconSize"
  sv-ng-svg-icon></svg>
</ng-template>

// src/react/components/list/list-item-content.tsx
import React from "react";
import { ListModel } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { SurveyElementBase } from "../../reactquestion_element";
import { SvgIcon } from "../svg-icon/svg-icon";

interface IListItemProps {
  model: ListModel;
  item: any;
}

export class ListItemContent extends SurveyElementBase<IListItemProps, any> {
  get model(): ListModel {
    return this.props.model;
  }
  get item(): any {
    return this.props.item;
  }
  getStateElement() {
    return this.item;
  }
  render(): JSX.Element | null {
    if (!this.item) return null;

    const content: Array<JSX.Element> = [];
    const text = this.renderLocString(this.item.locTitle, undefined, "locString");
    if(this.item.iconName) {
      const icon = <SvgIcon
        key={1}
        className={this.model.cssClasses.itemIcon}
        iconName={this.item.iconName}
        size={this.item.iconSize}
        aria-label={this.item.title}
      ></SvgIcon>;
      content.push(icon);
      content.push(<span key={2}>{text}</span>);
    } else {
      content.push(text);
    }

    if(this.item.markerIconName) {
      const icon = <SvgIcon
        key={1}
        className={this.item.cssClasses.itemMarkerIcon}
        iconName={this.item.markerIconName}
        size={this.item.markerIconSize}
      ></SvgIcon>;
      content.push(icon);
    }

    return <>
      {content}
    </>;
  }
}

ReactElementFactory.Instance.registerElement("sv-list-item-content", (props) => {
  return React.createElement(ListItemContent, props);
});
