// packages/survey-angular-ui/src/components/list/list-item-group.component.ts
import { Component, Input } from "@angular/core";
import { ListModel, Action } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-list-item-group, '[sv-ng-list-item-group]'",
  templateUrl: "./list-item-group.component.html",
  styleUrls: ["../../hide-host.scss"],
})

export class ListItemGroupComponent extends BaseAngular {
  @Input() element: any;
  @Input() model!: Action;
  @Input() listModel!: ListModel;

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-list-item-group", ListItemGroupComponent);
<ng-template #template>
  <sv-ng-list-item-content [model]="model" [listModel]="listModel"></sv-ng-list-item-content>
  <sv-ng-popup [popupModel]="model.popupModel"></sv-ng-popup>
</ng-template>

// packages/survey-vue3-ui/src/components/list/ListItemGroup.vue
<template>
  <component :is="sv-list-item-content" :item="item" :model="model">
  </component>
  <sv-popup :model="item.popupModel"></sv-popup>
</template>

<script lang="ts" setup>
import { useBase } from "@/base";
import type { ListModel, Action } from "survey-core";

const props = defineProps<{ model: ListModel; item: Action }>();

useBase(() => props.item);
</script>
