// packages/survey-react-ui/src/components/list/list-item-content.tsx
import * as React from "react";
import { ListModel } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { SurveyElementBase } from "../../reactquestion_element";
import { SvgIcon } from "../svg-icon/svg-icon";

interface IListItemProps {
  model: ListModel;
  item: any;
}

export class ListItemContent extends SurveyElementBase<IListItemProps, any> {
  get model(): ListModel {
    return this.props.model;
  }
  get item(): any {
    return this.props.item;
  }
  getStateElement() {
    return this.item;
  }
  render(): React.JSX.Element | null {
    if(!this.item) return null;

    const text = this.renderLocString(this.item.locTitle, undefined, "locString");
    const icon = (this.item.iconName) ?
      <SvgIcon
        className={this.model.cssClasses.itemIcon}
        iconName={this.item.iconName}
        size={this.item.iconSize}
        aria-label={this.item.title}
      ></SvgIcon> : null;

    const markerIcon = (this.item.markerIconName) ?
      <SvgIcon
        className={this.item.cssClasses.itemMarkerIcon}
        iconName={this.item.markerIconName}
        size={"auto"}
      ></SvgIcon> : null;

    return <>
      {icon}
      {text}
      {markerIcon}
    </>;
  }
}

ReactElementFactory.Instance.registerElement("sv-list-item-content", (props) => {
  return React.createElement(ListItemContent, props);
});

// packages/survey-vue3-ui/src/components/list/ListItemContent.vue
<template>
  <SvComponent
    :is="'sv-svg-icon'"
    v-if="item.iconName"
    v-bind:class="model.cssClasses.itemIcon"
    :iconName="item.iconName"
    :size="item.iconSize"
  ></SvComponent>
  <SvComponent :is="'survey-string'" :locString="item.locTitle" />
  <SvComponent
    :is="'sv-svg-icon'"
    v-if="item.markerIconName"
    v-bind:class="item.cssClasses.itemMarkerIcon"
    :iconName="item.markerIconName"
    :size="'auto'"
  ></SvComponent>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useBase } from "@/base";
import type { ListModel, Action } from "survey-core";

const props = defineProps<{ model: ListModel; item: Action }>();

useBase(() => props.item);
</script>
