// packages/survey-react-ui/src/components/list/list-item.tsx
import * as React from "react";
import { ListModel } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { SurveyElementBase } from "../../reactquestion_element";
import { attachKey2click } from "../../attach-key2click";

interface IListItemProps {
  model: ListModel;
  item: any;
}

export class ListItem extends SurveyElementBase<IListItemProps, any> {
  private elementRef: React.RefObject<HTMLDivElement>;

  constructor(props: any) {
    super(props);
    this.elementRef = React.createRef();
  }

  get model(): ListModel {
    return this.props.model;
  }
  get item(): any {
    return this.props.item;
  }
  handleKeydown = (event: any) => {
    this.model.onKeyDown(event);
  };
  getStateElement() {
    return this.item;
  }
  render(): React.JSX.Element | null {
    if (!this.item) return null;
    const className = this.model.getItemClass(this.item);
    const itemContent = this.item.component || this.model.itemComponent;
    const itemData = this.item.data;
    const newElement = ReactElementFactory.Instance.createElement(itemContent, {
      item: this.item,
      key: this.item.id,
      model: this.model,
      itemData,
      survey: itemData?.survey,
      page: itemData?.page
    });
    const contentWrap =
      <div
        ref={this.elementRef}
        style={this.model.getItemStyle(this.item) as any}
        className={this.model.cssClasses.itemBody}
        title={this.item.getTooltip()}
        onMouseOver={(event: any) => { this.model.onItemHover(this.item); }}
        onMouseLeave={(event: any) => { this.model.onItemLeave(this.item); }}
      >
        {newElement}
      </div>;
    const separator = this.item.needSeparator ? <div className={this.model.cssClasses.itemSeparator} /> : null;
    const isVisible = this.model.isItemVisible(this.item);
    const style = {
      display: isVisible ? null : "none"
    };
    return attachKey2click(
      <li
        className={className}
        role={this.model.listItemRole}
        style={style as any}
        id={this.item.elementId}
        aria-selected={this.model.getA11yItemAriaSelected(this.item)}
        aria-checked={this.model.getA11yItemAriaChecked(this.item)}
        onClick={(event: any) => {
          this.model.onItemClick(this.item);
          event.stopPropagation();
        }}
        onPointerDown={(event: any) => this.model.onPointerDown(event, this.item)}>
        {separator}
        {contentWrap}
      </li>, this.item
    );
  }
  componentDidMount() {
    super.componentDidMount();

    this.model.onItemRended(this.item, this.elementRef?.current);
  }
}

ReactElementFactory.Instance.registerElement("sv-list-item", (props) => {
  return React.createElement(ListItem, props);
});

// packages/survey-vue3-ui/src/components/list/ListItem.vue
<template>
  <li
    :role="model.listItemRole"
    :aria-selected="model.getA11yItemAriaSelected(item)"
    :aria-checked="model.getA11yItemAriaChecked(item)"
    v-show="model.isItemVisible(item)"
    :key="item.id"
    :id="elementId"
    ref="elementRef"
    @pointerdown="model.onPointerDown($event, item)"
    v-bind:class="model.getItemClass(item)"
    v-on:click="click"
    v-bind:tabindex="item.disableTabStop ? -1 : 0"
    v-key2click="{ processEsc: false, disableTabStop: item.disableTabStop }"
  >
    <div
      v-if="item.needSeparator"
      v-bind:class="model.cssClasses.itemSeparator"
    ></div>

    <div
      :style="model.getItemStyle(item)"
      v-bind:class="model.cssClasses.itemBody"
      :title="item.getTooltip()"
      @mouseover="(e) => model.onItemHover(item)"
      @mouseleave="(e) => model.onItemLeave(item)"
    >
      <SvComponent
        :is="itemComponent"
        :item="item"
        :model="model"
        v-bind="item.data || {}"
      ></SvComponent>
    </div>
  </li>
</template>

<script lang="ts" setup>
import { key2ClickDirective as vKey2click } from "@/directives/key2click";
import SvComponent from "@/SvComponent.vue";
import { useBase } from "@/base";
import type { ListModel, Action, IAction } from "survey-core";
import { computed, onMounted, ref } from "vue";

const props = defineProps<{ model: ListModel; item: Action }>();
const elementRef = ref<HTMLElement>(null as any);

const elementId = computed(() => (props.item as IAction).elementId);
const click = (event: any) => {
  props.model.onItemClick(props.item as any);
  event.stopPropagation();
};

useBase(() => props.item);

const itemComponent = computed(
  () => props.item.component || props.model.itemComponent
);

onMounted(() => {
  setTimeout(() => {
    props.model.onItemRended(props.item as any, elementRef.value);
  });
});
</script>
