// packages/survey-angular-ui/src/components/loading-indicator/loading-indicator.component.ts
import { Component } from "@angular/core";
import { EmbeddedViewContentComponent } from "../../embedded-view-content.component";

@Component({
  templateUrl: "./loading-indicator.component.html",
  selector: "sv-ng-loading-indicator",
  styleUrls: ["../../hide-host.scss"]
})
export class LoadingIndicatorComponent extends EmbeddedViewContentComponent {

}
<ng-template #template>
    <div class="sd-loading-indicator">
        <svg [iconName]="'icon-loading'" [size]="'auto'" sv-ng-svg-icon></svg>
    </div>
</ng-template>

// src/vue/components/loading-indicator.vue
<template>
  <div class="sd-loading-indicator">
    <sv-svg-icon :iconName="'icon-loading'" size="'auto'"></sv-svg-icon>
  </div>
</template>
<script lang="ts">
import { Component } from 'vue-property-decorator';
import Vue from 'vue';

@Component
export class LoadingIndicatorComponent extends Vue {}

Vue.component("sv-loading-indicator", LoadingIndicatorComponent);
export default LoadingIndicatorComponent;
</script>
