// packages/survey-react-ui/src/components/paneldynamic-actions/paneldynamic-prev-btn.tsx
import * as React from "react";
import { ReactElementFactory } from "../../element-factory";
import { SvgIcon } from "../svg-icon/svg-icon";
import { SurveyQuestionPanelDynamicAction } from "./paneldynamic-add-btn";

export class SurveyQuestionPanelDynamicPrevButton extends SurveyQuestionPanelDynamicAction {
  protected handleClick = (event: any) => {
    this.question.goToPrevPanel();
  };
  protected renderElement(): React.JSX.Element {
    return (
      <div title={this.question.panelPrevText} onClick={this.handleClick} className={this.question.getPrevButtonCss()}>
        <SvgIcon
          iconName={this.question.cssClasses.progressBtnIcon}
          size={"auto"}
        >
        </SvgIcon>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-paneldynamic-prev-btn",
  (props) => {
    return React.createElement(SurveyQuestionPanelDynamicPrevButton, props);
  }
);

// src/vue/components/paneldynamic-actions/paneldynamic-prev-btn.vue
<template>
  <div :title="question.panelPrevText" @click="prevPanelClick" :class="question.getPrevButtonCss()">
    <sv-svg-icon :iconName="question.cssClasses.progressBtnIcon" :size="'auto'"></sv-svg-icon>
  </div>
</template>
      
<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { PaneldynamicAction } from "./paneldynamic-add-btn.vue";

@Component
export class PanelDynamicPrevBtn extends PaneldynamicAction {
   prevPanelClick() {
    this.question.goToPrevPanel();
  }
}
Vue.component("sv-paneldynamic-prev-btn", PanelDynamicPrevBtn);
export default PanelDynamicPrevBtn;
</script>
