// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-prev-btn.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { PaneldynamicAction } from "./paneldynamic-add-btn.component";

@Component({
  selector: "sv-ng-paneldynamic-prev-btn",
  templateUrl: "./paneldynamic-prev-btn.component.html"
})
export class PanelDynamicPrevBtn extends PaneldynamicAction {
  prevPanelClick() {
    this.question.goToPrevPanel();
  }
}
AngularComponentFactory.Instance.registerComponent("sv-paneldynamic-prev-btn", PanelDynamicPrevBtn);
<div [attr.title]="question.prevPanelText" (click)="prevPanelClick()" [class]="question.getPrevButtonCss()">
  <svg [iconName]="question.cssClasses.progressBtnIcon" [size]="'auto'" sv-ng-svg-icon></svg>
</div>

// src/vue/components/paneldynamic-actions/paneldynamic-prev-btn.vue
<template>
  <div :title="question.panelPrevText" @click="prevPanelClick" :class="question.getPrevButtonCss()">
    <sv-svg-icon :iconName="question.cssClasses.progressBtnIcon" :size="'auto'"></sv-svg-icon>
  </div>
</template>
      
<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { PaneldynamicAction } from "./paneldynamic-add-btn.vue";

@Component
export class PanelDynamicPrevBtn extends PaneldynamicAction {
   prevPanelClick() {
    this.question.goToPrevPanel();
  }
}
Vue.component("sv-paneldynamic-prev-btn", PanelDynamicPrevBtn);
export default PanelDynamicPrevBtn;
</script>
