// src/react/components/paneldynamic-actions/paneldynamic-next-btn.tsx
import React from "react";
import { ReactElementFactory } from "../../element-factory";
import { SvgIcon } from "../svg-icon/svg-icon";
import { SurveyQuestionPanelDynamicAction } from "./paneldynamic-add-btn";

export class SurveyQuestionPanelDynamicNextButton extends SurveyQuestionPanelDynamicAction {
  protected handleClick = (event: any) => {
    this.question.goToNextPanel();
  }
  protected renderElement(): JSX.Element {
    return (
      <div title={this.question.panelNextText} onClick={this.handleClick}>
        <SvgIcon
          className={this.question.getNextButtonCss()}
          iconName={this.question.cssClasses.progressBtnIcon}
          size={"auto"}
        >
        </SvgIcon>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-paneldynamic-next-btn",
  (props) => {
    return React.createElement(SurveyQuestionPanelDynamicNextButton, props);
  }
);

// src/vue/components/paneldynamic-actions/paneldynamic-next-btn.vue
<template>
  <div :title="question.panelNextText" @click="nextPanelClick" :class="question.getNextButtonCss()">
    <sv-svg-icon :iconName="question.cssClasses.progressBtnIcon" :size="'auto'"></sv-svg-icon>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { PaneldynamicAction } from "./paneldynamic-add-btn.vue";

@Component
export class PanelDynamicNextBtn extends PaneldynamicAction {
  nextPanelClick() {
    this.question.goToNextPanel();
  }
}
Vue.component("sv-paneldynamic-next-btn", PanelDynamicNextBtn);
export default PanelDynamicNextBtn;
</script>
