// packages/survey-vue3-ui/src/BooleanRadioItem.vue
<template>
  <div
    role="presentation"
    :class="question.getRadioItemClass(question.cssClasses, value)"
  >
    <label :class="question.cssClasses.radioLabel">
      <input
        type="radio"
        :name="question.name"
        :value="value"
        :checked="value === question.value"
        :aria-errormessage="question.ariaErrormessage"
        :disabled="question.isDisabledAttr"
        :readonly="question.isReadOnlyAttr"
        :class="question.cssClasses.itemRadioControl"
        @change="handleChange"
      />
      <span
        v-if="question.cssClasses.materialRadioDecorator"
        :class="question.cssClasses.materialRadioDecorator"
      >
        <svg
          v-if="question.itemSvgIcon"
          :class="question.cssClasses.itemRadioDecorator"
        >
          <use :xlink:href="question.itemSvgIcon"></use>
        </svg>
      </span>
      <span :class="question.cssClasses.radioControlLabel">
        <SvComponent :is="'survey-string'" :locString="locText" />
      </span>
    </label>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { LocalizableString, QuestionBooleanModel } from "survey-core";

const props = defineProps<{
  question: QuestionBooleanModel;
  locText: LocalizableString;
  value: string | boolean;
}>();
const handleChange = () => {
  const question = props.question;
  if (!question.isInputReadOnly) {
    question.value = props.value;
  }
};
</script>

// packages/survey-angular-ui/src/components/renderAs/boolean-radio/boolean-radio-item.component.ts
import { Component, Input } from "@angular/core";
import { LocalizableString, QuestionBooleanModel } from "survey-core";
@Component({
  selector: "sv-ng-boolean-radio-item",
  templateUrl: "boolean-radio-item.component.html",
})
export class BooleanRadioItemComponent {
  @Input() question!: QuestionBooleanModel;
  @Input() value!: string | boolean;
  @Input() locText!: LocalizableString;
  constructor() {

  }
  public change() {
    if (!this.question.isInputReadOnly) {
      this.question.value = this.value;
    }
  }
}

<div role="presentation" [class]="question.getRadioItemClass(question.cssClasses, value)">
  <label [class]="question.cssClasses.radioLabel">
    <input
      type="radio"
      [attr.name]="question.name" [attr.aria-errormessage]="question.ariaErrormessage" [value]="value" [(ngModel)]="question.booleanValue"
      [disabled]="question.isDisabledAttr" [readonly]="question.isReadOnlyAttr" [class]="question.cssClasses.itemRadioControl || ''"
    />
    <span *ngIf="question.cssClasses.materialRadioDecorator" [class]="question.cssClasses.materialRadioDecorator">
      <svg
        *ngIf="question.itemSvgIcon"
        [class]="question.cssClasses.itemRadioDecorator"
      >
        <use [attr.xlink:href]="question.itemSvgIcon"></use>
      </svg>
    </span>
    <span [class]="question.cssClasses.radioControlLabel" [model]="locText" sv-ng-string>
    </span>
  </label>
</div>
