// src/vue/components/notifier.vue
<template>
  <div v-bind:class="model.css" v-if="model.isDisplayed"
    :style="{ visibility: model.active ? 'visible' : 'hidden' }" role="alert" aria-live="polite">
    <span>{{ model.message }}</span>
    <sv-action-bar :model="model.actionBar"></sv-action-bar>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { Notifier } from "survey-core";
import { BaseVue } from "../base";

@Component
export class NotifierComponent extends BaseVue {
  @Prop() model: Notifier;

  constructor() {
    super();
  }

  getModel() {
    return this.model;
  }
}

Vue.component("sv-notifier", NotifierComponent);

export default NotifierComponent;
</script>

// packages/survey-angular-ui/src/components/notifier/notifier.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { Base, Notifier } from "survey-core";

@Component({
  selector: "sv-notifier",
  templateUrl: "./notifier.component.html",
  styles: [":host { display: none; }"]
})
export class NotifierComponent extends BaseAngular<Notifier> {
  @Input() notifier!: Notifier;
  protected getStateElement(): Base {
    return this.notifier;
  }
  protected getModel(): Notifier {
    return this.notifier;
  }
}
<ng-template #template>
  <ng-container *ngIf="notifier.isDisplayed">
    <div [class]="notifier.css" [style]="{ visibility: notifier.active ? 'visible' : 'hidden' }" role="alert" aria-live="polite">
      <span>{{notifier.message}}</span>
      <sv-action-bar [model]="notifier.actionBar"></sv-action-bar> 
    </div>
  </ng-container>
</ng-template>
