// src/react/components/file/file-page.tsx
import React from "react";
import { SurveyElementBase } from "../../reactquestion_element";
import { QuestionFileModel, QuestionFilePage } from "survey-core";
import { SurveyFileItem } from "./file-item";

export class SurveyFilePage extends SurveyElementBase<{ question: QuestionFileModel, page: QuestionFilePage }, {}> {
  protected get question(): QuestionFileModel {
    return this.props.question;
  }

  protected get page(): any {
    return this.props.page;
  }

  protected renderElement(): JSX.Element | null {
    const items = this.page.items.map((item: any, index: number) => { return (<SurveyFileItem item={item} question={this.question} key={index}></SurveyFileItem>); });
    return (
      <div className={this.page.css} id={this.page.id} >
        {items}
      </div>
    );
  }
}

// src/vue/components/file/file-page.vue
<template>
  <div :class="page.css" :id="page.id">
    <sv-file-item
      v-for="(item, index) of page.items"
      :key="index"
      :item="item"
      :question="question"
    ></sv-file-item>
  </div>
</template>
<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { QuestionFilePage, QuestionFileModel } from "survey-core";
@Component
export class FilePage extends Vue {
  @Prop() page: QuestionFilePage;
  @Prop() question: QuestionFileModel;
}
Vue.component("sv-file-page", FilePage);
export default FilePage;
</script>
