// packages/survey-react-ui/src/components/title/title-actions.tsx
import React from "react";
import { SurveyElement, RendererFactory } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { SurveyActionBar } from "../action-bar/action-bar";
import { TitleContent } from "./title-content";

export class TitleActions extends React.Component<any, any> {
  protected get cssClasses() {
    return this.props.cssClasses;
  }
  protected get element(): SurveyElement {
    return this.props.element;
  }

  render(): React.JSX.Element {
    const titleContent: React.JSX.Element = <TitleContent element={this.element} cssClasses={this.cssClasses}></TitleContent>;
    if (!this.element.hasTitleActions) return titleContent;
    return (
      <div className="sv-title-actions">
        <span className="sv-title-actions__title">{titleContent}</span>
        <SurveyActionBar model={this.element.getTitleToolbar()}></SurveyActionBar>
      </div>
    );
  }
}

RendererFactory.Instance.registerRenderer(
  "element",
  "title-actions",
  "sv-title-actions"
);

ReactElementFactory.Instance.registerElement("sv-title-actions", (props) => {
  return React.createElement(TitleActions, props);
});

// src/vue/components/title/title-actions.vue
<template>
  <div class="sv-title-actions">
    <span class="sv-title-actions__title">
      <survey-string v-if="element.isPage" :locString="element.locTitle"></survey-string>
      <survey-element-title-content
        v-if="!element.isPage"
        :element="element"
        :css="css"
      ></survey-element-title-content>
    </span>
    <sv-action-bar :model="toolbar"></sv-action-bar>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import {
  Action,
  AdaptiveActionContainer,
  ISurveyElement,
  RendererFactory,
} from "survey-core";

@Component
export class TitleActions extends Vue {
  @Prop() element: ISurveyElement;
  @Prop() css: any;
  constructor() {
    super();
  }

  public get toolbar(): AdaptiveActionContainer<Action> {
    return this.element.getTitleToolbar();
  }
}

RendererFactory.Instance.registerRenderer("element", "title-actions", "sv-title-actions");

Vue.component("sv-title-actions", TitleActions);
export default TitleActions;
</script>
