// src/react/components/title-actions/title-actions.tsx
import React from "react";
import { ISurveyElement, RendererFactory } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { SurveyElementBase } from "../../reactquestion_element";
import { SurveyActionBar } from "../action-bar/action-bar";
import { TitleContent } from "../title-content/title-content";

export class TitleActions extends React.Component<any, any> {
  protected get cssClasses() {
    return this.props.cssClasses;
  }
  protected get element(): ISurveyElement {
    return this.props.element;
  }

  render(): JSX.Element {
    /*
    const titleContent: JSX.Element = !this.element.isPage ? (
      <TitleContent
        element={this.element}
        cssClasses={this.cssClasses}
      ></TitleContent>
    ) : (
      <>{SurveyElementBase.renderLocString((this.element as any).locTitle)}</>
    );
    */
    const titleContent: JSX.Element = <TitleContent element={this.element} cssClasses={this.cssClasses}></TitleContent>;
    return (
      <div className="sv-title-actions">
        <span className="sv-title-actions__title">{titleContent}</span>
        <SurveyActionBar model={this.element.getTitleToolbar()}></SurveyActionBar>
      </div>
    );
  }
}

RendererFactory.Instance.registerRenderer(
  "element",
  "title-actions",
  "sv-title-actions"
);

ReactElementFactory.Instance.registerElement("sv-title-actions", (props) => {
  return React.createElement(TitleActions, props);
});

// packages/survey-vue3-ui/src/components/title/TitleActions.vue
<template>
  <div class="sv-title-actions">
    <span class="sv-title-actions__title">
      <survey-string
        v-if="element.isPage"
        :locString="element.locTitle"
      ></survey-string>
      <survey-element-title-content
        v-if="!element.isPage"
        :element="element"
        :css="css"
      ></survey-element-title-content>
    </span>
    <sv-action-bar :model="toolbar"></sv-action-bar>
  </div>
</template>

<script lang="ts" setup>
import type { PanelModel, Question } from "survey-core";
import { computed } from "vue";

const props = defineProps<{
  element: Question | PanelModel;
  css: any;
}>();
const toolbar = computed(() => props.element.getTitleToolbar());
</script>
