// src/react/components/file/file-item.tsx
import React from "react";
import { SurveyElementBase } from "../../reactquestion_element";
import { QuestionFileModel } from "survey-core";
import { SvgIcon } from "../svg-icon/svg-icon";

export class SurveyFileItem extends SurveyElementBase<{ question: QuestionFileModel, item: any }, {}> {

  protected get question(): QuestionFileModel {
    return this.props.question;
  }

  protected get item(): any {
    return this.props.item;
  }

  protected renderFileSign(className: string, val: any): JSX.Element | null {
    if(!className || !val.name) return null;
    return (
      <div className={className}>
        <a
          href={val.content}
          onClick={event => {
            this.question.doDownloadFile(event, val);
          }}
          title={val.name}
          download={val.name}
          style={{ width: this.question.imageWidth }}
        >
          {val.name}
        </a>
      </div>
    );
  }

  protected renderElement(): JSX.Element | null {
    const val = this.item;
    return (
      <span
        className={this.question.cssClasses.previewItem}
      >
        {this.renderFileSign(this.question.cssClasses.fileSign, val)}
        <div className={this.question.getImageWrapperCss(val)}>
          {this.question.canPreviewImage(val) ? (
            <img
              src={val.content}
              style={{ height: this.question.imageHeight, width: this.question.imageWidth }}
              alt="File preview"
            />
          ) : (this.question.cssClasses.defaultImage?(
            <SvgIcon iconName={this.question.cssClasses.defaultImageIconId} size={"auto"} className={this.question.cssClasses.defaultImage}></SvgIcon>
          ):null)}
          {val.name && !this.question.isReadOnly ? (
            <div className={this.question.getRemoveButtonCss()} onClick={() => this.question.doRemoveFile(val)}>
              <span
                className={this.question.cssClasses.removeFile}
              >
                {this.question.removeFileCaption}
              </span>
              {(this.question.cssClasses.removeFileSvgIconId) ?
                (<SvgIcon title={this.question.removeFileCaption} iconName={this.question.cssClasses.removeFileSvgIconId} size={"auto"} className={this.question.cssClasses.removeFileSvg}></SvgIcon>): null }
            </div>
          ) : null}
        </div>
        {this.renderFileSign(this.question.cssClasses.fileSignBottom, val)}
      </span>
    );
  }
  protected canRender(): boolean {
    return this.question.showPreviewContainer;
  }
}

// packages/survey-vue3-ui/src/components/file/FileItem.vue
<template>
  <span v-show="item" :class="question.cssClasses.previewItem">
    <div
      v-if="item.name && question.cssClasses.fileSign"
      :class="question.cssClasses.fileSign"
    >
      <a
        @click="question.doDownloadFile($event, item)"
        :href="item.content"
        :title="item.name"
        :download="item.name"
        :style="{ width: question.imageWidth }"
        >{{ item.name }}</a
      >
    </div>
    <div :class="question.getImageWrapperCss(item)">
      <img
        v-if="question.canPreviewImage(item)"
        :src="item.content"
        :style="{
          height: question.imageHeight,
          width: question.imageWidth,
        }"
        alt="File preview"
      />
      <sv-svg-icon
        v-if="question.defaultImage(item)"
        :iconName="question.cssClasses.defaultImageIconId"
        :class="question.cssClasses.defaultImage"
        :size="'auto'"
      ></sv-svg-icon>
      <div
        v-if="item.name && !question.isReadOnly"
        :class="question.getRemoveButtonCss()"
        @click="question.doRemoveFile(item)"
      >
        <span :class="question.cssClasses.removeFile">{{
          question.removeFileCaption
        }}</span>
        <sv-svg-icon
          v-if="question.cssClasses.removeFileSvgIconId"
          :title="question.removeFileCaption"
          :class="question.cssClasses.removeFileSvg"
          :iconName="question.cssClasses.removeFileSvgIconId"
          :size="'auto'"
        ></sv-svg-icon>
      </div>
    </div>
    <div
      v-if="item.name && question.cssClasses.fileSignBottom"
      :class="question.cssClasses.fileSignBottom"
    >
      <a
        @click="question.doDownloadFile($event, item)"
        :href="item.content"
        :title="item.name"
        :download="item.name"
        :style="{ width: question.imageWidth }"
        >{{ item.name }}</a
      >
    </div>
  </span>
</template>
<script lang="ts" setup>
import type { QuestionFileModel } from "survey-core";
defineProps<{ item: any; question: QuestionFileModel }>();
</script>
