// packages/survey-angular-ui/src/components/file/file-preview.component.ts
import { Action, QuestionFileModel } from "survey-core";
import { AngularComponentFactory } from "../../component-factory";
import { Component, Input } from "@angular/core";
import { EmbeddedViewContentComponent } from "../../embedded-view-content.component";
@Component({
  selector: "sv-ng-file-preview",
  templateUrl: "./file-preview.component.html"
})
export class FilePreviewComponent extends EmbeddedViewContentComponent {
    @Input() question!: QuestionFileModel;
    trackFilesFn: (index: number) => string = (index: number): string => {
      return this.question.inputId + "_" + index;
    }
}
AngularComponentFactory.Instance.registerComponent("sv-file-preview", FilePreviewComponent);
<ng-template #template>
    <ng-container *ngIf="question.showPreviewContainer">
        <div [class]="question.cssClasses.fileList || undefined">
            <span *ngFor="let val of question.previewValue; index as index; trackBy: trackFilesFn"
                [visible]="val && question.isPreviewVisible(index)" [class]="question.cssClasses.previewItem"
                (click)="question.doDownloadFileFromContainer($event)">
                <div *ngIf="val.name && question.cssClasses.fileSign" [class]="question.cssClasses.fileSign">
                    <a (click)="question.doDownloadFile($event, val)" [attr.href]="val.content | safeUrl"
                        [attr.title]="val.name" [attr.download]="val.name" [style.width]="question.imageWidth">{{
                        val.name
                        }}</a>
                </div>
                <div [class]="question.getImageWrapperCss(val)">
                    <img *ngIf="question.canPreviewImage(val)" [attr.src]="val.content | safeUrl"
                        [style.height]="question.imageHeight" [style.width]="question.imageWidth" alt="File preview" />
                    <svg *ngIf="question.defaultImage(val)" [iconName]="question.cssClasses.defaultImageIconId"
                        [partCss]="question.cssClasses.defaultImage" [size]="'auto'" sv-ng-svg-icon></svg>
                    <div *ngIf="val.name && !question.isReadOnly" [class]="question.getRemoveButtonCss()"
                        (click)="question.doRemoveFile(val, $event)">
                        <span [class]="question.cssClasses.removeFile">{{ question.removeFileCaption }}</span>
                        <svg *ngIf="question.cssClasses.removeFileSvgIconId" [title]="question.removeFileCaption"
                            [partCss]="question.cssClasses.removeFileSvg"
                            [iconName]="question.cssClasses.removeFileSvgIconId" [size]="'auto'" sv-ng-svg-icon></svg>
                    </div>
                </div>
                <div *ngIf="val.name && question.cssClasses.fileSignBottom"
                    [class]="question.cssClasses.fileSignBottom">
                    <a (click)="question.doDownloadFile($event, val)" [attr.href]="val.content | safeUrl"
                        [attr.title]="val.name" [attr.download]="val.name" [style.width]="question.imageWidth">{{
                        val.name
                        }}</a>
                </div>
            </span>
        </div>
    </ng-container>
</ng-template>

// packages/survey-vue3-ui/src/components/file/FilePreview.vue
<template>
  <div
    v-if="question.showPreviewContainer"
    :class="question.cssClasses.fileList || undefined"
  >
    <span
      v-for="(val, index) in question.previewValue"
      :key="question.inputId + '_' + index"
      v-show="val && question.isPreviewVisible(index)"
      :class="question.cssClasses.previewItem"
      @click="question.doDownloadFileFromContainer($event)"
    >
      <div
        v-if="val.name && question.cssClasses.fileSign"
        :class="question.cssClasses.fileSign"
      >
        <a
          @click="question.doDownloadFile($event, val)"
          :href="val.content"
          :title="val.name"
          :download="val.name"
          :style="{ width: question.imageWidth }"
          >{{ val.name }}</a
        >
      </div>
      <div :class="question.getImageWrapperCss(val)">
        <img
          v-if="question.canPreviewImage(val)"
          :src="val.content"
          :style="{
            height: question.imageHeight,
            width: question.imageWidth,
          }"
          alt="File preview"
        />
        <SurveyVueComponent
          :name="'sv-svg-icon'"
          v-if="question.defaultImage(val)"
          :iconName="question.cssClasses.defaultImageIconId"
          :class="question.cssClasses.defaultImage"
          :size="'auto'"
        ></SurveyVueComponent>
        <div
          v-if="val.name && !question.isReadOnly"
          :class="question.getRemoveButtonCss()"
          @click="question.doRemoveFile(val, $event)"
        >
          <span :class="question.cssClasses.removeFile">{{
            question.removeFileCaption
          }}</span>
          <SurveyVueComponent
            :name="'sv-svg-icon'"
            v-if="question.cssClasses.removeFileSvgIconId"
            :title="question.removeFileCaption"
            :class="question.cssClasses.removeFileSvg"
            :iconName="question.cssClasses.removeFileSvgIconId"
            :size="'auto'"
          ></SurveyVueComponent>
        </div>
      </div>
      <div
        v-if="val.name && question.cssClasses.fileSignBottom"
        :class="question.cssClasses.fileSignBottom"
      >
        <a
          @click="question.doDownloadFile($event, val)"
          :href="val.content"
          :title="val.name"
          :download="val.name"
          :style="{ width: question.imageWidth }"
          >{{ val.name }}</a
        >
      </div>
    </span>
  </div>
</template>

<script setup lang="ts">
import type { QuestionFileModel } from "survey-core";
import SurveyVueComponent from "@/SurveyVueComponent.vue";
defineProps<{ question: QuestionFileModel }>();
</script>
