// packages/survey-react-ui/src/components/file/file-preview.tsx
import React from "react";
import { SurveyElementBase } from "../../reactquestion_element";
import { QuestionFileModel } from "survey-core";
import { SvgIcon } from "../svg-icon/svg-icon";
import { ReactElementFactory } from "../../element-factory";

export class SurveyFilePreview extends SurveyElementBase<{ question: QuestionFileModel }, {}> {

  protected get question(): QuestionFileModel {
    return this.props.question;
  }

  protected renderFileSign(className: string, val: any): JSX.Element | null {
    if(!className || !val.name) return null;
    return (
      <div className={className}>
        <a
          href={val.content}
          onClick={event => {
            this.question.doDownloadFile(event, val);
          }}
          title={val.name}
          download={val.name}
          style={{ width: this.question.imageWidth }}
        >
          {val.name}
        </a>
      </div>
    );
  }

  protected renderElement(): JSX.Element | null {
    var previews = this.question.previewValue.map((val, index) => {
      if (!val) return null;
      return (
        <span
          key={this.question.inputId + "_" + index}
          className={this.question.cssClasses.previewItem}
          onClick={(event) => this.question.doDownloadFileFromContainer(event as any)}
          style={{ display: this.question.isPreviewVisible(index) ? undefined : "none" }}
        >
          {this.renderFileSign(this.question.cssClasses.fileSign, val)}
          <div className={this.question.getImageWrapperCss(val)}>
            {this.question.canPreviewImage(val) ? (
              <img
                src={val.content}
                style={{ height: this.question.imageHeight, width: this.question.imageWidth }}
                alt="File preview"
              />
            ) : (this.question.cssClasses.defaultImage?(
              <SvgIcon iconName={this.question.cssClasses.defaultImageIconId} size={"auto"} className={this.question.cssClasses.defaultImage}></SvgIcon>
            ):null)}
            {val.name && !this.question.isReadOnly ? (
              <div className={this.question.getRemoveButtonCss()} onClick={(event) => this.question.doRemoveFile(val, event)}>
                <span
                  className={this.question.cssClasses.removeFile}
                >
                  {this.question.removeFileCaption}
                </span>
                {(this.question.cssClasses.removeFileSvgIconId) ?
                  (<SvgIcon title={this.question.removeFileCaption} iconName={this.question.cssClasses.removeFileSvgIconId} size={"auto"} className={this.question.cssClasses.removeFileSvg}></SvgIcon>): null }
              </div>
            ) : null}
          </div>
          {this.renderFileSign(this.question.cssClasses.fileSignBottom, val)}
        </span>
      );
    });
    return <div className={this.question.cssClasses.fileList || undefined}>{previews}</div>;
  }
  protected canRender(): boolean {
    return this.question.showPreviewContainer;
  }
}
ReactElementFactory.Instance.registerElement(
  "sv-file-preview",
  (props) => {
    return React.createElement(SurveyFilePreview, props);
  }
);

// packages/survey-vue3-ui/src/components/file/FilePreview.vue
<template>
  <div
    v-if="question.showPreviewContainer"
    :class="question.cssClasses.fileList || undefined"
  >
    <span
      v-for="(val, index) in question.previewValue"
      :key="question.inputId + '_' + index"
      v-show="val && question.isPreviewVisible(index)"
      :class="question.cssClasses.previewItem"
      @click="question.doDownloadFileFromContainer($event)"
    >
      <div
        v-if="val.name && question.cssClasses.fileSign"
        :class="question.cssClasses.fileSign"
      >
        <a
          @click="question.doDownloadFile($event, val)"
          :href="val.content"
          :title="val.name"
          :download="val.name"
          :style="{ width: question.imageWidth }"
          >{{ val.name }}</a
        >
      </div>
      <div :class="question.getImageWrapperCss(val)">
        <img
          v-if="question.canPreviewImage(val)"
          :src="val.content"
          :style="{
            height: question.imageHeight,
            width: question.imageWidth,
          }"
          alt="File preview"
        />
        <SurveyVueComponent
          :name="'sv-svg-icon'"
          v-if="question.defaultImage(val)"
          :iconName="question.cssClasses.defaultImageIconId"
          :class="question.cssClasses.defaultImage"
          :size="'auto'"
        ></SurveyVueComponent>
        <div
          v-if="val.name && !question.isReadOnly"
          :class="question.getRemoveButtonCss()"
          @click="question.doRemoveFile(val, $event)"
        >
          <span :class="question.cssClasses.removeFile">{{
            question.removeFileCaption
          }}</span>
          <SurveyVueComponent
            :name="'sv-svg-icon'"
            v-if="question.cssClasses.removeFileSvgIconId"
            :title="question.removeFileCaption"
            :class="question.cssClasses.removeFileSvg"
            :iconName="question.cssClasses.removeFileSvgIconId"
            :size="'auto'"
          ></SurveyVueComponent>
        </div>
      </div>
      <div
        v-if="val.name && question.cssClasses.fileSignBottom"
        :class="question.cssClasses.fileSignBottom"
      >
        <a
          @click="question.doDownloadFile($event, val)"
          :href="val.content"
          :title="val.name"
          :download="val.name"
          :style="{ width: question.imageWidth }"
          >{{ val.name }}</a
        >
      </div>
    </span>
  </div>
</template>

<script setup lang="ts">
import type { QuestionFileModel } from "survey-core";
import SurveyVueComponent from "@/SurveyVueComponent.vue";
defineProps<{ question: QuestionFileModel }>();
</script>
