// packages/survey-angular-ui/src/questions/customwidget.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnChanges, OnDestroy, SimpleChanges, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { Question } from "survey-core";

@Component(
  {
    templateUrl: "./customwidget.component.html",
    selector: "sv-ng-custom-widget"
  }
)
export class CustomWidgetComponent implements AfterViewInit, OnDestroy, OnChanges {
  @Input() css: any;
  @Input() model!: Question;

  @ViewChild("content") container!: ElementRef<HTMLDivElement>;

  get hasDefaultRender(): boolean {
    return this.model.customWidget.isDefaultRender || this.hasAngularComponent;
  }
  get hasHtml(): boolean {
    return this.model.customWidget.htmlTemplate ? true : false;
  }
  get customHtml(): string {
    return this.model.customWidget.htmlTemplate;
  }
  get hasAngularComponent(): boolean {
    return AngularComponentFactory.Instance.isComponentRegistered(this.model.customWidget.name);
  }
  get componentName(): string {
    if (this.hasAngularComponent) return this.model.customWidget.name;
    return this.model.getTemplate() + "-question";
  }
  ngAfterViewInit(): void {
    this.model.customWidget.afterRender(this.model, this.container.nativeElement);
  }
  ngOnChanges(simpleChanges: SimpleChanges) {
    if(simpleChanges["model"].previousValue !== undefined && simpleChanges["model"].currentValue !== undefined) {
      this.model.customWidget.afterRender(this.model, this.container.nativeElement);
    }
  }
  ngOnDestroy(): void {
    this.model.customWidget.willUnmount(this.model, this.container.nativeElement);
  }

}

AngularComponentFactory.Instance.registerComponent("survey-customwidget", CustomWidgetComponent);

<div #content>
  <div *ngIf="hasHtml" [innerHTML]="customHtml | safeHtml"></div>
  <ng-container *ngIf="hasDefaultRender">
    <ng-template [component]="{ name: componentName, data: { model: model, css: css } }"></ng-template>  
  </ng-container>
</div>

// packages/survey-vue-ui/src/CustomWidget.vue
<template>
  <div>
    <div v-if="hasHtml" v-html="customHtml"></div>
    <component
      v-if="hasDefaultRender"
      :is="componentName"
      :question="question"
      :css="css"
    />
  </div>
</template>
<script lang="ts">
import type { Question } from "survey-core";
import { defineComponent, type PropType } from "vue";

export default defineComponent({
  props: {
    question: { type: Object as PropType<Question>, required: true },
    css: Object,
  },
  computed: {
    hasDefaultRender(): boolean {
      return this.question.customWidget.isDefaultRender;
    },
    hasHtml(): boolean {
      return this.question.customWidget.htmlTemplate ? true : false;
    },
    customHtml(): string {
      return this.question.customWidget.htmlTemplate;
    },
    componentName(): string {
      return "survey-" + this.question.getTemplate();
    },
  },
  mounted() {
    this.question.customWidget.afterRender(this.question, this.$el);
  },
  beforeUnmount() {
    this.question.customWidget.willUnmount(this.question, this.$el);
  },
});
</script>
