// packages/survey-angular-ui/src/components/renderAs/dropdown-select/dropdown-select.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { RendererFactory } from "survey-core";

@Component({
  selector: "sv-ng-dropdown-select-question",
  templateUrl: "./dropdown-select.component.html"
})
export class DropdownSelectComponent {
  @Input() model: any;

  get editableValue() {
    return this.model.renderedValue || "";
  }
  set editableValue(newValue: any) {
    if(newValue === "") {
      this.model.renderedValue = undefined;
    } else {
      this.model.renderedValue = newValue;
    }
  }

  click(event: any) {
    this.model.onClick(event);
  }
  keyup(event: any) {
    this.model.onKeyUp(event);
  }
}

AngularComponentFactory.Instance.registerComponent("dropdown-select-question", DropdownSelectComponent);
RendererFactory.Instance.registerRenderer("dropdown", "select", "dropdown-select-question");
<div [class]="model.renderCssRoot">
  <div [class]="model.cssClasses.selectWrapper">
    <select *ngIf="!model.isReadOnly" [attr.id]="model.inputId" [(ngModel)]="editableValue"
      [disabled]="model.isInputReadOnly" (click)="click($event)" (keyup)="keyup($event)"
      [class]="model.getControlClass()" [attr.autocomplete]="model.autoComplete" [required]="model.isRequired"
      [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel"
      [attr.aria-invalid]="model.ariaInvalid" [attr.aria-describedby]="model.ariaDescribedBy">
      <option *ngIf="model.allowClear" value="">{{ model.placeholder }}</option>
      <ng-template *ngFor="let item of model.visibleChoices" [component]="{ name: 'sv-dropdown-option-item', data: { item } }"></ng-template>
    </select>
    <div *ngIf="model.isReadOnly" disabled [class]="model.getControlClass()" [attr.id]="model.inputId">{{ model.readOnlyText }}</div>
  </div>
  <div *ngIf="model.hasOther && model.isOtherSelected" class="form-group"
    [style.display]="model.isFlowLayout ? 'inline': '' " [question]="model" sv-ng-comment></div>
</div>

// packages/survey-vue-ui/src/DropdownSelect.vue
<template>
  <div :class="question.renderCssRoot">
    <div :class="question.cssClasses.selectWrapper">
      <select
        v-if="!question.isReadOnly"
        :id="question.inputId"
        v-model="renderedValue"
        @click="click"
        @keyup="keyUp"
        :autocomplete="question.autocomplete"
        :class="question.getControlClass()"
        :aria-required="question.ariaRequired"
        :aria-label="question.ariaLabel"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
        :required="question.isRequired"
      >
        <option v-if="question.allowClear" :value="''">
          {{ question.placeholder }}
        </option>
        <sv-dropdown-option-item
          v-for="item in question.visibleChoices"
          :item="item"
          :key="item.id"
        ></sv-dropdown-option-item>
      </select>
      <div
        disabled
        v-else
        :id="question.inputId"
        :class="question.getControlClass()"
      >
        {{ question.readOnlyText }}
      </div>
    </div>
    <survey-other-choice v-if="question.isOtherSelected" :question="question" />
  </div>
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import { useQuestion } from "./base";
import type { QuestionDropdownModel } from "survey-core";
const props = defineProps<{ question: QuestionDropdownModel }>();
const root = ref(null);
useQuestion(props, root);
const click = (event: any) => {
  props.question.onClick(event);
};
const keyUp = (event: any) => {
  props.question.onKeyUp(event);
};
const renderedValue = computed({
  get() {
    return props.question.value;
  },
  set(val) {
    const question = props.question;
    question.renderedValue = val;
  },
});
</script>

<script lang="ts">
import { RendererFactory } from "survey-core";
RendererFactory.Instance.registerRenderer(
  "dropdown",
  "select",
  "sv-dropdown-select"
);
</script>
