// packages/survey-angular-ui/src/errors.component.ts
import { Component, HostBinding, Input } from "@angular/core";
import { SurveyElement } from "survey-core";

@Component({
  templateUrl: "./errors.component.html",
  selector: "'[sv-ng-errors]'"
})
export class ErrorsComponent {
  @Input() element!: SurveyElement | any;
  @Input() location?: string;
  constructor() {}
  @HostBinding("attr.role") get role (): string {
    return "alert";
  }
  @HostBinding("id") get id(): string {
    return this.element.id + "_errors";
  }
  @HostBinding("attr.aria-live") get ariaLive(): string {
    return "polite";
  }
  @HostBinding("class") get class(): string {
    return this.element.cssError;
  }
}
<div *ngFor="let error of element.errors;">
  <div>
  <span
    [class]="element.cssClasses ? element.cssClasses.error.icon : 'panel-error-icon'"
    aria-hidden="true"
  ></span>
  <span [class]="element.cssClasses ? element.cssClasses.error.item : 'panel-error-item'" [model]="error.locText" sv-ng-string>
  </span>
  </div>
</div>

// packages/survey-vue-ui/src/Errors.vue
<template>
  <div
    role="alert"
    aria-live="polite"
    v-if="element.hasVisibleErrors"
    :class="element.cssError"
    :id="element.id + '_errors'"
    ref="root"
  >
    <div v-for="(error, index) in element.errors" :key="'error_' + index">
      <span
        :class="
          element.cssClasses
            ? element.cssClasses.error.icon || undefined
            : 'panel-error-icon'
        "
        aria-hidden="true"
      ></span>
      <span
        :class="
          element.cssClasses
            ? element.cssClasses.error.item || undefined
            : 'panel-error-item'
        "
      >
        <survey-string :locString="error.locText" />
      </span>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { type PanelModel, type Question, TooltipManager } from "survey-core";
import { onUnmounted, onUpdated, ref } from "vue";

const props = defineProps<{
  element: Question | PanelModel;
  location?: string;
}>();
const root = ref<HTMLElement>();
let tooltipManager: TooltipManager;

onUpdated(() => {
  if (props.location == "tooltip" && root.value instanceof HTMLElement) {
    if (!tooltipManager || root.value !== tooltipManager.tooltipElement) {
      tooltipManager = new TooltipManager(root.value as HTMLElement);
    }
  }
  if (!(root.value instanceof HTMLElement) && !!tooltipManager) {
    tooltipManager.dispose();
  }
});
onUnmounted(() => {
  if (tooltipManager) {
    tooltipManager.dispose();
  }
});
</script>
