// packages/survey-angular-ui/src/questions/imagepicker.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionImagePickerModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-imagepicker-question",
  templateUrl: "./imagepicker.component.html"
})
export class ImagePickerQuestionComponent extends QuestionAngular<QuestionImagePickerModel> {}

AngularComponentFactory.Instance.registerComponent("imagepicker-question", ImagePickerQuestionComponent);
  <fieldset [class]="model.getSelectBaseRootCss()" #contentElement>
      <legend [attr.aria-label]="model.locTitle.renderedHtml" role="radio"></legend>
      <ng-container *ngIf="!model.hasColumns">
        <ng-container *ngFor="let item of model.visibleChoices">
          <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
        </ng-container>
      </ng-container>
      <ng-container *ngIf="model.hasColumns">
        <div *ngFor="let column of model.columns" [class]="model.getColumnClass()" role="presentation">
          <ng-container *ngFor="let item of column">
            <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
          </ng-container>
        </div>
      </ng-container>
  </fieldset>

// packages/survey-vue-ui/src/Imagepicker.vue
<template>
  <fieldset :class="question.getSelectBaseRootCss()">
    <legend
      role="radio"
      v-bind:aria-label="question.locTitle.renderedHtml"
    >
    </legend>
    <survey-imagepicker-item v-if="!question.hasColumns" v-for="(item) in question.visibleChoices" :key="item.value" :question="question" :item="item"></survey-imagepicker-item>  
    <div
      v-if="question.hasColumns"
      v-for="(column, colIndex) in question.columns"
      :class="question.getColumnClass()"
      :key="colIndex"
      role="presentation"
    >
      <survey-imagepicker-item
        v-for="(item) in column"
        :key="item.value"
        :question="question"
        :item="item"
      ></survey-imagepicker-item>
    </div>
  </fieldset>
</template>

<script lang="ts">
import { QuestionImagePickerModel } from "survey-core";
import { defineSurveyComponent } from "./base";

export default defineSurveyComponent({
  // eslint-disable-next-line
  name: "survey-imagepicker",
  props: {
    question: QuestionImagePickerModel,
    css: Object,
  },
  data: (vm: any) => {
    return {
      getModel: () => { return vm.question; },
    };
  },
  methods: {
    getItemClass(item: any) {
      return this.question.getItemClass(item);
    },
  },
});
</script>
