// packages/survey-angular-ui/src/questions/multipletext.component.ts
import { QuestionAngular } from "../question";
import { MultipleTextItemModel, QuestionMultipleTextModel } from "survey-core";
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-multipletext-question",
  templateUrl: "./multipletext.component.html"
})
export class MultipleTextComponent extends QuestionAngular<QuestionMultipleTextModel> {
  trackRowBy = (index: number): string => {
    return this.model.inputId + "rowkey" + index;
  }
  trackItemBy (_: number, item: MultipleTextItemModel): string {
    return "item" + item.editor.id;
  }
}

AngularComponentFactory.Instance.registerComponent("multipletext-question", MultipleTextComponent);
<table [class]="model.cssClasses.root" #contentElement>
  <tbody>
    <tr
      *ngFor="let row of model.getRows(); index as rowIndex; trackBy: trackRowBy"
      [class]="model.cssClasses.row"
    >
      <ng-container *ngFor="let item of row; trackBy: trackItemBy" >
        <td [class]="model.cssClasses.cell" [question]="model" [model]="item" sv-ng-multipletext-item></td>
      </ng-container>
    </tr>
  </tbody>
</table>

// packages/survey-vue-ui/src/Multipletext.vue
<template>
  <table :class="question.cssClasses.root">
    <tbody>
      <tr
        v-for="(row, rowindex) in question.getRows()"
        :key="question.inputId + 'rowkey' + rowindex"
        :class="question.cssClasses.row"
      >
          <td v-for="item in row" :key="'item' + item.editor.id" :class="question.cssClasses.cell">
            <survey-multipletext-item :question="question" :item="item"></survey-multipletext-item>
          </td>
      </tr>
    </tbody>
  </table>
</template>

<script lang="ts">
import { QuestionMultipleTextModel } from "survey-core";
import { QuestionVue } from "./base";
import { defineComponent } from "vue";

export default defineComponent({
  // eslint-disable-next-line
  mixins: [QuestionVue],
  name: "survey-multipletext",
  props: {
    question: QuestionMultipleTextModel,
  },
});
</script>
