// packages/survey-angular-ui/src/questions/radiogroup-item.component.ts
import { Component, Input } from "@angular/core";
import { QuestionRadiogroupModel } from "survey-core";
import { ImplementorBase } from "../implementor-base";

@Component({
  selector: "sv-radiogroup-item",
  templateUrl: "./radiogroup-item.component.html",
  styleUrls: ["./radiogroup-item.component.scss"]
})
export class RadiogroupItemComponent {
  @Input() question: any;
  @Input() model: any;
  constructor() {
  }
  ngOnChanges(changes: any): void {
    new ImplementorBase(changes.model.currentValue);
  }
}

<div role="presentation" [class]="question.getItemClass(model)">
  <label [class]="question.getLabelClass(model)" [attr.aria-label]="question.getAriaItemLabel(model)">
    <input type="radio" [name]="question.questionName" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
      [disabled]="!question.getItemEnabled(model)" [checked]="question.renderedValue" [value]="model.value"
    />
    <span *ngIf="question.cssClasses.materialDecorator" [class]="question.cssClasses.materialDecorator">
      <svg *ngIf="question.itemSvgIcon" [class]="question.cssClasses.itemDecorator">
        <use data-bind="attr:{'xlink:href':question.itemSvgIcon}" xlink:href=''></use>
      </svg>
    </span>
    <span [class]="question.getControlLabelClass(model)" [style.visibility]="!model.hideCaption ? 'visible' : 'hidden'">
      <string-viewer [model]="model.locText"></string-viewer>
    </span>
  </label>
</div>

// packages/survey-vue-ui/src/RadiogroupItem.vue
<template>
  <div role="presentation">
    <label
      @mousedown="question.onMouseDown()"
      :class="getLabelClass(item)"
      :aria-label="question.getAriaItemLabel(item)"
    >
      <input
        type="radio"
        :name="question.questionName"
        :value="item.value"
        :id="question.getItemId(item)"
        :aria-describedby="question.ariaDescribedBy"
        v-model="question.renderedValue"
        :disabled="!question.getItemEnabled(item)"
        :class="question.cssClasses.itemControl"
      /><span
        v-if="question.cssClasses.materialDecorator"
        :class="question.cssClasses.materialDecorator"
      >
        <svg
          v-if="question.itemSvgIcon"
          :class="question.cssClasses.itemDecorator"
        >
          <use :xlink:href="question.itemSvgIcon"></use>
        </svg> </span
      ><span v-if="!hideLabel" :class="getControlLabelClass(item)">
        <survey-string :locString="item.locText" />
      </span>
    </label>
  </div>
</template>

<script lang="ts" setup>
import type { ItemValue, QuestionRadiogroupModel } from "survey-core";
import { useBase } from "./base";

const props = defineProps<{
  question: QuestionRadiogroupModel;
  item: ItemValue;
  index: string | number;
  hideLabel?: boolean;
}>();
const getLabelClass = (item: any) => {
  return props.question.getLabelClass(item);
};
const getControlLabelClass = (item: any) => {
  return props.question.getControlLabelClass(item);
};

useBase(() => props.item);
</script>
