// packages/survey-angular-ui/src/string-editor.component.ts
import { Component, Input } from "@angular/core";
import { LocalizableString } from "survey-core";
import { AngularComponentFactory } from "./component-factory";

@Component({
  selector: "sv-ng-string-editor",
  templateUrl: "./string-editor.component.html"
})
export class StringEditorComponent {
  @Input() model!: LocalizableString;

  onInput = (event: any) => {
    this.model.text = event.target.innerText;
  };
  onClick = (event: any) => {
    event.preventDefault();
    event.stopPropagation();
  };
}
AngularComponentFactory.Instance.registerComponent(LocalizableString.editableRenderer, StringEditorComponent);
<span style="position: static">
  <span
    class="sv-string-editor"
    contenteditable="true"
    style="position: static"
    *ngIf="model.hasHtml"
    [innerHtml]="model.renderedHtml"
    (blur)="onInput($event)"
    (click)="onClick($event)"
  ></span>
  <span
    class="sv-string-editor"
    contenteditable="true"
    style="position: static"
    *ngIf="!model.hasHtml"
    (blur)="onInput($event)"
    (click)="onClick($event)"
    >{{ model.renderedHtml }}</span
  >
</span>

// packages/survey-vue-ui/src/StringEditor.vue
<template>
  <span class="sv-string-editor" contenteditable="true"
    v-if="locString.hasHtml"
    v-html="locString.renderedHtml"
    @blur="onInput"
    @click="onClick"
  ></span>
  <span
    class="sv-string-editor"
    contenteditable="true"
    v-else
    @blur="onInput"
    @click="onClick"
    >{{ locString.renderedHtml }}</span
  >
</template>

<script lang="ts">
import { LocalizableString } from "survey-core";
import { ref, defineComponent, type ComponentOptions, unref } from "vue";

export default defineComponent({
  // eslint-disable-next-line
  name: LocalizableString.editableRenderer,
  props: {
    locString: LocalizableString,
  },
  data: (vm: any) => {
    return {
      onInput: (event: any) => {
        vm.locString.text = event.target.innerText;
      },
      onClick: (event: any) => {
        event.preventDefault();
        event.stopPropagation();
      }
    }
  }
});

// Vue.component(LocalizableString.editableRenderer, SurveyStringEditor);
// export default SurveyStringEditor;
</script>
