// packages/survey-angular-ui/src/survey.component.ts
import { Component, Input } from "@angular/core";
import { Observable, Subject, BehaviorSubject } from "rxjs";
import { SurveyModel } from "survey-core";

@Component({
  selector: "survey",
  templateUrl: "./survey.component.html",
  styleUrls: ["./survey.component.scss"]
})
export class SurveyComponent {
  title = "SurveyJS";
  @Input() json: any;
  model;
  constructor() {
    // debugger;
    this.model = new SurveyModel(this.json);
  }
  _visible = new BehaviorSubject<boolean>(true);
  get visible(): boolean {
    return this._visible.value;
  }
  set visible(val: boolean) {
    this._visible.next(val);
  }
  toggle(): void {
    this.visible = !this.visible;
  }
  time = new Observable<string>(observer => {
    setInterval(() => observer.next(new Date().toString()), 1000);
  });
}
<div *ngIf="!!model" [class]="model.css.root">
  <form onsubmit="return false;">
    <div class="sv_custom_header" [hidden]="model.hasLogo"></div>
    <div [class]="model.css.container">
      <!-- ko template: { name: koTitleTemplate, afterRender: koAfterRenderHeader } -->
      <!-- /ko -->
      <div *ngIf="model.state === 'starting'" [class]="model.bodyCss">
        <!-- ko if: isNavigationButtonsShowingOnTop -->
        <!-- ko template: { name: 'survey-navigation-start' } -->
        <!-- /ko -->
        <!-- /ko -->
        <div
          data-bind="attr: { id: startedPage.id }, template: { name: 'survey-page', data: startedPage, afterRender: koAfterRenderPage }">
        </div>
        <!-- ko if: isNavigationButtonsShowingOnBottom -->
        <!-- ko template: { name: 'survey-navigation-start' } -->
        <!-- /ko -->
        <!-- /ko -->
      </div>
      <div *ngIf="model.state === 'running' || model.state === 'preview'" [class]="model.bodyCss">
        <!-- ko if: isTimerPanelShowingOnTop -->
        <!-- ko template: { name: 'survey-timerpanel' } -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- ko if: isShowProgressBarOnTop -->
        <!-- ko component: { name: 'sv-progress-' + progressBarType, params: { model: $data } } -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- ko if: isNavigationButtonsShowingOnTop -->
        <!-- ko template: { name: 'survey-navigation' } -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- ko if: koCurrentPage -->
        <div
          data-bind="attr: { id: koCurrentPage().id }, template: { name: 'survey-page', data: koCurrentPage, afterRender: koAfterRenderPage }">
        </div>
        <!-- ko if: isCurrentPageEmpty() && $data.emptyPageTemplate -->
        <!-- ko template: { name: emptyPageTemplate, data: $data.emptyPageTemplateData || $data } -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- ko if: isShowProgressBarOnBottom -->
        <!-- ko component: { name: 'sv-progress-' + progressBarType, params: { model: $data } } -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- ko if: isTimerPanelShowingOnBottom -->
        <!-- ko template: { name: 'survey-timerpanel' } -->
        <!-- /ko -->
        <!-- /ko -->
        <!-- ko if: isNavigationButtonsShowingOnBottom -->
        <!-- ko template: { name: 'survey-navigation' } -->
        <!-- /ko -->
        <!-- /ko -->
      </div>
      <div *ngIf="model.state === 'completed' || model.showCompletedPage" [class]="model.completedCss"
        [innerHtml]="model.processedCompletedHtml"></div>
      <div data-bind="visible: koCompletedState() != '', css: css.saveData.root">
        <div data-bind="css: koCompletedStateCss">
          <span data-bind="text:koCompletedStateText"></span>
          <input type="button"
            data-bind="visible: koCompletedState() == 'error', value: getLocString('saveAgainButton'), click: doComplete, css: css.saveData.saveAgainButton" />
        </div>
      </div>
      <div *ngIf="model.state === 'completedbefore'" [class]="model.css.body"
        [innerHtml]="model.processedCompletedBeforeHtml"></div>
      <div *ngIf="model.state === 'loading'" [class]="model.css.body" [innerHtml]="model.processedLoadingHtml"></div>
      <div *ngIf="model.state === 'empty'" [class]="model.css.bodyEmpty">{{model.emptySurveyText}}</div>
    </div>
  </form>
</div>
<div style="margin-top: 100px;">
  <button type="button" (click)="toggle()">Toggle</button>
  <div [hidden]="!visible">
    <div>
      <code>observable|async</code>:
      Time: {{ time | async }}
    </div>
  </div>
</div>

// packages/survey-vue-ui/src/Survey.vue
<template>
  <div :class="survey.getRootCss()">
    <form onsubmit="return false;">
      <div v-if="!vueSurvey.hasLogo" class="sv_custom_header"></div>
      <div :class="css.container">
        <survey-header :survey="vueSurvey" />
          <component
                v-if="vueSurvey.isShowProgressBarOnTop && !vueSurvey.isShowStartingPage"
                :is="'sv-progress-' + vueSurvey.progressBarType.toLowerCase()"
                :survey="vueSurvey"
                :css="css"
              />
          <survey-timerpanel
            v-if="vueSurvey.isTimerPanelShowingOnTop && !vueSurvey.isShowStartingPage"
            :timerModel="vueSurvey.timerModel"
            :css="css"
          />
        <template
          v-if="vueSurvey.isShowingPage"
        >
          <div :class="vueSurvey.bodyCss"  :style="{maxWidth: survey.renderedWidth}">
            <sv-action-bar
              v-if="vueSurvey.isNavigationButtonsShowingOnTop"
              :key="navId + 'top'"
              :model="vueSurvey.navigationBar"
            />
            <survey-page
              :key="pageId"
              :survey="vueSurvey"
              :page="vueSurvey.activePage"
              :css="css"
            />
            <component
              v-if="vueSurvey.isShowProgressBarOnBottom && !vueSurvey.isShowStartingPage"
              :is="'sv-progress-' + vueSurvey.progressBarType.toLowerCase()"
              :survey="vueSurvey"
              :css="css"
            />
            <sv-action-bar
              v-if="vueSurvey.isNavigationButtonsShowingOnBottom"
              :key="navId + 'bottom'"
              :model="vueSurvey.navigationBar"
            />
          </div>
        </template>
        <survey-timerpanel
              v-if="vueSurvey.isTimerPanelShowingOnBottom && !vueSurvey.isShowStartingPage"
              :timerModel="vueSurvey.timerModel"
              :css="css"
            />
        <div v-if="hasCompletedPage">
          <div
            v-html="getProcessedCompletedHtml()"
            :class="vueSurvey.completedCss"
          ></div>
          <div v-if="vueSurvey.completedState != ''" :class="css.saveData.root">
            <div :class="getCompletedStateClasses()">
              <span>{{ vueSurvey.completedStateText }}</span>
              <input
                type="button"
                v-if="vueSurvey.completedState == 'error'"
                :value="vueSurvey.getLocalizationString('saveAgainButton')"
                @click="doTrySaveAgain"
                :class="css.saveData.saveAgainButton"
              />
            </div>
          </div>
        </div>
        <div
          v-if="vueSurvey.state === 'completedbefore'"
          :class="css.body"
          v-html="vueSurvey.processedCompletedBeforeHtml"
        ></div>
        <div
          v-if="vueSurvey.state === 'loading'"
          :class="css.body"
          v-html="vueSurvey.processedLoadingHtml"
        ></div>
        <div v-if="vueSurvey.state === 'empty'" :class="css.bodyEmpty">
          {{ vueSurvey.emptySurveyText }}
        </div>
      </div>
    </form>
    <sv-brand-info v-if="vueSurvey.showBrandInfo"></sv-brand-info>
  </div>
</template>

<script lang="ts">
import { SvgRegistry, SurveyModel } from "survey-core";
import { reactive, isReactive } from "vue";
import { defineSurveyComponent } from "./base";

export default defineSurveyComponent({
  // eslint-disable-next-line
  name: "survey",
  props: {
    model: SurveyModel,
    survey: SurveyModel,
  },
  data: (vm: any) => {
    return {
      processedCompletedHtmlValue: "",
      updater: 1,
      getModel: () => { return vm.vueSurvey; },
      getActivePageId: () => {
        const pageId = !!vm.vueSurvey.activePage ? vm.vueSurvey.activePage.id : "";
        return !!vm.vueSurvey && pageId + vm.updater.toString();
      },
      getProcessedCompletedHtml: () => {
        if (!vm.hasCompletedPage) return "";
        if (!vm.processedCompletedHtmlValue) {
          vm.processedCompletedHtmlValue = vm.vueSurvey.processedCompletedHtml;
        }
        return vm.processedCompletedHtmlValue;
      },
      getCompletedStateClasses: () => {
        return vm.css.saveData[vm.vueSurvey.completedState];
      },
      start: () => {
        vm.vueSurvey.start();
      },
      doTrySaveAgain: () => {
        vm.vueSurvey.doComplete();
      },
      forceUpdate: () => {
        vm.updater += 1;
        //vm.$forceUpdate();
      }
    }
  },
  computed: {
    vueSurvey(): SurveyModel {
      const survey = !!this.survey ? this.survey : this.model;
      return isReactive(survey) ? survey : reactive(survey);
    },
    pageId: {
      get() {
        return "page" + this.getActivePageId();
      }
    },
    navId: {
      get() {
        return "nav" + this.getActivePageId();
      }
    },
    hasTitle: {
      get() {
        return !!this.vueSurvey.title && this.vueSurvey.showTitle;
      }
    },
    hasCompletedPage: {
      get() {
        return this.vueSurvey.showCompletedPage && this.vueSurvey.state === "completed";
      }
    },
    css(): any {
      return this.vueSurvey.css;
    }
  },
  mounted() {
    if (!this.vueSurvey) return;
    if(this.vueSurvey["needRenderIcons"]) {
      SvgRegistry.renderIcons();
    }
    var el = this.$el;
    if (el) this.vueSurvey.afterRenderSurvey(el);
    this.vueSurvey.renderCallback = this.forceUpdate;
    this.vueSurvey.startTimerFromUI();
  },
  unmounted() {
    this.vueSurvey.stopTimer();
    this.vueSurvey.renderCallback = undefined;
  }
});

// TODO: make this functionality available via surveyCss in all examples
//Object.defineProperty(Survey, "cssType", {
//  get: function() {
//    return surveyCss.currentType;
//  },
//  set: function(newType) {
//    StylesManager.applyTheme(newType);
//  },
//  enumerable: true,
//  configurable: false,
//});

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped></style>
