// src/vue/components/popup/popup-container.vue
<template>
  <div
    tabindex="-1"
    class="sv-popup"
    v-bind:class="model.styleClass"
    v-show="model.isVisible"
    v-on:keydown="
      (event) => {
        model.onKeyDown(event);
      }
    "
    v-on:click="
      () => {
        model.clickOutside();
      }
    "
  >
    <div
      class="sv-popup__container"
      v-bind:style="{ left: model.left, top: model.top }"
      v-on:click="clickInside"
    >
      <span
        v-show="model.showPointer"
        v-bind:style="{
          left: model.pointerTarget.left,
          top: model.pointerTarget.top,
        }"
        class="sv-popup__pointer"
      ></span>
      <div class="sv-popup__scrolling-content">
        <div class="sv-popup__header"></div>

        <div class="sv-popup__content">
          <component
            :is="model.contentComponentName"
            v-bind="model.contentComponentData"
          ></component>
        </div>

        <div v-if="model.isModal" class="sv-popup__footer">
          <button
            v-on:click="
              () => {
                model.cancel();
              }
            "
            class="sv-popup__footer-item sv-popup__button sv-popup__button--cancel"
          >
            {{ model.cancelButtonText }}
          </button>
          <button
            v-on:click="
              () => {
                model.apply();
              }
            "
            class="sv-popup__footer-item sv-popup__button sv-popup__button--cancel"
          >
            {{ model.applyButtonText }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import Vue from "vue";
import { Prop, Component } from "vue-property-decorator";
import { PopupBaseViewModel, createPopupModalViewModel, settings } from "survey-core";
import { BaseVue } from "../../base";
@Component
export class PopupContainer extends BaseVue {
  @Prop() model: PopupBaseViewModel;
  private prevIsVisible: boolean;
  protected getModel() {
    return this.model;
  }
  clickInside(event: any) {
    event.stopPropagation();
  }
  onUpdated() {
    if (!this.prevIsVisible && this.model.isVisible) {
      this.model.updateOnShowing();
    }
    this.prevIsVisible = this.model.isVisible;
  }
}
export function showModal(
  componentName: string,
  data: any,
  onApply: () => boolean,
  onCancel?: () => void,
  cssClass?: string
) {
  const popupViewModel: PopupBaseViewModel = createPopupModalViewModel(
    componentName,
    data,
    onApply,
    onCancel,
    () => {
      popup.$destroy();
      popupViewModel.destroyPopupContainer();
    },
    undefined,
    cssClass
  );
  const popup = new PopupContainer({
    el: popupViewModel.container.appendChild(document.createElement("div")),
    propsData: { model: popupViewModel },
  });
  popupViewModel.model.isVisible = true;
}
settings.showModal = showModal;
Vue.component("sv-popup-container", PopupContainer);
export default PopupContainer;
</script>

// packages/survey-angular-ui/src/components/popup/popup-container.component.ts
import { ChangeDetectorRef, Component, Input } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { PopupBaseViewModel, PopupModalViewModel } from "survey-core";

@Component({
  selector: "sv-ng-popup-container, '[sv-ng-popup-container]'",
  templateUrl: "./popup-container.component.html"
  })

export class PopupBaseContainerComponent<T extends PopupBaseViewModel = PopupBaseViewModel> extends BaseAngular<T> {
  private prevIsVisible: boolean = false;
  @Input() model!: T;

  constructor(changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef);
    this.changeDetectorRef.detach();
  }
  protected getModel(): T {
    return this.model;
  }

  get applyButtonText(): string | null {
    const popupModalModel = this.model as any as PopupModalViewModel;
    if(!popupModalModel) return null;

    return popupModalModel.applyButtonText;
  }

  apply(): void {
    const popupModalModel = this.model as any as PopupModalViewModel;
    if(!popupModalModel) return;

    popupModalModel.apply();
  }

  protected override getShouldReattachChangeDetector(): boolean {
    return false;
  }

  protected override onModelChanged(): void {
    this.changeDetectorRef.detectChanges();
  }

  protected override afterUpdate(): void {
    super.afterUpdate();
    if (!this.prevIsVisible && this.model.isVisible) {
      this.model.updateOnShowing();
    }
    if (this.prevIsVisible !== this.model.isVisible) {
      this.prevIsVisible = this.model.isVisible;
    }
  }
  public clickInside(event: any) {
    event.stopPropagation();
  }
}
<div class="sv-popup" tabindex="-1" [class]="model.styleClass" [style.visibility]="isShow ? 'visible' : 'hidden'" [visible]="model.isVisible" (click)="model.clickOutside()" (keydown)="model.onKeyDown($event)">
    <div class="sv-popup__container" [style]="{ left: model.left, top: model.top, height: model.height, minWidth: model.minWidth }">
        <div class="sv-popup__shadow">
            <span *ngIf="model.showPointer" class="sv-popup__pointer" [style]="{ left: model.pointerTarget.left, top: model.pointerTarget.top }"></span>
            <div class="sv-popup__body-content">
                <div *ngIf="model.title" class="sv-popup__body-header">{{ model.title }}</div>
                <div class="sv-popup__scrolling-content">
                    <div class="sv-popup__content">
                        <ng-template [component]="{ name: model.contentComponentName, data: model.contentComponentData }"></ng-template>
                    </div>
                </div>
                <div *ngIf="model.showFooter" class="sv-popup__body-footer">
                    <button type="button" (click)="model.cancel()"
                        class="sv-popup__body-footer-item sv-popup__button sv-popup__button--cancel">{{ model.cancelButtonText }}</button>
                    <button type="button" *ngIf="model.isModal" (click)="model.apply()" 
                    class="sv-popup__body-footer-item sv-popup__button sv-popup__button--apply">{{ model.applyButtonText }}</button>
                </div>
            </div>
        </div>
    </div>
</div>
