// packages/survey-vue3-ui/src/components/popup/Popup.vue
<template>
  <div ref="root">
    <sv-popup-container :model="popupViewModel"></sv-popup-container>
  </div>
</template>
<script lang="ts" setup>
import { useBase } from "@/base";
import { PopupModel, createPopupViewModel } from "survey-core";
import { shallowRef, ref, onMounted, watch, onUnmounted } from "vue";
const props = defineProps<{
  getTarget?: (el: HTMLElement) => HTMLElement;
  getArea?: (el: HTMLElement) => HTMLElement;
  model: PopupModel;
}>();
const popupViewModel = shallowRef();
const root = ref<HTMLElement>(null as any);

const setContainerElement = () => {
  const container = root.value;
  if (container) {
    popupViewModel.value.setComponentElement(
      container,
      props.getTarget ? props.getTarget(container) : undefined,
      props.getArea ? props.getArea(container) : undefined
    );
  }
};

watch(
  () => props.model,
  (newValue) => {
    if (popupViewModel.value) {
      popupViewModel.value.dispose();
    }
    popupViewModel.value = createPopupViewModel(newValue, undefined as any);
    setContainerElement();
  },
  { immediate: true }
);
useBase(() => popupViewModel.value);

onMounted(() => {
  setContainerElement();
});
onUnmounted(() => {
  popupViewModel.value.dispose();
});
</script>

// packages/survey-angular-ui/src/components/popup/popup.component.ts
import { ChangeDetectorRef, Component, ElementRef, Input, ViewChild, ViewContainerRef } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { PopupBaseViewModel, PopupModel, createPopupViewModel } from "survey-core";

@Component({
  selector: "sv-ng-popup, '[sv-ng-popup]'",
  template: "<div #containerRef><sv-ng-popup-container [model]='model' ></sv-ng-popup-container></div>"
})

export class PopupComponent extends BaseAngular<PopupModel> {
  @Input() popupModel!: PopupModel;
  @Input() getTarget?: (container: HTMLElement) => HTMLElement;
  @Input() getArea?: (container: HTMLElement) => HTMLElement;
  @ViewChild("containerRef") containerRef!: ElementRef<HTMLDivElement>;

  public model!: PopupBaseViewModel;

  protected getModel(): PopupModel {
    return this.popupModel;
  }

  constructor(viewContainerRef: ViewContainerRef, changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef, viewContainerRef);
  }
  protected override onModelChanged(): void {
    if (this.model) {
      this.model.resetComponentElement();
      this.model.dispose();
    }
    this.model = createPopupViewModel(this.popupModel, this.viewContainerRef?.element.nativeElement);
    this.setContainerElement();
  }

  private setContainerElement(): void {
    if (!!this.containerRef?.nativeElement) {
      const container = this.containerRef.nativeElement as HTMLElement;
      this.model.setComponentElement(container.parentElement || container);
    }
  }
  ngAfterViewInit(): void {
    this.setContainerElement();
  }
  override ngOnInit() {
    this.onModelChanged();
  }
  override ngOnDestroy(): void {
    this.model.resetComponentElement();
    this.model.dispose();
    super.ngOnDestroy();
  }
}
