// src/vue/components/popup/popup.vue
<template>
  <div><sv-popup-container :model="popupViewModel"></sv-popup-container></div>
</template>
<script lang="ts">
import Vue from "vue";
import { Prop, Component } from "vue-property-decorator";
import { PopupBaseViewModel, PopupModel, PopupDropdownViewModel, createPopupViewModel, settings } from "survey-core";
import { PopupContainer } from "./popup-container.vue";
import { BaseVue } from "../../base";
@Component
export class Popup extends BaseVue {
  @Prop() model: PopupModel;
  @Prop() getTarget?: (container: HTMLElement) => HTMLElement;
  popupViewModel: PopupBaseViewModel;
  protected getModel() {
    return this.model;
  }
  constructor(props: any) {
    super(props);
    this.popupViewModel = createPopupViewModel(this.model, undefined as any);
  }
  onMounted() {
    const container = (this.$el as HTMLElement) as HTMLElement;
    this.popupViewModel.setComponentElement(container, this.getTarget ? this.getTarget(container) : undefined);
  }
  destroyed() {
    this.popupViewModel.dispose();
  }
}
Vue.component("sv-popup", Popup);
export default Popup;
</script>

// packages/survey-angular-ui/src/components/popup/popup.component.ts
import { ChangeDetectorRef, Component, ElementRef, Input, ViewChild, ViewContainerRef } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { PopupBaseViewModel, PopupModel, createPopupViewModel } from "survey-core";

@Component({
  selector: "sv-ng-popup, '[sv-ng-popup]'",
  template: "<div #containerRef><sv-ng-popup-container [model]='model' ></sv-ng-popup-container></div>"
})

export class PopupComponent extends BaseAngular<PopupModel> {
  @Input() popupModel!: PopupModel;
  @Input() getTarget?: (container: HTMLElement) => HTMLElement;
  @ViewChild("containerRef") containerRef!: ElementRef<HTMLDivElement>;

  public model!: PopupBaseViewModel;

  protected getModel(): PopupModel {
    return this.popupModel;
  }

  constructor(viewContainerRef: ViewContainerRef, changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef, viewContainerRef);
  }
  protected override onModelChanged(): void {
    this.model = createPopupViewModel(this.popupModel, this.viewContainerRef?.element.nativeElement);
  }
  ngAfterViewInit(): void {
    if(!!this.containerRef?.nativeElement) {
      const container = this.containerRef.nativeElement as HTMLElement;
      this.model.setComponentElement(container, this.getTarget ? this.getTarget(container.parentElement as HTMLElement) : container?.parentElement?.parentElement);
    }
  }
  override ngOnInit() {
    this.onModelChanged();
  }
}
