// packages/survey-vue-ui/src/components/popup/Popup.vue
<template>
  <div><sv-popup-container :model="popupViewModel"></sv-popup-container></div>
</template>
<script lang="ts">
import { PopupModel, createPopupViewModel } from "survey-core";
import { reactive, type PropType } from "vue";
import { defineSurveyComponent } from "../../base";

export default defineSurveyComponent({
  // eslint-disable-next-line
  name: "sv-popup",
  props: {
    model: Object as PropType<PopupModel>,
  },
  setup(props: any) {
    return {
      popupViewModel: reactive(
        createPopupViewModel(props.model, undefined as any)
      ),
    };
  },
  mounted() {
    const container = (this.$el as HTMLElement) as HTMLElement;
    this.popupViewModel.setComponentElement(
      container,
      this.getTarget ? this.getTarget(container) : undefined
    );
  },
  destroyed() {
    this.popupViewModel.dispose();
  },
  data(vm: any) {
    return {
      getModel: () => {
        return vm.model;
      },
    };
  },
  watch: {
    model(newValue: PopupModel) {
      this.popupViewModel.dispose();
      this.popupViewModel = reactive(
        createPopupViewModel(newValue, undefined as any)
      );
      this.popupViewModel = this.$el.parentElement;
    },
  },
});
</script>

// packages/survey-angular-ui/src/components/popup/popup.component.ts
import { ChangeDetectorRef, Component, ElementRef, Input, ViewChild, ViewContainerRef } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { PopupBaseViewModel, PopupModel, createPopupViewModel } from "survey-core";

@Component({
  selector: "sv-ng-popup, '[sv-ng-popup]'",
  template: "<div #containerRef><sv-ng-popup-container [model]='model' ></sv-ng-popup-container></div>"
})

export class PopupComponent extends BaseAngular<PopupModel> {
  @Input() popupModel!: PopupModel;
  @Input() getTarget?: (container: HTMLElement) => HTMLElement;
  @ViewChild("containerRef") containerRef!: ElementRef<HTMLDivElement>;

  public model!: PopupBaseViewModel;

  protected getModel(): PopupModel {
    return this.popupModel;
  }

  constructor(viewContainerRef: ViewContainerRef, changeDetectorRef: ChangeDetectorRef) {
    super(changeDetectorRef, viewContainerRef);
  }
  protected override onModelChanged(): void {
    this.model = createPopupViewModel(this.popupModel, this.viewContainerRef?.element.nativeElement);
  }
  ngAfterViewInit(): void {
    if(!!this.containerRef?.nativeElement) {
      const container = this.containerRef.nativeElement as HTMLElement;
      this.model.setComponentElement(container, this.getTarget ? this.getTarget(container.parentElement as HTMLElement) : container?.parentElement?.parentElement);
    }
  }
  override ngOnInit() {
    this.onModelChanged();
  }
}
