// packages/survey-angular-ui/src/components/action-bar-item.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../base-angular";

@Component({
  selector: "sv-action-bar-item",
  templateUrl: "./action-bar-item.component.html",
  styleUrls: ["./action-bar-item.component.scss"]
})
export class ActionBarItemComponent extends BaseAngular {
  @Input() model: any;
  getModel() {
    return this.model;
  }
}
<button type="button" (click)="model.action()" [class]="model.getActionBarItemCss()" [title]="model.tooltip || model.title" [disabled]="model.disabled"
  data-bind="key2click: { processEsc: false }"
>
  <!-- ko if: $data.iconName -->
  <!-- ko component: { name: 'sv-svg-icon', params: { css: $data.cssClasses.itemIcon, iconName: iconName, size: iconSize } } --><!-- /ko -->
  <!-- /ko -->
  <!-- ko if: $data.hasTitle -->
  <span *ngIf="model.hasTitle" [class]="model.getActionBarItemTitleCss()">{{ model.title }}</span>
  <!-- /ko -->
</button>

// packages/survey-vue-ui/src/components/action-bar/ActionBarItem.vue
<template>
  <button
    :class="item.getActionBarItemCss()"
    type="button"
    v-on:click="
      () => {
        item.action();
      }
    "
    v-on:keyup="
      (evt) => {
        evt.stopPropagation();
      }
    "
    v-bind:disabled="item.enabled !== undefined && !item.enabled"
    v-bind:title="item.tooltip || item.title"
    v-bind:aria-checked="item.ariaChecked"
    v-bind:aria-expanded="item.ariaExpanded"
    v-bind:role="item.ariaRole"
    v-bind:tabindex="item.disableTabStop ? -1 : 0"
  >
    <sv-svg-icon
      v-if="item.iconName"
      :class="item.cssClasses.itemIcon"
      :iconName="item.iconName"
      :size="item.iconSize"
      :title="item.tooltip || item.title"
    ></sv-svg-icon>

    <span
      v-if="item.hasTitle"
      :class="item.getActionBarItemTitleCss()"
      >{{ item.title }}</span
    >
  </button>
</template>

<script lang="ts">
import { Action } from "survey-core";
import { defineSurveyComponent } from "../../base";

export default defineSurveyComponent({
  // eslint-disable-next-line
  name: "sv-action-bar-item",
  props: {
    item: Action,
  },
  data: (vm: any) => {
    return {
      getModel: () => {
        return vm.item;
      },
    };
  },
});

</script>
