// src/vue3/src/components/Comment.vue
<script setup lang="ts">
import { QuestionCommentModel } from "survey-core";
import {toRefs} from "vue";
import {makeReactive} from "./base";

const props = defineProps<{
  question: QuestionCommentModel
}>();

function change(event: any) {
  props.question.value = event.target.value;
}
makeReactive(props.question);
</script>

<template>
  <textarea
      v-if="!question.isReadOnlyRenderDiv()"
      :readonly="question.isInputReadOnly"
      :disabled="question.renderedInputDisabled"
      :value="question.value"
      :id="question.inputId"
      :maxlength="question.getMaxLength()"
      :cols="question.cols"
      :rows="question.rows"
      :placeholder="question.renderedPlaceHolder"
      :class="question.className"
      @change="change"
      @input="(e) => { question.onInput(e) }"
      @keydown="(e) => { question.onKeyDown(e) }"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-describedby="question.ariaDescribedBy"
      v-bind:style="{ resize: question.resizeStyle }"
    ></textarea>
    <div v-else>{{ question.value }}</div>
</template>

// packages/survey-angular-ui/src/comment.component.ts
import { Component, Input } from "@angular/core";
import { Question } from "survey-core";

@Component({
  selector: "sv-ng-comment, '[sv-ng-comment]'",
  templateUrl: "./comment.component.html",
})
export class SurveyCommentComponent {
  @Input() question!: Question;
  constructor() {
  }
}
<textarea *ngIf="!question.isReadOnlyRenderDiv()" [id]="question.commentId" [attr.maxlength]="question.getOthersMaxLength()"  [attr.aria-required]="question.ariaRequired || question.a11y_input_ariaRequired" [attr.aria-label]="question.ariaLabel || question.a11y_input_ariaLabel" [attr.placeholder]="question.renderedCommentPlaceholder" 
  [value]="comment"
  [style.resize]="question.resizeStyle"
  [attr.rows]="question.commentAreaRows"
  [disabled]="question.isInputReadOnly"
  (change)="question.onCommentChange($event)"
  (input)="question.onCommentInput($event)"
  [class]="question.cssClasses.other">
</textarea>
<div *ngIf="question.isReadOnlyRenderDiv()">{{ question.comment }}</div>
