// src/vue/errors.vue
<template>
  <div
    role="alert"
    aria-live="polite"
    v-show="element.hasVisibleErrors"
    :class="element.cssError"
    :id="element.id + '_errors'"
  >
    <div v-for="(error, index) in element.errors" :key="'error_' + index">
      <span
        :class="
          element.cssClasses
            ? element.cssClasses.error.icon
            : 'panel-error-icon'
        "
        aria-hidden="true"
      ></span>
      <span
        :class="
          element.cssClasses
            ? element.cssClasses.error.item
            : 'panel-error-item'
        "
      >
        <survey-string :locString="error.locText" />
      </span>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { SurveyElement, TooltipManager } from "survey-core";

@Component
export class Errors extends Vue {
  @Prop() element: SurveyElement;
  @Prop() location: String;
  private tooltipManager: TooltipManager; 
  mounted() {
    if(this.location == "tooltip") {
      this.tooltipManager = new TooltipManager(<HTMLElement>this.$el);
    }
  }
  destroyed() {
    this.tooltipManager.dispose()
  }
  
}
Vue.component("survey-errors", Errors);
export default Errors;
</script>

// packages/survey-angular-ui/src/errors.component.ts
import { Component, HostBinding, Input } from "@angular/core";
import { SurveyElement } from "survey-core";

@Component({
  templateUrl: "./errors.component.html",
  selector: "'[sv-ng-errors]'"
})
export class ErrorsComponent {
  @Input() element!: SurveyElement | any;
  @Input() location?: String;
  constructor() {}
  @HostBinding("attr.role") get role (): string {
    return "alert";
  }
  @HostBinding("id") get id(): string {
    return this.element.id + "_errors";
  }
  @HostBinding("attr.aria-live") get ariaLive(): string {
    return "polite";
  }
  @HostBinding("class") get class(): string {
    return this.element.cssError;
  }
}
<div *ngFor="let error of element.errors;">
  <div>
  <span
    [class]="element.cssClasses ? element.cssClasses.error.icon : 'panel-error-icon'"
    aria-hidden="true"
  ></span>
  <span [class]="element.cssClasses ? element.cssClasses.error.item : 'panel-error-item'" [model]="error.locText" sv-ng-string>
  </span>
  </div>
</div>
