// packages/survey-vue3-ui/src/StringEditor.vue
<template>
  <span
    class="sv-string-editor"
    contenteditable="true"
    v-if="model.hasHtml"
    v-html="model.renderedHtml"
    @blur="onInput"
    @click="onClick"
  ></span>
  <span
    class="sv-string-editor"
    contenteditable="true"
    v-else
    @blur="onInput"
    @click="onClick"
    >{{ model.renderedHtml }}</span
  >
</template>

<script lang="ts" setup>
import type { LocalizableString } from "survey-core";

const props = defineProps<{
  model: LocalizableString;
}>();

const onInput = (event: any) => {
  const locString = props.model;
  locString.text = event.target.innerText;
};
const onClick = (event: any) => {
  event.preventDefault();
  event.stopPropagation();
};
</script>

// packages/survey-angular-ui/src/string-editor.component.ts
import { Component, Input } from "@angular/core";
import { LocalizableString } from "survey-core";
import { AngularComponentFactory } from "./component-factory";

@Component({
  selector: "sv-ng-string-editor",
  templateUrl: "./string-editor.component.html"
})
export class StringEditorComponent {
  @Input() model!: LocalizableString;

  onInput = (event: any) => {
    this.model.text = event.target.innerText;
  };
  onClick = (event: any) => {
    event.preventDefault();
    event.stopPropagation();
  };
}
AngularComponentFactory.Instance.registerComponent(LocalizableString.editableRenderer, StringEditorComponent);
<span style="position: static">
  <span
    class="sv-string-editor"
    contenteditable="true"
    style="position: static"
    *ngIf="model.hasHtml"
    [innerHtml]="model.renderedHtml"
    (blur)="onInput($event)"
    (click)="onClick($event)"
  ></span>
  <span
    class="sv-string-editor"
    contenteditable="true"
    style="position: static"
    *ngIf="!model.hasHtml"
    (blur)="onInput($event)"
    (click)="onClick($event)"
    >{{ model.renderedHtml }}</span
  >
</span>
