// packages/survey-angular-ui/src/components/brand-info/brand-info.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
@Component({
  selector: "sv-brand-info",
  templateUrl: "./brand-info.component.html"
})
export class BrandInfoComponent {}
AngularComponentFactory.Instance.registerComponent("sv-brand-info", BrandInfoComponent);
<div class="sv-brand-info">
  <a class="sv-brand-info__logo" href="https://surveyjs.io/?utm_source=built-in_links&utm_medium=online_survey_tool&utm_campaign=landing_page"><img src="https://surveyjs.io/Content/Images/design/SJLogo.svg"/></a>
  <div class="sv-brand-info__text">Try and see how easy it is to <a href="https://surveyjs.io/create-survey?utm_source=built-in_links&utm_medium=online_survey_tool&utm_campaign=create_survey">create a survey</a></div>
  <div class="sv-brand-info__terms"><a href="https://surveyjs.io/TermsOfUse">Terms of Use & Privacy Statement</a></div>
</div>

// src/react/components/brand-info.tsx
import React from "react";

export class BrandInfo extends React.Component<any, any> {
  render() {
    return (
      <div className="sv-brand-info">
        <a className="sv-brand-info__logo" href="https://surveyjs.io/?utm_source=built-in_links&utm_medium=online_survey_tool&utm_campaign=landing_page"><img src="https://surveyjs.io/Content/Images/design/SJLogo.svg"/></a>
        <div className="sv-brand-info__text">Try and see how easy it is to <a href="https://surveyjs.io/create-survey?utm_source=built-in_links&utm_medium=online_survey_tool&utm_campaign=create_survey">create a survey</a></div>
        <div className="sv-brand-info__terms"><a href="https://surveyjs.io/TermsOfUse">Terms of Use & Privacy Statement</a></div>
      </div>
    );
  }
}
