// src/vue/components/character-counter.vue
<template>
  <div :class="remainingCharacterCounter">{{ counter.remainingCharacterCounter }}</div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { CharacterCounter } from "survey-core";
import { BaseVue } from "../base";

@Component
export class CharacterCounterComponent extends BaseVue {
  @Prop() counter: CharacterCounter;
  @Prop() remainingCharacterCounter: string;

  constructor() {
    super();
  }

  getModel() {
    return this.counter;
  }
}

Vue.component("sv-character-counter", CharacterCounterComponent);

export default CharacterCounterComponent;
</script>

// src/react/components/character-counter.tsx
import React from "react";
import { Base, CharacterCounter } from "survey-core";
import { ReactElementFactory } from "../element-factory";
import { SurveyElementBase } from "../reactquestion_element";

export interface ICharacterCounterComponentProps {
  counter: CharacterCounter;
  remainingCharacterCounter: string;
}

export class CharacterCounterComponent extends SurveyElementBase<ICharacterCounterComponentProps, any> {
  protected getStateElement(): Base {
    return this.props.counter;
  }

  renderElement(): JSX.Element | null {
    return (<div className={this.props.remainingCharacterCounter}>{this.props.counter.remainingCharacterCounter}</div>);
  }
}

ReactElementFactory.Instance.registerElement("sv-character-counter", (props) => {
  return React.createElement(CharacterCounterComponent, props);
});
