// packages/survey-angular-ui/src/components-container.component.ts
import { Component, Input, TemplateRef, ViewContainerRef, OnChanges, OnInit, SimpleChanges, ChangeDetectorRef } from "@angular/core";
import { SurveyModel } from "survey-core";
import { AngularComponentFactory } from "./component-factory";

@Component({
  selector: "sv-components-container, [sv-components-container], sv-ng-components-container",
  templateUrl: "./components-container.component.html"
})
export class ComponentsContainerComponent {
  @Input() survey!: SurveyModel;
  @Input() container!: string;
  get components(): Array<any> {
    return this.survey.getContainerContent(this.container as any);
  }
}
AngularComponentFactory.Instance.registerComponent("sv-components-container", ComponentsContainerComponent);
<ng-template #template>
  <ng-container *ngIf="isNeedRenderWrapper">
    <div *ngIf="components.length > 0" class="sv-components-column">
      <ng-container *ngFor="let component of components">
        <ng-template [component]="{ name: component.component, data: { survey: survey, model: component.data } }"></ng-template>
      </ng-container>
    </div>
  </ng-container>
  <ng-container *ngIf="!isNeedRenderWrapper && components.length > 0">
    <ng-container *ngFor="let component of components">
      <ng-template [component]="{ name: component.component, data: { survey: survey, model: component.data } }"></ng-template>
    </ng-container>
  </ng-container>
</ng-template>

// src/react/components/components-container.tsx
import React from "react";
import { ISurveyAddon } from "survey-core";
import { ReactElementFactory } from "../element-factory";

export class ComponentsContainer extends React.Component<any, any> {
  render(): JSX.Element | null {
    const components: Array<ISurveyAddon> = this.props.survey.getContainerContent(this.props.container);
    if(components.length == 0) {
      return null;
    }
    return <div className="sv-components-column">
      {components.map(component => {
        return ReactElementFactory.Instance.createElement(component.component, { survey: this.props.survey, model: component.data, key: component.id });
      })}
    </div>;
  }
}

ReactElementFactory.Instance.registerElement("sv-components-container", (props: any) => {
  return React.createElement(ComponentsContainer, props);
});
