// packages/survey-angular-ui/src/components/cover/cover.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { BaseAngular } from "../../base-angular";
import { Cover, CoverCell, SurveyModel } from "survey-core";

@Component({
  selector: "sv-cover, sv-ng-cover",
  templateUrl: "./cover.component.html",
  styles: [":host { display: none }"]
})
export class CoverComponent extends BaseAngular<Cover> {
  @Input() model!: Cover;
  @Input() survey!: SurveyModel;
  @ViewChild("container") container!: ElementRef<HTMLDivElement>;
  getModel(): Cover {
    this.model.survey = this.survey;
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-cover", CoverComponent);
<ng-template #template>
  <div *ngIf="(survey.titleView === 'cover' && survey.renderedHasHeader)" [class]="model.coverClasses" [style]="{ height: model.renderedHeight, backgroundColor: model.backgroundColor }">
    <div *ngIf="!!model.backgroundImage" [style]="model.backgroundImageStyle" [class]="model.backgroundImageClasses"></div>
    <div [class]="model.contentClasses">
      <ng-container *ngFor="let cell of model.cells">
        <sv-ng-cover-cell [model]="cell"></sv-ng-cover-cell>
      </ng-container>
    </div>
  </div>
</ng-template>

// src/react/components/cover.tsx
import React from "react";
import { Base, SurveyModel, Cover, CoverCell } from "survey-core";
import { SurveyElementBase } from "../reactquestion_element";
import { ReactElementFactory } from "../element-factory";
import { TitleElement } from "./title/title-element";

export interface ILayoutElementProps<T = Base> {
  survey: SurveyModel;
  model: T;
}

export class CoverCellComponent extends React.Component<any, any> {
  get model(): CoverCell {
    return this.props.model;
  }
  private renderLogoImage(): JSX.Element | null {
    const componentName: string = this.model.survey.getElementWrapperComponentName(
      this.model.survey,
      "logo-image"
    );
    const componentData: any = this.model.survey.getElementWrapperComponentData(
      this.model.survey,
      "logo-image"
    );
    return ReactElementFactory.Instance.createElement(componentName, {
      data: componentData,
    });
  }

  render(): JSX.Element | null {
    return (<div className={this.model.css} style={this.model.style}>
      <div className="sv-cover__cell-content" style={this.model.contentStyle}>
        {this.model.showLogo ? (<div className="sv-cover__logo">
          {this.renderLogoImage()}
        </div>) : null}
        {this.model.showTitle ? (<div className="sv-cover__title" style={{ maxWidth: this.model.textWidth }}>
          {/* {ReactElementFactory.Instance.createElement("survey-element-title", { element: this.model.survey })} */}
          <TitleElement element={this.model.survey}/>
        </div>) : null}
        {this.model.showDescription ? (<div className="sv-cover__description" style={{ maxWidth: this.model.textWidth }}>
          <h5 className={this.model.survey.css.description}>
            {SurveyElementBase.renderLocString(this.model.survey.locDescription)}
          </h5>
        </div>) : null}
      </div>
    </div>);
  }
}

export class CoverComponent extends SurveyElementBase<ILayoutElementProps<Cover>, any> {
  get model(): Cover {
    return this.props.model;
  }
  protected getStateElement(): Base {
    return this.model;
  }

  renderElement(): JSX.Element | null {
    this.model.survey = this.props.survey;

    if(!(this.props.survey.titleView === "cover" && this.props.survey.renderedHasHeader)) {
      return null;
    }

    return (
      <div className={this.model.coverClasses} style={{ height: this.model.renderedHeight, backgroundColor: this.model.backgroundColor }}>
        {this.model.backgroundImage ? <div style={this.model.backgroundImageStyle} className={this.model.backgroundImageClasses}></div> : null}
        <div className={this.model.contentClasses}>
          {this.model.cells.map((cell, index) => <CoverCellComponent key={index} model={cell}/>)}
        </div>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("sv-cover", (props) => {
  return React.createElement(CoverComponent, props);
});
