// src/vue/components/loading-indicator.vue
<template>
  <div class="sd-loading-indicator">
    <sv-svg-icon :iconName="'icon-loading'" size="'auto'"></sv-svg-icon>
  </div>
</template>
<script lang="ts">
import { Component } from 'vue-property-decorator';
import Vue from 'vue';

@Component
export class LoadingIndicatorComponent extends Vue {}

Vue.component("sv-loading-indicator", LoadingIndicatorComponent);
export default LoadingIndicatorComponent;
</script>

// src/react/components/loading-indicator.tsx
import React from "react";
import { SvgIcon } from "./svg-icon/svg-icon";

export class LoadingIndicatorComponent extends React.Component<any, any> {
  render(): JSX.Element | null {
    return (<div className="sd-loading-indicator"><SvgIcon iconName="icon-loading" size="auto"></SvgIcon></div>);
  }
}
