// src/vue/components/text-area.vue
<template>
<textarea
ref="contentElement"
:readonly="model.isReadOnlyAttr"
:disabled="model.isDisabledAttr"
:value="value"
:id="model.id"
:maxlength="model.maxLength"
:cols="model.cols"
:rows="model.rows"
:placeholder="model.placeholder"
:class="model.className"
@blur="(e) => { model.onTextAreaChange(e) }"
@change="(e) => { model.onTextAreaChange(e) }"
@input="(e) => { model.onTextAreaInput(e) }"
@keydown="(e) => { model.onTextAreaKeyDown(e) }"
:aria-required="model.ariaRequired"
:aria-label="model.ariaLabel"
:aria-labelledby="model.ariaLabelledBy"
:aria-describedby="model.ariaDescribedBy"
:aria-invalid="model.ariaInvalid"
:aria-errormessage="model.ariaErrormessage"
v-bind:style="{ resize: model.question.resizeStyle }"
></textarea>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop, Watch } from "vue-property-decorator";
import { TextAreaModel } from "survey-core";
import { BaseVue } from "../base";

@Component
export class TextAreaComponent extends BaseVue {
  @Prop() model: TextAreaModel;
  constructor() {
    super();
  }
  get value() {
    return this.model.getTextValue() || "";
  }
  protected onMounted() {
    this.model.setElement(this.$refs["contentElement"] as HTMLTextAreaElement);
  }
  protected onUpdated() {
    this.model.setElement(this.$refs["contentElement"] as HTMLTextAreaElement);
  }
}

Vue.component("sv-text-area", TextAreaComponent);

export default TextAreaComponent;
</script>

// src/react/components/text-area.tsx
import React from "react";
import { TextAreaModel } from "survey-core";
import { ReactElementFactory } from "../element-factory";
import { SurveyElementBase } from "../reactquestion_element";

interface ITextAreaProps {
  viewModel: TextAreaModel;
}

export class TextAreaComponent extends SurveyElementBase<ITextAreaProps, any> {
  private initialValue;

  constructor(props: ITextAreaProps) {
    super(props);
    this.initialValue = this.viewModel.getTextValue() || "";
  }
  get viewModel(): TextAreaModel {
    return this.props.viewModel;
  }
  protected canRender(): boolean {
    return !!this.viewModel.question;
  }

  protected renderElement(): JSX.Element {
    return (
      <textarea
        id={this.viewModel.id}
        className={this.viewModel.className}
        ref={(textarea) => (this.viewModel.setElement(textarea))}
        disabled={this.viewModel.isDisabledAttr}
        readOnly={this.viewModel.isReadOnlyAttr}
        rows={this.viewModel.rows}
        cols={this.viewModel.cols}
        placeholder={this.viewModel.placeholder}
        maxLength={this.viewModel.maxLength}
        defaultValue={this.initialValue}
        onChange={(event: any) => { this.viewModel.onTextAreaInput(event); }}
        onBlur={(event: any) => { this.viewModel.onTextAreaChange(event); }}
        onKeyDown={(event: any) => { this.viewModel.onTextAreaKeyDown(event); }}
        aria-required={this.viewModel.ariaRequired}
        aria-label={this.viewModel.ariaLabel}
        aria-labelledby={this.viewModel.ariaLabelledBy}
        aria-describedby={this.viewModel.ariaDescribedBy}
        aria-invalid={this.viewModel.ariaInvalid}
        aria-errormessage={this.viewModel.ariaErrormessage}
        style={{ resize: this.viewModel.question.resizeStyle }}
      />
    );
  }
}

ReactElementFactory.Instance.registerElement("sv-text-area", (props) => {
  return React.createElement(TextAreaComponent, props);
});
