// packages/survey-angular-ui/src/components/header/header.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { BaseAngular } from "../../base-angular";
import { Cover, CoverCell, SurveyModel } from "survey-core";

@Component({
  selector: "sv-cover, sv-ng-cover",
  templateUrl: "./header.component.html",
  styles: [":host { display: none }"]
})
export class HeaderComponent extends BaseAngular<Cover> {
  @Input() model!: Cover;
  @Input() survey!: SurveyModel;
  @ViewChild("container") container!: ElementRef<HTMLDivElement>;
  getModel(): Cover {
    this.model.survey = this.survey;
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-cover", HeaderComponent);
<ng-template #template>
  <div *ngIf="(survey.headerView === 'advanced' && survey.renderedHasHeader)" [class]="model.coverClasses" [style]="{ height: model.renderedHeight }">
    <div *ngIf="!!model.backgroundImage" [style]="model.backgroundImageStyle" [class]="model.backgroundImageClasses"></div>
    <div *ngIf="!survey.isMobile" [class]="model.contentClasses" [style.width]="model.maxWidth">
      <ng-container *ngFor="let cell of model.cells">
        <sv-ng-header-cell [model]="cell"></sv-ng-header-cell>
      </ng-container>
    </div>
    <div *ngIf="survey.isMobile">
      <sv-ng-header-mobile [model]="survey"></sv-ng-header-mobile>
    </div>
  </div>
</ng-template>

// packages/survey-vue3-ui/src/components/header/Header.vue
<template>
  <div :class="model.coverClasses" :style="{ 'height': model.renderedHeight }">
    <div v-if="!!model.backgroundImage" :class="model.backgroundImageClasses" :style="model.backgroundImageStyle"></div>
    <div v-if="!survey.isMobile" :class="model.contentClasses" :style="{ maxWidth: model.maxWidth }">
    <sv-cover-cell
      v-for="cell in model.cells"
      :model="cell"
    ></sv-cover-cell>
    </div>
    <div v-if="survey.isMobile">
      <sv-header-mobile :model="survey"></sv-header-mobile>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { Base, SurveyModel, Cover, CoverCell } from "survey-core";
import { useBase } from "@/base";
import { onMounted, onUnmounted, ref } from "vue";

const props = defineProps<{
  model: Cover;
  survey: SurveyModel;
}>();

useBase(() => {
  props.model.survey = props.survey
  return props.model;
});
</script>
