// packages/survey-angular-ui/src/questions/checkbox.component.ts
import { Component } from "@angular/core";
import { QuestionCheckboxModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";
import { SelectBaseComponent } from "./selectbase.component";

@Component({
  selector: "sv-ng-checkbox-question",
  templateUrl: "./selectbase.component.html"
})
export class CheckboxComponent extends SelectBaseComponent<QuestionCheckboxModel> {}

AngularComponentFactory.Instance.registerComponent("checkbox-question", CheckboxComponent);
<fieldset [class]="model.getSelectBaseRootCss()" role="presentation">
  <legend role="presentation" class="sv-hidden"></legend>
  <div *ngIf="!model.hasColumns">
    <sv-checkbox-item *ngFor="let item of model.visibleChoices" [question]="model" [model]="item"></sv-checkbox-item>
  </div>
  <!-- ko ifnot: question.hasColumns  -->
    <!-- ko foreach: { data: question.visibleChoices, as: 'item', afterRender: question.koAfterRender }  -->
      <!-- ko component: { name: question.getItemValueWrapperComponentName(item), params: { componentData:  question.getItemValueWrapperComponentData(item), templateData: { name: 'survey-checkbox-item', data: item } } } -->
      <!-- /ko -->
    <!-- /ko -->
  <!-- /ko -->
  <!-- ko if: question.hasColumns  -->
    <!-- ko if: question.hasHeadItems  -->
      <!-- ko foreach: { data: question.headItems, as: 'item', afterRender: question.koAfterRender }  -->
        <!-- ko component: { name: question.getItemValueWrapperComponentName(item), params: { componentData:  question.getItemValueWrapperComponentData(item), templateData: { name: 'survey-checkbox-item', data: item } } } -->
        <!-- /ko -->
      <!-- /ko -->
    <!-- /ko -->
    <div *ngIf="model.hasColumns" data-bind="css: question.koCss().rootMultiColumn">
    <!-- ko foreach: question.columns -->
        <div data-bind="css: question.getColumnClass()" role="presentation">
        <!-- ko foreach: { data: $data, as: 'item', afterRender: question.koAfterRender }  -->
          <!-- ko component: { name: question.getItemValueWrapperComponentName(item), params: { componentData:  question.getItemValueWrapperComponentData(item), templateData: { name: 'survey-checkbox-item', data: item } } } -->
          <!-- /ko -->
        <!-- /ko -->
        </div>
    <!-- /ko -->
    </div>
    <!-- ko if: question.hasFootItems  -->
      <!-- ko foreach: { data: question.footItems, as: 'item', afterRender: question.koAfterRender }  -->
        <!-- ko component: { name: question.getItemValueWrapperComponentName(item), params: { componentData:  question.getItemValueWrapperComponentData(item), templateData: { name: 'survey-checkbox-item', data: item } } } -->
        <!-- /ko -->
      <!-- /ko -->
    <!-- /ko -->
  <!-- /ko -->
  <div *ngIf="model.hasOther && model.isOtherSelected" class="form-group" data-bind="template: { name: 'survey-comment', data: {'question': question, 'visible': question.isOtherSelected } }"></div>
</fieldset>

// src/vue/checkbox.vue
<template>
  <fieldset :class="question.getSelectBaseRootCss()" role="presentation">
    <legend role="presentation" class="sv-hidden"></legend>
    <survey-checkbox-item
      v-if="!question.hasColumns"
      v-for="(item, index) in question.visibleChoices"
      :key="item.value"
      :class="question.getItemClass(item)"
      :question="question"
      :item="item"
      :index="index"
    ></survey-checkbox-item>
    <survey-checkbox-item
        v-for="(item, index) in question.headItems"
        v-if="question.hasColumns && question.hasHeadItems"
        :key="item.value"
        :class="question.getItemClass(item)"
        :question="question"
        :item="item"
        :index="'' + index"
      ></survey-checkbox-item>
    <div 
      v-if="question.hasColumns"
      :class="question.cssClasses.rootMultiColumn">

    <div
      
      v-for="(column, colIndex) in question.columns"
      :class="question.getColumnClass()"
      role="presentation"
    >
      <survey-checkbox-item
        v-for="(item, index) in column"
        :key="item.value"
        :class="question.getItemClass(item)"
        :question="question"
        :item="item"
        :index="'' + colIndex + index"
      ></survey-checkbox-item>
    </div>
    </div>
        <survey-checkbox-item
        v-for="(item, index) in question.footItems"
        v-if="question.hasColumns && question.hasFootItems"
        :key="item.value"
        :class="question.getItemClass(item)"
        :question="question"
        :item="item"
        :index="'' + index"
      ></survey-checkbox-item>
      <survey-other-choice
        v-if="
          question.renderedValue && question.isOtherSelected
        "
        :question="question"
      />
      </fieldset>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop, Watch } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionCheckboxModel } from "survey-core";

@Component
export class Checkbox extends QuestionVue<QuestionCheckboxModel> {
}
Vue.component("survey-checkbox", Checkbox);
export default Checkbox;
</script>
