// packages/survey-angular-ui/src/questions/customwidget.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnChanges, OnDestroy, SimpleChanges, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { Question } from "survey-core";

@Component(
  {
    templateUrl: "./customwidget.component.html",
    selector: "sv-ng-custom-widget"
  }
)
export class CustomWidgetComponent implements AfterViewInit, OnDestroy, OnChanges {
  @Input() css: any;
  @Input() model!: Question;

  @ViewChild("content") container!: ElementRef<HTMLDivElement>;

  get hasDefaultRender(): boolean {
    return this.model.customWidget.isDefaultRender || this.hasAngularComponent;
  }
  get hasHtml(): boolean {
    return this.model.customWidget.htmlTemplate ? true : false;
  }
  get customHtml(): string {
    return this.model.customWidget.htmlTemplate;
  }
  get hasAngularComponent(): boolean {
    return AngularComponentFactory.Instance.isComponentRegistered(this.model.customWidget.name);
  }
  get componentName(): string {
    if (this.hasAngularComponent) return this.model.customWidget.name;
    return this.model.getTemplate() + "-question";
  }
  ngAfterViewInit(): void {
    this.model.customWidget.afterRender(this.model, this.container.nativeElement);
  }
  ngOnChanges(simpleChanges: SimpleChanges) {
    if(simpleChanges["model"].previousValue !== undefined && simpleChanges["model"].currentValue !== undefined) {
      this.model.customWidget.afterRender(this.model, this.container.nativeElement);
    }
  }
  ngOnDestroy(): void {
    this.model.customWidget.willUnmount(this.model, this.container.nativeElement);
  }

}

AngularComponentFactory.Instance.registerComponent("survey-customwidget", CustomWidgetComponent);

<div #content>
  <div *ngIf="hasHtml" [innerHTML]="customHtml | safeHtml"></div>
  <ng-container *ngIf="hasDefaultRender">
    <ng-template [component]="{ name: componentName, data: { model: model, css: css } }"></ng-template>  
  </ng-container>
</div>

// src/vue/customwidget.vue
<template>
  <div>
    <div v-if="hasHtml" v-html="customHtml"></div>
    <component
      v-if="hasDefaultRender"
      :is="componentName"
      :question="question"
      :css="css"
    />
  </div>
</template>

<script lang="ts">
import Vue, { ComponentOptions } from "vue";
import { Component, Prop } from "vue-property-decorator";
import { Question } from "survey-core";

@Component
export class CustomWidget extends Vue {
  @Prop() css: any;
  @Prop() question: Question;
  get hasDefaultRender(): boolean {
    return this.question.customWidget.isDefaultRender || this.hasVueComponent;
  }
  get hasHtml(): boolean {
    return this.question.customWidget.htmlTemplate ? true : false;
  }
  get customHtml(): string {
    return this.question.customWidget.htmlTemplate;
  }
  get hasVueComponent(): boolean {
    var options = (<any>Vue)["options"];
    if (!options) return false;
    return (
      options.components && options.components[this.question.customWidget.name]
    );
  }
  get componentName(): string {
    if (this.hasVueComponent) return this.question.customWidget.name;
    return "survey-" + this.question.getTemplate();
  }
  mounted() {
    this.question.customWidget.afterRender(this.question, this.$el);
  }
  updated() {
    //this.question.customWidget.afterRender(this.question, this.$el);
  }
  beforeDestroy() {
    this.question.customWidget.willUnmount(this.question, this.$el);
  }
}
Vue.component("survey-customwidget", CustomWidget);

export default CustomWidget;
</script>
