// packages/survey-angular-ui/src/components/dropdown/dropdown-select.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { RendererFactory } from "survey-core";

@Component({
  selector: "sv-ng-dropdown-select-question",
  templateUrl: "./dropdown-select.component.html"
})
export class DropdownSelectComponent {
  @Input() model: any;

  click(event: any) {
    this.model.onClick(event);
  }
  keyup(event: any) {
    this.model.onKeyUp(event);
  }
}

AngularComponentFactory.Instance.registerComponent("dropdown-select-question", DropdownSelectComponent);
RendererFactory.Instance.registerRenderer("dropdown", "select", "dropdown-select-question");
<div [class]="model.renderCssRoot">
  <div [class]="model.cssClasses.selectWrapper">
    <select *ngIf="!model.isReadOnly" [attr.id]="model.inputId" [(ngModel)]="model.renderedValue"
      [disabled]="model.isInputReadOnly" (click)="click($event)" (keyup)="keyup($event)"
      [class]="model.getControlClass()" [attr.autocomplete]="model.autoComplete" [required]="model.isRequired"
      [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel"
      [attr.aria-invalid]="model.ariaInvalid" [attr.aria-describedby]="model.ariaDescribedBy">
      <option *ngIf="model.allowClear" [value]="undefined">{{ model.placeholder }}</option>
      <option *ngFor="let item of model.visibleChoices" [value]="item.value" [disabled]="!item.isEnabled">{{ item.text }}</option>
    </select>
    <div *ngIf="model.isReadOnly" disabled [class]="model.getControlClass()" [attr.id]="model.inputId">{{ model.readOnlyText }}</div>
  </div>
  <div *ngIf="model.hasOther && model.isOtherSelected" class="form-group"
    [style.display]="model.isFlowLayout ? 'inline': '' " [question]="model" sv-ng-comment></div>
</div>

// src/vue/dropdown-select.vue
<template>
  <div :class="question.renderCssRoot">
    <div :class="question.cssClasses.selectWrapper">
      <select
        v-if="!question.isReadOnly"
        :id="question.inputId"
        v-model="question.renderedValue"
        @click="click"
        @keyup="keyUp"
        :autocomplete="question.autocomplete"
        :class="question.getControlClass()"
        :aria-required="question.ariaRequired"
        :aria-label="question.ariaLabel"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
        :required="question.isRequired"
      >
        <option v-if="question.allowClear" :value="undefined">{{ question.placeholder }}</option>
        <sv-dropdown-option-item
          v-for="item in question.visibleChoices"
          :item="item"
          :key="item.id"
        ></sv-dropdown-option-item>
      </select>
      <div disabled v-else :id="question.inputId" :class="question.getControlClass()">{{ question.readOnlyText }}</div>
    </div>
    <survey-other-choice v-if="question.isOtherSelected" :question="question" />
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionDropdownModel, RendererFactory } from "survey-core";

@Component
export class DropdownSelect extends QuestionVue<QuestionDropdownModel> {
  public click(event: any) {
    this.question.onClick(event);
  }
  public keyUp(event: any) {
    this.question.onKeyUp(event);
  }
}

Vue.component("sv-dropdown-select", DropdownSelect);
RendererFactory.Instance.registerRenderer("dropdown", "select", "sv-dropdown-select");

export default DropdownSelect;
</script>
