// packages/survey-angular-ui/src/components/dropdown.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "sv-ng-dropdown, '[sv-ng-dropdown]'",
  templateUrl: "./dropdown.component.html"
})
export class DropdownComponent {
  @Input() model: any;
}
<div [class]="model.cssClasses.selectWrapper">
  <select *ngIf="!model.isReadOnly" [attr.id]="model.inputId" [(ngModel)]="model.renderedValue" [disabled]="model.isInputReadOnly"
    [class]="model.getControlClass()" [autocomplete]="model.autoComplete" [required]="model.isRequired"
    [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid"
    [attr.aria-describedby]="model.ariaDescribedBy">
    <option *ngIf="model.showOptionsCaption" [value]="''">{{ model.optionsCaption }}</option>
    <option *ngFor="let item of model.visibleChoices" [value]="item.value" [disabled]="!item.isEnabled">{{ item.text }}</option>
  </select>
  <div *ngIf="model.isReadOnly" disabled [class]="model.getControlClass()" [attr.id]="model.inputId">{{ model.readOnlyText }}</div>
</div>

// src/vue/dropdown.vue
<template>
  <div :class="question.renderCssRoot">
    <div v-if="!question.isReadOnly" :class="question.cssClasses.selectWrapper">
      <select
        :id="question.inputId"
        v-model="question.renderedValue"
        :autocomplete="question.autoComplete"
        :class="question.getControlClass()"
        :aria-required="question.ariaRequired"
        :aria-label="question.ariaLabel"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
        :required="question.isRequired"
      >
        <option v-if="question.showOptionsCaption" :value="undefined">{{ question.optionsCaption }}</option><option
          v-for="item in question.visibleChoices"
          :value="item.value"
          :disabled="!item.isEnabled"
        >{{ item.text }}</option>
      </select>
    </div><div
      disabled
      v-else
      :id="question.inputId"
      :class="question.getControlClass()"
    >{{ question.readOnlyText }}</div><survey-other-choice v-if="question.isOtherSelected" :question="question" />
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionDropdownModel } from "survey-core";

@Component
export class Dropdown extends QuestionVue<QuestionDropdownModel> {
}
Vue.component("survey-dropdown", Dropdown);
export default Dropdown;
</script>
