// packages/survey-angular-ui/src/questions/expression.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { QuestionAngular } from "../question";
import { QuestionExpressionModel } from "survey-core";

@Component({
  selector: "sv-ng-expression",
  template: "<div [class]='model.cssClasses.root' #contentElement>{{ model.formatedValue }}</div>"
})
export class ExpressionComponent extends QuestionAngular<QuestionExpressionModel> {
}

AngularComponentFactory.Instance.registerComponent("expression-question", ExpressionComponent);

// src/vue/expression.vue
<template>
  <div :class="question.cssClasses.root">{{ question.formatedValue }}</div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionExpressionModel } from "survey-core";

@Component
export class Expression extends QuestionVue<QuestionExpressionModel> {}
Vue.component("survey-expression", Expression);
export default Expression;
</script>
