// packages/survey-angular-ui/src/questions/file.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionFileModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";
@Component({
  selector: "sv-ng-file-question",
  templateUrl: "./file.component.html",
  styleUrls: []
})
export class FileQuestionComponent extends QuestionAngular<QuestionFileModel> {}

AngularComponentFactory.Instance.registerComponent("file-question", FileQuestionComponent);
<div [class]="model.fileRootCss" #contentElement>
  <input
    [class]="model.cssClasses.fileInput"
    *ngIf="!model.isReadOnly"
    tabindex="-1"
    type="file"
    [attr.id]="model.inputId"
    (change)="model.doChange($event)"
    [attr.aria-required]="model.ariaRequired"
    [attr.aria-label]="model.ariaLabel"
    [attr.aria-invalid]="model.ariaInvalid"
    [attr.aria-describedby]="model.ariaDescribedBy"
    [attr.multiple]="model.multipleRendered"
    [attr.title]="model.inputTitle"
    [attr.accept]="model.acceptedTypes"
    [attr.capture]="model.renderCapture"
  />
  <input
    *ngIf="model.isReadOnly"
    type="file"
    disabled
    [class]="model.getReadOnlyFileCss()"
    [attr.id]="model.inputId"
    [attr.multiple]="model.multipleRendered"
    [attr.placeholder]="model.title"
    style="color: transparent"
  />
  <div [class]="model.cssClasses.dragArea"
    (dragenter)="model.onDragEnter($event)"
    (drop)="model.onDrop($event)"
    (dragover)="model.onDragOver($event)"
    (dragleave)="model.onDragLeave($event)">  
    <div
      [class]="model.getFileDecoratorCss()"
    >
      <span [class]="model.cssClasses.dragAreaPlaceholder">{{ model.dragAreaPlaceholder }}</span>
      <div [class]="model.cssClasses.wrapper">
        <label
          *ngIf="!model.isReadOnly"
          role="button"
          tabindex="0"
          [class]="model.getChooseFileCss()"
          [attr.for]="model.inputId"
          [attr.aria-label]="model.chooseButtonCaption"
          [key2click]
          >
          <span>{{ model.chooseButtonCaption }}</span>
          <svg *ngIf="model.cssClasses.chooseFileIconId" [title]="model.chooseButtonCaption" [iconName]="model.cssClasses.chooseFileIconId" [size]="'auto'" sv-ng-svg-icon></svg>
        </label>
        <span
          [class]="model.cssClasses.noFileChosen"
          *ngIf="model.isEmpty()"
          >{{ model.noFileChosenCaption }}</span
        >
      </div>
    </div>
    <button
      type="button"
      *ngIf="model.showRemoveButton"
      [class]="model.cssClasses.removeButton"
      (click)="model.doClean($event)"
    >
      <span>{{ model.clearButtonCaption }}</span>
      <svg *ngIf="model.cssClasses.removeButtonIconId" [iconName]="model.cssClasses.removeButtonIconId" [size]="'auto'" [title]="model.clearButtonCaption" sv-ng-svg-icon></svg>
    </button>
    <div [class]="model.cssClasses.fileList || undefined" *ngIf="!model.isEmpty()">
      <span
        *ngFor="let val of model.previewValue; index as index; trackBy: trackFilesFn"
        [visible]="val && model.isPreviewVisible(index)"
        [class]="model.cssClasses.preview"
      >
        <div *ngIf="val.name && model.cssClasses.fileSign" [class]="model.cssClasses.fileSign">
          <a
            (click)="model.doDownloadFile($event, val)"
            [attr.href]="val.content | safeUrl"
            [attr.title]="val.name"
            [attr.download]="val.name"
            [style.width]="model.imageWidth"
            >{{ val.name }}</a
          >
        </div>
        <div [class]="model.cssClasses.imageWrapper">
          <img
            *ngIf="model.canPreviewImage(val)"
            [attr.src]="val.content | safeUrl"
            [style.height]="model.imageHeight"
            [style.width]="model.imageWidth"
            alt="File preview"
          />
          <svg *ngIf="model.defaultImage(val)" 
            [iconName]="model.cssClasses.defaultImageIconId" [partCss]="model.cssClasses.defaultImage" [size]="'auto'" sv-ng-svg-icon></svg>
          <div *ngIf="val.name && !model.isReadOnly" [class]="model.cssClasses.removeFileButton" (click)="model.doRemoveFile(val)">
            <span
              [class]="model.cssClasses.removeFile"
              >{{ model.removeFileCaption }}</span
            >
            <svg *ngIf="model.cssClasses.removeFileSvgIconId" [title]="model.removeFileCaption" [partCss]="model.cssClasses.removeFileSvg" [iconName]="model.cssClasses.removeFileSvgIconId" [size]="'auto'" sv-ng-svg-icon ></svg>
          </div>
        </div>
        <div *ngIf="val.name && model.cssClasses.fileSignBottom" [class]="model.cssClasses.fileSignBottom">
          <a
            (click)="model.doDownloadFile($event, val)"
            [attr.href]="val.content | safeUrl"
            [attr.title]="val.name"
            [attr.download]="val.name"
            [style.width]="model.imageWidth"
            >{{ val.name }}</a
          >
        </div>
      </span>
    </div>
    <button
      type="button"
      *ngIf="model.showRemoveButtonBottom"
      [class]="model.showRemoveButtonBottom"
      (click)="model.doClean($event)"
    >
      <span>{{ model.clearButtonCaption }}</span>
      <svg *ngIf="model.cssClasses.removeButtonIconId" [iconName]="model.cssClasses.removeButtonIconId" [size]="'auto'" [title]="model.clearButtonCaption" sv-ng-svg-icon></svg>
    </button>
    <sv-action-bar *ngIf="model.mobileFileNavigatorVisible" [model]="model.mobileFileNavigator"></sv-action-bar>
  </div>
</div>

// src/vue/file.vue
<template>
  <div :class="question.fileRootCss">
    <input
      :class="question.cssClasses.fileInput"
      v-if="!question.isReadOnly"
      tabindex="-1"
      type="file"
      :id="question.inputId"
      @change="question.doChange"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-describedby="question.ariaDescribedBy"
      :multiple="question.multipleRendered"
      v-bind:title="question.inputTitle"
      v-bind:accept="question.acceptedTypes"
      :capture="question.renderCapture"
    />
    <input
      v-if="question.isReadOnly"
      type="file"
      disabled
      :id="question.inputId"
      :class="question.getReadOnlyFileCss()"
      :multiple="question.multipleRendered"
      :placeholder="question.title"
      style="color: transparent"
    />
    <div 
      :class="question.cssClasses.dragArea"
      @drop="question.onDrop"
      @dragover="question.onDragOver"
      @dragleave="question.onDragLeave"
      @dragenter="question.onDragEnter"
    >
      <div
        :class="question.getFileDecoratorCss()"
      >
        <span :class="question.cssClasses.dragAreaPlaceholder">{{ question.dragAreaPlaceholder }}</span>
        <div :class="question.cssClasses.wrapper">
          <label
            v-if="!question.isReadOnly"
            role="button"
            tabindex="0"
            :class="question.getChooseFileCss()"
            :for="question.inputId"
            v-bind:aria-label="question.chooseButtonText"
              v-key2click
            >
            <span>{{ question.chooseButtonText }}</span>
            <sv-svg-icon v-if="question.cssClasses.chooseFileIconId" :title="question.chooseButtonText" :iconName="question.cssClasses.chooseFileIconId" :size="'auto'"></sv-svg-icon>
          </label>
          <span
            :class="question.cssClasses.noFileChosen"
            v-if="question.isEmpty()"
            >{{ question.noFileChosenCaption }}</span
          >
        </div>
      </div>
      <button
        type="button"
        v-if="question.showRemoveButton"
        :class="question.cssClasses.removeButton"
        @click="question.doClean"
      >
        <span>{{ question.clearButtonCaption }}</span>
        <sv-svg-icon v-if="question.cssClasses.removeButtonIconId" :iconName="question.cssClasses.removeButtonIconId" :size="'auto'" :title="question.clearButtonCaption"></sv-svg-icon>
      </button>
      <div :class="question.cssClasses.fileList || undefined" v-if="!question.isEmpty()">
        <span
          v-for="(val, index) in question.previewValue"
          :key="question.inputId + '_' + index"
          v-show="val && isPreviewVisible(index)"
          :class="question.cssClasses.preview"
        >
          <div v-if="val.name && question.cssClasses.fileSign" :class="question.cssClasses.fileSign">
            <a
              @click="question.doDownloadFile($event, val)"
              :href="val.content"
              :title="val.name"
              :download="val.name"
              :style="{width: question.imageWidth}"
              >{{ val.name }}</a
            >
          </div>
          <div :class="question.cssClasses.imageWrapper">
            <img
              v-if="question.canPreviewImage(val)"
              :src="val.content"
              :style="{height: question.imageHeight, width: question.imageWidth}"
              alt="File preview"
            />
            <sv-svg-icon v-if="question.defaultImage(val)" 
              :iconName="question.cssClasses.defaultImageIconId" :class="question.cssClasses.defaultImage" :size="'auto'"></sv-svg-icon>
            <div v-if="val.name && !question.isReadOnly" :class="question.cssClasses.removeFileButton" @click="question.doRemoveFile(val)">
              <span
                :class="question.cssClasses.removeFile"
                >{{ question.removeFileCaption }}</span
              >
              <sv-svg-icon v-if="question.cssClasses.removeFileSvgIconId" :title="question.removeFileCaption" :class="question.cssClasses.removeFileSvg" :iconName="question.cssClasses.removeFileSvgIconId" :size="'auto'"></sv-svg-icon>
            </div>
          </div>
          <div v-if="val.name && question.cssClasses.fileSignBottom" :class="question.cssClasses.fileSignBottom">
            <a
              @click="question.doDownloadFile($event, val)"
              :href="val.content"
              :title="val.name"
              :download="val.name"
              :style="{width: question.imageWidth}"
              >{{ val.name }}</a
            >
          </div>
        </span>
      </div>
      <button
        type="button"
        v-if="question.showRemoveButtonBottom"
        :class="question.showRemoveButtonBottom"
        @click="question.doClean"
      >
        <span>{{ question.clearButtonCaption }}</span>
        <sv-svg-icon v-if="question.cssClasses.removeButtonIconId" :iconName="question.cssClasses.removeButtonIconId" :size="'auto'" :title="question.clearButtonCaption"></sv-svg-icon>
      </button>
      <sv-action-bar v-if="question.mobileFileNavigatorVisible" :model="question.mobileFileNavigator"></sv-action-bar>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionFileModel } from "survey-core";
@Component
export class File extends QuestionVue<QuestionFileModel> {
  doRemoveFile(data: any) {
    this.question.doRemoveFile(data);
  }
  isPreviewVisible(index: any) {
    return this.question.isPreviewVisible(index);
  }
}
Vue.component("survey-file", File);
export default File;
</script>
