// packages/survey-angular-ui/src/questions/matrixdynamic.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionMatrixDynamicModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-matrixdynamic-question",
  templateUrl: "./matrixdynamic.component.html"
})
export class MatrixDynamicComponent extends QuestionAngular<QuestionMatrixDynamicModel> {}

AngularComponentFactory.Instance.registerComponent("matrixdynamic-question", MatrixDynamicComponent);
<ng-template #template>
  <div [style]="{ overflowX: model.showHorizontalScroll ? 'scroll' : '' }" [class]="model.cssClasses.tableWrapper" #contentElement>
    <div *ngIf="model.renderedTable.showAddRowOnTop" [class]="model.cssClasses.footer">
      <ng-container *ngTemplateOutlet="addRowButton"></ng-container>
    </div>
    <sv-ng-matrix-table *ngIf="model.renderedTable?.showTable" [question]="model" [table]="model.renderedTable"></sv-ng-matrix-table>
    <div *ngIf="!model.renderedTable.showTable" [class]="model.cssClasses.emptyRowsSection">
      <div [class]="model.cssClasses.emptyRowsText" [model]="model.locEmptyRowsText" sv-ng-string></div>
      <ng-container *ngTemplateOutlet="addRowButton"></ng-container>
    </div>
    <div *ngIf="model.renderedTable.showAddRowOnBottom" [class]="model.cssClasses.footer">
      <ng-container *ngTemplateOutlet="addRowButton"></ng-container>
    </div>
  </div>
  <ng-template #addRowButton>
    <button type="button" [class]="model.getAddRowButtonCss(true)" (click)="model.addRowUI()">
        <sv-ng-string [model]="model.locAddRowText" ></sv-ng-string>
        <span [class]="model.cssClasses.iconAdd"></span>
    </button>
  </ng-template>
</ng-template>

// src/vue/matrixdynamic.vue
<template>
  <div :style="{ overflowX: question.horizontalScroll ? 'scroll' : '' }">
    <div
      v-if="question.renderedTable.showAddRowOnTop"
      :class="question.cssClasses.footer"
    >
      <button
        type="button"
        :class="
          question.cssClasses.button + ' ' + question.cssClasses.buttonAdd
        "
        @click="addRowClick"
      >
        <survey-string :locString="question.locAddRowText" />
        <span :class="question.cssClasses.iconAdd"></span>
      </button>
    </div>
    <survey-matrixtable
      v-if="question.renderedTable.showTable"
      :question="question"
    />
    <div
      v-if="!question.renderedTable.showTable"
      :class="question.cssClasses.emptyRowsSection"
    >
      <div :class="question.cssClasses.emptyRowsText">
        <survey-string :locString="question.locEmptyRowsText" />
      </div>
      <button
        type="button"
        :class="
          question.cssClasses.button +
            ' ' +
            question.cssClasses.buttonAdd +
            ' ' +
            question.cssClasses.emptyRowsButton
        "
        @click="addRowClick"
      >
        <survey-string :locString="question.locAddRowText" />
        <span :class="question.cssClasses.iconAdd"></span>
      </button>
    </div>
    <div
      v-if="question.renderedTable.showAddRowOnBottom"
      :class="question.cssClasses.footer"
    >
      <button
        type="button"
        :class="
          question.cssClasses.button + ' ' + question.cssClasses.buttonAdd
        "
        @click="addRowClick"
      >
        <survey-string :locString="question.locAddRowText" />
        <span :class="question.cssClasses.iconAdd"></span>
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionMatrixDynamicModel } from "survey-core";
import { MatrixDropdownRowModelBase } from "survey-core";

@Component
export class MatrixDynamic extends QuestionVue<QuestionMatrixDynamicModel> {
  addRowClick() {
    this.question.addRow();
  }
}
Vue.component("survey-matrixdynamic", MatrixDynamic);
export default MatrixDynamic;
</script>
