// packages/survey-angular-ui/src/questions/matrixdropdowncell.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { BaseAngular } from "../base-angular";
import {
  Question,
  QuestionMatrixDropdownModelBase,
  QuestionMatrixDropdownRenderedCell,
  MatrixDropdownRowModelBase,
  SurveyModel
} from "survey-core";
import { getComponentName } from "../question";

@Component({
  selector: "sv-ng-matrixdropdown-cell",
  templateUrl: "./matrixdropdowncell.component.html",
  styles: [":host { display: none; }"]
})
export class MatrixDropdownCellComponent extends BaseAngular<Question> {
  @Input() question!: QuestionMatrixDropdownModelBase;
  @Input() cell!: QuestionMatrixDropdownRenderedCell;

  @ViewChild("cellContainer") cellContainer!: ElementRef<HTMLElement>;
  getModel() {
    if(this.cell.hasQuestion) {
      return this.cell.question;
    }
    if(!!this.cell.column) {
      return this.cell.column;
    }
    return null as any;
  }
  public get row(): MatrixDropdownRowModelBase {
    return this.cell.row;
  }
  public override ngDoCheck(): void {
    super.ngDoCheck();
    if(this.cell.isErrorsCell && this.cell?.question) {
      this.cell.question.registerFunctionOnPropertiesValueChanged(["errors", "visible"], () => {
        this.update();
      }, "__ngSubscription");
    }
  }
  public get panelComponentName(): string {
    const panel = this.cell.panel;
    const survey = <SurveyModel>panel.survey;
    if(!!survey) {
      const name = survey.getElementWrapperComponentName(panel);
      if(!!name) {
        return name;
      }
    }
    return "panel";
  }
  public get panelComponentData(): any {
    const panel = this.cell.panel;
    const survey = <SurveyModel>panel.survey;
    let data: any;
    if(!!survey) {
      data = survey.getElementWrapperComponentData(panel);
    }
    return {
      componentName: "panel",
      componentData: {
        model: panel,
        data: data
      }
    };
  }

  getComponentName(element: Question) { return getComponentName(element); }
  getCellStyle() {
    if (!!this.cell.width || !!this.cell.minWidth)
      return { width: this.cell.width, minWidth: this.cell.minWidth };
    return null;
  }
  public get isRequiredCell(): boolean {
    return !!this.cell.column && this.cell.column.isRenderedRequired;
  }
  ngAfterViewInit() {
    if (!this.cell.hasQuestion || !this.question || !this.question.survey) return;
    const el = this.cellContainer?.nativeElement;
    if(el) {
      const cellQ = this.cell.question;
      var options = {
        cell: this.cell.cell,
        cellQuestion: cellQ,
        htmlElement: el,
        row: this.cell.row,
        column: this.cell.cell.column,
      };
      this.question.survey.matrixAfterCellRender(this.question, options);
      cellQ.afterRenderCore(el);
    }
  }
  override ngOnDestroy(): void {
    super.ngOnDestroy();
    if(this.cell.isErrorsCell && this.cell?.question) {
      this.cell.question.unRegisterFunctionOnPropertiesValueChanged(["errors", "visible"], "__ngSubscription");
    }
  }
  public get canRender() {
    return this.question && this.question.survey && this.cell.isVisible;
  }
}
<ng-template #template>
  <td [class]="cell.className" *ngIf="canRender" [title]="cell.getTitle()"
    [style]="getCellStyle()" [attr.colspan]="cell.colSpans" (focusin)="cell.focusIn()" #cellContainer>
    <sv-ng-matrix-drag-drop-icon *ngIf="cell.isDragHandlerCell"
      [model]="$any({ data: { row: row, question: question } })"></sv-ng-matrix-drag-drop-icon>
    <sv-action-bar *ngIf="cell.isActionsCell" [model]="cell.item.getData()" [handleClick]="false"></sv-action-bar>
    <ng-container *ngIf="cell.hasPanel">
      <ng-template [component]="{ name: panelComponentName, data: panelComponentData }"></ng-template>
    </ng-container>
    <div *ngIf="cell.isErrorsCell && cell.question?.hasVisibleErrors" [element]="cell.question" sv-ng-errors></div>
    <span *ngIf="cell.showResponsiveTitle" [class]="cell.responsiveTitleCss">
      <sv-ng-string [model]="cell.responsiveLocTitle"></sv-ng-string>
      <sv-ng-matrixheaderrequired [column]="cell.column" [question]="cell.matrix">
      </sv-ng-matrixheaderrequired>
    </span>
    <div *ngIf="cell.hasQuestion" [class]="cell.cellQuestionWrapperClassName"
      [visible]="cell.question.isVisible">
      <ng-container *ngIf="!cell.isChoice && cell.question.isDefaultRendering()">
        <ng-template
          [component]="{ name: question.getCellWrapperComponentName(cell.cell), data: { componentData: question.getCellWrapperComponentData(cell.cell)} }">
          <ng-template
            [component]="{ name: getComponentName(cell.question), data: { model: cell.question } }"></ng-template>
        </ng-template>
      </ng-container>
      <ng-template *ngIf="!cell.isChoice && !cell.question.isDefaultRendering()"
        [component]="{ name: cell.question.getComponentName(), data: { model: cell.question } }">
      </ng-template>
      <ng-container *ngIf="cell.isItemChoice">
        <ng-template
          [component]="{ name: question.getCellWrapperComponentName(cell.cell), data: { componentData: question.getCellWrapperComponentData(cell.cell)} }">
          <sv-ng-selebase-item [showLabel]="false" [inputType]="cell.isCheckbox ? 'checkbox': 'radio'" [ariaLabel]="ariaLabel"
            [question]="cell.question" [model]="cell.item"></sv-ng-selebase-item>
        </ng-template>
      </ng-container>
      <div *ngIf="cell.isOtherChoice" [class]="cell.question.getCommentAreaCss(true)" [question]="cell.question" [item]="cell.question.otherItem"
        sv-ng-comment-choice></div>
    </div>
    <ng-container *ngIf="cell.hasTitle">
      <ng-template
        [component]="{ name: question.getCellWrapperComponentName($any(cell)), data: { componentData: question.getCellWrapperComponentData($any(cell))} }">
        <sv-ng-string [model]="cell.locTitle"></sv-ng-string>
        <span *ngIf="isRequiredCell" [class]="question.cssClasses.cellRequiredMark">{{ cell.requiredMark }}</span>
      </ng-template>
    </ng-container>
  </td>
</ng-template>

// src/vue/matrixdropdowncell.vue
<template>
  <td
    :class="cell.className"
    :title="cell.getTitle()"
    :style="getCellStyle()"
    :colspan="cell.colSpans"
    v-on:focusin="cell.focusIn()"
    v-if="cell.isVisible"
  >
    <survey-errors
      v-if="cell.isErrorsCell"
      :element="cell.question"
    />
    <sv-action-bar
      v-if="cell.isActionsCell"
      :model="cell.item.getData()"
      :handleClick="false"
    ></sv-action-bar>
    <component
      v-if="cell.hasPanel"
      :is="getComponentName(cell.panel)"
      :question="cell.panel"
      :css="question.cssClasses"
    ></component>
    <span v-if="cell.showResponsiveTitle" :class="cell.responsiveTitleCss">
      <survey-string :locString="cell.responsiveLocTitle" />
      <survey-matrixheaderrequired :column="cell.column" :question="cell.matrix"></survey-matrixheaderrequired>
    </span>
    <div v-if="cell.hasQuestion" :class="cell.cellQuestionWrapperClassName">
      <component
        v-if="!cell.isChoice && cell.question.isDefaultRendering()"
        v-show="isVisible"
        :is="getComponentName(cell.question)"
        :question="cell.question"
      />
      <component
        v-if="!cell.isChoice && !cell.question.isDefaultRendering()"
        v-show="isVisible"
        :is="cell.question.getComponentName()"
        :question="cell.question"
      />
      <survey-radiogroup-item
        v-if="cell.isRadio"
        :key="cell.item.value"
        :question="cell.question"
        :item="cell.item"
        :hideLabel="true"
      ></survey-radiogroup-item>
      <survey-checkbox-item
        v-if="cell.isCheckbox"
        :key="cell.item.value"
        :question="cell.question"
        :item="cell.item"
        :hideLabel="true"
      ></survey-checkbox-item>
      <survey-other-choice
        v-if="cell.isOtherChoice"
        :question="cell.question"
      />
    </div>
    <survey-string v-if="cell.hasTitle" :locString="cell.locTitle" />
  </td>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import BaseVue from "./base";
import {
  Question,
  QuestionMatrixDropdownRenderedCell,
  CssClassBuilder,
} from "survey-core";
import { getComponentName } from "./question";

@Component
export class MatrixDropdownCellComp extends BaseVue {
  @Prop() question: Question;
  @Prop() cell: QuestionMatrixDropdownRenderedCell;

  isVisible: boolean = false;
  getComponentName(element: Question | any) {
    return getComponentName(element);
  }
  getModel() {
    if(this.cell.hasQuestion) {
      return this.cell.question;
    }
    if(!!this.cell.column) {
      return this.cell.column;
    }
    return null as any;
  }
  getRequiredText(): string {
    return this.cell.requiredText;
  }
  getCellStyle() {
    if (!!this.cell.width || !!this.cell.minWidth)
      return { width: this.cell.width, minWidth: this.cell.minWidth };
    return null;
  }
  getCellIndex(): string {
    return (this.cell as any).index || "";
  }
  mounted() {
    if (!this.cell.hasQuestion || !this.question || !this.question.survey) return;
    this.onVisibilityChanged();
    this.cell.question.registerPropertyChangedHandlers(["isVisible"], () => {
      this.onVisibilityChanged();
    });
    const cQ = this.cell.question;
    const el: any = this.$el;
    const options = {
      cell: this.cell.cell,
      cellQuestion: cQ,
      htmlElement: el,
      row: this.cell.row,
      column: this.cell.cell.column,
    };
    this.question.survey.matrixAfterCellRender(this.question, options);
    if (cQ) {
      cQ.afterRenderCore(el);
    }
  }
  private onVisibilityChanged() {
    this.isVisible = this.cell.question.isVisible;
  }
}

Vue.component("survey-matrixdropdown-cell", MatrixDropdownCellComp);
export default MatrixDropdownCellComp;
</script>
