// packages/survey-react-ui/src/progressToc.tsx
import * as React from "react";
import { createTOCListModel, getTocRootCss, TOCModel } from "survey-core";
import { SurveyNavigationBase } from "./reactSurveyNavigationBase";
import { ReactElementFactory } from "./element-factory";
import { List } from "./components/list/list";
import { Popup } from "./components/popup/popup";
import { SvgIcon } from "./components/svg-icon/svg-icon";

export class SurveyProgressToc extends SurveyNavigationBase {
  render(): React.JSX.Element {
    const tocModel = this.props.model;
    let content: React.JSX.Element;
    if (tocModel.isMobile) {
      content = <div onClick={tocModel.togglePopup}>
        <SvgIcon iconName={tocModel.icon} size={24} />
        <Popup model={tocModel.popupModel} />
      </div>;
    } else {
      content = <List model={tocModel.listModel} />;
    }
    return (
      <div className={tocModel.containerCss}>
        {content}
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("sv-navigation-toc", (props) => {
  return React.createElement(SurveyProgressToc, props);
});

// src/vue/progressToc.vue
<template>
  <div :class="model.containerCss">
      <div v-if="model.isMobile" v-on:click="model.togglePopup" v-key2click>
          <sv-svg-icon :iconName="model.icon" :size="24"></sv-svg-icon>
          <sv-popup :model="model.popupModel"></sv-popup>
      </div>
      <sv-list v-else :model="model.listModel"></sv-list>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { SurveyModel, createTOCListModel, getTocRootCss, TOCModel } from "survey-core";

@Component
export class ProgressToc extends Vue {
  @Prop() model: TOCModel;
  @Prop() survey: SurveyModel;
  @Prop() css: any;
  constructor() {
    super();
  }
}

Vue.component("sv-navigation-toc", ProgressToc);
export default ProgressToc;
</script>
