// packages/survey-angular-ui/src/questions/radiogroup-item.component.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "sv-ng-radiogroup-item, '[sv-ng-radiogroup-item]'",
  templateUrl: "./radiogroup-item.component.html",
  styleUrls: ["./radiogroup-item.component.scss"]
})
export class RadiogroupItemComponent {
  @Input() question: any;
  @Input() model: any;
  constructor() {
  }
}

<div role="presentation" [class]="question.getItemClass(model)">
  <label [class]="question.getLabelClass(model)" [attr.aria-label]="question.getAriaItemLabel(model)">
    <input type="radio" [name]="question.questionName" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
      [disabled]="!question.getItemEnabled(model)" [checked]="question.renderedValue" [(ngModel)]="question.value" [value]="model.value"
    />
    <span *ngIf="question.cssClasses.materialDecorator" [class]="question.cssClasses.materialDecorator">
      <svg *ngIf="question.itemSvgIcon" [class]="question.cssClasses.itemDecorator">
        <use data-bind="attr:{'xlink:href':question.itemSvgIcon}" xlink:href=''></use>
      </svg>
    </span>
    <span [class]="question.getControlLabelClass(model)" [style.visibility]="!model.hideCaption ? 'visible' : 'hidden'">
      <string-viewer [model]="model.locText"></string-viewer>
    </span>
  </label>
</div>

// src/vue/radiogroupitem.vue
<template>
  <div role="presentation">
    <label :class="getLabelClass(item)" :aria-label="item.locText.renderedHtml">
      <input
        type="radio"
        :name="question.questionName"
        :value="item.value"
        :id="question.getItemId(item)"
        :aria-required="question.ariaRequired"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
        v-model="question.renderedValue"
        :disabled="!question.getItemEnabled(item)"
        :class="question.cssClasses.itemControl"
      /><span
        v-if="question.cssClasses.materialDecorator"
        :class="question.cssClasses.materialDecorator"
      >
        <svg
          v-if="question.itemSvgIcon"
          :class="question.cssClasses.itemDecorator"
        >
          <use :xlink:href="question.itemSvgIcon"></use>
        </svg> </span
      ><span
        v-if="!hideLabel"
        :class="getControlLabelClass(item)"
        :title="item.locText.renderedHtml"
      >
        <survey-string :locString="item.locText" />
      </span> </label
    ><survey-other-choice
      v-show="question.isOtherSelected"
      v-if="question.isOtherItem(item)"
      :question="question"
    />
  </div>
</template>

<script lang="ts">
import { ItemValue, Base } from "survey-core";
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { BaseVue } from "./base";

@Component
export class RadiogroupItem extends BaseVue {
  @Prop() question: any;
  @Prop() item: ItemValue;
  @Prop() index: any;
  @Prop() hideLabel: boolean;
  protected getModel(): Base {
    return this.item;
  }
  getLabelClass(item: any) {
    return this.question.getLabelClass(item);
  }
  getControlLabelClass(item: any) {
    return this.question.getControlLabelClass(item);
  }
}
Vue.component("survey-radiogroup-item", RadiogroupItem);
export default RadiogroupItem;
</script>
