// packages/survey-angular-ui/src/questions/rating.component.ts
import { Component, Input } from "@angular/core";
import { QuestionRatingModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-rating-question",
  templateUrl: "./rating.component.html"
})
export class RatingQuestionComponent {
  @Input() model!: QuestionRatingModel;
  constructor() {

  }
  trackByFn(index: number): number {
    return index;
  }
  public onClick(event: any) {
    event.stopPropagation();
    this.model.setValueFromClick(event.target.value);
  }
}

AngularComponentFactory.Instance.registerComponent("rating-question", RatingQuestionComponent);
  <div [class]="model.ratingRootCss">
      <fieldset role="radiogroup">
          <legend role="presentation" class="sv-hidden"></legend>
          <span *ngIf="model.hasMinLabel" [class]="model.cssClasses.minText" [model]="model.locMinRateDescription" sv-ng-string-viewer>
          </span>
          <label *ngFor="let item of model.renderedRateItems; index as index; trackBy: trackByFn" [class]="model.getItemClass(item.itemValue)" >
            <input type="radio"
              class="sv-visuallyhidden"
              [attr.name]="model.name" [attr.id]="model.getInputId(index)" [value]="item.value" [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid" [attr.aria-describedby]="model.ariaDescribedBy"
              [disabled]="model.isInputReadOnly" [checked]="model.value === item.value" (click)="onClick($event)"
              />
              <span [class]="model.cssClasses.itemText" [model]="item.locText" sv-ng-string-viewer></span>
          </label>
          <span *ngIf="model.hasMaxLabel" [class]="model.cssClasses.maxText" [model]="model.locMaxRateDescription" sv-ng-string-viewer></span>
      </fieldset>
  </div>

// src/vue/rating.vue
<template>
  <div :class="question.ratingRootCss">
      <fieldset role="radiogroup">
        <legend role="presentation" class="sv-hidden"></legend>
        <span v-if="question.hasMinLabel"
          :class="question.cssClasses.minText">
          <survey-string :locString="question.locMinRateDescription" />
        </span>
        <label
          v-for="(item, index) in question.renderedRateItems"
          :key="item.value"
          :class="question.getItemClass(item.itemValue)"
        >
          <input
            type="radio"
            class="sv-visuallyhidden"
            :name="question.name"
            :id="getInputId(index)"
            :value="item.value"
            :disabled="question.isInputReadOnly"
            @click="(e) => question.setValueFromClick(e.target.value)"
            :aria-required="question.ariaRequired"
            :aria-label="question.ariaLabel"
            :aria-invalid="question.ariaInvalid"
            :aria-describedby="question.ariaDescribedBy"
          />
          <span :class="question.cssClasses.itemText">
            <survey-string :locString="item.locText" />
          </span>
        </label>
        <span v-if="question.hasMaxLabel"
              :class="question.cssClasses.maxText"
        >
        <survey-string :locString="question.locMaxRateDescription" />
        </span>
      </fieldset>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionRatingModel } from "survey-core";

@Component
export class Rating extends QuestionVue<QuestionRatingModel> {
  getInputId(index: any) {
    return this.question.getInputId(index)
  }
}
Vue.component("survey-rating", Rating);
export default Rating;
</script>
