// packages/survey-angular-ui/src/string-editor.component.ts
import { Component, Input } from "@angular/core";
import { LocalizableString } from "survey-core";
import { AngularComponentFactory } from "./component-factory";

@Component({
  selector: "sv-ng-string-editor",
  templateUrl: "./string-editor.component.html"
})
export class StringEditorComponent {
  @Input() model!: LocalizableString;

  onInput = (event: any) => {
    this.model.text = event.target.innerText;
  };
  onClick = (event: any) => {
    event.preventDefault();
    event.stopPropagation();
  };
}
AngularComponentFactory.Instance.registerComponent(LocalizableString.editableRenderer, StringEditorComponent);
<span style="position: static">
  <span
    class="sv-string-editor"
    contenteditable="true"
    style="position: static"
    *ngIf="model.hasHtml"
    [innerHtml]="model.renderedHtml"
    (blur)="onInput($event)"
    (click)="onClick($event)"
  ></span>
  <span
    class="sv-string-editor"
    contenteditable="true"
    style="position: static"
    *ngIf="!model.hasHtml"
    (blur)="onInput($event)"
    (click)="onClick($event)"
    >{{ model.renderedHtml }}</span
  >
</span>

// src/vue/string-editor.vue
<template>
  <span style="position: static">
    <span
      class="sv-string-editor"
      contenteditable="true"
      style="position: static"
      v-if="locString.hasHtml"
      v-html="locString.renderedHtml"
      @blur="onInput"
      @click="onClick"
    ></span>
    <span
      class="sv-string-editor"
      contenteditable="true"
      style="position: static"
      v-else
      @blur="onInput"
      @click="onClick"
      >{{ locString.renderedHtml }}</span
    >
  </span>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { LocalizableString } from "survey-core";

@Component
export class SurveyStringEditor extends Vue {
  @Prop() locString: LocalizableString;

  onInput = (event: any) => {
    this.locString.text = event.target.innerText;
  };
  onClick = (event: any) => {
    event.preventDefault();
    event.stopPropagation();
  };
}

Vue.component(LocalizableString.editableRenderer, SurveyStringEditor);
export default SurveyStringEditor;
</script>
