// packages/survey-angular-ui/src/components/timer-panel/timer-panel.component.ts
import { Component, Input } from "@angular/core";
import { Base, SurveyTimerModel } from "survey-core";
import { BaseAngular } from "../../base-angular";

@Component(
  {
    selector: "sv-timerpanel",
    templateUrl: "./timer-panel.component.html",
  }
)

export class TimerPanelComponent extends BaseAngular<SurveyTimerModel> {
  @Input() model!: SurveyTimerModel;
  private readonly circleLengthValue = 440;

  protected getStateElement(): Base {
    return this.model;
  }
  protected getModel(): SurveyTimerModel {
    return this.model;
  }
  public get circleLength(): number {
    return this.circleLengthValue;
  }
  public get progress(): number {
    return -this.model.progress * this.circleLength;
  }
}

<div *ngIf="model.isRunning && model.showTimerAsClock" [class]="model.rootCss">
    <svg *ngIf="model.showProgress" [class]="model.getProgressCss()" [style.stroke-dasharray]="circleLength" [style.stroke-dashoffset]="progress" [size]="'auto'" [iconName]="'icon-timercircle'" sv-ng-svg-icon></svg>
    <div [class]="model.textContainerCss">
        <span [class]="model.majorTextCss">{{ model.clockMajorText }}</span>
        <span *ngIf="model.clockMinorText" [class]="model.minorTextCss">{{ model.clockMinorText }}</span>
    </div>
</div>
<div *ngIf="model.isRunning && !model.showTimerAsClock" [class]='model.survey.getCss().timerRoot'>{{model.text}}</div>

// src/vue/timerpanel.vue
<template>
  <div v-if="model.isRunning && model.showTimerAsClock" :class="model.rootCss">
    <svg
      v-if="model.showProgress"
      :class="model.getProgressCss()"
      :style="{ strokeDasharray: circleRadius, strokeDashoffset: progress }"
    >
      <use :xlink:href="'#icon-timercircle'"></use>
    </svg>
    <div :class="model.textContainerCss">
      <span :class="model.majorTextCss">{{ model.clockMajorText }}</span>
      <span v-if="!!model.clockMinorText" :class="model.minorTextCss">{{ model.clockMinorText }}</span>
    </div>
  </div>
  <div v-else v-show="model.isRunning && !model.showTimerAsClock" :class="model.survey.getCss().timerRoot">
    {{ text }}
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { Base, SurveyTimerModel } from "survey-core";
import { BaseVue } from "./base";

@Component
export class TimerPanel extends BaseVue {
  @Prop() model: SurveyTimerModel;
  @Prop() css: any;
  public readonly circleRadius: number = 440;
  public get progress(): number {
    return -this.circleRadius * this.model.progress;
  }
  get text() {
    return this.model.text;
  }
  protected getModel(): Base {
    return this.model;
  }
}
Vue.component("sv-timerpanel", TimerPanel);
export default TimerPanel;
</script>
