// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-progress-text.component.ts
import { Component } from "@angular/core";
import { PaneldynamicAction } from "./paneldynamic-add-btn.component";

@Component({
  selector: "sv-ng-paneldynamic-progress-text",
  templateUrl: "./paneldynamic-progress-text.component.html"
})
export class PanelDynamicProgressText extends PaneldynamicAction {
}

<div [class]="question.cssClasses.progressText">{{ question.progressText }}</div>

// packages/survey-vue-ui/src/components/paneldynamic-actions/PaneldynamicProgressText.vue
<template>
  <div :class="question.cssClasses.progressText">{{ question.progressText }}</div>
</template>

<script lang="ts">
import { PaneldynamicActionMixin } from "./action";
import { defineComponent } from "vue";

export default defineComponent({
  // eslint-disable-next-line
  mixins: [PaneldynamicActionMixin],
  name: "sv-paneldynamic-progress-text",
});
</script>
