// packages/survey-angular-ui/src/components/cover/cover-cell.component.ts
import { Component, Input, ViewChild, ViewContainerRef } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { EmbeddedViewContentComponent } from "../../embedded-view-content.component";
import { AngularComponentFactory } from "../../component-factory";
import { Cover, CoverCell, SurveyModel } from "survey-core";

@Component({
  selector: "sv-ng-cover-cell",
  templateUrl: "./cover-cell.component.html",
  styles: [":host { display: none; }"],
})
export class CoverCellComponent extends EmbeddedViewContentComponent {
  @Input() model!: CoverCell;
  @ViewChild("actionContent", { read: ViewContainerRef, static: true }) actionContent!: ViewContainerRef;
}

AngularComponentFactory.Instance.registerComponent("sv-cover-cell", CoverCellComponent);

<ng-template #template>
  <div [class]="model.css" [style]="model.style">
    <div class="sv-cover__cell-content" [style]="model.contentStyle">
      <div *ngIf="model.showLogo" class="sv-cover__logo">
        <div [class]="model.survey.logoClassNames">
          <ng-template [component]="{ name: model.survey.getElementWrapperComponentName(model.survey, 'logo-image'), data: { data: model.survey.getElementWrapperComponentData(model.survey, 'logo-image') } }"></ng-template>
        </div>
      </div>
      <div *ngIf="model.showTitle" class="sv-cover__title" [style]="{ maxWidth: model.textAreaWidth }">
        <sv-ng-element-title [element]="model.survey"></sv-ng-element-title>
      </div>
      <div *ngIf="model.showDescription" class="sv-cover__description" [style]="{ maxWidth: model.textAreaWidth }">
        <h5 *ngIf="model.survey.renderedHasDescription" [class]="model.survey.css.description" [model]="model.survey.locDescription" sv-ng-string></h5>
      </div>
    </div>
  </div>
</ng-template>

// packages/survey-vue3-ui/src/components/cover/CoverCell.vue
<template>
  <div :class="model.css" :style="model.style">
    <div class="sv-cover__cell-content" :style="model.contentStyle">
      <div v-if="model.showLogo" class="sv-cover__logo">
      <div :class="model.survey.logoClassNames">
        <img
          :class="model.survey.css.logoImage"
          :src="model.survey.locLogo.renderedHtml"
          :width="model.survey.renderedLogoWidth"
          :height="model.survey.renderedLogoHeight"
          :alt="model.survey.locTitle.renderedHtml"
          :style="{ 'objectFit': model.survey.logoFit as any, 'width': model.survey.renderedStyleLogoWidth, 'height': model.survey.renderedStyleLogoHeight }"
        />
      </div>
      </div>
      <div v-if="model.showTitle" class="sv-cover__title" :style="{ 'maxWidth': model.textWidth }">
        <survey-element-title :element="model.survey" :css="model.survey.css" />
      </div>
      <div v-if="model.showDescription" class="sv-cover__description" :style="{ 'maxWidth': model.textWidth }">
        <h5 v-if="model.survey.renderedHasDescription" :class="model.survey.css.description">
          <survey-string :locString="model.survey.locDescription" />
        </h5>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { Base, SurveyModel, Cover, CoverCell } from "survey-core";
import { onMounted, onUnmounted, ref } from "vue";

const props = defineProps<{
  model: CoverCell;
}>();
</script>
