// packages/survey-vue3-ui/src/components/matrix-actions/remove-button/RemoveButton.vue
<template>
  <button
    type="button"
    :class="question.getRemoveRowButtonCss()"
    :disabled="question.isInputReadOnly"
    @click="() => question.removeRowUI(row)"
  >
    <SvComponent :is="'survey-string'" :locString="question.locRemoveRowText" />
    <span :class="question.cssClasses.iconRemove"></span>
  </button>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { Action } from "survey-core";
import { useMatrixAction } from "../matrix-action";
const props = defineProps<{ item: Action }>();
const { question, row } = useMatrixAction(props);
</script>

// packages/survey-angular-ui/src/components/matrix-actions/remove-button/remove-button.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { Action, Base } from "survey-core";

@Component({
  selector: "sv-ng-matrix-remove-btn",
  templateUrl: "./remove-button.component.html"
})
export class MatrixDynamicRemoveButtonComponent {
  @Input() model!: Action;

  get question() {
    return this.model.data.question;
  }

  get row() {
    return this.model.data.row;
  }

  getModel(): Base {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent(
  "sv-matrix-remove-button",
  MatrixDynamicRemoveButtonComponent
);

<button type="button" [id]="question.getRowRemoveButtonId(row)" [class]="question.getRemoveRowButtonCss()" [disabled]="question.isInputReadOnly" (click)="question.removeRowUI(row)">
  <sv-ng-string [model]="question.locRemoveRowText" ></sv-ng-string>
  <span [class]="question.cssClasses.iconRemove"></span>
</button>
