// src/vue/components/paneldynamic-actions/paneldynamic-remove-btn.vue
<template>
  <button
    type="button"
    :class="question.getPanelRemoveButtonCss()"
    @click="removePanelClick(panel)"
  >
    <span :class="question.cssClasses.buttonRemoveText">{{
      question.panelRemoveText
    }}</span>
    <span :class="question.cssClasses.iconRemove"></span>
  </button>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { PaneldynamicAction } from "./paneldynamic-add-btn.vue";

@Component
export class PanelDynamicRemoveButton extends PaneldynamicAction {
  public get panel() {
    return (this.item && this.item.data.panel) || this.data.panel;
  }
  removePanelClick(panel: any) {
    if (!this.question.isInputReadOnly) {
      this.question.removePanelUI(panel);
    }
  }
}
Vue.component("sv-paneldynamic-remove-btn", PanelDynamicRemoveButton);
export default PanelDynamicRemoveButton;
</script>

// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-remove-btn.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { PaneldynamicAction } from "./paneldynamic-add-btn.component";

@Component({
  selector: "sv-ng-paneldynamic-remove-btn",
  templateUrl: "./paneldynamic-remove-btn.component.html"
})
export class PaneldynamicRemoveButtonComponent extends PaneldynamicAction {
  get panel() {
    return (this.data ? this.data : this.model.data).panel;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-paneldynamic-remove-btn", PaneldynamicRemoveButtonComponent);

<button type="button" (click)="question.removePanelUI(panel)" [class]="question.getPanelRemoveButtonCss()"> 
  <span [class]="question.cssClasses.buttonRemoveText">{{question.panelRemoveText}}</span>
  <span [class]="question.cssClasses.iconRemove"></span>
</button>
