// src/vue/components/paneldynamic-actions/paneldynamic-next-btn.vue
<template>
  <div :title="question.panelNextText" @click="nextPanelClick" :class="question.getNextButtonCss()">
    <sv-svg-icon :iconName="question.cssClasses.progressBtnIcon" :size="'auto'"></sv-svg-icon>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { PaneldynamicAction } from "./paneldynamic-add-btn.vue";

@Component
export class PanelDynamicNextBtn extends PaneldynamicAction {
  nextPanelClick() {
    this.question.goToNextPanel();
  }
}
Vue.component("sv-paneldynamic-next-btn", PanelDynamicNextBtn);
export default PanelDynamicNextBtn;
</script>

// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-next-btn.component.ts
import { Component } from "@angular/core";
import { PaneldynamicAction } from "./paneldynamic-add-btn.component";

@Component({
  selector: "sv-ng-paneldynamic-next-btn",
  templateUrl: "./paneldynamic-next-btn.component.html"
})
export class PanelDynamicNextBtn extends PaneldynamicAction {
  nextPanelClick() {
    this.question.goToNextPanel();
  }
}
export default PanelDynamicNextBtn;

<div [attr.title]="question.panelNextText" (click)="nextPanelClick()" [class]="question.getNextButtonCss()">
  <svg [iconName]="question.cssClasses.progressBtnIcon" [size]="'auto'" sv-ng-svg-icon></svg>
</div>
