// packages/survey-react-ui/src/components/paneldynamic-actions/paneldynamic-add-btn.tsx
import * as React from "react";
import {
  QuestionPanelDynamicModel
} from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { ReactSurveyElement } from "../../reactquestion_element";

export class SurveyQuestionPanelDynamicAction extends ReactSurveyElement {
  constructor(props: any) {
    super(props);
  }
  protected get data(): any {
    return (this.props.item && this.props.item.data) || this.props.data;
  }
  protected get question(): QuestionPanelDynamicModel {
    return (this.props.item && this.props.item.data.question) || this.props.data.question;
  }
  protected get isActionEnabled(): boolean {
    return !this.props.item || this.props.item.enabled !== false;
  }
}

export class SurveyQuestionPanelDynamicAddButton extends SurveyQuestionPanelDynamicAction {
  protected handleClick = (event: any) => {
    if (!this.isActionEnabled) return;
    this.question.addPanelUI();
  };
  protected renderElement(): React.JSX.Element | null {
    if (!this.question.canAddPanel) return null;
    const btnText = this.renderLocString(this.question.locAddPanelText);
    return (
      <button type="button" id={this.question.addButtonId} className={this.question.getAddButtonCss()} onClick={this.handleClick} disabled={!this.isActionEnabled}>
        <span className={this.question.cssClasses.buttonAddText}>{btnText}</span>
      </button>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-paneldynamic-add-btn",
  (props) => {
    return React.createElement(SurveyQuestionPanelDynamicAddButton, props);
  }
);

// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-add-btn.component.ts
import { Action, QuestionPanelDynamicModel } from "survey-core";
import { AngularComponentFactory } from "../../component-factory";
import { Component, Input } from "@angular/core";

@Component({
  selector: "",
  template: ""
})
export class PaneldynamicAction {
  @Input() data: any;
  @Input() model!: Action;
  public get question(): QuestionPanelDynamicModel {
    return (this.model && this.model.data.question) || this.data.question;
  }
  public get isActionEnabled(): boolean {
    return !this.model || this.model.enabled !== false;
  }
}

@Component({
  selector: "sv-ng-paneldynamic-add-btn",
  templateUrl: "./paneldynamic-add-btn.component.html"
})
export class PanelDynamicAddBtn extends PaneldynamicAction {
  addPanelClick() {
    if (!this.isActionEnabled) return;
    this.question.addPanelUI();
  }
}
AngularComponentFactory.Instance.registerComponent("sv-paneldynamic-add-btn", PanelDynamicAddBtn);
<button type="button" [id]="question.addButtonId" *ngIf="question.canAddPanel" [class]="question.getAddButtonCss()" [disabled]="!isActionEnabled" (click)="addPanelClick()">
<span [class]="question.cssClasses.buttonAddText"><sv-ng-string [model]="question.locAddPanelText"></sv-ng-string></span>
</button>
