// packages/survey-react-ui/src/components/paneldynamic-actions/paneldynamic-progress-text.tsx
import * as React from "react";
import { ReactElementFactory } from "../../element-factory";
import { ReactSurveyElement } from "../../reactquestion_element";
import { QuestionPanelDynamicModel } from "survey-core";

export class SurveyQuestionPanelDynamicProgressText extends ReactSurveyElement {
  protected get data(): any {
    return (this.props.item && this.props.item.data) || this.props.data;
  }
  protected get question(): QuestionPanelDynamicModel {
    return (this.props.item && this.props.item.data.question) || this.props.data.question;
  }
  protected renderElement(): React.JSX.Element {
    return (<div className={this.question.cssClasses.progressText}>
      {this.question.progressText}
    </div>);
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-paneldynamic-progress-text",
  (props) => {
    return React.createElement(SurveyQuestionPanelDynamicProgressText, props);
  }
);

// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-progress-text.component.ts
import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../component-factory";
import { Action, QuestionPanelDynamicModel } from "survey-core";
@Component({
  selector: "sv-ng-paneldynamic-progress-text",
  templateUrl: "./paneldynamic-progress-text.component.html"
})
export class PanelDynamicProgressText {
  @Input() data: any;
  @Input() model!: Action;
  public get question(): QuestionPanelDynamicModel {
    return (this.model && this.model.data.question) || this.data.question;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-paneldynamic-progress-text", PanelDynamicProgressText);
<div [class]="question.cssClasses.progressText">{{ question.progressText }}</div>
