// packages/survey-react-ui/src/components/slider/slider-label-item.tsx
import * as React from "react";
import { Base, ItemValue, QuestionSliderModel } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { ReactSurveyElement, SurveyElementBase } from "../../reactquestion_element";

export class SliderLabelItem extends SurveyElementBase<any, any> {
  protected getStateElement(): Base {
    return this.item;
  }
  protected get item(): ItemValue {
    return this.props.item;
  }
  protected get question(): QuestionSliderModel {
    return this.props.question;
  }
  componentDidUpdate(prevProps: any, prevState: any) {
    super.componentDidUpdate(prevProps, prevState);
  }

  protected renderElement(): React.JSX.Element {
    const { cssClasses, handleLabelPointerUp, getLabelCss, getPercent, getLabelMaxWidth } = this.question;
    const { value, locText } = this.item;
    let labelText = null;
    let labelTextSecondary = null;
    if (this.item.showValue) {
      labelText = <div className={cssClasses.labelText} title={"" + this.item.value}>{this.item.value}</div>;
      labelTextSecondary = <div className={cssClasses.labelTextSecondaryMode} title={locText.renderedHtml}>
        {this.renderLocString(locText)}
      </div>;
    } else {
      labelText = <div className={cssClasses.labelText} title={locText.renderedHtml}>
        {this.renderLocString(locText)}
      </div>;
    }
    return <div key={this.item.uniqueId} className={getLabelCss(locText)}
      style={{ left: getPercent(value) + "%", maxWidth: getLabelMaxWidth(this.item) }}
      onPointerUp={ (e)=>{ handleLabelPointerUp(e.nativeEvent, value); } }>
      <div className={cssClasses.labelTick}></div>
      <div className={cssClasses.labelTextContainer}>
        {labelText}
        {labelTextSecondary}
      </div>
    </div>;
  }
}

ReactElementFactory.Instance.registerElement("sv-slider-label-item", (props) => {
  return React.createElement(SliderLabelItem, props);
});

// packages/survey-angular-ui/src/components/slider/slider-label-item.component.ts
import { Component, Input } from "@angular/core";
import { ItemValue, QuestionSliderModel } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-slider-label-item",
  templateUrl: "./slider-label-item.component.html"
})

export class SliderLabelItemComponent extends BaseAngular {
  @Input() model!: QuestionSliderModel;
  @Input() item!: ItemValue;

  // onClick(event: any): void {
  //   this.model.setValueFromClick(event.target.value);
  //   event.stopPropagation();
  // }

  getModel() {
    return this.item;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-slider-label-item", SliderLabelItemComponent);
<ng-template #template>
    <div [class]="model.getLabelCss(item.locText)"
      [style]="{ left: model.getPercent(item.value) + '%', maxWidth: model.getLabelMaxWidth(item) }"
      (pointerup)="model.handleLabelPointerUp($any($event), item.value)">
        <div [class]="model.cssClasses.labelTick"></div>
        <div [class]="model.cssClasses.labelTextContainer">
          <div *ngIf="!item.showValue" [class]="model.cssClasses.labelText" [title]="item.locText.renderedHtml" [model]="item.locText" sv-ng-string></div>
          <div *ngIf="item.showValue" [class]="model.cssClasses.labelText" [title]="'' + item.value">{{ item.value }}</div>
          <div *ngIf="item.showValue" [class]="model.cssClasses.labelTextSecondaryMode" [title]="item.locText.renderedHtml" [model]="item.locText" sv-ng-string></div>
        </div>
    </div>
</ng-template>
