// src/vue/components/title/title-content.vue
<template>
  <div class="sv-vue-title-additional-div">
    <survey-string v-if="element.isTitleRenderedAsString" :locString="element.locTitle" />
    <span
      v-if="!element.isTitleRenderedAsString && element.isRequireTextOnStart"
      :class="cssClasses.requiredText"
      :aria-hidden="true"
      >{{ element.requiredText }}</span
    >
    <span
      v-if="!element.isTitleRenderedAsString && element.no"
      style="position: static"
      :class="element.cssTitleNumber"
      :aria-hidden="true"
      >{{ element.no }}</span
    >
    <span v-if="!element.isTitleRenderedAsString && element.no">&nbsp;</span>
    <span
      v-if="!element.isTitleRenderedAsString && element.isRequireTextBeforeTitle"
      :class="cssClasses.requiredText"
      :aria-hidden="true"
      >{{ element.requiredText }}</span
    >
    <span v-if="!element.isTitleRenderedAsString && element.isRequireTextBeforeTitle">&nbsp;</span>
    <survey-string v-if="!element.isTitleRenderedAsString" :locString="element.locTitle" />
    <span v-if="!element.isTitleRenderedAsString && element.isRequireTextAfterTitle">&nbsp;</span>
    <span
      v-if="!element.isTitleRenderedAsString && element.isRequireTextAfterTitle"
      :class="cssClasses.requiredText"
      :aria-hidden="true"
      >{{ element.requiredText }}</span
    >
  </div>
</template>

<script lang="ts">
import { Component, Prop } from "vue-property-decorator";

import Vue from "vue";
import { SurveyElementCore } from "survey-core";
@Component
export class TitleContent extends Vue {
  @Prop() element: any;
  @Prop() css: any;

  get cssClasses() {
    return (this.element.isPanel ? this.element.cssClasses.panel : this.element.cssClasses) || {};
  }

}
Vue.component("survey-element-title-content", TitleContent);
export default TitleContent;
</script>

// packages/survey-react-ui/src/components/title/title-content.tsx
import React from "react";
import { SurveyElementCore, ITitleOwner } from "survey-core";
import { SurveyElementBase } from "../../reactquestion_element";

export class TitleContent extends React.Component<any, any> {
  constructor(props: any) {
    super(props);
  }

  private get cssClasses() {
    return this.props.cssClasses;
  }

  private get element(): SurveyElementCore {
    return this.props.element;
  }
  render(): JSX.Element {
    if(this.element.isTitleRenderedAsString)
      return SurveyElementBase.renderLocString(this.element.locTitle);
    var spans = this.renderTitleSpans(this.element.getTitleOwner(), this.cssClasses);
    return <>{spans}</>;
  }
  protected renderTitleSpans(element: ITitleOwner, cssClasses: any): Array<JSX.Element> {
    var getSpaceSpan = (key: any) => {
      return (
        <span data-key={key} key={key}>
          &nbsp;
        </span>
      );
    };
    var spans: Array<JSX.Element> = [];
    if (element.isRequireTextOnStart) {
      spans.push(this.renderRequireText(element, cssClasses));
      spans.push(getSpaceSpan("req-sp"));
    }
    var questionNumber = element.no;
    if (questionNumber) {
      spans.push(
        <span
          data-key={"q_num"}
          key={"q_num"}
          className={element.cssTitleNumber}
          style={{ position: "static" }}
          aria-hidden={true}
        >
          {questionNumber}
        </span>
      );
      spans.push(getSpaceSpan("num-sp"));
    }
    if (element.isRequireTextBeforeTitle) {
      spans.push(this.renderRequireText(element, cssClasses));
      spans.push(getSpaceSpan("req-sp"));
    }
    spans.push(
      SurveyElementBase.renderLocString(element.locTitle, null, "q_title")
    );
    if (element.isRequireTextAfterTitle) {
      spans.push(getSpaceSpan("req-sp"));
      spans.push(this.renderRequireText(element, cssClasses));
    }
    return spans;
  }

  private renderRequireText(
    element: ITitleOwner,
    cssClasses: any
  ): JSX.Element {
    return (
      <span
        data-key={"req-text"}
        key={"req-text"}
        className={cssClasses.requiredText || cssClasses.panel.requiredText}
        aria-hidden={true}
      >
        {element.requiredText}
      </span>
    );
  }
}
