// packages/survey-angular-ui/example/src/app/app.component.ts
import { Component } from "@angular/core";
const json = require("../assets/survey.json");

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html"
})
export class AppComponent {
  public isTest = !!(<any>window)["%hammerhead%"];
}

<test *ngIf="isTest"></test>
<example *ngIf="!isTest"></example>

// packages/survey-vue-ui/example/src/App.vue
<script setup lang="ts">
import Example from './components/example/Example.vue';
import Test from "./components/test/Test.vue"

// const isTest = !!(window as any)["%hammerhead%"];
const isTest = true;

</script>

<template>
  <Example v-if="!isTest"></Example>
  <Test v-if="isTest"></Test>
</template>

<style scoped>
</style>
