// src/vue/checkboxitem.vue
<template>
  <div>
    <label :class="question.getLabelClass(item)">
      <input
        v-if="item == question.selectAllItem"
        type="checkbox"
        :name="question.name"
        :value="isAllSelected"
        v-model="isAllSelected"
        :id="question.getItemId(item)"
        :disabled="!question.getItemEnabled(item)"
        :aria-required="question.ariaRequired"
        :aria-label="question.ariaLabel"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
        :class="question.cssClasses.itemControl"
      /><input
        v-if="item != question.selectAllItem"
        type="checkbox"
        :name="question.name"
        :value="item.value"
        v-model="question.renderedValue"
        :id="question.getItemId(item)"
        :disabled="!question.getItemEnabled(item)"
        v-bind:aria-required="question.ariaRequired"
        :aria-label="question.ariaLabel"
        :aria-invalid="question.ariaInvalid"
        :aria-describedby="question.ariaDescribedBy"
        :class="question.cssClasses.itemControl"
      /><span v-if="question.cssClasses.materialDecorator" :class="question.cssClasses.materialDecorator">
        <svg v-if="question.itemSvgIcon" :class="question.cssClasses.itemDecorator">
          <use
            :xlink:href="question.itemSvgIcon"
          ></use>
        </svg>
      </span><span
        v-if="!hideLabel"
        :class="question.cssClasses.controlLabel"
        :title="item.locText.renderedHtml"
      >
        <survey-string :locString="item.locText" />
      </span>
    </label><survey-other-choice
      v-show="
        question.renderedValue && question.isOtherSelected
      "
      v-if="question.isOtherItem(item)"
      :question="question"
    />
  </div>
</template>

<script lang="ts">
import { ItemValue, Base } from "survey-core";
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { BaseVue } from "./base";

@Component
export class CheckboxItem extends BaseVue {
  @Prop() question: any;
  @Prop() item: ItemValue;
  @Prop() index: any;
  @Prop() hideLabel: boolean;
  protected getModel(): Base {
    return this.item;
  }
  get isAllSelected() {
    return this.question.isAllSelected;
  }
  set isAllSelected(val: boolean) {
    this.question.isAllSelected = val;
  }
}
Vue.component("survey-checkbox-item", CheckboxItem);
export default CheckboxItem;
</script>

// packages/survey-angular-ui/src/questions/checkbox-item.component.ts
import { Component, Input } from "@angular/core";
import { ItemValue, QuestionCheckboxModel } from "survey-core";

@Component({
  selector: "sv-ng-checkbox-item, '[sv-ng-checkbox-item]'",
  templateUrl: "./checkbox-item.component.html",
  styleUrls: ["./checkbox-item.component.scss"]
})
export class CheckboxItemComponent {
  @Input() question!: QuestionCheckboxModel;
  @Input() model!: ItemValue;
  @Input() ariaLabel?: string;
  constructor() {
  }
  onChange(event: any) {
    this.question["clickItemHandler"](this.model, event.target.checked);
  }
  onSelectAllChange(event: any) {
    this.question.toggleSelectAll();
  }
}

<input *ngIf="model == question.selectAllItem" role="option" type="checkbox" [name]="question.name" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
  [disabled]="!question.getItemEnabled(model)" [checked]="question.isAllSelected" [value]="''" (change)="onSelectAllChange($event)"/>
<input *ngIf="model != question.selectAllItem" role="option" type="checkbox" [name]="question.name" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
  [disabled]="!question.getItemEnabled(model)" [checked]="question.isItemSelected(model)" [value]="model.value" (change)="onChange($event)"/>
<ng-content></ng-content>
