// packages/survey-vue3-ui/src/CheckboxItem.vue
<template>
  <div role="presentation" :class="question.getItemClass(item)">
    <label :class="question.getLabelClass(item)">
      <input
        type="checkbox"
        role="option"
        :name="question.name + item.id"
        :checked="question.isItemSelected(item)"
        @input="
          (e) => {
            change(e);
          }
        "
        :value="item.value"
        :id="question.getItemId(item)"
        :disabled="!question.getItemEnabled(item)"
        :readonly="question.isReadOnlyAttr"
        :class="question.cssClasses.itemControl"
      /><span
        v-if="question.cssClasses.materialDecorator"
        :class="question.cssClasses.materialDecorator"
      >
        <svg
          v-if="question.itemSvgIcon"
          :class="question.cssClasses.itemDecorator"
        >
          <use :xlink:href="question.itemSvgIcon"></use>
        </svg> </span
      ><span v-if="!hideLabel" :class="question.cssClasses.controlLabel">
        <survey-string :locString="item.locText" />
      </span>
    </label>
  </div>
</template>

<script lang="ts" setup>
import type { ItemValue, QuestionCheckboxModel } from "survey-core";
import { useBase } from "./base";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  question: QuestionCheckboxModel;
  item: ItemValue;
  hideLabel?: boolean;
}>();

useBase(() => props.item);

const change = (event: any) => {
  props.question.clickItemHandler(props.item, event.target.checked);
};
</script>

// packages/survey-angular-ui/src/questions/checkbox-item.component.ts
import { Component, Input } from "@angular/core";
import { ItemValue, QuestionCheckboxModel } from "survey-core";

@Component({
  selector: "sv-ng-checkbox-item, '[sv-ng-checkbox-item]'",
  templateUrl: "./checkbox-item.component.html",
  styleUrls: ["./checkbox-item.component.scss"]
})
export class CheckboxItemComponent {
  @Input() question!: QuestionCheckboxModel;
  @Input() model!: ItemValue;
  constructor() {
  }
  onChange(event: any) {
    this.question.clickItemHandler(this.model, event.target.checked);
  }
  onSelectAllChange(event: any) {
    this.question.toggleSelectAll();
  }
}

<input *ngIf="model == question.selectAllItem" role="option" type="checkbox" [name]="question.name" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
  [disabled]="!question.getItemEnabled(model)" [checked]="question.isAllSelected" [value]="''" (change)="onSelectAllChange($event)"/>
<input *ngIf="model != question.selectAllItem" role="option" type="checkbox" [name]="question.name" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
  [disabled]="!question.getItemEnabled(model)" [checked]="question.isItemSelected(model)" [value]="model.value" (change)="onChange($event)"/>
<ng-content></ng-content>
