// packages/survey-vue3-ui/src/Composite.vue
<template>
  <survey-panel ref="root" :question="contentPanel" :css="css" />
</template>

<script lang="ts" setup>
import { computed, ref } from "vue";
import type { QuestionCompositeModel } from "survey-core";
import { useQuestion } from "./base";
const props = defineProps<{ question: QuestionCompositeModel; css?: object }>();
const root = ref(null);
useQuestion(props, root);
const contentPanel = computed(() => {
  return props.question.contentPanel;
});
</script>

// packages/survey-angular-ui/src/questions/composite.component.ts

import { Component } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { QuestionAngular } from "../question";
import { PanelModel, QuestionCompositeModel } from "survey-core";

@Component({
  selector: "sv-ng-composite-question",
  template: "<sv-ng-panel [model]='contentPanel'></sv-ng-panel>"
})
export class CompositeQuestionComponent extends QuestionAngular<QuestionCompositeModel> {
  get contentPanel(): PanelModel {
    return this.model.contentPanel;
  }
}
AngularComponentFactory.Instance.registerComponent("composite-question", CompositeQuestionComponent);
