// packages/survey-vue3-ui/src/CustomWidget.vue
<template>
  <div ref="root">
    <div v-if="hasHtml" v-html="customHtml"></div>
    <SurveyVueComponent
      v-if="hasDefaultRender"
      :name="componentName"
      :question="question"
      :css="css"
    />
  </div>
</template>
<script lang="ts" setup>
import SurveyVueComponent from "@/SurveyVueComponent.vue";
import type { Question } from "survey-core";
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
const props = defineProps<{
  question: Question;
  css?: any;
}>();
const root = ref<HTMLElement>();
const hasDefaultRender = computed(
  () => props.question.customWidget.isDefaultRender
);
const hasHtml = computed(() =>
  props.question.customWidget.htmlTemplate ? true : false
);
const customHtml = computed(() => props.question.customWidget.htmlTemplate);
const componentName = computed(() => "survey-" + props.question.getTemplate());

onMounted(() => {
  props.question.customWidget.afterRender(props.question, root.value);
});
onBeforeUnmount(() => {
  props.question.customWidget.willUnmount(props.question, root.value);
});
</script>

// packages/survey-angular-ui/src/questions/customwidget.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnChanges, OnDestroy, SimpleChanges, ViewChild } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { Question } from "survey-core";

@Component(
  {
    templateUrl: "./customwidget.component.html",
    selector: "sv-ng-custom-widget"
  }
)
export class CustomWidgetComponent implements AfterViewInit, OnDestroy, OnChanges {
  @Input() css: any;
  @Input() model!: Question;

  @ViewChild("content") container!: ElementRef<HTMLDivElement>;

  get hasDefaultRender(): boolean {
    return this.model.customWidget.isDefaultRender || this.hasAngularComponent;
  }
  get hasHtml(): boolean {
    return this.model.customWidget.htmlTemplate ? true : false;
  }
  get customHtml(): string {
    return this.model.customWidget.htmlTemplate;
  }
  get hasAngularComponent(): boolean {
    return AngularComponentFactory.Instance.isComponentRegistered(this.model.customWidget.name);
  }
  get componentName(): string {
    if (this.hasAngularComponent) return this.model.customWidget.name;
    return this.model.getTemplate() + "-question";
  }
  ngAfterViewInit(): void {
    this.model.customWidget.afterRender(this.model, this.container.nativeElement);
  }
  ngOnChanges(simpleChanges: SimpleChanges) {
    if(simpleChanges["model"].previousValue !== undefined && simpleChanges["model"].currentValue !== undefined) {
      this.model.customWidget.afterRender(this.model, this.container.nativeElement);
    }
  }
  ngOnDestroy(): void {
    this.model.customWidget.willUnmount(this.model, this.container.nativeElement);
  }

}

AngularComponentFactory.Instance.registerComponent("survey-customwidget", CustomWidgetComponent);

<div #content>
  <div *ngIf="hasHtml" [innerHTML]="customHtml | safeHtml"></div>
  <ng-container *ngIf="hasDefaultRender">
    <ng-template [component]="{ name: componentName, data: { model: model, css: css } }"></ng-template>  
  </ng-container>
</div>
