// packages/survey-vue3-ui/src/Custom.vue
<template>
  <SurveyVueComponent
    :ref="root"
    :name="getComponentName(contentQuestion)"
    :question="contentQuestion"
    :css="css"
  />
</template>

<script lang="ts" setup>
import SurveyVueComponent from "@/SurveyVueComponent.vue";
import { computed, ref } from "vue";
import type { QuestionCustomModel, Question } from "survey-core";
import { getComponentName as getComponent, useQuestion } from "./base";
defineOptions({ inheritAttrs: false });
const props = defineProps<{ question: QuestionCustomModel; css?: any }>();

const root = ref(null);

useQuestion(props, root);

const contentQuestion = computed((): Question => {
  return props.question.contentQuestion;
});
const getComponentName = (element: Question): string => {
  return getComponent(element);
};
</script>

// packages/survey-angular-ui/src/questions/custom.component.ts
import { Question } from "survey-core";
import { QuestionCustomModel } from "survey-core";
import { Component } from "@angular/core";
import { QuestionAngular, getComponentName } from "../question";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-custom-question",
  template: "<ng-template [component]='{ name: getComponentName(contentQuestion), data: { model: contentQuestion } }'></ng-template>"
})
export class CustomQuestionComponent extends QuestionAngular<QuestionCustomModel> {
  get contentQuestion(): Question {
    return this.model.contentQuestion;
  }
  getComponentName(element: Question): string { return getComponentName(this.model); }
}

AngularComponentFactory.Instance.registerComponent("custom-question", CustomQuestionComponent);
