// packages/survey-vue3-ui/src/Expression.vue
<template>
  <div :class="question.cssClasses.root" ref="root" aria-live="polite" :aria-label="question.formatedValue">
    {{ question.formatedValue }}
  </div>
</template>

<script lang="ts" setup>
import type { QuestionExpressionModel } from "survey-core";
import { useQuestion } from "./base";
import { ref } from "vue";
defineOptions({ inheritAttrs: false });
const props = defineProps<{ question: QuestionExpressionModel }>();
const root = ref(null);
useQuestion(props, root);
</script>

// packages/survey-angular-ui/src/questions/expression.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { QuestionAngular } from "../question";
import { QuestionExpressionModel } from "survey-core";

@Component({
  selector: "sv-ng-expression",
  template: "<div [class]='model.cssClasses.root' #contentElement [attr.aria-label]='model.formatedValue' aria-live='polite' >{{ model.formatedValue }}</div>"
})
export class ExpressionComponent extends QuestionAngular<QuestionExpressionModel> {
}

AngularComponentFactory.Instance.registerComponent("expression-question", ExpressionComponent);
