// src/vue/image.vue
<template>
  <div :class="question.cssClasses.root">
    <img
      v-if="question.renderedMode === 'image'"
      v-show="question.imageLink && !question.contentNotLoaded"
      :class="question.getImageCss()"
      :src="question.locImageLink.renderedHtml"
      :alt="question.altText || question.title"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      v-bind:style="{ objectFit: question.imageFit }"
      @load="(event) => { question.onLoadHandler() }"
      @error="(event) => { question.onErrorHandler() }"
    /><video
      controls
      v-if="question.renderedMode === 'video'"
      v-show="question.imageLink && !question.contentNotLoaded"
      :class="question.getImageCss()"
      :src="question.locImageLink.renderedHtml"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      v-bind:style="{ objectFit: question.imageFit }"
      @loadedmetadata="(event) => { question.onLoadHandler() }"
      @error="(event) => { question.onErrorHandler() }"
    ></video>
    <iframe
      v-if="question.renderedMode === 'youtube'"
      :class="question.getImageCss()"
      :src="question.locImageLink.renderedHtml"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      v-bind:style="{ objectFit: question.imageFit }"
    ></iframe>
    <div v-if="!question.imageLink || question.contentNotLoaded"
      :class="question.cssClasses.noImage">
      <sv-svg-icon :iconName="question.cssClasses.noImageSvgIconId" :size="48"></sv-svg-icon>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { QuestionImageModel } from "survey-core";

@Component
export class QuestionImage extends Vue {
  @Prop() question: QuestionImageModel;
  @Prop() css: any;
}
Vue.component("survey-image", QuestionImage);
export default QuestionImage;
</script>

// packages/survey-angular-ui/src/questions/image.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionImageModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-image-question",
  templateUrl: "./image.component.html"
})
export class ImageQuestionComponent extends QuestionAngular<QuestionImageModel> {}

AngularComponentFactory.Instance.registerComponent("image-question", ImageQuestionComponent);
<div [class]="model.cssClasses.root" #contentElement>
  <img
    *ngIf="model.renderedMode === 'image'"
    [visible]="!!model.locImageLink.renderedHtml && !model.contentNotLoaded"
    [class]="model.getImageCss()"
    [attr.src]="model.locImageLink.renderedHtml"
    [attr.alt]="model.altText || model.title"
    [attr.width]="model.renderedWidth"
    [attr.height]="model.renderedHeight"
    [style]="{ objectFit: model.imageFit,  width: model.renderedStyleWidth, height: model.renderedStyleHeight }"
    (load)="model.onLoadHandler()"
    (error)="model.onErrorHandler()"
  /><video
    controls
    *ngIf="model.renderedMode === 'video'"
    [visible]="!!model.locImageLink.renderedHtml && !model.contentNotLoaded"
    [class]="model.getImageCss()"
    [attr.src]="model.locImageLink.renderedHtml"
    [attr.width]="model.renderedWidth"
    [attr.height]="model.renderedHeight"
    [style]="{ objectFit: model.imageFit,  width: model.renderedStyleWidth, height: model.renderedStyleHeight }"
    (loadedmetadata)="model.onLoadHandler()"
    (error)="model.onErrorHandler()"
  ></video>
  <iframe
    *ngIf="model.renderedMode === 'youtube'"
    [class]="model.getImageCss()"
    [attr.src]="model.locImageLink.renderedHtml | safeResourceUrl"
    [attr.width]="model.renderedWidth"
    [attr.height]="model.renderedHeight"
    [attr.title]="model.renderedAltText"
    [style]="{ objectFit: model.imageFit,  width: model.renderedStyleWidth, height: model.renderedStyleHeight }"
    ></iframe>
    <div *ngIf="!model.locImageLink.renderedHtml || model.contentNotLoaded" [class]="model.cssClasses.noImage">
      <svg [iconName]="model.cssClasses.noImageSvgIconId" [size]="48" sv-ng-svg-icon></svg>
    </div>
</div>
