// src/vue/imagepicker-item.vue
<template>
  <div :class="getItemClass(item)">
      <label :class="question.cssClasses.label">
        <input
          v-if="question.multiSelect"
          type="checkbox"
          :name="question.questionName"
          :value="item.value"
          :id="question.getItemId(item)"
          v-model="question.value"
          :disabled="!question.getItemEnabled(item)"
          v-bind:aria-required="question.ariaRequired"
          :aria-label="question.ariaLabel"
          :aria-invalid="question.ariaInvalid"
          :aria-describedby="question.ariaDescribedBy"
          :class="question.cssClasses.itemControl"
        />
        <input
          v-else
          type="radio"
          :name="question.questionName"
          :value="item.value"
          :id="question.getItemId(item)"
          v-model="question.value"
          :disabled="!question.getItemEnabled(item)"
          v-bind:aria-required="question.ariaRequired"
          :aria-label="question.ariaLabel"
          :aria-invalid="question.ariaInvalid"
          :aria-describedby="question.ariaDescribedBy"
          :class="question.cssClasses.itemControl"
        /><div :class="question.cssClasses.itemDecorator">
          <div :class="question.cssClasses.imageContainer">
            <img
              v-if="item.imageLink && question.contentMode === 'image'"
              :class="question.cssClasses.image"
              :src="item.imageLink"
              :width="question.renderedImageWidth"
              :height="question.renderedImageHeight"
              v-bind:style="{ objectFit: question.imageFit }"
              :alt="item.locText.renderedHtml"
              @load="(event) => { question.onContentLoaded(item, event) }"

            /><video controls
              v-if="item.imageLink && question.contentMode === 'video'"
              :class="question.cssClasses.image"
              :src="item.imageLink"
              :width="question.renderedImageWidth"
              :height="question.renderedImageHeight"
              v-bind:style="{ objectFit: question.imageFit }"
              @loadedmetadata="(event) => { question.onContentLoaded(item, event) }"
            ></video>
            <div
              v-if="!item.imageLink"
              :class="question.cssClasses.itemNoImage"
              v-bind:style="{ width: question.renderedImageWidth, height: question.renderedImageHeight, objectFit: question.imageFit }"
            >
              <svg v-if="question.cssClasses.itemNoImageSvgIconId"
                :class="question.cssClasses.itemNoImageSvgIcon"
              >
                <use :xlink:href="question.cssClasses.itemNoImageSvgIconId"></use>
              </svg>
            </div>
          </div><span
            v-if="question.showLabel"
            :class="question.cssClasses.itemText"
            >
              <survey-string :locString="item.locText" />
            </span
          ></div>
      </label>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionImagePickerModel, ImageItemValue } from "survey-core";

@Component
export class ImagePickerItem extends QuestionVue<QuestionImagePickerModel> {
  @Prop() question: QuestionImagePickerModel;
  @Prop() item: ImageItemValue;
  getItemClass(item: any) {
    return this.question.getItemClass(item);
  }
}
Vue.component("survey-imagepicker-item", ImagePickerItem);
export default ImagePickerItem;
</script>

// packages/survey-angular-ui/src/questions/imagepicker-item.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../base-angular";
import { ImageItemValue, QuestionImagePickerModel } from "survey-core";
@Component({
  selector: "sv-ng-imagepicker-item",
  templateUrl: "./imagepicker-item.component.html",
})
export class ImagePickerItemComponent extends BaseAngular<ImageItemValue> {
  @Input() question!: QuestionImagePickerModel;
  @Input() model!: ImageItemValue;
  protected getModel(): ImageItemValue {
    return this.model;
  }
  onChange(event: any) {
    if (this.question.multiSelect) {
      if (event.target.checked) {
        this.question.value = this.question.value.concat(event.target.value);
      } else {
        var currValue = this.question.value;
        currValue.splice(this.question.value.indexOf(event.target.value), 1);
        this.question.value = currValue;
      }
    } else {
      this.question.value = event.target.value;
    }
  }
}

<div [class]="question.getItemClass(model)">
  <label [class]="question.cssClasses.label">
      <input [type]="question.inputType" [attr.name]="question.questionName" [attr.value]="model.value" [id]="question.getItemId(model)" [attr.aria-required]="question.ariaRequired" [attr.aria-label]="question.ariaLabel" [attr.aria-invalid]="question.ariaInvalid" [attr.aria-describedby]="question.ariaDescribedBy"
       (change)="onChange($event)" [checked]="question.isItemSelected(model)" [disabled]="!question.getItemEnabled(model)" [class]="question.cssClasses.itemControl"
      />
      <div [class]="question.cssClasses.itemDecorator">
          <div [class]="question.cssClasses.imageContainer">
            <img *ngIf="model.locImageLink.renderedHtml && question.contentMode === 'image'" [class]="question.cssClasses.image" [attr.src]="model.locImageLink.renderedHtml" [attr.width]="question.renderedImageWidth" [attr.height]="question.renderedImageHeight" [attr.alt]="model.locText.renderedHtml"  [style.objectFit]="question.imageFit" (load)="question.onContentLoaded(model, $event)"/>
            <video *ngIf="model.locImageLink.renderedHtml && question.contentMode === 'video'" controls [class]="question.cssClasses.image" [attr.src]="model.locImageLink.renderedHtml" [attr.width]="question.renderedImageWidth" [attr.height]="question.renderedImageHeight" [style.objectFit]="question.imageFit" (loadedmetadata)="question.onContentLoaded(model, $event)"></video>
            <div *ngIf="!model.locImageLink.renderedHtml" [class]="question.cssClasses.itemNoImage" [style.width]="question.renderedImageWidth" [style.height]="question.renderedImageHeight" [style.objectFit]="question.imageFit">
              <svg [class]="question.cssClasses.itemNoImageSvgIcon" *ngIf="question.cssClasses.itemNoImageSvgIcon">
                <use [attr.xlink:href]="question.cssClasses.itemNoImageSvgIconId"></use>
              </svg>
            </div>
          </div>
          <span *ngIf="question.showLabel" [class]="question.cssClasses.itemText" [model]="model.locText" sv-ng-string-viewer></span>
      </div>
  </label>
</div>
