// packages/survey-vue3-ui/src/MatrixCell.vue
<template>
  <td
    :class="cell.className"
    :data-responsive-title="getHeaders()"
    :title="cell.getTitle()"
    :style="(getCellStyle() as StyleValue)"
    :colspan="cell.colSpans"
    v-on:focusin="cell.focusIn()"
    ref="root"
  >
    <survey-errors v-if="cell.isErrorsCell" :element="cell.question" />
    <sv-matrix-drag-drop-icon
      v-if="cell.isDragHandlerCell"
      :item="{ data: { row: cell.row, question: question } }"
    ></sv-matrix-drag-drop-icon>
    <sv-action-bar
      v-if="cell.isActionsCell"
      :model="cell.item.getData()"
      :handleClick="false"
    ></sv-action-bar>
    <component
      v-if="cell.hasPanel"
      :is="panelComponentName"
      v-bind="panelComponentData"
    ></component>
    <div
      v-if="cell.hasQuestion"
      :class="question.cssClasses.cellQuestionWrapper"
      v-show="isVisible"
    >
      <component
        v-if="!cell.isChoice && cell.question.isDefaultRendering()"
        :is="question.getCellWrapperComponentName(cell.cell)"
        :componentData="question.getCellWrapperComponentData(cell.cell)"
      >
        <component
          :is="getComponentName(cell.question)"
          :question="cell.question"
        />
      </component>
      <component
        v-if="!cell.isChoice && !cell.question.isDefaultRendering()"
        :is="cell.question.getComponentName()"
        :question="cell.question"
      />
      <component
        v-if="cell.isItemChoice"
        :is="question.getCellWrapperComponentName(cell.cell)"
        :componentData="question.getCellWrapperComponentData(cell.cell)"
      >
        <survey-radiogroup-item
          v-if="cell.isRadio"
          :key="cell.item.value"
          :class="cell.question.getItemClass(cell.item)"
          :question="cell.question"
          :item="cell.item"
          :index="getCellIndex()"
          :hideLabel="true"
        ></survey-radiogroup-item>
        <survey-checkbox-item
          v-if="cell.isCheckbox"
          :key="cell.item.value"
          :class="cell.question.getItemClass(cell.item)"
          :question="cell.question"
          :item="cell.item"
          :index="getCellIndex()"
          :hideLabel="true"
        ></survey-checkbox-item>
      </component>
      <survey-other-choice
        v-if="cell.isOtherChoice"
        :question="cell.question"
      />
    </div>
    <template v-if="cell.hasTitle">
      <component
        :is="question.getCellWrapperComponentName(cell)"
        :componentData="question.getCellWrapperComponentData(cell)"
      >
        <survey-string v-if="cell.hasTitle" :locString="cell.locTitle" />
        <span
          v-if="!!cell.requiredText"
          :class="question.cssClasses.cellRequiredText"
          >{{ cell.requiredText }}</span
        >
      </component>
    </template>
  </td>
</template>

<script lang="ts" setup>
import type {
  Question,
  QuestionMatrixDropdownRenderedCell,
  SurveyModel,
} from "survey-core";
import { getComponentName as getComponent } from "./base";
import { ref, onMounted, type StyleValue, computed } from "vue";

const props = defineProps<{
  question: Question;
  cell: QuestionMatrixDropdownRenderedCell;
}>();
const isVisible = ref(false);
const root = ref<HTMLElement>();

const getHeaders = () => props.cell.headers;
const getCellStyle = () => {
  if (!!props.cell.width || !!props.cell.minWidth)
    return { width: props.cell.width, minWidth: props.cell.minWidth };
  return null;
};
const getCellIndex = () => (props.cell as any).index || "";
const onVisibilityChanged = () =>
  (isVisible.value = props.cell.question.isVisible);
const getComponentName = (element: Question | any) => {
  return getComponent(element);
};

onMounted(() => {
  if (!props.cell.hasQuestion || !props.question || !props.question.survey)
    return;
  onVisibilityChanged();
  props.cell.question.registerPropertyChangedHandlers(["isVisible"], () => {
    onVisibilityChanged();
  });
  const el = root.value;
  const cQ = props.cell.question;
  const options = {
    cell: props.cell.cell,
    cellQuestion: cQ,
    htmlElement: el,
    row: props.cell.row,
    column: props.cell.cell.column,
  };
  props.question.survey.matrixAfterCellRender(props.question, options);
  if (cQ) {
    cQ.afterRenderCore(el);
  }
});
const panelComponentName = computed(() => {
  const cell = props.cell;
  if (cell.hasPanel) {
    const panel = cell.panel;
    const survey = panel.survey as SurveyModel;
    if (survey) {
      const name = survey.getElementWrapperComponentName(panel);
      if (name) {
        return name;
      }
    }
    return "survey-panel";
  }
  return undefined;
});
const panelComponentData = computed(() => {
  const cell = props.cell;
  if (cell.hasPanel) {
    const panel = props.cell.panel;
    const survey = panel.survey as SurveyModel;
    let data: any;
    if (survey) {
      data = survey.getElementWrapperComponentData(panel);
    }
    return {
      componentName: "survey-panel",
      componentData: {
        element: panel,
        data: data,
        css: props.question.cssClasses,
      },
    };
  }
  return undefined;
});
</script>

// packages/survey-angular-ui/src/questions/matrixcell.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { BaseAngular } from "../base-angular";
import {
  Question,
  QuestionMatrixDropdownModelBase,
  QuestionMatrixDropdownRenderedCell,
  MatrixDropdownRowModelBase,
  SurveyModel
} from "survey-core";

@Component({
  selector: "sv-ng-matrix-cell",
  templateUrl: "./matrixcell.component.html",
  styles: [":host { display: none; }"]
  })
export class MatrixCellComponent extends BaseAngular<Question> {
  @Input() question!: QuestionMatrixDropdownModelBase;
  @Input() cell!: QuestionMatrixDropdownRenderedCell;

  @ViewChild("cellContainer") cellContainer!: ElementRef<HTMLElement>;

  isVisible: boolean = false;

  getModel() {
    return this.cell.question;
  }
  public get row(): MatrixDropdownRowModelBase {
    return this.cell.row;
  }
  public get panelComponentName(): string {
    const panel = this.cell.panel;
    const survey = <SurveyModel>panel.survey;
    if(!!survey) {
      const name = survey.getElementWrapperComponentName(panel);
      if(!!name) {
        return name;
      }
    }
    return "panel";
  }
  public get panelComponentData(): any {
    const panel = this.cell.panel;
    const survey = <SurveyModel>panel.survey;
    let data: any;
    if(!!survey) {
      data = survey.getElementWrapperComponentData(panel);
    }
    return {
      componentName: "panel",
      componentData: {
        model: panel,
        data: data
      }
    };
  }

  getComponentName(element: Question) {
    if (element.customWidget) {
      return "survey-customwidget";
    }
    return element.getType()+"-question";
  }
  getHeaders(): string {
    return this.cell.headers;
  }
  getCellStyle() {
    if (!!this.cell.width || !!this.cell.minWidth)
      return { width: this.cell.width, minWidth: this.cell.minWidth };
    return null;
  }
  ngAfterViewInit() {
    if (!this.cell.hasQuestion || !this.question || !this.question.survey) return;
    var options = {
      cell: this.cell.cell,
      cellQuestion: this.cell.question,
      htmlElement: this.cellContainer.nativeElement,
      row: this.cell.row,
      column: this.cell.cell.column,
    };
    this.question.survey.matrixAfterCellRender(this.question, options);
  }
}
<ng-template #template>
  <td [class]="cell.className" [attr.data-responsive-title]="getHeaders()" [title]="cell.getTitle()" [style]="getCellStyle()" [attr.colspan]="cell.colSpans" #cellContainer>
    <sv-ng-matrix-drag-drop-icon *ngIf="cell.isDragHandlerCell" [model]="$any({ data: { row: row, question: question } })"></sv-ng-matrix-drag-drop-icon>
    <sv-action-bar *ngIf="cell.isActionsCell" [model]="cell.item.getData()" [handleClick]="false"></sv-action-bar>
    <ng-container *ngIf="cell.hasPanel">
      <ng-template [component]="{ name: panelComponentName, data: panelComponentData }"></ng-template>
    </ng-container>
    <div *ngIf="cell.hasQuestion" [class]="question.cssClasses.cellQuestionWrapper" [visible]="cell.question.isVisible">
      <div *ngIf="cell.showErrorOnTop && cell.question.hasVisibleErrors" [element]="cell.question" [location]="'top'" sv-ng-errors></div>
      <ng-container *ngIf="!cell.isChoice && cell.question.isDefaultRendering()">
          <ng-template [component]="{ name: question.getCellWrapperComponentName(cell.cell), data: { componentData: question.getCellWrapperComponentData(cell.cell)} }">
            <ng-template  [component]="{ name: getComponentName(cell.question), data: { model: cell.question } }"></ng-template>
          </ng-template>
      </ng-container>
      <ng-template *ngIf="!cell.isChoice && !cell.question.isDefaultRendering()" [component]="{ name: cell.question.getComponentName(), data: { model: cell.question } }">
      </ng-template>
      <sv-ng-selebase-item
        *ngIf="cell.isItemChoice"
        [showLabel]="false"
        [inputType]="cell.isCheckbox ? 'checkbox': 'radio'"
        [question]="cell.question"
        [model]="cell.item"
      ></sv-ng-selebase-item>
      <div *ngIf="cell.isOtherChoice" [class]="cell.question.getCommentAreaCss(true)" [question]="cell.question" sv-ng-comment-other></div>
      <div *ngIf="cell.showErrorOnBottom && cell.question.hasVisibleErrors" [element]="cell.question" [location]="'top'" sv-ng-errors></div>
      <div *ngIf="cell.question.isErrorsModeTooltip && cell.question.hasVisibleErrors" [element]="cell.question" [location]="'tooltip'" sv-ng-errors></div>
    </div>
    <ng-container *ngIf="cell.hasTitle">
      <ng-template [component]="{ name: question.getCellWrapperComponentName($any(cell)), data: { componentData: question.getCellWrapperComponentData($any(cell))} }">
        <sv-ng-string [model]="cell.locTitle"></sv-ng-string>
        <span *ngIf="!!cell.requiredText" [class]="question.cssClasses.cellRequiredText">{{ cell.requiredText }}</span>  
      </ng-template>
    </ng-container>
</td>
</ng-template>
