// packages/survey-vue3-ui/src/Matrix.vue
<template>
  <div :class="question.cssClasses.tableWrapper" ref="root">
    <fieldset>
      <legend class="sv-hidden">{{question.locTitle.renderedHtml}}</legend>
      <table :class="question.getTableCss()">
        <thead v-if="question.showHeader">
          <tr>
            <td v-if="question.hasRows"></td>
            <th
              v-for="(column, columnIndex) in question.visibleColumns"
              :key="columnIndex"
              :class="question.cssClasses.headerCell"
              :style="{
                minWidth: question.columnMinWidth,
                width: question.columnMinWidth,
              }"
            >
              <survey-string :locString="column.locText" />
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="(row, rowIndex) in visibleRows"
            :key="'row_' + row.name + '_' + rowIndex"
            :class="row.rowClasses || undefined"
          >
            <td
              :class="question.cssClasses.rowTextCell"
              v-show="question.hasRows"
              :style="{
                minWidth: question.rowTitleWidth,
                width: question.rowTitleWidth,
              }"
            >
              <survey-string :locString="row.locText" />
            </td>
            <template v-if="question.hasCellText">
              <td
                v-for="(column, columnIndex) in question.visibleColumns"
                :key="columnIndex"
                :class="question.getItemClass(row, column)"
                v-on:click="cellClick(row, column)"
              >
                <survey-string
                  :locString="question.getCellDisplayLocText(row.name, column)"
                ></survey-string>
              </td>
            </template>
            <template v-if="!question.hasCellText">
              <td
                v-for="(column, columnIndex) in question.visibleColumns"
                :key="columnIndex"
                :data-responsive-title="column.locText.renderedHtml"
                :class="question.cssClasses.cell"
                v-on:click="cellClick(row, column)"
              >
                <label
                  @mousedown="question.onMouseDown()"
                  :class="question.getItemClass(row, column)"
                >
                  <input
                    type="radio"
                    :class="question.cssClasses.itemValue"
                    :name="row.fullName"
                    v-model="row.value"
                    :value="column.value"
                    :disabled="question.isInputReadOnly"
                    :id="question.inputId + '_' + row.name + '_' + columnIndex"
                    :aria-required="question.ariaRequired"
                    :aria-label="column.locText.renderedHtml"
                    :aria-label="question.getCellAriaLabel(row.locText.renderedHtml, column.locText.renderedHtml)"
                    :aria-invalid="question.ariaInvalid"
                    :aria-describedby="question.ariaDescribedBy"
                  />
                  <span :class="question.cssClasses.materialDecorator">
                    <svg
                      v-if="question.itemSvgIcon"
                      :class="question.cssClasses.itemDecorator"
                    >
                      <use :xlink:href="question.itemSvgIcon"></use>
                    </svg>
                  </span>
                  <span
                    v-show="question.isMobile"
                    :class="question.cssClasses.cellResponsiveTitle"
                  >
                    <survey-string :locString="column.locText"></survey-string>
                  </span>
                </label>
              </td>
            </template>
          </tr>
        </tbody>
      </table>
    </fieldset>
  </div>
</template>

<script lang="ts" setup>
import type { QuestionMatrixModel } from "survey-core";
import { useQuestion } from "./base";
import { ref, shallowRef } from "vue";
const props = defineProps<{ question: QuestionMatrixModel }>();
const root = ref(null);
const visibleRows = shallowRef();
useQuestion<QuestionMatrixModel>(
  props,
  root,
  (value) => {
    visibleRows.value = value.visibleRows;
    value.visibleRowsChangedCallback = () => {
      visibleRows.value = value.visibleRows;
    };
  },
  (value) => {
    value.visibleRowsChangedCallback = () => {};
  }
);

const cellClick = (row: any, column: any) => {
  if (props.question.isInputReadOnly) return;
  row.value = column.value;
};
</script>

// packages/survey-angular-ui/src/questions/matrix.component.ts
import { ChangeDetectorRef, Component, Input } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionImagePickerModel, QuestionMatrixModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-matrix-question",
  templateUrl: "./matrix.component.html"
})
export class MatrixQuestionComponent extends QuestionAngular<QuestionMatrixModel> {
  constructor(private changeDetectorRef: ChangeDetectorRef) {
    super();
  }
  ngOnInit() {
    this.model.visibleRowsChangedCallback = () => {
      this.changeDetectorRef.detectChanges();
    };
  }
  public onChange(row: any, column: any): void {
    if (this.model.isInputReadOnly) return;
    row.value = column.value;
    this.changeDetectorRef.detectChanges();
  }
  trackRowByFn(i: number, row: any): string {
    return "column-" + row.name + "-" + i;
  }
  trackColumnByFn(i: number, column: any): string {
    return "column-" + column.value + "-" + i;
  }
}

AngularComponentFactory.Instance.registerComponent("matrix-question", MatrixQuestionComponent);
<ng-template #template>
  <div [class]="model.cssClasses.tableWrapper" #contentElement>
    <fieldset>
      <legend class="sv-hidden">{{model.locTitle.renderedHtml}}</legend>
      <table [class]="model.getTableCss()">
        <thead *ngIf="model.showHeader">
          <tr>
            <td *ngIf="model.hasRows"></td>
            <th
              *ngFor="let column of model.visibleColumns" [style]="{ minWidth: model.columnMinWidth, width: model.columnMinWidth }" [class]="model.cssClasses.headerCell">
              <ng-template [component]="{ name: model.getColumnHeaderWrapperComponentName(column), data: { componentData: model.getColumnHeaderWrapperComponentData(column) } }">
                <sv-ng-string [model]="column.locText"></sv-ng-string>
              </ng-template>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let row of model.visibleRows; trackBy: trackRowByFn " [class]="row.rowClasses || undefined">
           <td [class]="model.cssClasses.rowTextCell" [style]="{ minWidth: model.rowTitleWidth, width: model.rowTitleWidth }" *ngIf="model.hasRows">
              <ng-template [component]="{ name: model.getRowHeaderWrapperComponentName($any(row)), data: { componentData: model.getRowHeaderWrapperComponentData($any(row)) } }">
                <sv-ng-string [model]="row.locText"></sv-ng-string>
              </ng-template>
            </td>
            <ng-container *ngIf="model.hasCellText">
              <td *ngFor="let column of model.visibleColumns"
                [class]="model.getItemClass(row, column)"
                (click)="onChange(row, column)" [model]="model.getCellDisplayLocText(row.name, column)" sv-ng-string>
              </td>
            </ng-container>
            <ng-container *ngIf="!model.hasCellText">
              <td
              *ngFor="let column of model.visibleColumns; index as columnIndex; trackBy: trackColumnByFn"
              [attr.data-responsive-title]="column.locText.renderedHtml"
              [class]="model.cssClasses.cell">
                <label (mousedown)="model.onMouseDown()" [class]="model.getItemClass(row, column)">
                  <input
                    type="radio"
                    [class]="model.cssClasses.itemValue"
                    [name]="row.fullName"
                    [value]="column.value"
                    [checked]="row.value === column.value"
                    [disabled]="model.isInputReadOnly"
                    [attr.id]="model.inputId + '_' + row.name + '_' + columnIndex"
                    (change)="onChange(row, column)"
                    [attr.aria-required]="model.ariaRequired"
                    [attr.aria-label]="model.getCellAriaLabel(row.locText.renderedHtml, column.locText.renderedHtml)"
                    [attr.aria-invalid]="model.ariaInvalid"
                    [attr.aria-describedby]="model.ariaDescribedBy"
                  />
                  <span [class]="model.cssClasses.materialDecorator">
                    <svg *ngIf="model.itemSvgIcon" [class]="model.cssClasses.itemDecorator">
                      <use [attr.xlink:href]="model.itemSvgIcon"></use>
                    </svg> 
                  </span>
                  <span [visible]="model.isMobile" [class]="model.cssClasses.cellResponsiveTitle" [model]="column.locText" sv-ng-string></span>
                </label>
              </td>
            </ng-container>
          </tr>
        </tbody>
      </table>
    </fieldset>
  </div>
</ng-template>
