// src/vue/matrix.vue
<template>
  <div :class="question.cssClasses.tableWrapper">
    <fieldset>
      <legend v-bind:aria-label="question.locTitle.renderedHtml"></legend>
      <table :class="question.cssClasses.root">
        <thead v-if="question.showHeader">
          <tr>
            <td v-show="question.hasRows"></td>
            <th
              v-for="(column, columnIndex) in question.visibleColumns"
              :key="columnIndex"
              :class="question.cssClasses.headerCell"
            >
              <survey-string :locString="column.locText" />
            </th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="(row, rowIndex) in question.visibleRows"
            :key="rowIndex"
            :class="row.rowClasses"
          >
            <td :class="question.cssClasses.cell" v-show="question.hasRows">
              <survey-string :locString="row.locText" />
            </td>
            <td
              v-if="question.hasCellText"
              v-for="(column, columnIndex) in question.visibleColumns"
              :key="columnIndex"
              :class="question.getItemClass(row, column)"
              v-on:click="cellClick(row, column)"
            >
              <survey-string
                :locString="question.getCellDisplayLocText(row.name, column)"
              ></survey-string>
            </td>
            <td
              v-if="!question.hasCellText"
              v-for="(column, columnIndex) in question.visibleColumns"
              :key="columnIndex"
              :headers="column.locText.renderedHtml"
              :class="question.cssClasses.cell"
              v-on:click="cellClick(row, column)"
            >
              <label :class="question.getItemClass(row, column)">
                <input
                  type="radio"
                  :class="question.cssClasses.itemValue"
                  :name="row.fullName"
                  v-model="row.value"
                  :value="column.value"
                  :disabled="question.isReadOnly"
                  :id="question.inputId + '_' + row.name + '_' + columnIndex"
                  v-bind:aria-required="question.isRequired"
                  :aria-label="question.locTitle.renderedHtml"
                />
                <span :class="question.cssClasses.materialDecorator">
                  <svg
                    :class="question.cssClasses.itemDecorator"
                    viewBox="-12 -12 24 24"
                  >
                    <circle r="6" cx="0" cy="0" />
                  </svg>
                </span>
                <span class="circle"></span>
                <span class="check"></span>
                <span :style="{ display: 'none' }">{{
                  question.locTitle.renderedHtml
                }}</span>
              </label>
            </td>
          </tr>
        </tbody>
      </table>
    </fieldset>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionMatrixModel } from "survey-core";

@Component
export class Matrix extends QuestionVue<QuestionMatrixModel> {
  cellClick(row: any, column: any) {
    if (this.question.isReadOnly) return;
    row.value = column.value;
  }
}
Vue.component("survey-matrix", Matrix);
export default Matrix;
</script>

// packages/survey-angular-ui/src/questions/matrix.component.ts
import { ChangeDetectorRef, Component, Input } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionImagePickerModel, QuestionMatrixModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-matrix-question",
  templateUrl: "./matrix.component.html"
})
export class MatrixQuestionComponent extends QuestionAngular<QuestionMatrixModel> {
  constructor(private changeDetectorRef: ChangeDetectorRef) {
    super();
  }
  ngOnInit() {
    this.model.visibleRowsChangedCallback = () => {
      this.changeDetectorRef.detectChanges();
    };
  }
  public onChange(row: any, column: any): void {
    if (this.model.isInputReadOnly) return;
    row.value = column.value;
    this.changeDetectorRef.detectChanges();
  }
  trackRowByFn(i: number, row: any): string {
    return "column-" + row.name + "-" + i;
  }
  trackColumnByFn(i: number, column: any): string {
    return "column-" + column.value + "-" + i;
  }
}

AngularComponentFactory.Instance.registerComponent("matrix-question", MatrixQuestionComponent);
<ng-template #template>
  <div [class]="model.cssClasses.tableWrapper" #contentElement>
    <fieldset>
      <legend class="sv-hidden">{{model.locTitle.renderedHtml}}</legend>
      <table [class]="model.getTableCss()">
        <thead *ngIf="model.showHeader">
          <tr>
            <td *ngIf="model.hasRows"></td>
            <th
              *ngFor="let column of model.visibleColumns" [style]="{ minWidth: model.columnMinWidth, width: model.columnMinWidth }" [class]="model.cssClasses.headerCell">
              <ng-template [component]="{ name: model.getColumnHeaderWrapperComponentName(column), data: { componentData: model.getColumnHeaderWrapperComponentData(column) } }">
                <sv-ng-string [model]="column.locText"></sv-ng-string>
              </ng-template>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let row of model.visibleRows; trackBy: trackRowByFn " [class]="row.rowClasses || undefined">
           <td [class]="model.cssClasses.rowTextCell" [style]="{ minWidth: model.rowTitleWidth, width: model.rowTitleWidth }" *ngIf="model.hasRows">
              <ng-template [component]="{ name: model.getRowHeaderWrapperComponentName($any(row)), data: { componentData: model.getRowHeaderWrapperComponentData($any(row)) } }">
                <sv-ng-string [model]="row.locText"></sv-ng-string>
              </ng-template>
            </td>
            <ng-container *ngIf="model.hasCellText">
              <td *ngFor="let column of model.visibleColumns"
                [class]="model.getItemClass(row, column)"
                (click)="onChange(row, column)" [model]="model.getCellDisplayLocText(row.name, column)" sv-ng-string>
              </td>
            </ng-container>
            <ng-container *ngIf="!model.hasCellText">
              <td
              *ngFor="let column of model.visibleColumns; index as columnIndex; trackBy: trackColumnByFn"
              [attr.data-responsive-title]="column.locText.renderedHtml"
              [class]="model.cssClasses.cell">
                <label (mousedown)="model.onMouseDown()" [class]="model.getItemClass(row, column)">
                  <input
                    type="radio"
                    [class]="model.cssClasses.itemValue"
                    [name]="row.fullName"
                    [value]="column.value"
                    [checked]="row.value === column.value"
                    [disabled]="model.isInputReadOnly"
                    [attr.id]="model.inputId + '_' + row.name + '_' + columnIndex"
                    (change)="onChange(row, column)"
                    [attr.aria-required]="model.ariaRequired"
                    [attr.aria-label]="model.getCellAriaLabel(row.locText.renderedHtml, column.locText.renderedHtml)"
                    [attr.aria-invalid]="model.ariaInvalid"
                    [attr.aria-describedby]="model.ariaDescribedBy"
                  />
                  <span [class]="model.cssClasses.materialDecorator">
                    <svg *ngIf="model.itemSvgIcon" [class]="model.cssClasses.itemDecorator">
                      <use [attr.xlink:href]="model.itemSvgIcon"></use>
                    </svg> 
                  </span>
                  <span [visible]="model.isMobile" [class]="model.cssClasses.cellResponsiveTitle" [model]="column.locText" sv-ng-string></span>
                </label>
              </td>
            </ng-container>
          </tr>
        </tbody>
      </table>
    </fieldset>
  </div>
</ng-template>
