// packages/survey-vue3-ui/src/MatrixTable.vue
<template>
  <div
    :style="{ overflowX: question.showHorizontalScroll ? 'scroll' : '' as any }"
    :class="question.cssClasses.tableWrapper"
    :data-sv-drop-target-matrix-row="question.renderedTable.lastRenderedRow.dropTargetId"
  >
    <table :class="question.getTableCss()">
      <thead v-if="table.showHeader">
        <tr>
          <template v-for="cell in table.headerRow.cells">
            <th
              v-if="cell.hasTitle"
              :key="'header_' + cell.id"
              :class="cell.className"
              :style="{ minWidth: cell.minWidth, width: cell.width }"
            >
              <SvComponent
                :is="question.getColumnHeaderWrapperComponentName(cell as any)"
                :componentData="question.getColumnHeaderWrapperComponentData(cell as any)"
              >
                <SvComponent :is="'survey-string'" :locString="cell.locTitle" />
                <SvComponent
                  :is="'survey-matrixheaderrequired'"
                  v-if="!!cell.column"
                  :column="cell.column"
                  :question="question"
                ></SvComponent>
              </SvComponent>
            </th>
            <td
              v-if="!cell.hasTitle"
              :class="cell.className"
              :key="'header_' + cell.id"
              :style="{ minWidth: cell.minWidth, width: cell.width }"
            ></td>
          </template>
        </tr>
      </thead>
      <tbody>
        <template
          v-for="row in table.renderedRows"
          :key="question.inputId + '_' + row.id"
        >
          <SvComponent
            :is="'survey-matrix-row'"
            :row="row"
            :question="question"
          ></SvComponent>
        </template>
      </tbody>
      <tfoot v-if="table.showFooter">
        <tr>
          <SvComponent
            :is="'survey-matrixdropdown-cell'"
            :cell="cell"
            :question="question"
            v-for="(cell, cellIndex) in table.footerRow.cells"
            :key="'footer_' + cellIndex"
          />
        </tr>
      </tfoot>
    </table>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { QuestionMatrixDropdownModelBase } from "survey-core";
import { computed } from "vue";
import { useBase } from "./base";

const props = defineProps<{ question: QuestionMatrixDropdownModelBase }>();
const table = computed(() => {
  return props.question.renderedTable;
});
useBase(() => table.value);
</script>

// packages/survey-angular-ui/src/questions/matrixtable.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../base-angular";
import { QuestionMatrixDropdownModelBase, QuestionMatrixDropdownRenderedTable } from "survey-core";

@Component({
  selector: "sv-ng-matrix-table",
  templateUrl: "./matrixtable.component.html"
})
export class MatrixTableComponent extends BaseAngular<QuestionMatrixDropdownRenderedTable> {
  @Input() question!: QuestionMatrixDropdownModelBase;
  @Input() table!: QuestionMatrixDropdownRenderedTable;
  protected getModel(): QuestionMatrixDropdownRenderedTable {
    return this.table;
  }
  public trackCellBy(_: number, cell: any): string {
    return cell.id;
  }
  public trackRowBy(index: number, row: any): string {
    return row.id;
  }
}

<div #contentElement [class]="question.cssClasses.tableWrapper" [attr.data-sv-drop-target-matrix-row]="question.renderedTable.lastRenderedRow.dropTargetId">
  <table [class]="question.getTableCss()">
    <thead *ngIf="table.showHeader">
      <tr>
        <ng-container *ngFor="let cell of table.headerRow.cells; trackBy: trackCellBy">
          <th *ngIf="cell.hasTitle" [class]="cell.className" [style]="{ minWidth: cell.minWidth, width: cell.width }">
            <ng-template
              [component]="{ name: question.getColumnHeaderWrapperComponentName($any(cell)), data: { componentData: question.getColumnHeaderWrapperComponentData($any(cell)) } }">
              <sv-ng-string [model]="cell.locTitle"></sv-ng-string>
              <sv-ng-matrixheaderrequired *ngIf="!!cell.column" [column]="cell.column" [question]="question">
              </sv-ng-matrixheaderrequired>
            </ng-template>
          </th>

          <td *ngIf="!cell.hasTitle" [class]="cell.className" [style]="{ minWidth: cell.minWidth, width: cell.width }">
          </td>
        </ng-container>
      </tr>
    </thead>
    <tbody>
      <ng-container *ngFor="let row of table.renderedRows; trackBy: trackRowBy">
        <sv-ng-matrix-row [model]="row" [question]="question"></sv-ng-matrix-row>
      </ng-container>
    </tbody>
    <tfoot *ngIf="table.showFooter">
      <tr>
        <sv-ng-matrixdropdown-cell [cell]="cell" [question]="question"
          *ngFor="let cell of table.footerRow.cells; trackBy: trackCellBy">
        </sv-ng-matrixdropdown-cell>
      </tr>
    </tfoot>
  </table>
</div>
