// src/vue/matrixtable.vue
<template>
  <table :class="question.getTableCss()">
    <thead v-if="table.showHeader">
      <tr>
        <template v-for="cell in table.headerRow.cells">
          <th
            v-if="cell.hasTitle"
            :class="cell.className"
            :key="'header_' + cell.id"
            :style="{ minWidth: cell.minWidth, width: cell.width }"
          >
            <survey-string :locString="cell.locTitle" />
            <survey-matrixheaderrequired v-if="!!cell.column" :column="cell.column" :question="question"></survey-matrixheaderrequired>
          </th>
          <td
            v-if="!cell.hasTitle"
            :class="cell.className"
            :key="'header_' + cell.id"
            :style="{ minWidth: cell.minWidth, width: cell.width }"
          ></td>
        </template>
      </tr>
    </thead>
    <tbody>
      <tr
        v-for="row in table.rows"
        :class="row.className"
        :key="question.inputId + '_' + row.id"
      >
        <survey-matrixcell
          :cell="cell"
          :question="question"
          v-for="(cell, cellIndex) in row.cells"
          :key="row.id + '_' + cellIndex"
        />
      </tr>
    </tbody>
    <tfoot v-if="table.showFooter">
      <tr>
        <survey-matrixcell
          :cell="cell"
          :question="question"
          v-for="(cell, cellIndex) in table.footerRow.cells"
          :key="'footer_' + cellIndex"
        />
      </tr>
    </tfoot>
  </table>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { Question } from "survey-core";
import {
  QuestionMatrixDropdownModelBase,
  QuestionMatrixDropdownRenderedTable,
} from "survey-core";
import { BaseVue } from "./base";
import { Base } from "survey-core";

@Component
export class MatrixTable extends BaseVue {
  @Prop() question: QuestionMatrixDropdownModelBase;
  get table(): QuestionMatrixDropdownRenderedTable {
    return this.question.renderedTable;
  }
  protected getModel(): Base {
    return this.question.renderedTable;
  }
}

Vue.component("survey-matrixtable", MatrixTable);
export default MatrixTable;
</script>

// packages/survey-angular-ui/src/questions/matrixtable.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../base-angular";
import { QuestionMatrixDropdownModelBase, QuestionMatrixDropdownRenderedTable } from "survey-core";

@Component({
  selector: "sv-ng-matrix-table",
  templateUrl: "./matrixtable.component.html"
})
export class MatrixTableComponent extends BaseAngular<QuestionMatrixDropdownRenderedTable> {
  @Input() question!: QuestionMatrixDropdownModelBase;
  @Input() table!: QuestionMatrixDropdownRenderedTable;
  protected getModel(): QuestionMatrixDropdownRenderedTable {
    return this.table;
  }
  public trackCellBy(_: number, cell: any): string {
    return cell.id;
  }
  public trackRowBy(index: number, row: any): string {
    return row.id;
  }
}

<div #contentElement [class]="question.cssClasses.tableWrapper" [attr.data-sv-drop-target-matrix-row]="question.renderedTable.lastRenderedRow.dropTargetId">
  <table [class]="question.getTableCss()">
    <thead *ngIf="table.showHeader">
      <tr>
        <ng-container *ngFor="let cell of table.headerRow.cells; trackBy: trackCellBy">
          <th *ngIf="cell.hasTitle" [class]="cell.className" [style]="{ minWidth: cell.minWidth, width: cell.width }">
            <ng-template
              [component]="{ name: question.getColumnHeaderWrapperComponentName($any(cell)), data: { componentData: question.getColumnHeaderWrapperComponentData($any(cell)) } }">
              <sv-ng-string [model]="cell.locTitle"></sv-ng-string>
              <sv-ng-matrixheaderrequired *ngIf="!!cell.column" [column]="cell.column" [question]="question">
              </sv-ng-matrixheaderrequired>
            </ng-template>
          </th>

          <td *ngIf="!cell.hasTitle" [class]="cell.className" [style]="{ minWidth: cell.minWidth, width: cell.width }">
          </td>
        </ng-container>
      </tr>
    </thead>
    <tbody>
      <ng-container *ngFor="let row of table.renderedRows; trackBy: trackRowBy">
        <sv-ng-matrix-row [model]="row" [question]="question"></sv-ng-matrix-row>
      </ng-container>
    </tbody>
    <tfoot *ngIf="table.showFooter">
      <tr>
        <sv-ng-matrixdropdown-cell [cell]="cell" [question]="question"
          *ngFor="let cell of table.footerRow.cells; trackBy: trackCellBy">
        </sv-ng-matrixdropdown-cell>
      </tr>
    </tfoot>
  </table>
</div>
