// packages/survey-vue3-ui/src/MatrixRow.vue
<template>
  <tr
    :data-sv-drop-target-matrix-row="row.row && row.row.id"
    @pointerdown="question.onPointerDown($event, row.row)"
    :class="row.className"
    v-if="row.visible"
    ref="root"
  >
    <survey-matrixdropdown-cell
      :cell="cell"
      :question="question"
      v-for="(cell, cellIndex) in row.cells"
      :key="row.id + '_' + cellIndex"
    />
  </tr>
</template>
<script lang="ts" setup>
import type {
  QuestionMatrixDropdownRenderedRow,
  QuestionMatrixDropdownModel,
} from "survey-core";
import { useBase } from "./base";
import { watch, onMounted, onUnmounted, ref } from "vue";
const props = defineProps<{
  question: QuestionMatrixDropdownModel;
  row: QuestionMatrixDropdownRenderedRow;
}>();
const root = ref<HTMLElement>();

useBase(() => props.row);

const stopWatch = watch(
  () => props.row,
  (newValue, oldValue) => {
    if (oldValue) {
      oldValue.setRootElement(undefined as any);
    }
    newValue.setRootElement(root.value as any);
  }
);

onMounted(() => {
  props.row.setRootElement(root.value as any);
});
onUnmounted(() => {
  props.row.setRootElement(undefined as any);
  stopWatch();
});
</script>

// packages/survey-angular-ui/src/questions/matrix-row.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { BaseAngular } from "../base-angular";
import {
  MatrixDropdownRowModelBase,
  Question,
  QuestionMatrixDropdownModelBase,
  QuestionMatrixDropdownRenderedCell,
  QuestionMatrixDropdownRenderedRow
} from "survey-core";

@Component({
  selector: "sv-ng-matrix-row",
  templateUrl: "./matrix-row.component.html",
  styles: [":host { display: none; }"]
})
export class MatrixRowComponent extends BaseAngular<QuestionMatrixDropdownRenderedRow> {
  @Input() model!: QuestionMatrixDropdownRenderedRow;
  @Input() question!: QuestionMatrixDropdownModelBase;
  protected getModel(): QuestionMatrixDropdownRenderedRow {
    return this.model;
  }
  public get row(): MatrixDropdownRowModelBase {
    return this.model.row;
  }
  public trackCellBy(_: number, cell: any): string {
    return cell.id;
  }
}
<ng-template #template>
  <tr *ngIf="model.visible" [class]="model.className" (pointerdown)="question.onPointerDown($event, row)"
    [attr.data-sv-drop-target-matrix-row]="model.dropTargetId" #container>
    <sv-ng-matrixdropdown-cell [cell]="cell" [question]="question"
      *ngFor="let cell of model.cells; trackBy: trackCellBy"></sv-ng-matrixdropdown-cell>
  </tr>
</ng-template>
