// src/vue/multipletext.vue
<template>

  <table :class="question.cssClasses.root">
    <tbody>
      <tr
        v-for="(row, rowindex) in question.getRows()"
        :key="question.inputId + 'rowkey' + rowindex"
        :class="question.cssClasses.row"
      >
        <template v-for="item in row">
          <td :key="'item' + item.editor.id" :class="question.cssClasses.cell">
            <survey-multipletext-item :question="question" :item="item"></survey-multipletext-item>
          </td>
        </template>
      </tr>
    </tbody>
  </table>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionMultipleTextModel } from "survey-core";

@Component
export class MultipleText extends QuestionVue<QuestionMultipleTextModel> {
}
Vue.component("survey-multipletext", MultipleText);
export default MultipleText;
</script>

// packages/survey-angular-ui/src/questions/multipletext.component.ts
import { QuestionAngular } from "../question";
import { MultipleTextItemModel, QuestionMultipleTextModel } from "survey-core";
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-multipletext-question",
  templateUrl: "./multipletext.component.html"
})
export class MultipleTextComponent extends QuestionAngular<QuestionMultipleTextModel> {
  trackRowBy = (index: number): string => {
    return this.model.inputId + "rowkey" + index;
  }
  trackItemBy (_: number, item: MultipleTextItemModel): string {
    return "item" + item.editor.id;
  }
}

AngularComponentFactory.Instance.registerComponent("multipletext-question", MultipleTextComponent);
<table [class]="model.cssClasses.root" #contentElement>
  <tbody>
    <tr
      *ngFor="let row of model.getRows(); index as rowIndex; trackBy: trackRowBy"
      [class]="model.cssClasses.row"
    >
      <ng-container *ngFor="let item of row; trackBy: trackItemBy" >
        <td [class]="model.cssClasses.cell" [question]="model" [model]="item" sv-ng-multipletext-item></td>
      </ng-container>
    </tr>
  </tbody>
</table>
