// src/vue/paneldynamic.vue
<template>
  <div :class="question.cssClasses.root">
    <div v-if="question.getShowNoEntriesPlaceholder()" :class="question.cssClasses.noEntriesPlaceholder">
      <span>
        <survey-string :locString="question.locNoEntriesText"></survey-string>
      </span>
      <sv-paneldynamic-add-btn :data="{ question }" />
    </div>
    <div :class="question.cssClasses.progress" v-if="!question.showLegacyNavigation && question.isProgressTopShowing && question.isRangeShowing">
      <div
        :class="question.cssClasses.progressBar"
        :style="{ width: question.progress }"
        role="progressbar"
      ></div>
    </div>
    <survey-paneldynamicprogress
      v-if="question.showLegacyNavigation && question.isProgressTopShowing"
      :question="question"
    />
    <template v-for="(panel, index) in renderedPanels">
      <div :class="question.getPanelWrapperCss()" :key="panel.id">
        <survey-panel :question="panel" :css="css" />
        <survey-paneldynamicremove :question="question" :panel="panel" />
      </div>
      <hr :class="question.cssClasses.separator" v-if="question.isRenderModeList && index < question.panelCount - 1" :key="'separator' + panel.id" />
    </template>
    <survey-paneldynamicprogress
      v-if="question.showLegacyNavigation && question.isProgressBottomShowing"
      :question="question"
    />
    <sv-paneldynamic-add-btn v-if="question.showLegacyNavigation && question.isRenderModeList" :data="{ question }" />
    <survey-paneldynamicprogress-v2 v-if="question.panelCount !== 0"
      :question="question"
    />
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { PanelModel, QuestionPanelDynamicModel } from "survey-core";
import { default as QuestionVue } from "./question";

@Component
export class PanelDynamic extends QuestionVue<QuestionPanelDynamicModel> {
  get renderedPanels(): PanelModel[] {
    if (this.question.isRenderModeList) return this.question.panels;
    const panels = [];
    if (this.question.currentPanel) {
      panels.push(this.question.currentPanel);
    }
    return panels;
  }
}
Vue.component("survey-paneldynamic", PanelDynamic);
export default PanelDynamic;
</script>

// packages/survey-angular-ui/src/questions/paneldynamic.component.ts
import { Component, OnInit } from "@angular/core";
import { QuestionAngular } from "../question";
import { PanelModel, QuestionPanelDynamicModel, SurveyModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-paneldynamic-question",
  templateUrl: "./paneldynamic.component.html"
})
export class PanelDynamicQuestionComponent extends QuestionAngular<QuestionPanelDynamicModel | any> implements OnInit {
  get renderedPanels(): PanelModel[] {
    if (this.model.isRenderModeList) return this.model.panels;
    const panels = [];
    if (this.model.currentPanel) {
      panels.push(this.model.currentPanel);
    }
    return panels;
  }
  protected override onModelChanged(): void {
    super.onModelChanged();
    this.model.panelCountChangedCallback = () => {
      this.detectChanges();
    };
    this.model.currentIndexChangedCallback = () => {
      this.detectChanges();
    };
    this.model.renderModeChangedCallback = () => {
      this.detectChanges();
    };
  }
  get progressCssClass() {
    return this.model.isProgressTopShowing
      ? this.model.cssClasses.progressTop
      : this.model.cssClasses.progressBottom;
  }
  override ngOnDestroy(): void {
    this.model.panelCountChangedCallback = () => {};
    this.model.currentIndexChangedCallback = () => {};
    this.model.renderModeChangedCallback = () => {};
    super.ngOnDestroy();
  }
  public getPanelComponentName(panel: PanelModel): string {
    const survey = this.surveyModel as SurveyModel;
    if(!!survey) {
      const name = survey.getElementWrapperComponentName(panel);
      if(!!name) {
        return name;
      }
    }
    return "panel";
  }
  public getPanelComponentData(panel: PanelModel): any {
    const survey = this.surveyModel as SurveyModel;
    let data: any;
    if(!!survey) {
      data = survey.getElementWrapperComponentData(panel);
    }
    return {
      componentName: "panel",
      componentData: {
        model: panel,
        data: data
      }
    };
  }
}

AngularComponentFactory.Instance.registerComponent("paneldynamic-question", PanelDynamicQuestionComponent);
<div [class]="model.cssClasses.root" #contentElement>
  <div *ngIf="model.getShowNoEntriesPlaceholder()" [class]="model.cssClasses.noEntriesPlaceholder">
    <span [model]="model.locNoEntriesText" sv-ng-string></span>
    <sv-ng-paneldynamic-add-btn [data]="{ question: model }"></sv-ng-paneldynamic-add-btn>
  </div>
  <div [class]="model.cssClasses.progress" *ngIf="!model.showLegacyNavigation && model.isProgressTopShowing && model.isRangeShowing">
    <div
      [class]="model.cssClasses.progressBar"
      [style]="{ width: model.progress }"
      role="progressbar"
    ></div>
  </div>
  <ng-container [ngTemplateOutlet]="progress" *ngIf="model.showLegacyNavigation && model.isProgressTopShowing"></ng-container>
  <!-- add track by [key]="panel.id" -->
  <ng-container *ngFor="let panel of renderedPanels; index as index"> 
    <div [class]="model.getPanelWrapperCss()">
      <sv-ng-panel [model]="panel"></sv-ng-panel>
      <ng-container *ngTemplateOutlet="removeBtn; context: { panel }"></ng-container>
    </div>
    <!-- add track by [key]="'separator' + panel.id" -->
    <hr [class]="model.cssClasses.separator" *ngIf="model.isRenderModeList && index < model.panelCount - 1"/>
  </ng-container>
  <ng-container [ngTemplateOutlet]="progress" *ngIf="model.showLegacyNavigation && model.isProgressBottomShowing"></ng-container>
  <sv-ng-paneldynamic-add-btn *ngIf="model.showLegacyNavigation && model.isRenderModeList" [data]="{ question: model }"></sv-ng-paneldynamic-add-btn>
  <ng-container [ngTemplateOutlet]="progressV2" *ngIf="model.panelCount !== 0 && !model.showLegacyNavigation"></ng-container>
</div>

<ng-template #progressV2>
  <div [class]="model.cssClasses.footer" *ngIf="!!model.cssClasses.footer">
    <hr [class]="model.cssClasses.separator"/>
    <div [class]="model.cssClasses.progress" *ngIf="model.isRangeShowing && model.isProgressBottomShowing">
      <div
        [class]="model.cssClasses.progressBar"
        [style]="{ width: model.progress }"
        role="progressbar"
      ></div>
    </div>
    <div [class]="model.cssClasses.footerButtonsContainer" [model]="model.footerToolbar" sv-ng-action-bar></div>
  </div>
</ng-template>
<ng-template #progress>
  <div [class]="this.progressCssClass">
    <div style="clear: both" [class]="this.progressCssClass">
      <div [class]="model.cssClasses.progressContainer">
        <sv-ng-paneldynamic-prev-btn [data]="{ question: model }"></sv-ng-paneldynamic-prev-btn>
        <div [class]="model.cssClasses.progress" *ngIf="model.isRangeShowing">
          <div
            [class]="model.cssClasses.progressBar"
            [style]="{ width: model.progress }"
            role="progressbar"
          ></div>
        </div>
          <sv-ng-paneldynamic-next-btn [data]="{ question: model }"></sv-ng-paneldynamic-next-btn>
      </div>
      <sv-ng-paneldynamic-add-btn [data]="{ question: model }"></sv-ng-paneldynamic-add-btn>
      <sv-ng-paneldynamic-progress-text [data]="{ question: model }"></sv-ng-paneldynamic-progress-text>
    </div>
  </div>
</ng-template>

<ng-template #removeBtn let-panel="panel">
  <button type="button"
      [visible]="model.canRemovePanel && panel.state != 'collapsed'" (click)="model.removePanelUI(panel)" [class]="model.getPanelRemoveButtonCss()">
      <span [class]="model.cssClasses.buttonRemoveText">{{model.panelRemoveText}}</span>
      <span [class]="model.cssClasses.iconRemove"></span>
    </button>
</ng-template>
