// packages/survey-vue-ui/src/Rating.vue
<template>
    <div :class="question.ratingRootCss">
      <fieldset role="radiogroup">
        <legend role="presentation" class="sv-hidden"></legend>
        <span v-if="question.hasMinLabel"
          :class="question.cssClasses.minText">
          <survey-string :locString="question.locMinRateDescription" />
        </span>
        <component
          v-for="(item, index) in question.renderedRateItems"
            :is="question.itemComponentName"
          :item="item"
          :index="index"
          :question="question"
        ></component>
        <span v-if="question.hasMaxLabel"
              :class="question.cssClasses.maxText"
        >
        <survey-string :locString="question.locMaxRateDescription" />
        </span>
      </fieldset>
  </div>
</template>

<script lang="ts">
import { QuestionRatingModel } from "survey-core";
import { QuestionVue } from "./base";
import { defineComponent, type PropType } from "vue";

export default defineComponent({
  // eslint-disable-next-line
  mixins: [QuestionVue],
  name: "survey-rating",
  props: {
    question: { type: Object as PropType<QuestionRatingModel>, required: true },
  },
  methods: {
    getInputId(index: any): string {
      return this.question.getInputId(index);
    },
  },
});
</script>

// packages/survey-angular-ui/src/questions/rating.component.ts
import { Component, Input } from "@angular/core";
import { QuestionRatingModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-rating-question",
  templateUrl: "./rating.component.html"
})
export class RatingQuestionComponent {
  @Input() model!: QuestionRatingModel;
  trackByFn(index: number): number {
    return index;
  }
  public onClick(event: any) {
    event.stopPropagation();
    this.model.setValueFromClick(event.target.value);
  }
}

AngularComponentFactory.Instance.registerComponent("rating-question", RatingQuestionComponent);
  <div [class]="model.ratingRootCss" #contentElement>
      <fieldset role="radiogroup">
          <legend role="presentation" class="sv-hidden"></legend>
          <span *ngIf="model.hasMinLabel" [class]="model.cssClasses.minText" [model]="model.locMinRateDescription" sv-ng-string-viewer>
          </span>
          <label *ngFor="let item of model.renderedRateItems; index as index; trackBy: trackByFn" [class]="model.getRenderedItemClass(item)" >
            <input type="radio"
              class="sv-visuallyhidden"
              [attr.name]="model.name" [attr.id]="model.getInputId(index)" [value]="item.value" [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid" [attr.aria-describedby]="model.ariaDescribedBy"
              [disabled]="model.isInputReadOnly" [checked]="model.value === item.value" (click)="onClick($event)"
              />
              <span [class]="model.cssClasses.itemText" [model]="item.locText" sv-ng-string-viewer></span>
          </label>
          <span *ngIf="model.hasMaxLabel" [class]="model.cssClasses.maxText" [model]="model.locMaxRateDescription" sv-ng-string-viewer></span>
      </fieldset>
  </div>
