// packages/survey-vue3-ui/src/Rating.vue
<template>
  <div :class="question.ratingRootCss" ref="root">
    <fieldset
      @keydown="question.onKeyDown($event)"
      :role="question.a11y_input_ariaRole"
      :aria-required="question.a11y_input_ariaRequired"
      :aria-label="question.a11y_input_ariaLabel"
      :aria-labelledby="question.a11y_input_ariaLabelledBy"
      :aria-describedby="question.a11y_input_ariaDescribedBy"
      :aria-invalid="question.a11y_input_ariaInvalid"
      :aria-errormessage="question.a11y_input_ariaErrormessage"
    >
      <legend role="presentation" class="sv-hidden"></legend>
      <span v-if="question.hasMinLabel" :class="question.cssClasses.minText">
        <SvComponent
          :is="'survey-string'"
          :locString="question.locMinRateDescription"
        />
      </span>
      <SvComponent
        v-for="(item, index) in question.renderedRateItems"
        :key="getInputId(index)"
        :is="question.itemComponent"
        :item="item"
        :index="index"
        :question="question"
      />
      <span v-if="question.hasMaxLabel" :class="question.cssClasses.maxText">
        <SvComponent
          :is="'survey-string'"
          :locString="question.locMaxRateDescription"
        />
      </span>
    </fieldset>
  </div>
</template>
<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { QuestionRatingModel } from "survey-core";
import { useQuestion } from "./base";
import { ref, onMounted, getCurrentInstance } from "vue";
defineOptions({
  inheritAttrs: false,
});
const props = defineProps<{ question: QuestionRatingModel }>();
const root = ref(null);
useQuestion<QuestionRatingModel>(props, root);
const getInputId = (index: any): string => {
  return props.question.getInputId(index);
};

const instance = getCurrentInstance();
onMounted(() => {
  instance.proxy.$forceUpdate();
});
</script>

// packages/survey-angular-ui/src/questions/rating.component.ts
import { Component, Input } from "@angular/core";
import { QuestionRatingModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-rating-question",
  templateUrl: "./rating.component.html"
})
export class RatingQuestionComponent {
  @Input() model!: QuestionRatingModel;
  trackByFn(index: number): number {
    return index;
  }
  public onClick(event: any) {
    event.stopPropagation();
    this.model.setValueFromClick(event.target.value);
  }
}

AngularComponentFactory.Instance.registerComponent("rating-question", RatingQuestionComponent);
  <div [class]="model.ratingRootCss" #contentElement>
      <fieldset role="radiogroup">
          <legend role="presentation" class="sv-hidden"></legend>
          <span *ngIf="model.hasMinLabel" [class]="model.cssClasses.minText" [model]="model.locMinRateDescription" sv-ng-string-viewer>
          </span>
          <label *ngFor="let item of model.renderedRateItems; index as index; trackBy: trackByFn" [class]="model.getRenderedItemClass(item)" >
            <input type="radio"
              class="sv-visuallyhidden"
              [attr.name]="model.name" [attr.id]="model.getInputId(index)" [value]="item.value" [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid" [attr.aria-describedby]="model.ariaDescribedBy"
              [disabled]="model.isInputReadOnly" [checked]="model.value === item.value" (click)="onClick($event)"
              />
              <span [class]="model.cssClasses.itemText" [model]="item.locText" sv-ng-string-viewer></span>
          </label>
          <span *ngIf="model.hasMaxLabel" [class]="model.cssClasses.maxText" [model]="model.locMaxRateDescription" sv-ng-string-viewer></span>
      </fieldset>
  </div>
