// packages/survey-vue3-ui/src/Slider.vue
<template>
    <div :class="question.rootCss" ref="rootRef">
        <input v-if="question.sliderType !== 'single' && question.allowDragRange" ref="rangeInputRef"
        name="range-input" :class="question.cssClasses.input" type="range" tabIndex="-1" 
        :min="question.min" :max="question.max" :step="question.step" aria-hidden="true"
        @input="(e)=>{question.handleRangeOnChange(e as InputEvent)}"
        @pointerdown="(e)=>{question.handleRangePointerDown(e, rootRef as HTMLElement)}"
        @pointerup="(e)=>{question.handleRangePointerUp(e, rootRef as HTMLElement)}" />

        <div :class="question.cssClasses.visualContainer" @pointerup="(e)=>{question.setValueByClickOnPath(e, rootRef as HTMLElement)}">
          <div :class="question.cssClasses.visualContainerSlider">
            <div :class="question.cssClasses.inverseTrackLeft" :style="{ width: question.getTrackPercentLeft() + '%' }"></div>
            <div :class="question.cssClasses.inverseTrackRight" :style="{ width: question.getTrackPercentRight() + '%' }"></div>
            <div :class="question.cssClasses.rangeTrack" :style="{ left: question.getTrackPercentLeft() + '%', right: question.getTrackPercentRight() + '%' }" ></div>
            
            <template v-for="(value, i) in question.getRenderedValue()" :key="i">
              <input :class="question.cssClasses.input" :id="'sjs-slider-input-' + i" type="range" :value="value" 
                :min="question.min" :max="question.max" :step="question.step" :disabled="question.isDisabledAttr"
                @input="(e)=>{question.handleOnChange(e as InputEvent, i)}"
                @pointerdown="(e)=>{question.handlePointerDown(e)}"
                @pointerup="(e)=>{e.stopPropagation();question.handlePointerUp(e)}"
                @keydown="(e)=>{question.handleKeyDown(e)}"
                @keyup="(e)=>{question.handleKeyUp(e)}"
                @focus="()=>{question.handleOnFocus(i)}"
                @blur="()=>{question.handleOnBlur()}"
                :aria-required="question.a11y_input_ariaRequired"
                :aria-label="question.a11y_input_ariaLabel"
                :aria-labelledby="question.a11y_input_ariaLabelledBy"
                :aria-describedby="question.a11y_input_ariaDescribedBy"
                :aria-invalid="question.a11y_input_ariaInvalid"
                :aria-errormessage="question.a11y_input_ariaErrormessage"
              />
              <div :class="question.getThumbContainerCss(i)" :style="{ left: question.getPercent(value) + '%' }">
                <div v-if="question.tooltipVisibility !== 'never'" :class="question.tooltipCss">
                  <div :class="question.cssClasses.tooltipPanel">
                    <div :class="question.cssClasses.tooltipValue">
                      {{question.getTooltipValue(i)}}
                    </div>
                  </div>
                </div>
                <div :class="question.cssClasses.thumb">
                  <div :class="question.cssClasses.thumbDot"></div>
                </div>
              </div>

            </template>

          </div>
        </div>

        <div v-if="question.showLabels" :class="question.cssClasses.labelsContainer">
          <div>
            <SvComponent
              v-for="(label) in question.renderedLabels"
              :key="label.id"
              :is="'sv-slider-label-item'"
              :item="label"
              :question="question"
            />
          </div>
        </div>
    </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { QuestionSliderModel } from "survey-core";
import { useQuestion } from "./base";
import { onMounted, ref } from "vue";
defineOptions({
  inheritAttrs: false,
});
const props = defineProps<{ question: QuestionSliderModel }>();
const rootRef = ref<HTMLElement | null>(null);
const rangeInputRef = ref<HTMLInputElement | null>(null)
useQuestion<QuestionSliderModel>(props, rootRef);

onMounted(() => {
  props.question.refreshInputRange(rangeInputRef.value);
});
</script>

// packages/survey-angular-ui/src/questions/slider.component.ts
import { Component, ElementRef, ViewChild } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionSliderModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-slider-question",
  templateUrl: "./slider.component.html"
})
export class SliderQuestionComponent extends QuestionAngular<QuestionSliderModel> {
  @ViewChild("rangeInputRef") rangeInputRef!: ElementRef<HTMLInputElement>;

  override ngAfterViewInit(): void {
    super.ngAfterViewInit();
    if (this.model && this.rangeInputElement) {
      this.model.refreshInputRange(this.rangeInputElement);
    }
  }
  get rootRef(): HTMLElement {
    return this.elementContentRef?.nativeElement;
  }
  get rangeInputElement(): HTMLInputElement {
    return this.rangeInputRef?.nativeElement;
  }
  get labelCountArray(): number[] {
    const result:number[] = [];
    for (let i = 0; i < this.model.labelCount; i++) {
      result.push(i);
    }
    return result;
  }
  get valueArray(): number[] {
    return this.model.getRenderedValue();
  }
  trackByRenderedValue (i: number): number {
    return i;
  }
  trackByLabelCount (i: number): number {
    return i;
  }
}

AngularComponentFactory.Instance.registerComponent("slider-question", SliderQuestionComponent);

<div [class]="model.rootCss" #contentElement>
  <input *ngIf="model.sliderType !== 'single' && model.allowDragRange" #rangeInputRef
  name="range-input" [class]="model.cssClasses.input" type="range" tabIndex="-1" 
  [attr.min]="model.min" [attr.max]="model.max" [attr.step]="model.step" aria-hidden="true"
  (input)="model.handleRangeOnChange($any($event))"
  (pointerdown)="model.handleRangePointerDown($any($event), rootRef)"
  (pointerup)="model.handleRangePointerUp($any($event), rangeInputRef)" />
  
  <div [class]="model.cssClasses.visualContainer" (pointerup)="model.setValueByClickOnPath($any($event), rootRef)">
    <div [class]="model.cssClasses.visualContainerSlider">
      <div [class]="model.cssClasses.inverseTrackLeft" [style]="{ width: model.getTrackPercentLeft() + '%' }"></div>
      <div [class]="model.cssClasses.inverseTrackRight" [style]="{ width: model.getTrackPercentRight() + '%' }"></div>
      <div [class]="model.cssClasses.rangeTrack" [style]="{ left: model.getTrackPercentLeft() + '%', right: model.getTrackPercentRight() + '%' }" ></div>

       <ng-container *ngFor="let value of valueArray; index as i; trackBy: trackByRenderedValue;">
        <input [class]="model.cssClasses.input" [attr.id]="'sjs-slider-input-' + i" type="range" [value]="value" 
          [attr.min]="model.min" [attr.max]="model.max" [attr.step]="model.step" [disabled]="model.isDisabledAttr"
          (input)="model.handleOnChange($any($event), i)"
          (pointerdown)="model.handlePointerDown($any($event))"
          (pointerup)="model.handlePointerUp($any($event))"
          (keydown)="model.handleKeyDown($any($event))"
          (keyup)="model.handleKeyUp($any($event))"
          (focus)="model.handleOnFocus(i)"
          (blur)="model.handleOnBlur()"
          [attr.aria-required]="model.a11y_input_ariaRequired"
          [attr.aria-label]="model.a11y_input_ariaLabel"
          [attr.aria-labelledby]="model.a11y_input_ariaLabelledBy"
          [attr.aria-describedby]="model.a11y_input_ariaDescribedBy"
          [attr.aria-invalid]="model.a11y_input_ariaInvalid"
          [attr.aria-errormessage]="model.a11y_input_ariaErrormessage"
        />
        <div [class]="model.getThumbContainerCss(i)" [style]="{ left: model.getPercent(value) + '%' }">
          <div *ngIf="model.tooltipVisibility !== 'never'" [class]="model.tooltipCss">
            <div [class]="model.cssClasses.tooltipPanel">
              <div [class]="model.cssClasses.tooltipValue">{{model.getTooltipValue(i)}}</div>
            </div>
          </div>
          <div [class]="model.cssClasses.thumb">
            <div [class]="model.cssClasses.thumbDot"></div>
          </div>
        </div>
      </ng-container>

    </div>
  </div>

  <div *ngIf="model.showLabels" [class]="model.cssClasses.labelsContainer">
    <div>
      <div *ngFor="let label of model.renderedLabels; index as i; trackBy: trackByLabelCount;"  [class]="model.getLabelCss(i)"
      [style]="{ left: label.value + '%' }"
      (pointerup)="model.handleLabelPointerUp($any($event), i)">
        <div [class]="model.cssClasses.labelTick"></div>
        <div [class]="model.cssClasses.labelText" [model]="label.locText" sv-ng-string></div>
      </div>
    </div>
  </div>
</div>
