// src/vue/tagbox.vue
<template>
  <div :class="question.renderCssRoot">
    <sv-tagbox :question="question"></sv-tagbox>
    <survey-other-choice v-if="question.isOtherSelected" :question="question" />
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { default as QuestionVue } from "./question";
import { QuestionTagboxModel } from "survey-core";

@Component
export class Tagbox extends QuestionVue<QuestionTagboxModel> {}

Vue.component("survey-tagbox", Tagbox);

export default Tagbox;
</script>

// packages/survey-angular-ui/src/questions/tagbox.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { AngularComponentFactory } from "../component-factory";
import { QuestionTagboxModel } from "survey-core";

@Component({
  selector: "sv-ng-tagbox-question",
  templateUrl: "./tagbox.component.html"
})
export class TagboxQuestionComponent extends QuestionAngular<QuestionTagboxModel> {
}

AngularComponentFactory.Instance.registerComponent("tagbox-question", TagboxQuestionComponent);
<div [class]="model.renderCssRoot" #contentElement>
  <sv-ng-tagbox [model]="model"></sv-ng-tagbox>
  <div *ngIf="model.isOtherSelected" [class]="model.getCommentAreaCss(true)" [question]="model" [item]="model.otherItem" sv-ng-comment-choice></div>
</div>
