// packages/survey-vue-ui/src/ElementHeader.vue
<template>
  <div :class="element.cssHeader" @click="clickTitleFunction">
    <survey-element-title :element="element" :css="css" />
    <div
      v-if="element.hasDescriptionUnderTitle"
      v-show="element.hasDescription"
      :class="element.cssDescription"
    >
      <survey-string :locString="element.locDescription" />
    </div>
    <sv-action-bar
      v-if="!!element.additionalTitleToolbar"
      :model="element.additionalTitleToolbar"
    ></sv-action-bar>
  </div>
</template>

<script lang="ts" setup>
import type { Question, PanelModel } from "survey-core";

const props = defineProps<{ element: Question | PanelModel; css?: any }>();
const clickTitleFunction = () => {
  if (typeof props.element.clickTitleFunction === "function") {
    props.element.clickTitleFunction();
  }
};
</script>

// src/react/element-header.tsx
import React from "react";
import { Question, PanelModel, QuestionPanelDynamicModel } from "survey-core";
import { SurveyActionBar } from "./components/action-bar/action-bar";
import { TitleElement } from "./components/title/title-element";
import { SurveyElementBase } from "./reactquestion_element";

export class SurveyElementHeader extends React.Component<any, any> {
  private get element(): Question | PanelModel {
    return this.props.element;
  }
  public render(): JSX.Element {
    const element = this.element;
    const title = element.hasTitle ? (
      <TitleElement element={element}></TitleElement>
    ) : null;
    const description = element.hasDescriptionUnderTitle
      ? SurveyElementBase.renderQuestionDescription(this.element)
      : null;

    const additionalTitleToolbarElement = !!element.additionalTitleToolbar ? <SurveyActionBar model= {element.additionalTitleToolbar}></SurveyActionBar> : null;

    return (
      <div className={element.cssHeader} onClick={element.clickTitleFunction}>
        {title}
        {description}
        {additionalTitleToolbarElement}
      </div>
    );
  }
}
