// packages/survey-vue3-ui/src/BooleanSwitch.vue
<template>
  <div
    :class="question.cssClasses.rootSwitch"
    ref="root"
    @click="renderedValue = !renderedValue"
  >
    <div
      :class="question.getSwitchButtonCss()"
      role="checkbox"
      tabindex="0"
      :aria-checked="question.booleanValue || false"
      :aria-required="question.a11y_input_ariaRequired"
      :aria-label="question.a11y_input_ariaLabel"
      :aria-labelledby="question.a11y_input_ariaLabelledBy"
      :aria-invalid="question.a11y_input_ariaInvalid"
      :aria-errormessage="question.a11y_input_ariaErrormessage"
      v-key2click="{ processEsc: false }"
    >
      <div :class="question.cssClasses.switchThumb">
        <div
          :class="question.cssClasses.switchThumbCircle + ' ' + question.cssClasses.switchThumbLeft"
        ></div>
      </div>
      <div :class="question.cssClasses.switchThumb">
        <div
          :class="question.cssClasses.switchThumbCircle + ' ' + question.cssClasses.switchThumbRight"
        ></div>
      </div>
    </div>
    <div :class="question.cssClasses.switchCaption">
      <div :class="question.cssClasses.switchTitle" :id="question.labelRenderedAriaID">
        <SvComponent :is="'survey-string'" :locString="question.locTitle" />
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { RendererFactory } from "survey-core";
import { computed, ref } from "vue";
import { useQuestion } from "./base";
import { key2ClickDirective as vKey2click } from "@/directives/key2click";
import type { IBooleanProps } from "./boolean";
defineOptions({ inheritAttrs: false });
const props = defineProps<IBooleanProps>();
const root = ref(null);
useQuestion(props, root);

const renderedValue = computed({
  get() {
    return props.question.booleanValue;
  },
  set(val) {
    // eslint-disable-next-line vue/no-mutating-props
    props.question.booleanValue = val;
  },
});
</script>

<script lang="ts">
RendererFactory.Instance.registerRenderer(
  "boolean",
  "switch",
  "sv-boolean-switch"
);
</script>

// packages/survey-angular-ui/src/components/renderAs/boolean-switch/boolean-switch.component.ts

import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { QuestionBooleanModel, RendererFactory } from "survey-core";

@Component({
  selector: "sv-ng-boolean-switch-question",
  templateUrl: "./boolean-switch.component.html"
})
export class BooleanSwitchComponent {
  @Input() model!: QuestionBooleanModel;
}

AngularComponentFactory.Instance.registerComponent("boolean-switch-question", BooleanSwitchComponent);
RendererFactory.Instance.registerRenderer(
  "boolean",
  "switch",
  "boolean-switch-question"
);

<div [class]="model.cssClasses.rootSwitch" role="checkbox" [attr.aria-checked]="model.booleanValue || false"
  [attr.aria-required]="model.a11y_input_ariaRequired" [attr.aria-label]="model.a11y_input_ariaLabel"
  [attr.aria-labelledby]="model.a11y_input_ariaLabelledBy" [attr.aria-invalid]="model.a11y_input_ariaInvalid"
  [attr.aria-errormessage]="model.a11y_input_ariaErrormessage" (click)="model.booleanValue = !model.booleanValue">
  <div [class]="model.cssClasses.switchButton + (model.booleanValue ? ' ' + model.cssClasses.switchButtonChecked : '')"
    tabindex="0" [key2click]>
    <div [class]="model.cssClasses.switchThumb">
      <div [class]="model.cssClasses.switchThumbCircle + ' ' + model.cssClasses.switchThumbLeft"></div>
    </div>
    <div [class]="model.cssClasses.switchThumb">
      <div [class]="model.cssClasses.switchThumbCircle + ' ' + model.cssClasses.switchThumbRight"></div>
    </div>
  </div>
  <div [class]="model.cssClasses.switchCaption">
    <div [class]="model.cssClasses.switchTitle" [id]="model.labelRenderedAriaID">
      <span [model]="model.locTitle" sv-ng-string></span>
    </div>
  </div>
</div>
