// packages/survey-react-ui/src/boolean-switch.tsx
import * as React from "react";
import { RendererFactory } from "survey-core";
import { ReactQuestionFactory } from "./reactquestion_factory";
import { SurveyQuestionBoolean } from "./boolean";
import { SurveyElementBase } from "./reactquestion_element";
import { attachKey2click } from "./reactSurvey";

export class SurveyQuestionBooleanSwitch extends SurveyQuestionBoolean {
  constructor(props: any) {
    super(props);
  }
  protected renderElement(): React.JSX.Element {
    const cssClasses = this.question.cssClasses;
    const buttonClass = cssClasses.switchButton + (this.question.booleanValue ? " " + cssClasses.switchButtonChecked : "");
    const button = attachKey2click(<div className={buttonClass} tabIndex={0}
      role="checkbox"
      aria-checked={this.question.booleanValue || false}
      aria-required={this.question.a11y_input_ariaRequired}
      aria-label={this.question.a11y_input_ariaLabel}
      aria-labelledby={this.question.a11y_input_ariaLabelledBy}
      aria-invalid={this.question.a11y_input_ariaInvalid}
      aria-errormessage={this.question.a11y_input_ariaErrormessage}
    >
      <div className={cssClasses.switchThumb}>
        <div className={cssClasses.switchThumbCircle + " " + cssClasses.switchThumbLeft}></div>
      </div>
      <div className={cssClasses.switchThumb}>
        <div className={cssClasses.switchThumbCircle + " " + cssClasses.switchThumbRight}></div>
      </div>
    </div>, this.question, { processEsc: false });

    return (
      <div className={cssClasses.rootSwitch} onClick={() => this.question.booleanValue = !this.question.booleanValue}>
        {button}
        <div className={cssClasses.switchCaption}>
          <div className={cssClasses.switchTitle} id={this.question.labelRenderedAriaID}>
            {SurveyElementBase.renderLocString(this.question.locTitle)}
          </div>
        </div>
      </div>
    );
  }
}

ReactQuestionFactory.Instance.registerQuestion(
  "sv-boolean-switch",
  (props) => {
    return React.createElement(SurveyQuestionBooleanSwitch, props);
  }
);

RendererFactory.Instance.registerRenderer(
  "boolean",
  "switch",
  "sv-boolean-switch"
);

// packages/survey-angular-ui/src/components/renderAs/boolean-switch/boolean-switch.component.ts

import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { QuestionBooleanModel, RendererFactory } from "survey-core";

@Component({
  selector: "sv-ng-boolean-switch-question",
  templateUrl: "./boolean-switch.component.html"
})
export class BooleanSwitchComponent {
  @Input() model!: QuestionBooleanModel;
}

AngularComponentFactory.Instance.registerComponent("boolean-switch-question", BooleanSwitchComponent);
RendererFactory.Instance.registerRenderer(
  "boolean",
  "switch",
  "boolean-switch-question"
);

<div [class]="model.cssClasses.rootSwitch" role="checkbox" [attr.aria-checked]="model.booleanValue || false"
  [attr.aria-required]="model.a11y_input_ariaRequired" [attr.aria-label]="model.a11y_input_ariaLabel"
  [attr.aria-labelledby]="model.a11y_input_ariaLabelledBy" [attr.aria-invalid]="model.a11y_input_ariaInvalid"
  [attr.aria-errormessage]="model.a11y_input_ariaErrormessage" (click)="model.booleanValue = !model.booleanValue">
  <div [class]="model.cssClasses.switchButton + (model.booleanValue ? ' ' + model.cssClasses.switchButtonChecked : '')"
    tabindex="0" [key2click]>
    <div [class]="model.cssClasses.switchThumb">
      <div [class]="model.cssClasses.switchThumbCircle + ' ' + model.cssClasses.switchThumbLeft"></div>
    </div>
    <div [class]="model.cssClasses.switchThumb">
      <div [class]="model.cssClasses.switchThumbCircle + ' ' + model.cssClasses.switchThumbRight"></div>
    </div>
  </div>
  <div [class]="model.cssClasses.switchCaption">
    <div [class]="model.cssClasses.switchTitle" [id]="model.labelRenderedAriaID">
      <span [model]="model.locTitle" sv-ng-string></span>
    </div>
  </div>
</div>
