// packages/survey-react-ui/src/components/survey-actions/survey-nav-button.tsx
import React from "react";
import { Action } from "survey-core";
import { ReactElementFactory } from "../../element-factory";
import { ReactSurveyElement } from "../../reactquestion_element";

export class SurveyNavigationButton extends ReactSurveyElement {
  protected get item(): Action {
    return this.props.item;
  }
  protected canRender(): boolean {
    return this.item.isVisible;
  }
  protected renderElement(): React.JSX.Element {
    return (
      <input
        className={this.item.innerCss}
        type="button"
        disabled={this.item.disabled}
        onMouseDown={this.item.data && this.item.data.mouseDown}
        onClick={this.item.action}
        title={this.item.getTooltip()}
        value={this.item.title}
      />
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-nav-btn",
  (props) => {
    return React.createElement(SurveyNavigationButton, props);
  }
);

// src/vue/components/survey-actions/survey-nav-button.vue
<template>
 <input
    v-if="item.visible"
    type="button"
    :disabled="item.disabled"
    :value="item.title"
    :class="item.innerCss"
    :title="item.getTooltip()"
    @mousedown="buttonMouseDown"
    @click="item.action"
  />
</template>

<script lang="ts">
import Vue from "vue";
import { Prop, Component } from "vue-property-decorator";
import { Action } from "survey-core";
import { Base } from "survey-core";
import { BaseVue } from "../../base";

@Component
export class SurveyNavigationButton extends BaseVue {
  @Prop() public item: Action;
  getModel(): Base {
    return this.item;
  }
  buttonMouseDown(): Base {
    return this.item.data && this.item.data.mouseDown();
  }
}

Vue.component("sv-nav-btn", SurveyNavigationButton);
export default SurveyNavigationButton;
</script>
