// packages/survey-angular-ui/src/components/action.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../base-angular";
import { SurveyModel, PageModel } from "survey-core";

@Component({
  selector: "sv-action",
  templateUrl: "./action.component.html",
  styleUrls: ["./action.component.scss"]
})
export class ActionComponent extends BaseAngular {
  @Input() model: any;
  getModel() {
    return this.model;
  }
}
<div [class]="model.getActionRootCss()" [id]="model.id">
  <div *ngIf="!model.isEmpty" class="sv-action__content">
      <!-- <sv-action-bar-separator *ngIf="model.needSeparator"></sv-action-bar-separator> -->
      <sv-action-bar-item *ngIf="!model.template" [model]="model"></sv-action-bar-item>
      <!-- ko ifnot: $data.template-->
      <!-- ko component: { name: $data.component || 'sv-action-bar-item', params: { item: $data } } -->
      <!-- /ko -->
      <!-- /ko -->
      <!-- ko if: $data.template  -->
      <!-- ko template: { name: $data.template, data: $data.data || $data } -->
      <!-- /ko -->
      <!-- /ko -->
  </div>
</div>

// src/vue/components/action-bar/action.vue
<template>
  <div v-bind:class="item.getActionRootCss()"
      :id="item.id">
    <div class="sv-action__content">
      <sv-action-bar-separator
        v-if="item.needSeparator"
      ></sv-action-bar-separator>
      <component :is="getComponentName()" :item="item"> </component>
    </div>
  </div>
</template>
<script lang="ts">
import Vue from "vue";
import { Prop, Component } from "vue-property-decorator";
import { Action, Base } from "survey-core";
import BaseVue from "../../base";
@Component
export class ActionViewModel extends BaseVue {
  @Prop() item: Action;
  constructor(props: any) {
    super(props);
  }
  getModel(): Base {
    return this.item;
  }
  getComponentName() {
    return this.item.component || "sv-action-bar-item";
  }
}
Vue.component("sv-action", ActionViewModel);
export default ActionViewModel;
</script>
