// packages/survey-angular-ui/src/components/action-bar/action-bar-item-dropdown.component.ts
import { Component, Input } from "@angular/core";
import { ActionDropdownViewModel, getActionDropdownButtonTarget } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-action-bar-item-dropdown",
  templateUrl: "./action-bar-item-dropdown.component.html",
  styleUrls: ["../../hide-host.scss"]
})
export class ActionBarItemDropdownComponent extends BaseAngular {
  @Input() model: any
  public getTarget: (container: HTMLElement) => HTMLElement = getActionDropdownButtonTarget;
  protected viewModel!: ActionDropdownViewModel;

  protected getModel() {
    return this.model;
  }
  override ngOnInit(): void {
    super.ngOnInit();
    this.viewModel = new ActionDropdownViewModel(this.model);
  }
  override ngOnDestroy(): void {
    this.viewModel.dispose();
    super.ngOnDestroy();
  }
}

AngularComponentFactory.Instance.registerComponent("sv-action-bar-item-dropdown", ActionBarItemDropdownComponent);
<ng-template #template>
    <button type="button" (click)="model.action(model, model.getIsTrusted($event))" [key2click]="{ processEsc: false }" [class]="model.getActionBarItemCss()" [title]="model.tooltip || model.title" [disabled]="model.disabled" [attr.role]="model.ariaRole">
        <svg *ngIf="model.iconName" [iconName]="model.iconName" [size]="model.iconSize" [title]="model.tooltip || model.title" [class]="model.cssClasses.itemIcon" sv-ng-svg-icon></svg>
        <span *ngIf="model.hasTitle" [class]="model.getActionBarItemTitleCss()">{{ model.title }}</span>
    </button>
    <sv-ng-popup [popupModel]="model.popupModel" [getTarget]="getTarget"></sv-ng-popup>
</ng-template>

// src/vue/components/action-bar/action-bar-item-dropdown.vue
<template>
  <div style="width: 100%">
    <button
      type="button"
      :class="item.getActionBarItemCss()"
      v-on:click="
        (args) => {
          item.action(item, !!args.pointerType);
        }
      "
      v-on:keyup="
        (evt) => {
          evt.stopPropagation();
        }
      "
      v-bind:disabled="item.disabled"
      v-bind:title="item.tooltip || item.title"
      v-bind:role="item.ariaRole"
      v-bind:tabindex="item.disableTabStop ? -1 : 0"
      v-key2click="{ processEsc: false, disableTabStop: item.disableTabStop }"
    >
      <sv-svg-icon
        v-if="item.iconName"
        :class="item.cssClasses.itemIcon"
        :iconName="item.iconName"
        :size="item.iconSize"
        :title="item.tooltip || item.title"
      ></sv-svg-icon>

      <span
        v-if="item.hasTitle"
        :class="item.getActionBarItemTitleCss()"
        >{{ item.title }}</span
      >
    </button>
    <sv-popup 
      :model="item.popupModel" 
      :getTarget="getTarget"></sv-popup>
  </div>
</template>

<script lang="ts">
import { Component } from "vue-property-decorator";
import Vue from "vue";
import ActionBarItemViewModel from "./action-bar-item.vue";
import { ActionDropdownViewModel, getActionDropdownButtonTarget } from "survey-core";

@Component
export class ActionBarItemDropdownViewModel extends ActionBarItemViewModel {
  private viewModel: ActionDropdownViewModel;
  public getTarget: (container: HTMLElement) => HTMLElement = getActionDropdownButtonTarget;
  constructor() {
    super();
    this.viewModel = new ActionDropdownViewModel(this.item);
  }
  onDestroyed() {
    this.viewModel.dispose();
  }
}
Vue.component("sv-action-bar-item-dropdown", ActionBarItemDropdownViewModel);
export default ActionBarItemDropdownViewModel;
</script>
