// packages/survey-vue3-ui/src/components/file/FilePage.vue
<template>
  <div :class="page.css">
    <sv-file-item
      v-for="item of page.items"
      :key="item"
      :item="item"
      :question="question"
    ></sv-file-item>
  </div>
</template>
<script lang="ts" setup>
import { useBase } from "@/base";
import type { QuestionFileModel, QuestionFilePage } from "survey-core";

const props = defineProps<{
  page: QuestionFilePage;
  question: QuestionFileModel;
}>();
useBase(() => props.page);
</script>

// packages/survey-angular-ui/src/components/file/file-page.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { QuestionFileModel, QuestionFilePage } from "survey-core";

@Component({
    templateUrl: "./file-page.component.html",
    selector: "sv-ng-file-page",
    styleUrls: ["../../hide-host.scss"]
})
export class FilePageComponent extends BaseAngular<QuestionFilePage> {
    @Input() page!: QuestionFilePage;
    @Input() question!: QuestionFileModel;
    protected override getModel() {
        return this.page;
    }
}
<ng-template #template>
    <div [class]="page.css" [attr.id]="page.id">
        <ng-container *ngFor="let item of page.items">
            <ng-template [component]="{ name: 'sv-file-item', data: { item, question } }"></ng-template>
        </ng-container>
    </div>
</ng-template>
