// packages/survey-angular-ui/src/components/list/list-item.component.ts
import { AfterViewInit, Component, Input } from "@angular/core";
import { ListModel, Action } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-list-item, '[sv-ng-list-item]'",
  templateUrl: "./list-item.component.html",
  styleUrls: ["../../hide-host.scss"],
})

export class ListItemComponent extends BaseAngular implements AfterViewInit {
  @Input() element: any;
  @Input() model!: Action;
  @Input() listModel!: ListModel;

  get ariaSelected(): boolean | string {
    return this.listModel.isItemSelected(this.model) || "";
  }
  get class(): string {
    return this.listModel.getItemClass(this.model);
  }
  get paddingLeft(): string {
    return this.listModel.getItemIndent(this.model);
  }
  click(event: any): void {
    this.listModel.onItemClick(this.model);
    event.stopPropagation();
  }
  pointerdown(event: any): void {
    this.listModel.onPointerDown(event, this.model);
  }

  getModel() {
    return this.model;
  }

  ngAfterViewInit(): void {
    this.listModel.onLastItemRended(this.model);
  }
}

AngularComponentFactory.Instance.registerComponent("sv-list-item", ListItemComponent);
<ng-template #template>
  <li role="option" [key2click] [visible]="listModel.isItemVisible(model)" [class]="class" [attr.id]="elementId" [attr.aria-selected]="ariaSelected ? 'true' : 'false'" (click)="click($event)" (pointerdown)="pointerdown($event)">
    <ng-container *ngIf="model.needSeparator">
    <div [class]="listModel.cssClasses.itemSeparator"></div>
    </ng-container>
    <div [class]="listModel.cssClasses.itemBody" [style.paddingInlineStart]="paddingLeft">
    <ng-container *ngIf="!model.component">
      <svg *ngIf="model.iconName" [class]="listModel.cssClasses.itemIcon" [iconName]="model.iconName" [size]="24"
        sv-ng-svg-icon></svg>
      <sv-ng-string [model]="model.locTitle"></sv-ng-string>
    </ng-container>
    <ng-container *ngIf="model.component">
      <ng-template [component]="{ name: model.component, data: { model: model } }"></ng-template>
    </ng-container>
    </div>
  </li>
</ng-template>

// src/vue/components/list/list-item.vue
<template>
  <li
    tabindex="0"
    role="option"
    :id="elementId"
    :aria-selected="model.isItemSelected(item) ? 'true' : 'false'"
    v-show="model.isItemVisible(item)"
    :key="item.id"
    v-bind:class="model.getItemClass(item)"
    v-on:click="click"
    v-key2click
  >
    <div 
      v-if="item.needSeparator"
      v-bind:class="model.cssClasses.itemSeparator"
      />

    <div
      :style="{ paddingInlineStart: model.getItemIndent(item) }"
      v-bind:class="model.cssClasses.itemBody"
    >
      <sv-svg-icon
        v-if="item.iconName && !item.component"
        v-bind:class="model.cssClasses.itemIcon"
        :iconName="item.iconName"
        :size="24"
      ></sv-svg-icon>
      <survey-string v-if="!item.component" :locString="item.locTitle" />
      <component v-if="item.component" :is="item.component" :item="item"> </component>
    </div>
  </li>
</template>

<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { Base, ListModel, Action, IAction } from "survey-core";
import { BaseVue } from "../../base";
export * from "./list.vue";

@Component
export class ListItem extends BaseVue {
  @Prop() item: Action;
  @Prop() model: ListModel;
  constructor() {
    super();
  }
  getModel() {
    return this.item;
  }
  get elementId() {
    return (this.item as IAction)?.elementId;
  }
  public click(event: any) {
    this.model.onItemClick(this.item as any);
    event.stopPropagation();
  }
  protected onMounted() {
    this.model.onLastItemRended(<any>this.item);
  }
}

Vue.component("sv-list-item", ListItem);
export default ListItem;
</script>
