// src/vue/components/file/file-choose-button.vue
<template>
  <label
    tabindex="0"
    :class="question.getChooseFileCss()"
    :for="question.inputId"
    v-bind:aria-label="question.chooseButtonText"
    v-key2click
    v-on:click="function(event) { question.chooseFile(event); }"
  >
    <sv-svg-icon
      v-if="question.cssClasses.chooseFileIconId"
      :title="question.chooseButtonText"
      :iconName="question.cssClasses.chooseFileIconId"
      :size="'auto'"
    ></sv-svg-icon>
    <span>{{ question.chooseButtonText }}</span>
  </label>
</template>
<script lang="ts">
import Vue from "vue";
import { Component, Prop } from "vue-property-decorator";
import { Action, QuestionFileModel } from "survey-core";

@Component
export class FileChooseButton extends Vue {
  @Prop() data: any;
  @Prop() item: Action;
  get question(): QuestionFileModel {
    return (this.item && this.item.data.question) || this.data.question;
  }
}
Vue.component("sv-file-choose-btn", FileChooseButton);
export default FileChooseButton;
</script>

// packages/survey-react-ui/src/components/file/file-choose-button.tsx
import React from "react";
import { attachKey2click } from "../../reactSurvey";
import { ReactSurveyElement } from "../../reactquestion_element";
import { QuestionFileModel } from "survey-core";
import { SvgIcon } from "../svg-icon/svg-icon";
import { ReactElementFactory } from "../../element-factory";

export class SurveyFileChooseButton extends ReactSurveyElement {
  constructor(props: any) {
    super(props);
  }
  protected get question(): QuestionFileModel {
    return (this.props.item && this.props.item.data.question) || this.props.data.question;
  }
  render() {
    return attachKey2click(
      <label
        tabIndex={0}
        className={this.question.getChooseFileCss()}
        htmlFor={this.question.inputId}
        aria-label={this.question.chooseButtonText}
        onClick={(e) => this.question.chooseFile(e.nativeEvent)}
      >
        {(!!this.question.cssClasses.chooseFileIconId) ? <SvgIcon title={this.question.chooseButtonText} iconName={this.question.cssClasses.chooseFileIconId} size={"auto"}></SvgIcon>: null }
        <span>{this.question.chooseButtonText}</span>
      </label>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-file-choose-btn",
  (props) => {
    return React.createElement(SurveyFileChooseButton, props);
  }
);
