// packages/survey-vue3-ui/src/components/file/FileChooseButton.vue
<template>
  <label
    tabindex="0"
    :class="item.getActionBarItemCss()"
    :for="question.inputId"
    v-bind:aria-label="question.chooseButtonText"
    v-key2click
    v-on:click="question.chooseFile($event)"
  >
    <SvComponent
      :is="'sv-svg-icon'"
      v-if="item.iconName"
      :title="question.chooseButtonText"
      :class="item.cssClasses.itemIcon"
      :iconName="question.cssClasses.chooseFileIconId"
      :size="'auto'"
    ></SvComponent>
    <StringViewer v-if="item.hasTitle" :model="item.locTitle" :textClass="item.getActionBarItemTitleCss()" />
  </label>
</template>
<script setup lang="ts">
import { key2ClickDirective as vKey2click } from "@/directives/key2click";
import SvComponent from "@/SvComponent.vue";
import StringViewer from "@/StringViewer.vue";
import type { QuestionFileModel, Action } from "survey-core";
import { computed } from "vue";
const props = defineProps<{
  item: Action;
}>();
const question = computed(
  () => props.item.data?.question as QuestionFileModel
);
</script>

// packages/survey-react-ui/src/components/file/file-choose-button.tsx
import * as React from "react";
import { attachKey2click } from "../../attach-key2click";
import { ReactSurveyElement } from "../../reactquestion_element";
import { QuestionFileModel } from "survey-core";
import { SvgIcon } from "../svg-icon/svg-icon";
import { ReactElementFactory } from "../../element-factory";
import { SurveyLocStringViewer } from "../../string-viewer";

export class SurveyFileChooseButton extends ReactSurveyElement {
  constructor(props: any) {
    super(props);
  }
  protected get question(): QuestionFileModel {
    return (this.props.item && this.props.item.data.question) || this.props.data.question;
  }
  render() {
    return attachKey2click(
      <label
        tabIndex={0}
        className={this.props.item.getActionBarItemCss()}
        htmlFor={this.question.inputId}
        aria-label={this.question.chooseButtonText}
        onClick={(e) => this.question.chooseFile(e.nativeEvent)}
      >
        {!!this.props.item.iconName ? <SvgIcon title={this.question.chooseButtonText} iconName={this.question.cssClasses.chooseFileIconId} size={"auto"} className={this.props.item.cssClasses.itemIcon}></SvgIcon> : null}
        {this.props.item.hasTitle ? <SurveyLocStringViewer model={this.props.item.locTitle} textClass={this.props.item.getActionBarItemTitleCss()} /> : null}
      </label>
    );
  }
}

ReactElementFactory.Instance.registerElement(
  "sv-file-choose-btn",
  (props) => {
    return React.createElement(SurveyFileChooseButton, props);
  }
);
