// packages/survey-vue3-ui/src/PanelDynamicPlaceholder.vue
<template>
  <div
    v-if="question.getShowNoEntriesPlaceholder()"
    :class="question.cssClasses.noEntriesPlaceholder"
  >
    <span>
      <SvComponent
        :is="'survey-string'"
        :locString="question.locNoEntriesText"
      ></SvComponent>
    </span>
    <SvComponent :is="'sv-paneldynamic-add-btn'" :data="{ question }" />
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { QuestionPanelDynamicModel } from "survey-core";

defineProps<{
  question: QuestionPanelDynamicModel;
}>();
</script>

// packages/survey-angular-ui/src/components/paneldynamicplaceholder/paneldynamicplaceholder.component.ts
import { Component, Input } from "@angular/core";
import { QuestionPanelDynamicModel } from "survey-core";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-placeholder-paneldynamic",
  templateUrl: "./paneldynamicplaceholder.component.html"
})
export class PanelDynamicPlaceholderComponent {
  @Input() question!: QuestionPanelDynamicModel;
}
AngularComponentFactory.Instance.registerComponent("sv-ng-placeholder-paneldynamic", PanelDynamicPlaceholderComponent);
<div *ngIf="question.getShowNoEntriesPlaceholder()" [class]="question.cssClasses.noEntriesPlaceholder">
  <span>
    <sv-ng-string [model]="question.locNoEntriesText"></sv-ng-string>
  </span>
  <sv-ng-paneldynamic-add-btn *ngIf="question.canAddPanel" [data]="{ question }"></sv-ng-paneldynamic-add-btn>
</div>
