// packages/survey-vue3-ui/src/components/rating/RatingItemSmiley.vue
<template>
  <label
    :key="item.value"
    @mousedown="question.onMouseDown()"
    :style="question.getItemStyle(item.itemValue, item.highlight)"
    :class="question.getItemClass(item.itemValue, item.highlight)"
    @mouseover="(e) => question.onItemMouseIn(item)"
    @mouseleave="(e) => question.onItemMouseOut(item)"
  >
    <input
      type="radio"
      class="sv-visuallyhidden"
      :name="question.questionName"
      :id="question.getInputId(index)"
      :value="item.value"
      :disabled="question.isDisabledAttr"
      :readonly="question.isReadOnlyAttr"
      @click="(e) => question.setValueFromClick(((e.target as any).value))"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-errormessage="question.ariaErrormessage"
    />
    <SvComponent
      :name="'sv-svg-icon'"
      :iconName="question.getItemSmileyIconName(item.itemValue)"
      :size="'auto'"
      :title="item.text"
    ></SvComponent>
  </label>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { IRatingItemProps } from "./rating";
import { useBase } from "@/base";

const props = defineProps<IRatingItemProps>();

useBase(() => props.item);
</script>

// packages/survey-angular-ui/src/components/rating/rating-item-smiley.component.ts
import { AfterViewInit, Component, Input } from "@angular/core";
import { ListModel, Action, QuestionRatingModel, RenderedRatingItem } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-rating-item-smiley",
  templateUrl: "./rating-item-smiley.component.html",
  styleUrls: ["../../hide-host.scss"],
})

export class RatingItemSmileyComponent extends BaseAngular<RenderedRatingItem> {
  @Input() element: any;
  @Input() model!: QuestionRatingModel;
  @Input() item!: RenderedRatingItem;
  @Input() index!: number;

  onClick(event: any): void {
    this.model.setValueFromClick(event.target.value);
    event.stopPropagation();
  }

  getModel() {
    return this.item;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-rating-item-smiley", RatingItemSmileyComponent);
<ng-template #template>
  <label [style]="model.getItemStyle(item.itemValue, item.highlight)" [class]="model.getItemClass(item.itemValue, item.highlight)" (mouseover)="model.onItemMouseIn(item)" (mouseout)="model.onItemMouseOut(item)" (mousedown)="model.onMouseDown()" [title]="item.text">
    <input type="radio"
      class="sv-visuallyhidden"
      [attr.name]="model.questionName" [attr.id]="model.getInputId(index)" [value]="item.value" [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid" [attr.aria-errormessage]="model.ariaErrormessage"
      [disabled]="model.isDisabledAttr" [readonly]="model.isReadOnlyAttr" [checked]="model.value === item.value" (click)="onClick($event)"
      />
      <svg [iconName]="model.getItemSmileyIconName(item.itemValue)" [size]="'auto'" sv-ng-svg-icon></svg>
  </label>
</ng-template>
