// packages/survey-vue3-ui/src/components/rating/RatingItemStar.vue
<template>
  <label
    :key="item.value"
    @mousedown="question.onMouseDown()"
    :class="question.getItemClass(item.itemValue)"
    @mouseover="(e) => question.onItemMouseIn(item)"
    @mouseleave="(e) => question.onItemMouseOut(item)"
  >
    <input
      type="radio"
      class="sv-visuallyhidden"
      :name="question.questionName"
      :id="question.getInputId(index)"
      :value="item.value"
      :disabled="question.isDisabledAttr"
      :readonly="question.isReadOnlyAttr"
      @click="(e) => question.setValueFromClick((e?.target as any).value)"
      :aria-required="question.ariaRequired"
      :aria-label="question.ariaLabel"
      :aria-invalid="question.ariaInvalid"
      :aria-errormessage="question.ariaErrormessage"
    />
    <sv-svg-icon
      :class="'sv-star'"
      :iconName="question.itemStarIcon"
      :size="'auto'"
      :title="item.text"
    ></sv-svg-icon
    ><sv-svg-icon
      :class="'sv-star-2'"
      :iconName="question.itemStarIconAlt"
      :size="'auto'"
      :title="item.text"
    ></sv-svg-icon>
  </label>
</template>

<script lang="ts" setup>
import type { IRatingItemProps } from "./rating";
import { useBase } from "@/base";

const props = defineProps<IRatingItemProps>();

useBase(() => props.item);
</script>

// packages/survey-angular-ui/src/components/rating/rating-item-star.component.ts
import { AfterViewInit, Component, Input } from "@angular/core";
import { ListModel, Action, QuestionRatingModel, RenderedRatingItem } from "survey-core";
import { BaseAngular } from "../../base-angular";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-rating-item-star",
  templateUrl: "./rating-item-star.component.html",
  styleUrls: ["../../hide-host.scss"],
})

export class RatingItemStarComponent extends BaseAngular {
  @Input() element: any;
  @Input() model!: QuestionRatingModel;
  @Input() item!: RenderedRatingItem;
  @Input() index!: number;

  onClick(event: any): void {
    this.model.setValueFromClick(event.target.value);
    event.stopPropagation();
  }

  getModel() {
    return this.model;
  }
}

AngularComponentFactory.Instance.registerComponent("sv-rating-item-star", RatingItemStarComponent);
<ng-template #template>
  <label [class]="model.getItemClass(item.itemValue, item.highlight)" (mouseover)="model.onItemMouseIn(item)" (mouseout)="model.onItemMouseOut(item)" (mousedown)="model.onMouseDown()">
    <input type="radio"
      class="sv-visuallyhidden"
      [attr.name]="model.questionName" [attr.id]="model.getInputId(index)" [value]="item.value" [attr.aria-required]="model.ariaRequired" [attr.aria-label]="model.ariaLabel" [attr.aria-invalid]="model.ariaInvalid" [attr.aria-errormessage]="model.ariaErrormessage"
      [disabled]="model.isDisabledAttr" [readonly]="model.isReadOnlyAttr" [checked]="model.value === item.value" (click)="onClick($event)"
      />
      <svg [iconName]="model.itemStarIcon" [size]="'auto'" [title]="item.text" [class]="'sv-star'" sv-ng-svg-icon></svg>
      <svg [iconName]="model.itemStarIconAlt" [size]="'auto'" [title]="item.text" [class]="'sv-star-2'" sv-ng-svg-icon></svg>
  </label>
</ng-template>
