// packages/survey-angular-ui/src/components/paneldynamic-actions/paneldynamic-add-btn.component.ts
import { Action, QuestionPanelDynamicModel } from "survey-core";
import { AngularComponentFactory } from "../../component-factory";
import { Component, Input } from "@angular/core";

@Component({
  selector: "",
  template: ""
})
export class PaneldynamicAction {
  @Input() data: any;
  @Input() model!: Action;
  public get question(): QuestionPanelDynamicModel {
    return (this.model && this.model.data.question) || this.data.question;
  }
}

@Component({
  selector: "sv-ng-paneldynamic-add-btn",
  templateUrl: "./paneldynamic-add-btn.component.html"
})
export class PanelDynamicAddBtn extends PaneldynamicAction {
  addPanelClick() {
    this.question.addPanelUI();
  }
}
AngularComponentFactory.Instance.registerComponent("sv-paneldynamic-add-btn", PanelDynamicAddBtn);
<button type="button" [id]="question.addButtonId" *ngIf="question.canAddPanel" [class]="question.getAddButtonCss()" [disabled]="!isActionEnabled" (click)="addPanelClick()">
<span [class]="question.cssClasses.buttonAddText"><sv-ng-string [model]="question.locAddPanelText"></sv-ng-string></span>
</button>

// packages/survey-vue3-ui/src/components/paneldynamic-actions/PaneldynamicAddBtn.vue
<template>
  <button
    type="button"
    :id="question.addButtonId"
    v-if="question.canAddPanel"
    :class="question.getAddButtonCss()"
    :disabled="!isActionEnabled"
    @click="addPanelClick"
  >
    <span :class="question.cssClasses.buttonAddText"
      ><SvComponent :is="'survey-string'" :locString="question.locAddPanelText"
    /></span>
  </button>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { type IPanelDynamicActionProps, usePanelDynamicAction, useIsAddActionEnabled } from "./action";

const props = defineProps<IPanelDynamicActionProps>();
const question = usePanelDynamicAction(props);
const isActionEnabled = useIsAddActionEnabled(props);
const addPanelClick = () => {
  if (!isActionEnabled.value) return;
  question.value.addPanelUI();
};
</script>
