// packages/survey-angular-ui/src/components/renderAs/boolean-radio/boolean-radio.component.ts

import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { QuestionBooleanModel, RendererFactory } from "survey-core";

@Component({
  selector: "sv-ng-boolean-radio-question",
  templateUrl: "./boolean-radio.component.html"
})
export class BooleanRadioComponent {
  @Input() model!: QuestionBooleanModel;
}

AngularComponentFactory.Instance.registerComponent("boolean-radio-question", BooleanRadioComponent);
RendererFactory.Instance.registerRenderer(
  "boolean",
  "radio",
  "boolean-radio-question"
);

<div [class]="model.cssClasses.rootRadio" (keydown)="model.onKeyDownCore($event)">
  <fieldset role="presentation" [class]="model.cssClasses.radioFieldset">
    <sv-ng-boolean-radio-item *ngIf="model.swapOrder" [value]="model.getValueTrue()" [locText]="model.locLabelTrue" [question]="model" ></sv-ng-boolean-radio-item>
    <sv-ng-boolean-radio-item  [value]="model.getValueFalse()" [locText]="model.locLabelFalse" [question]="model" ></sv-ng-boolean-radio-item>
    <sv-ng-boolean-radio-item *ngIf="!model.swapOrder" [value]="model.getValueTrue()" [locText]="model.locLabelTrue" [question]="model" ></sv-ng-boolean-radio-item>
  </fieldset>
</div>

// packages/survey-vue3-ui/src/BooleanRadio.vue
<template>
  <div :class="question.cssClasses.rootRadio" ref="root" @keydown="(e) => question.onKeyDownCore(e)">
    <fieldset role="presentation" :class="question.cssClasses.radioFieldset">
      <SvComponent
        :is="'sv-boolean-radio-item'"
        v-if="question.swapOrder"
        :key="'true'"
        :question="question"
        :locText="question.locLabelTrue"
        :value="question.getValueTrue()"
      ></SvComponent>
      <SvComponent
        :is="'sv-boolean-radio-item'"
        :key="'false'"
        :question="question"
        :locText="question.locLabelFalse"
        :value="question.getValueFalse()"
      ></SvComponent>
      <SvComponent
        :is="'sv-boolean-radio-item'"
        v-if="!question.swapOrder"
        :key="'true'"
        :question="question"
        :locText="question.locLabelTrue"
        :value="question.getValueTrue()"
      ></SvComponent>
    </fieldset>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { RendererFactory } from "survey-core";
import { ref } from "vue";
import { useQuestion } from "./base";
import type { IBooleanProps } from "./boolean";
defineOptions({ inheritAttrs: false });
const root = ref(null);
const props = defineProps<IBooleanProps>();
useQuestion(props, root);
</script>

<script lang="ts">
RendererFactory.Instance.registerRenderer(
  "boolean",
  "radio",
  "sv-boolean-radio"
);
</script>
