// packages/survey-angular-ui/src/questions/boolean.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionBooleanModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-boolean-question",
  templateUrl: "./boolean.component.html"
})
export class BooleanQuestionComponent extends QuestionAngular<QuestionBooleanModel> {
  onChange(event: any) {
    this.model.booleanValue = event.target.value;
  }
}

AngularComponentFactory.Instance.registerComponent("boolean-question", BooleanQuestionComponent);
<div [class]="model.cssClasses.root" (keydown)="model.onKeyDownCore($event)" #contentElement>
    <label [class]="model.getItemCss()">
      <input
        type="checkbox"
        [attr.name]="model.name" [attr.id]="model.inputId" 
        [attr.role]="model.a11y_input_ariaRole"
        [attr.aria-required]="model.a11y_input_ariaRequired"
        [attr.aria-label]="model.a11y_input_ariaLabel"
        [attr.aria-labelledby]="model.a11y_input_ariaLabelledBy"
        [attr.aria-describedby]="model.a11y_input_ariaDescribedBy"
        [attr.aria-invalid]="model.a11y_input_ariaInvalid"
        [attr.aria-errormessage]="model.a11y_input_ariaErrormessage"
        [class]="model.cssClasses.control" [disabled]="model.isDisabledAttr" [readonly]="model.isReadOnlyAttr"  [indeterminate]="model.isIndeterminate" [value]="model.booleanValue" [(ngModel)]="model.booleanValue" />
      <div [class]="model.cssClasses.sliderGhost" (click)="model.onLabelClick($event, model.swapOrder)">
        <span [class]="model.getLabelCss(model.swapOrder)" [model]="model.locLabelLeft" sv-ng-string></span>
      </div>
      <div [class]="model.cssClasses.switch" (click)="model.onSwitchClickModel($event)">
        <span [class]="model.cssClasses.slider" [style.marginLeft]="model.thumbMargin">
            <span *ngIf="model.cssClasses.sliderText && model.isDeterminated" [class]="model.cssClasses.sliderText" [model]="model.getCheckedLabel()" sv-ng-string></span>
        </span>
      </div>
      <div [class]="model.cssClasses.sliderGhost" (click)="model.onLabelClick($event, !model.swapOrder)">
        <span [class]="model.getLabelCss(!model.swapOrder)" [model]="model.locLabelRight"  sv-ng-string></span>
      </div>
    </label>
</div>

// packages/survey-vue3-ui/src/Boolean.vue
<template>
  <div
    :class="question.cssClasses.root"
    ref="root"
    v-on:keydown="question.onKeyDownCore($event)"
  >
    <label :class="question.getItemCss()">
      <input
        type="checkbox"
        :name="question.name"
        :value="question.booleanValue ?? ''"
        v-model="question.booleanValue"
        :class="question.cssClasses.control"
        :id="question.inputId"
        :indeterminate.prop="question.isIndeterminate"
        :disabled="question.isDisabledAttr"
        :readonly="question.isReadOnlyAttr"
        :role="question.a11y_input_ariaRole"
        :aria-required="question.a11y_input_ariaRequired"
        :aria-label="question.a11y_input_ariaLabel"
        :aria-labelledby="question.a11y_input_ariaLabelledBy"
        :aria-describedby="question.a11y_input_ariaDescribedBy"
        :aria-invalid="question.a11y_input_ariaInvalid"
        :aria-errormessage="question.a11y_input_ariaErrormessage"
      />
      <div
        :class="question.cssClasses.sliderGhost"
        v-on:click="onLabelClick($event, question.swapOrder)"
      >
        <span :class="question.getLabelCss(question.swapOrder)"
          ><SvComponent
            :is="'survey-string'"
            :locString="question.locLabelLeft"
          />
        </span>
      </div>
      <div
        :class="question.cssClasses.switch"
        v-on:click="onSwitchClick($event)"
      >
        <span :class="question.cssClasses.slider">
          <span
            v-if="question.cssClasses.sliderText && question.isDeterminated"
            :class="question.cssClasses.sliderText"
          >
            <SvComponent
              :is="'survey-string'"
              :locString="question.getCheckedLabel()"
            ></SvComponent>
          </span>
        </span>
      </div>
      <div
        :class="question.cssClasses.sliderGhost"
        v-on:click="onLabelClick($event, !question.swapOrder)"
      >
        <span :class="question.getLabelCss(!question.swapOrder)"
          ><SvComponent
            :is="'survey-string'"
            :locString="question.locLabelRight"
        /></span>
      </div>
    </label>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import { useQuestion } from "./base";
import { ref } from "vue";
import type { IBooleanProps } from "./boolean";
defineOptions({ inheritAttrs: false });
const props = defineProps<IBooleanProps>();
const root = ref(null);
useQuestion(props, root);
const onLabelClick = (event: any, value: boolean) => {
  props.question.onLabelClick(event, value);
};
const onSwitchClick = (event: any) => {
  props.question.onSwitchClickModel(event);
};
</script>
