// packages/survey-angular-ui/src/questions/comment.component.ts
import { Component } from "@angular/core";
import { AngularComponentFactory } from "../component-factory";
import { QuestionAngular } from "../question";
import { QuestionCommentModel } from "survey-core";

@Component({
  templateUrl: "./comment.component.html",
  selector: "sv-ng-question-comment"
})

export class CommentQuestionComponent extends QuestionAngular<QuestionCommentModel> {
  onChange(event: any) {
    this.model.value = event.target.value;
  }
}
AngularComponentFactory.Instance.registerComponent("comment-question", CommentQuestionComponent);
<textarea
*ngIf="!model.isReadOnlyRenderDiv()"
[readonly]="model.isReadOnlyAttr"
[disabled]="model.isDisabledAttr"
[id]="model.inputId"
[attr.maxlength]="model.getMaxLength()"
[attr.cols]="model.cols"
[attr.rows]="model.rows"
[attr.placeholder]="model.renderedPlaceholder"
[class]="model.className"
[value]="model.value || null"
(input)="model.onInput($event)"
(keydown)="model.onKeyDown($event)"
(change)="onChange($event)"
(focus)="model.onFocus($event)"
(blur)="model.onBlur($event)"
[attr.aria-required]="model.a11y_input_ariaRequired"
[attr.aria-label]="model.a11y_input_ariaLabel"
[attr.aria-labelledby]="model.a11y_input_ariaLabelledBy"
[attr.aria-describedby]="model.a11y_input_ariaDescribedBy"
[attr.aria-invalid]="model.a11y_input_ariaInvalid"
[attr.aria-errormessage]="model.a11y_input_ariaErrormessage"
[style.resize]="model.resizeStyle"
#contentElement></textarea>
<sv-ng-character-counter *ngIf="!model.isReadOnlyRenderDiv() && model.getMaxLength()" 
[counter]="model.characterCounter"
[remainingCharacterCounter]="model.cssClasses.remainingCharacterCounter">
</sv-ng-character-counter>
<div *ngIf="model.isReadOnlyRenderDiv()" #contentElement>{{ model.value }}</div>

// packages/survey-vue3-ui/src/Comment.vue
<template>
  <textarea
    ref="root"
    v-if="!question.isReadOnlyRenderDiv() && !question.getMaxLength()"
    :readonly="question.isReadOnlyAttr"
    :disabled="question.isDisabledAttr"
    :value="question.value"
    :id="question.inputId"
    :maxlength="question.getMaxLength()"
    :cols="question.cols"
    :rows="question.rows"
    :placeholder="question.renderedPlaceholder"
    :class="question.className"
    @change="change"
    @input="
      (e) => {
        question.onInput(e);
      }
    "
    @keydown="
      (e) => {
        question.onKeyDown(e);
      }
    "
    :aria-required="question.a11y_input_ariaRequired"
    :aria-label="question.a11y_input_ariaLabel"
    :aria-labelledby="question.a11y_input_ariaLabelledBy"
    :aria-describedby="question.a11y_input_ariaDescribedBy"
    :aria-invalid="question.a11y_input_ariaInvalid"
    :aria-errormessage="question.a11y_input_ariaErrormessage"
    v-bind:style="{ resize: question.resizeStyle }"
  ></textarea>
  <div
    ref="root"
    v-else-if="!question.isReadOnlyRenderDiv() && question.getMaxLength()"
  >
    <textarea
      :readonly="question.isReadOnlyAttr"
      :disabled="question.isDisabledAttr"
      :value="question.value"
      :id="question.inputId"
      :maxlength="question.getMaxLength()"
      :cols="question.cols"
      :rows="question.rows"
      :placeholder="question.renderedPlaceholder"
      :class="question.className"
      @change="change"
      @input="
        (e) => {
          question.onInput(e);
        }
      "
      @keydown="
        (e) => {
          question.onKeyDown(e);
        }
      "
      :aria-required="question.a11y_input_ariaRequired"
      :aria-label="question.a11y_input_ariaLabel"
      :aria-labelledby="question.a11y_input_ariaLabelledBy"
      :aria-describedby="question.a11y_input_ariaDescribedBy"
      :aria-invalid="question.a11y_input_ariaInvalid"
      :aria-errormessage="question.a11y_input_ariaErrormessage"
      v-bind:style="{ resize: question.resizeStyle }"
    ></textarea>
    <SurveyVueComponent
      :name="'sv-character-counter'"
      :counter="question.characterCounter"
      :remainingCharacterCounter="question.cssClasses.remainingCharacterCounter"
    ></SurveyVueComponent>
  </div>
  <div ref="root" v-else>{{ question.value }}</div>
</template>

<script lang="ts" setup>
import SurveyVueComponent from "@/SurveyVueComponent.vue";
import type { QuestionCommentModel } from "survey-core";
import { useQuestion } from "./base";
import { ref } from "vue";
defineOptions({ inheritAttrs: false });
const props = defineProps<{
  question: QuestionCommentModel;
  css?: object;
}>();
const root = ref(null);
useQuestion(props, root);
const change = (event: any) => {
  const question = props.question;
  question.value = event.target.value;
};
</script>
