// packages/survey-angular-ui/src/questions/dropdown.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { AngularComponentFactory } from "../component-factory";
import { QuestionDropdownModel } from "survey-core";

@Component({
  selector: "sv-ng-dropdown-question",
  templateUrl: "./dropdown.component.html"
})
export class DropdownQuestionComponent extends QuestionAngular<QuestionDropdownModel> {
}

AngularComponentFactory.Instance.registerComponent("dropdown-question", DropdownQuestionComponent);
<div [class]="model.renderCssRoot" #contentElement>
  <sv-ng-dropdown [model]="model"></sv-ng-dropdown>
  <div *ngIf="model.isShowingChoiceComment" [class]="model.getCommentAreaCss(true)" [question]="model" [item]="model.selectedItem" sv-ng-comment-choice></div>
</div>

// packages/survey-vue3-ui/src/Dropdown.vue
<template>
  <div :class="question.renderCssRoot" ref="root">
    <SvComponent :is="'sv-dropdown'" :question="question"></SvComponent>
    <SvComponent
      :is="'survey-other-choice'"
      v-if="isShowingChoiceComment"
      :question="question"
      :item="selectedItem"
    />
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { QuestionDropdownModel } from "survey-core";
import { useQuestion } from "./base";
import { computed, ref } from "vue";
defineOptions({ inheritAttrs: false });
const props = defineProps<{ question: QuestionDropdownModel }>();
const root = ref(null);
useQuestion(props, root);
const selectedItem = computed(() => props.question.selectedItem );
const isShowingChoiceComment = computed(() => props.question.isShowingChoiceComment);
</script>
