// packages/survey-angular-ui/src/questions/image.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionImageModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-image-question",
  templateUrl: "./image.component.html"
})
export class ImageQuestionComponent extends QuestionAngular<QuestionImageModel> {}

AngularComponentFactory.Instance.registerComponent("image-question", ImageQuestionComponent);
<div [class]="model.cssClasses.root" #contentElement>
  <img
    *ngIf="model.renderedMode === 'image'"
    [visible]="!!model.locImageLink.renderedHtml && !model.contentNotLoaded"
    [class]="model.getImageCss()"
    [attr.src]="model.locImageLink.renderedHtml"
    [attr.alt]="model.altText || model.title"
    [attr.width]="model.renderedWidth"
    [attr.height]="model.renderedHeight"
    [style]="{ objectFit: model.imageFit,  width: model.renderedStyleWidth, height: model.renderedStyleHeight }"
    (load)="model.onLoadHandler()"
    (error)="model.onErrorHandler()"
  /><video
    controls
    *ngIf="model.renderedMode === 'video'"
    [visible]="!!model.locImageLink.renderedHtml && !model.contentNotLoaded"
    [class]="model.getImageCss()"
    [attr.src]="model.locImageLink.renderedHtml"
    [attr.width]="model.renderedWidth"
    [attr.height]="model.renderedHeight"
    [style]="{ objectFit: model.imageFit,  width: model.renderedStyleWidth, height: model.renderedStyleHeight }"
    (loadedmetadata)="model.onLoadHandler()"
    (error)="model.onErrorHandler()"
  ></video>
  <iframe
    *ngIf="model.renderedMode === 'youtube'"
    [class]="model.getImageCss()"
    [attr.src]="model.locImageLink.renderedHtml | safeResourceUrl"
    [attr.width]="model.renderedWidth"
    [attr.height]="model.renderedHeight"
    [attr.title]="model.renderedAltText"
    [style]="{ objectFit: model.imageFit,  width: model.renderedStyleWidth, height: model.renderedStyleHeight }"
    ></iframe>
    <div *ngIf="!model.locImageLink.renderedHtml || model.contentNotLoaded" [class]="model.cssClasses.noImage">
      <svg [iconName]="model.cssClasses.noImageSvgIconId" [size]="48" sv-ng-svg-icon></svg>
    </div>
</div>

// packages/survey-vue3-ui/src/Image.vue
<template>
  <div :class="question.cssClasses.root" ref="root">
    <img
      v-if="question.renderedMode === 'image'"
      v-show="imageLink && !question.contentNotLoaded"
      :class="question.getImageCss()"
      :src="imageLink"
      :alt="question.altText || question.title"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      :style="{
        objectFit: question.imageFit as any,
        width: question.renderedStyleWidth,
        height: question.renderedStyleHeight,
      }"
      @load="
        (event) => {
          question.onLoadHandler();
        }
      "
      @error="
        (event) => {
          question.onErrorHandler();
        }
      "
    /><video
      controls
      v-if="question.renderedMode === 'video'"
      v-show="imageLink && !question.contentNotLoaded"
      :class="question.getImageCss()"
      :src="imageLink"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      v-bind:style="{
        objectFit: question.imageFit as any,
        width: question.renderedStyleWidth,
        height: question.renderedStyleHeight,
      }"
      @loadedmetadata="
        (event) => {
          question.onLoadHandler();
        }
      "
      @error="
        (event) => {
          question.onErrorHandler();
        }
      "
    ></video>
    <iframe
      v-if="question.renderedMode === 'youtube'"
      :class="question.getImageCss()"
      :src="imageLink"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      :style="{
        objectFit: question.imageFit as any,
        width: question.renderedStyleWidth,
        height: question.renderedStyleHeight,
      }"
    ></iframe>
    <div
      v-if="!imageLink || question.contentNotLoaded"
      :class="question.cssClasses.noImage"
    >
      <sv-svg-icon
        :iconName="question.cssClasses.noImageSvgIconId"
        :size="48"
      ></sv-svg-icon>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { QuestionImageModel } from "survey-core";
import { useLocString, useQuestion } from "./base";
import { ref } from "vue";
const props = defineProps<{ question: QuestionImageModel }>();
const root = ref(null);
useQuestion(props, root);
const imageLink = useLocString(() => props.question.locImageLink);
</script>
