// packages/survey-react-ui/src/image.tsx
import * as React from "react";
import { SurveyQuestionElementBase } from "./reactquestion_element";
import { QuestionImageModel } from "survey-core";
import { ReactQuestionFactory } from "./reactquestion_factory";
import { SvgIcon } from "./components/svg-icon/svg-icon";

export class SurveyQuestionImage extends SurveyQuestionElementBase {
  constructor(props: any) {
    super(props);
  }
  componentDidMount() {
    super.componentDidMount();
    this.question.locImageLink.onChanged = () => {
      this.forceUpdate();
    };
  }
  componentWillUnmount() {
    super.componentWillUnmount();
    this.question.locImageLink.onChanged = () => { };
  }

  protected get question(): QuestionImageModel {
    return this.questionBase as QuestionImageModel;
  }

  protected renderElement(): React.JSX.Element {
    var cssClasses = this.question.getImageCss();
    var style: any = { objectFit: this.question.imageFit, width: this.question.renderedStyleWidth, height: this.question.renderedStyleHeight };
    if(!this.question.imageLink || this.question.contentNotLoaded) {
      style["display"] = "none";
    }
    var control: React.JSX.Element | null = null;
    if(this.question.renderedMode === "image") {
      control = (
        <img
          className={cssClasses}
          src={this.question.locImageLink.renderedHtml || null}
          alt={this.question.altText || this.question.title}
          width={this.question.renderedWidth}
          height={this.question.renderedHeight}
          //alt={item.text || item.value}
          style={style}
          onLoad={(event: any) => { this.question.onLoadHandler(); }}
          onError={(event: any) => { this.question.onErrorHandler(); }}
        />
      );
    }
    if(this.question.renderedMode === "video") {
      control = (
        <video controls
          className={cssClasses}
          src={this.question.locImageLink.renderedHtml}
          width={this.question.renderedWidth}
          height={this.question.renderedHeight}
          style={style}
          onLoadedMetadata={(event: any) => { this.question.onLoadHandler(); }}
          onError={(event: any) => { this.question.onErrorHandler(); }}
        ></video>
      );
    }
    if(this.question.renderedMode === "youtube") {
      control = (
        <iframe
          className={cssClasses}
          src={this.question.locImageLink.renderedHtml}
          width={this.question.renderedWidth}
          height={this.question.renderedHeight}
          style={style}
        ></iframe>
      );
    }
    var noImage: React.JSX.Element | null = null;
    if(!this.question.imageLink || this.question.contentNotLoaded) {
      noImage = (
        <div className={this.question.cssClasses.noImage}>
          <SvgIcon
            iconName={this.question.cssClasses.noImageSvgIconId}
            size={48}
          >
          </SvgIcon>
        </div>
      );
    }
    return <div className={this.question.cssClasses.root}>{control}{noImage}</div>;
  }
}

ReactQuestionFactory.Instance.registerQuestion("image", (props) => {
  return React.createElement(SurveyQuestionImage, props);
});

// packages/survey-vue3-ui/src/Image.vue
<template>
  <div :class="question.cssClasses.root" ref="root">
    <img
      v-if="question.renderedMode === 'image'"
      v-show="imageLink && !question.contentNotLoaded"
      :class="question.getImageCss()"
      :src="imageLink"
      :alt="question.altText || question.title"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      :style="{
        objectFit: question.imageFit as any,
        width: question.renderedStyleWidth,
        height: question.renderedStyleHeight,
      }"
      @load="
        (event) => {
          question.onLoadHandler();
        }
      "
      @error="
        (event) => {
          question.onErrorHandler();
        }
      "
    /><video
      controls
      v-if="question.renderedMode === 'video'"
      v-show="imageLink && !question.contentNotLoaded"
      :class="question.getImageCss()"
      :src="imageLink"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      v-bind:style="{
        objectFit: question.imageFit as any,
        width: question.renderedStyleWidth,
        height: question.renderedStyleHeight,
      }"
      @loadedmetadata="
        (event) => {
          question.onLoadHandler();
        }
      "
      @error="
        (event) => {
          question.onErrorHandler();
        }
      "
    ></video>
    <iframe
      v-if="question.renderedMode === 'youtube'"
      :class="question.getImageCss()"
      :src="imageLink"
      :width="question.renderedWidth"
      :height="question.renderedHeight"
      :style="{
        objectFit: question.imageFit as any,
        width: question.renderedStyleWidth,
        height: question.renderedStyleHeight,
      }"
    ></iframe>
    <div
      v-if="!imageLink || question.contentNotLoaded"
      :class="question.cssClasses.noImage"
    >
      <sv-svg-icon
        :iconName="question.cssClasses.noImageSvgIconId"
        :size="48"
      ></sv-svg-icon>
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { QuestionImageModel } from "survey-core";
import { useLocString, useQuestion } from "./base";
import { ref } from "vue";
const props = defineProps<{ question: QuestionImageModel }>();
const root = ref(null);
useQuestion(props, root);
const imageLink = useLocString(() => props.question.locImageLink);
</script>
