// packages/survey-angular-ui/src/questions/imagepicker.component.ts
import { Component, Input } from "@angular/core";
import { QuestionImagePickerModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-imagepicker-question",
  templateUrl: "./imagepicker.component.html"
})
export class ImagePickerQuestionComponent {
  @Input() model!: QuestionImagePickerModel;
}

AngularComponentFactory.Instance.registerComponent("imagepicker-question", ImagePickerQuestionComponent);
  <fieldset [class]="model.getSelectBaseRootCss()">
      <legend [attr.aria-label]="model.locTitle.renderedHtml" role="radio"></legend>
      <ng-container *ngIf="!model.hasColumns">
        <sv-ng-imagepicker-item *ngFor="let item of model.visibleChoices" [model]="item" [question]="model"></sv-ng-imagepicker-item>
      </ng-container>
      <ng-container *ngIf="model.hasColumns">
        <div *ngFor="let column of model.columns" [class]="model.getColumnClass()" role="presentation">
          <sv-ng-imagepicker-item *ngFor="let item of column" [model]="item" [question]="model"></sv-ng-imagepicker-item>
        </div>
      </ng-container>
  </fieldset>

// packages/survey-vue3-ui/src/Imagepicker.vue
<template>
  <fieldset :class="question.getSelectBaseRootCss()" ref="root">
    <legend
      role="radio"
      v-bind:aria-label="question.locTitle.renderedHtml"
    ></legend>
    <template v-if="!question.hasColumns">
      <survey-imagepicker-item
        v-for="item in question.visibleChoices"
        :key="item.value"
        :question="question"
        :item="item"
      ></survey-imagepicker-item>
    </template>
    <template v-if="question.hasColumns">
      <div
        v-for="(column, colIndex) in question.columns"
        :class="question.getColumnClass()"
        :key="colIndex"
        role="presentation"
      >
        <survey-imagepicker-item
          v-for="item in column"
          :key="item.value"
          :question="question"
          :item="item"
        ></survey-imagepicker-item>
      </div>
    </template>
  </fieldset>
</template>

<script lang="ts" setup>
import type { QuestionImagePickerModel } from "survey-core";
import { useQuestion } from "./base";
import { ref } from "vue";
const props = defineProps<{ question: QuestionImagePickerModel }>();
const root = ref(null);
useQuestion(props, root);
</script>
