// packages/survey-angular-ui/src/questions/imagemap.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionImageMapModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-imagemap-component",
  templateUrl: "./imagemap.component.html"
})
export class ImageMapQuestionComponent extends QuestionAngular<QuestionImageMapModel> {}

AngularComponentFactory.Instance.registerComponent("imagemap-question", ImageMapQuestionComponent);
<div
  [class]="model.cssClasses.root"
  #contentElement
  >

  <img [class]="model.cssClasses.background" [id]="'imagemap-' + model.id + '-background'" [src]="model.imageLink | safeUrl" role="presentation">
  <canvas [class]="model.cssClasses.canvas.preview" [id]="'imagemap-' + model.id + '-canvas-preview'"></canvas>
  <canvas [class]="model.cssClasses.canvas.hover" [id]="'imagemap-' + model.id + '-canvas-hover'"></canvas>
  <canvas [class]="model.cssClasses.canvas.selected" [id]="'imagemap-' + model.id + '-canvas-selected'"></canvas>
  <img
    [class]="model.cssClasses.map"
    [src]="model.imageLink | safeUrl"
    [useMap]="'#imagemap-' + model.id"
  />
  <map [name]="'imagemap-' + model.id"></map>

</div>

// packages/survey-vue3-ui/src/Imagemap.vue
<template>
  <div
    :class="question.cssClasses.root"
    ref="root"
  >
    <img :class="question.cssClasses.background" :id="`imagemap-${question.id}-background`" :src="question.imageLink" />
    <canvas :class="question.cssClasses.canvas.preview" :id="`imagemap-${question.id}-canvas-preview`"></canvas>
    <canvas :class="question.cssClasses.canvas.hover" :id="`imagemap-${question.id}-canvas-hover`"></canvas>
    <canvas :class="question.cssClasses.canvas.selected" :id="`imagemap-${question.id}-canvas-selected`"></canvas>
    <img
      :class="question.cssClasses.map"
      :src="question.imageLink"
      :useMap="`#imagemap-${question.id}`"
    />
    <map :name="`imagemap-${question.id}`"></map>
  </div>
</template>

<script setup lang="ts">
  import type { QuestionImageMapModel } from "survey-core";
  import { useQuestion } from "./base";
  import { ref } from "vue";
  defineOptions({
    inheritAttrs: false,
  });
  const props = defineProps<{
    question: QuestionImageMapModel;
  }>();
  const root = ref(null);
  useQuestion<QuestionImageMapModel>(props, root);
</script>
