// packages/survey-angular-ui/src/questions/multipletextrow.component.ts
import { MultipleTextCell, MultipleTextItemModel, MutlipleTextRow, QuestionMultipleTextModel, QuestionTextModel } from "survey-core";
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../base-angular";

@Component({
  selector: "sv-ng-multipletext-row",
  templateUrl: "./multipletextrow.component.html",
  styleUrls: ["../hide-host.scss"]
})
export class MultipleTextRowComponent extends BaseAngular<MutlipleTextRow> {
  @Input() question!: QuestionMultipleTextModel;
  @Input() model!: MutlipleTextRow;
  protected getModel(): MutlipleTextRow {
    return this.model;
  }
  trackItemBy (_: number, cell: MultipleTextCell): string {
    return "item" + cell.item.editor.id;
  }
}

<ng-template #template>
    <tr [class]="question.cssClasses.row" *ngIf="model.isVisible">
        <ng-container *ngFor="let cell of model.cells; trackBy: trackItemBy">
            <td [class]="cell.className" [question]="question" [model]="cell" sv-ng-multipletext-item></td>
        </ng-container>
    </tr>
</ng-template>

// packages/survey-vue3-ui/src/MultipleTextRow.vue
<template>
  <tr :class="question.cssClasses.row" v-if="row.isVisible">
    <td
      v-for="cell in row.cells"
      :key="'item' + cell.item.editor.id"
      :class="cell.className"
    >
      <SvComponent
        :is="'survey-multipletext-item'"
        :question="question"
        :cell="cell"
      ></SvComponent>
    </td>
  </tr>
</template>
<script lang="ts" setup>
import SvComponent from './SvComponent.vue';
import type { MutlipleTextRow, QuestionMultipleTextModel } from 'survey-core';
import { useBase } from './base';
const props = defineProps<{ question: QuestionMultipleTextModel, row: MutlipleTextRow }>()
useBase(() => props.row);
</script>
