// packages/survey-angular-ui/src/page.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnChanges, SimpleChanges, ViewChild } from "@angular/core";
import { PageModel, SurveyModel } from "survey-core";
import { BaseAngular } from "./base-angular";
@Component({
  selector: "page, sv-ng-page",
  templateUrl: "./page.component.html",
  styleUrls: ["./page.component.scss"]
  })
export class PageComponent extends BaseAngular<PageModel> {
  @Input() model!: PageModel;
  @Input() survey?: SurveyModel;
  @ViewChild("pageContainer", { static: false, read: ElementRef }) pageContainerRef!: ElementRef<HTMLDivElement>;
  protected getModel(): PageModel {
    return this.model;
  }
  protected override onModelChanged(): void {
    if(!!this.pageContainerRef && this.pageContainerRef.nativeElement) {
      this.model.survey.afterRenderPage(this.pageContainerRef.nativeElement);
    }
  }
  ngAfterViewInit(): void {
    this.model.survey?.afterRenderPage(this.pageContainerRef?.nativeElement);
  }
}
<ng-template #template>
  <ng-container *ngIf="!!this.survey && !!this.model && this.model.isVisible && !!this.model.survey">
    <div [class]="model.cssRoot" #pageContainer>
      <div *ngIf="model.hasTitle || model._showDescription" [class]="model.cssHeader">
        <sv-ng-element-title [element]="model"></sv-ng-element-title>
        <div *ngIf="model._showDescription" [class]="model.cssClasses.page?.description">
          <sv-ng-string [model]="model.locDescription"></sv-ng-string>
        </div>
      </div>
      <div [class]="model.cssContent">
        <div *ngIf="model.hasVisibleErrors" [element]="model" sv-ng-errors></div>
        <ng-container *ngFor="let row of model.visibleRows">
          <ng-template [component]="{ name: $any(model.survey).getRowWrapperComponentName(row), data: { componentData: $any(model.survey).getRowWrapperComponentData(row) } }">
            <sv-ng-row [row]="row"></sv-ng-row>
          </ng-template>
        </ng-container>
      </div>
    </div>
  </ng-container>  
</ng-template>

// packages/survey-vue3-ui/src/Page.vue
<template>
  <div :class="page.cssRoot" ref="root">
    <SurveyVueComponent
      :name="'survey-element-title'"
      :element="page"
      :css="css"
    />
    <div v-if="showDescription" :class="page.cssClasses.page.description">
      <SurveyVueComponent
        :name="'survey-string'"
        :locString="page.locDescription"
      />
    </div>
    <SurveyVueComponent :name="'survey-errors'" :element="page" />
    <template v-for="row in page.visibleRows" :key="row.id">
      <SurveyVueComponent
        :name="(page.getSurvey() as SurveyModel).getRowWrapperComponentName(row)"
        v-bind="{
            componentData: (page.getSurvey() as SurveyModel).getRowWrapperComponentData(row),
          }"
      >
        <SurveyVueComponent
          :name="'survey-row'"
          :row="row"
          :survey="survey"
          :css="css"
        >
        </SurveyVueComponent>
      </SurveyVueComponent>
    </template>
  </div>
</template>

<script lang="ts" setup>
import SurveyVueComponent from "@/SurveyVueComponent.vue";
import type { SurveyModel } from "survey-core";
import type { PageModel } from "survey-core";
import { computed, onMounted, ref } from "vue";
import { useBase } from "./base";

const props = defineProps<{
  survey: SurveyModel;
  page: PageModel;
  css?: object;
}>();

const root = ref<HTMLElement>(null as any);

const onAfterRender = () => {
  if (props.survey && root.value) {
    props.survey.afterRenderPage(root.value);
  }
};

const showDescription = computed(() => {
  return props.page._showDescription;
});

useBase(
  () => props.page,
  () => {
    onAfterRender();
  }
);

onMounted(() => {
  onAfterRender();
});
</script>
