// packages/survey-angular-ui/src/panel.component.ts
import { AfterViewInit, Component, ElementRef, Input, ViewChild } from "@angular/core";
import { PanelModel } from "survey-core";
import { BaseAngular } from "./base-angular";
import { AngularComponentFactory } from "./component-factory";
@Component({
  selector: "sv-ng-panel, '[sv-ng-panel]'",
  templateUrl: "./panel.component.html",
})
export class PanelComponent extends BaseAngular<PanelModel> implements AfterViewInit {
  @Input() model!: PanelModel;
  @ViewChild("panelContainer", { static: false, read: ElementRef }) panelContainerRef!: ElementRef<HTMLDivElement>;
  protected getModel(): PanelModel {
    return this.model;
  }
  ngAfterViewInit(): void {
    if(!!this.panelContainerRef?.nativeElement) {
      this.model.survey?.afterRenderPanel(this.model, this.panelContainerRef.nativeElement);
    }
  }
  trackRowBy = (_: any, row: any) => {
    return row.id;
  }
}
AngularComponentFactory.Instance.registerComponent("panel", PanelComponent);
<ng-template #template>
  <div *ngIf="!!model && model.isVisible" [attr.id]="model.id" [class]="model.getContainerCss()" (focusin)="model.focusIn()" #panelContainer>
    <div *ngIf="model.showErrorsAbovePanel && model.hasVisibleErrors" [element]="model" sv-ng-errors></div>
    <div *ngIf="model.hasDescription || model.hasTitle" [element]="model" sv-ng-element-header></div>
    <div *ngIf="!model.showErrorsAbovePanel && model.hasVisibleErrors" [element]="model" sv-ng-errors></div>
    <div *ngIf="model.renderedIsExpanded" [style.paddingLeft]="model.innerPaddingLeft" [class]="model.cssClasses.panel.content" [attr.id]="model.contentId">
      <ng-container *ngFor="let row of model.rows; trackBy: trackRowBy">
        <ng-template [component]="{ name: $any(model.survey).getRowWrapperComponentName(row), data: { componentData: $any(model.survey).getRowWrapperComponentData(row) } }">
          <sv-ng-row [row]="row"></sv-ng-row>
        </ng-template>
      </ng-container>
      <sv-ng-action-bar [model]="model.getFooterToolbar()"></sv-ng-action-bar>
    </div>
  </div>
</ng-template>

// packages/survey-vue3-ui/src/Panel.vue
<template>
  <div
    v-if="element.isVisible"
    :class="element.getContainerCss()"
    :id="element.id"
    @focusin="element.focusIn()"
    ref="root"
  >
    <survey-errors :element="element" v-if="element.showErrorsAbovePanel" />
    <survey-element-header
      v-if="element.hasTitle || element.hasDescription"
      :element="element"
      :css="css"
    ></survey-element-header>
    <survey-errors :element="element" v-if="!element.showErrorsAbovePanel" />
    <div
      :id="element.contentId"
      :style="{ paddingLeft: element.innerPaddingLeft }"
      v-if="element.renderedIsExpanded"
      :class="element.cssClasses.panel.content"
    >
      <template v-for="row in element.rows" :key="row.id">
        <component
          :is="(element.getSurvey() as SurveyModel).getRowWrapperComponentName(row)"
          v-bind="{
            componentData: (element.getSurvey() as SurveyModel).getRowWrapperComponentData(row),
          }"
        >
          <survey-row v-if="row.visible" :row="row" :survey="survey" :css="css">
          </survey-row>
        </component>
      </template>
      <sv-action-bar :model="element.getFooterToolbar()"></sv-action-bar>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>
<script lang="ts" setup>
import type { PanelModel, SurveyModel } from "survey-core";
import { ref, computed, onMounted } from "vue";
import { useBase } from "./base";
defineOptions({
  inheritAttrs: false,
});
const props = defineProps<{
  element: PanelModel;
  isEditMode?: boolean;
  css?: any;
}>();
const root = ref<HTMLElement>(null as any);
const survey = computed(() => props.element.survey);

useBase(() => props.element);

onMounted(() => {
  if (props.element.survey) {
    props.element.survey.afterRenderPanel(props.element, root.value);
  }
});
</script>
