// packages/survey-angular-ui/src/question.component.ts
import { Component, ElementRef, Input, ViewChild } from "@angular/core";
import { Question, SurveyElement } from "survey-core";
import { BaseAngular } from "./base-angular";
import { AngularComponentFactory } from "./component-factory";

@Component({
  selector: "sv-ng-question",
  templateUrl: "./question.component.html"
})
export class QuestionComponent {
  @Input() model!: Question;
  @ViewChild("elementContainer") rootEl?: ElementRef<HTMLDivElement>;
  ngAfterViewInit(): void {
    this.model.afterRender(this.rootEl?.nativeElement);
  }
}

AngularComponentFactory.Instance.registerComponent("question", QuestionComponent);
<ng-template #template>
  <div *ngIf="!!model" #elementContainer [class]="model.getRootCss()" [style]="model.getRootStyle()" [id]="model.id"
    [attr.data-name]="model.name" [attr.role]="model.ariaRole" [attr.aria-required]="model.ariaRequired"
    [attr.aria-invalid]="model.ariaInvalid" [attr.aria-label]="model.ariaLabel"
    [attr.aria-labelledby]="model.ariaLabelledBy" [attr.aria-describedby]="model.ariaDescribedBy"
    [attr.aria-expanded]="model.ariaExpanded">
    <sv-breadcrumbs
      *ngIf="model.singleInputHasActions"
      [model]="model.singleInputActions"
      [css]="model.cssClasses"
    ></sv-breadcrumbs>
    <div [class]="model.getQuestionContainerCss()">
      <div *ngIf="model.showErrorsAboveQuestion && model.hasVisibleErrors" [element]="model" sv-ng-errors></div>
      <div [class]="model.getHeaderAndContentContainerCss()">
        <div [element]="model" *ngIf="model.hasTitleOnLeftTop" sv-ng-element-header></div>
        <hr *ngIf="model.hasTitleOnLeftTop && model.isComplexQuestion" />
        <sv-single-input-summary
          *ngIf="!!model.singleInputSummary"
          [model]="model.singleInputSummary"
          [css]="model.cssClasses"
        ></sv-single-input-summary>
        <sv-ng-element
          *ngIf="!model.singleInputSummary && !!singleQuestion"
          [model]="singleQuestion"
        ></sv-ng-element>
        <ng-template
          *ngIf="!model.singleInputSummary && !singleQuestion"
          [component]="{ name: getQuestionContentWrapperComponentName(), data: getQuestionContentWrapperComponentData() }">
          <div [class]="model.cssContent" role="presentation" [visible]="model.renderedIsExpanded" [attr.aria-hidden]="model.contentAriaHidden" [attr.data-sv-drop-target-matrix-row]="model.dragDropMatrixAttribute" [attr.data-sv-drop-target-matrix]="model.dragDropMatrixAttribute">
            <ng-template
              [component]="{ name: getComponentName(), data: { model: model }, default: 'skeleton-question' }"></ng-template>
            <div *ngIf="model.hasComment" [class]="model.getCommentAreaCss(false)">
              <div [model]="model.locCommentText" sv-ng-string></div>
              <sv-ng-comment [question]="model"></sv-ng-comment>
            </div>
            <div *ngIf="model.hasDescriptionUnderInput" [class]="model.cssDescription" [attr.id]="model.ariaDescriptionId"
              [model]="model.locDescription" sv-ng-string></div>
          </div>
        </ng-template>
        <div [element]="model" *ngIf="model.hasTitleOnBottom" sv-ng-element-header></div>
      </div>
      <div *ngIf="model.showErrorsBelowQuestion && model.hasVisibleErrors" [element]="model" sv-ng-errors></div>
    </div>
  </div>
</ng-template>

// packages/survey-vue3-ui/src/Question.vue
<template>
  <div
    :class="element.getRootCss()"
    :style="getRootStyle()"
    ref="root"
    v-on:focusin="element.focusIn()"
    :id="element.id"
    :role="element.ariaRole"
    :aria-required="element.ariaRequired"
    :aria-invalid="element.ariaInvalid"
    :aria-label="element.ariaLabel"
    :aria-labelledby="element.ariaLabelledBy"
    :aria-describedby="element.ariaDescribedBy"
    :aria-expanded="element.ariaExpanded"
    :data-name="element.name"
  >
    <SvComponent
      :is="'sv-breadcrumbs'"
      v-if="element.singleInputHasActions"
      :model="element.singleInputActions"
      :css="element.cssClasses"
    />
    <div :class="element.getQuestionContainerCss()">
      <SvComponent
        :is="'survey-errors'"
        v-if="element.showErrorsAboveQuestion"
        :element="element"
        :location="'top'"
      />
      <div :class="element.getHeaderAndContentContainerCss()">
        <SvComponent
          :is="'survey-element-header'"
          v-if="element.hasTitleOnLeftTop"
          :element="element"
          :css="element.cssClasses"
        />
        <SvComponent
          :is="'sv-single-input-summary'"
          v-if="element.singleInputSummary"
          :css="element.cssClasses"
          :summary="element.singleInputSummary"
        ></SvComponent>
        <SvComponent
          :is="'survey-question'"
          v-else-if="singleQuestion"
          :css="css"
          :element="singleQuestion"
          :survey="survey"
          :key="(singleQuestion as any).id"
        ></SvComponent>
        <SvComponent
          v-else
          :is="contentComponentName"
          v-bind="contentComponentData"
        >
          <div
            :class="getContentClass(element) || undefined"
            :aria-hidden="element.contentAriaHidden"
            :style="{ display: !element.renderedIsExpanded ? 'none' : undefined }"
            role="presentation"
            :data-sv-drop-target-matrix="element.dragDropMatrixAttribute"
            :data-sv-drop-target-matrix-row="element.dragDropMatrixAttribute"
          >
            <SvComponent :is="componentName" :question="element" />
            <div v-if="element.hasComment" :class="element.getCommentAreaCss()">
              <div>
                <SvComponent
                  :is="'survey-string'"
                  :locString="element.locCommentText"
                />
              </div>
              <SvComponent :is="'survey-question-comment'" :question="element" />
            </div>
            <div
              v-if="element.hasDescriptionUnderInput"
              :class="element.cssDescription"
              :id="element.ariaDescriptionId"
            >
              <SvComponent
                :is="'survey-string'"
                :locString="element.locDescription"
              />
            </div>
          </div>
        </SvComponent>
        <SvComponent
          :is="'survey-element-header'"
          v-if="element.hasTitleOnBottom"
          :element="element"
          :css="css"
        />
      </div>
      <SvComponent
        :is="'survey-errors'"
        v-if="element.showErrorsBelowQuestion"
        :element="element"
        :location="'bottom'"
      />
    </div>
  </div>
</template>

<script lang="ts">
export default {
  inheritAttrs: false,
};
</script>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { SurveyModel, Question } from "survey-core";
import { useBase } from "./base";
import { computed, onUnmounted, ref, watch } from "vue";

const props = defineProps<{
  survey: SurveyModel;
  element: Question;
  css?: any;
}>();
const root = ref<HTMLElement>(null as any);
useBase(() => props.element);
const getContentClass = (element: Question) => {
  return element.cssContent;
};
const getRootStyle: () => any = () => props.element.getRootStyle();
const singleQuestion = computed(() => {
  return props.element.singleInputQuestion;
});

const afterRender = () => {
  if (root.value) {
    props.element.afterRender(root.value as HTMLElement);
  }
};
const stopWatch = watch(
  () => root.value,
  () => {
    afterRender();
  }
);
const componentName = computed(() => {
  if (props.element.customWidget) return "survey-customwidget";
  if (props.element.isDefaultRendering()) {
    return "survey-" + props.element.getTemplate();
  }
  return props.element.getComponentName();
});
const contentComponentName = computed(() => {
  return (
    props.element.survey as SurveyModel
  ).getQuestionContentWrapperComponentName(props.element);
});
const contentComponentData = computed(() => {
  return {
    componentData: {
      question: props.element,
      data: (
        props.element.survey as SurveyModel
      ).getElementWrapperComponentData(props.element),
    },
  };
});

onUnmounted(() => {
  stopWatch();
});
</script>
