// packages/survey-angular-ui/src/questions/radiogroup-item.component.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "sv-ng-radiogroup-item, '[sv-ng-radiogroup-item]'",
  templateUrl: "./radiogroup-item.component.html",
  styleUrls: ["./radiogroup-item.component.scss"]
})
export class RadiogroupItemComponent {
  @Input() question: any;
  @Input() model: any;
  @Input() ariaLabel?: string;
  constructor() {
  }
  public get renderedValue(): any {
    return this.question.renderedValue;
  }
  public set renderedValue(val: any) {
    this.question.clickItemHandler(this.model);
  }
}

<div role="presentation" [class]="question.getItemClass(model)">
  <label [class]="question.getLabelClass(model)" [attr.aria-label]="question.getAriaItemLabel(model)">
    <input type="radio" [name]="question.questionName" [id]="question.getItemId(model)" [attr.aria-describedby]="question.ariaDescribedBy" [class]="question.cssClasses.itemControl"
      [disabled]="!question.getItemEnabled(model)" [checked]="question.renderedValue" [(ngModel)]="question.value" [value]="model.value"
    />
    <span *ngIf="question.cssClasses.materialDecorator" [class]="question.cssClasses.materialDecorator">
      <svg *ngIf="question.itemSvgIcon" [class]="question.cssClasses.itemDecorator">
        <use data-bind="attr:{'xlink:href':question.itemSvgIcon}" xlink:href=''></use>
      </svg>
    </span>
    <span [class]="question.getControlLabelClass(model)" [style.visibility]="!model.hideCaption ? 'visible' : 'hidden'">
      <string-viewer [model]="model.locText"></string-viewer>
    </span>
  </label>
</div>

// packages/survey-vue3-ui/src/RadiogroupItem.vue
<template>
  <div role="presentation" :class="question.getItemClass(item)">
    <label @mousedown="question.onMouseDown()" :class="getLabelClass(item)">
      <input
        type="radio"
        :name="question.questionName"
        :value="item.value"
        :id="question.getItemId(item)"
        :aria-errormessage="question.ariaErrormessage"
        v-model="renderedValue"
        :disabled="!question.getItemEnabled(item)"
        :readonly="question.isReadOnlyAttr"
        :class="question.cssClasses.itemControl"
      /><span
        v-if="question.cssClasses.materialDecorator"
        :class="question.cssClasses.materialDecorator"
      >
        <svg
          v-if="question.itemSvgIcon"
          :class="question.cssClasses.itemDecorator"
        >
          <use :xlink:href="question.itemSvgIcon"></use>
        </svg> </span
      ><span v-if="!hideLabel" :class="getControlLabelClass(item)">
        <survey-string :locString="item.locText" />
      </span>
    </label>
  </div>
</template>

<script lang="ts" setup>
import type { ItemValue, QuestionRadiogroupModel } from "survey-core";
import { useBase } from "./base";
import { computed } from "vue";

defineOptions({ inheritAttrs: false });

const props = defineProps<{
  question: QuestionRadiogroupModel;
  item: ItemValue;
  hideLabel?: boolean;
}>();
const getLabelClass = (item: any) => {
  return props.question.getLabelClass(item);
};
const getControlLabelClass = (item: any) => {
  return props.question.getControlLabelClass(item);
};

const renderedValue = computed({
  get: () => props.question.renderedValue,
  set: (val) => {
    const question = props.question;
    question.renderedValue = val;
  },
});

useBase(() => props.item);
</script>
