// packages/survey-angular-ui/src/questions/ranking-item-content.component.ts
import { Component, Input } from "@angular/core";
import { ItemValue } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-ranking-item-content",
  templateUrl: "./ranking-item-content.component.html"
})
export class RankingItemContentComponent {
  @Input() item!: ItemValue;
  @Input() cssClasses: any;
}
AngularComponentFactory.Instance.registerComponent("sv-ng-ranking-item-content", RankingItemContentComponent);
<div [class]="cssClasses.controlLabel">
  <sv-ng-string [model]="item.locText"></sv-ng-string>
</div>

// packages/survey-vue3-ui/src/RankingItemContent.vue
<template>
  <div :class="cssClasses.controlLabel">
    <survey-string :locString="item.locText" />
  </div>
</template>

<script lang="ts" setup>
import type { ItemValue } from "survey-core";
defineOptions({ inheritAttrs: false });
const props = defineProps<{
  item: ItemValue;
  cssClasses: any;
}>();
</script>
