// packages/survey-angular-ui/src/components/renderAs/rating-dropdown/rating-dropdown.component.ts

import { Component, Input } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { RendererFactory } from "survey-core";

@Component({
  selector: "sv-ng-rating-dropdown-question",
  templateUrl: "./rating-dropdown.component.html"
})
export class RatingDropdownComponent {
  @Input() model: any;
}

AngularComponentFactory.Instance.registerComponent("rating-dropdown-question", RatingDropdownComponent);
RendererFactory.Instance.registerRenderer(
  "rating",
  "dropdown",
  "rating-dropdown-question"
);

<div [class]="model.cssClasses.rootDropdown">
    <sv-ng-dropdown [model]="model"></sv-ng-dropdown>
</div>

// packages/survey-vue3-ui/src/RatingDropdown.vue
<template>
  <div :class="question.cssClasses.rootDropdown" ref="root">
    <sv-dropdown :question="question"></sv-dropdown>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { useQuestion } from "./base";
const props = defineProps<{ question: QuestionRatingModel }>();
const root = ref(null);
useQuestion(props, root);
</script>

<script lang="ts">
import { QuestionRatingModel, RendererFactory } from "survey-core";
RendererFactory.Instance.registerRenderer(
  "rating",
  "dropdown",
  "sv-rating-dropdown"
);
</script>
