// src/react/rating-dropdown.tsx
import * as React from "react";
import { QuestionRatingModel, RendererFactory } from "survey-core";
import { SurveyQuestionDropdownBase } from "./dropdown-base";
import { ReactQuestionFactory } from "./reactquestion_factory";

export class SurveyQuestionRatingDropdown extends SurveyQuestionDropdownBase<QuestionRatingModel> {
  constructor(props: any) {
    super(props);
  }
  protected renderElement(): JSX.Element {
    var cssClasses = this.question.cssClasses;
    var select = this.renderSelect(cssClasses);
    return (
      <div className={this.question.cssClasses.rootDropdown}>
        {select}
      </div>
    );
  }
}
ReactQuestionFactory.Instance.registerQuestion(
  "sv-rating-dropdown",
  (props) => {
    return React.createElement(SurveyQuestionRatingDropdown, props);
  }
);

RendererFactory.Instance.registerRenderer(
  "rating",
  "dropdown",
  "sv-rating-dropdown"
);

// packages/survey-vue3-ui/src/RatingDropdown.vue
<template>
  <div :class="question.cssClasses.rootDropdown" ref="root">
    <sv-dropdown :question="question"></sv-dropdown>
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { useQuestion } from "./base";
const props = defineProps<{ question: QuestionRatingModel }>();
const root = ref(null);
useQuestion(props, root);
</script>

<script lang="ts">
import { QuestionRatingModel, RendererFactory } from "survey-core";
RendererFactory.Instance.registerRenderer(
  "rating",
  "dropdown",
  "sv-rating-dropdown"
);
</script>
