// packages/survey-angular-ui/src/questions/selectbase.component.ts
import { Component, Input } from "@angular/core";
import { QuestionAngular } from "../question";
import { ItemValue, QuestionRadiogroupModel, QuestionSelectBase } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "['sv-ng-selectbase']",
  templateUrl: "./selectbase.component.html"
})
export class SelectBaseComponent<T extends QuestionSelectBase> extends QuestionAngular<T> {
  //#todo temp fix (CanClearButton should be placed in selectbase so it could work with imagepicker)
  @Input() override model!: any;

  public inputType: string = "checkbox";
  public showLegend: boolean = true;

  public getDefaultComponentName(): string {
    return "sv-ng-selectbase-item";
  }
  public trackItemBy(_: number, item: ItemValue): any {
    return item.value;
  }
  public trackColumnBy(index: number): any {
    return index;
  }

  public getItemValueComponentName(item: ItemValue): string {
    return this.model.getItemValueWrapperComponentName(item) || this.getDefaultComponentName();
  }
  public getItemValueComponentData(item: ItemValue): any {
    return {
      componentName: this.getDefaultComponentName(),
      componentData: {
        question: this.model,
        model: item,
        inputType: this.inputType,
        data: this.model.getItemValueWrapperComponentData(item)
      }
    };
  }
}

AngularComponentFactory.Instance.registerComponent("selectbase", SelectBaseComponent);
<fieldset [class]="model.getSelectBaseRootCss()" #contentElement 
  [attr.role]="model.a11y_input_ariaRole"
  [attr.aria-required]="model.a11y_input_ariaRequired"
  [attr.aria-label]="model.a11y_input_ariaLabel"
  [attr.aria-labelledby]="model.a11y_input_ariaLabelledBy"
  [attr.aria-describedby]="model.a11y_input_ariaDescribedBy"
  [attr.aria-invalid]="model.a11y_input_ariaInvalid"
  [attr.aria-errormessage]="model.a11y_input_ariaErrormessage"
>
  <legend *ngIf="showLegend" class="sv-hidden">{{model.locTitle.renderedHtml}}</legend>
  <ng-container *ngIf="model.hasHeadItems">
    <ng-container *ngFor="let item of model.headItems; trackBy: trackItemBy">
      <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
    </ng-container>
  </ng-container>
  <ng-container *ngIf="!model.hasColumns && !model.blockedRow">
    <ng-container *ngFor="let item of model.bodyItems; trackBy: trackItemBy" >
      <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
    </ng-container>
  </ng-container>
  <div [class]="model.cssClasses.rootRow" *ngIf="!model.hasColumns && model.blockedRow">
    <ng-container *ngFor="let item of model.dataChoices; trackBy: trackItemBy">
      <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
    </ng-container>
  </div>
  <ng-container *ngIf="model.hasColumns">
    <div [class]="model.cssClasses.rootMultiColumn">
      <div [class]="model.getColumnClass()" *ngFor="let column of model.columns; trackBy: trackColumnBy" role="presentation">
        <ng-container *ngFor="let item of column; trackBy: trackItemBy">
          <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
        </ng-container>
      </div>
    </div>
  </ng-container>
  <ng-container *ngIf="model.hasFootItems">
    <ng-container *ngFor="let item of model.footItems; trackBy: trackItemBy">
      <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item) }"></ng-template>
    </ng-container>
  </ng-container>
  <div *ngIf="model.isOtherSelected" [class]="model.getCommentAreaCss(true)" [question]="model" sv-ng-comment-other></div>
  <div *ngIf="model.showClearButtonInContent">
    <input
      type="button"
      (click)="model.clearValue(true)"
      [value]="model.clearButtonCaption"
      [class]="model.cssClasses.clearButton"
    />
  </div>
</fieldset>

// packages/survey-vue3-ui/src/SelectBase.vue
<template>
  <fieldset
    :class="question.getSelectBaseRootCss()"
    ref="root"
    :role="question.a11y_input_ariaRole"
    :aria-required="question.a11y_input_ariaRequired"
    :aria-label="question.a11y_input_ariaLabel"
    :aria-labelledby="question.a11y_input_ariaLabelledBy"
    :aria-describedby="question.a11y_input_ariaDescribedBy"
    :aria-invalid="question.a11y_input_ariaInvalid"
    :aria-errormessage="question.a11y_input_ariaErrormessage"
  >
    <legend v-if="showLegend" class="sv-hidden">
      {{ question.locTitle.renderedHtml }}
    </legend>
    <template v-if="question.hasHeadItems">
      <SvComponent
        v-for="item in question.headItems"
        :key="item.value"
        :name="getItemValueComponentName(item)"
        v-bind="getItemValueComponentData(item)"
      ></SvComponent>
    </template>
    <template v-if="!question.hasColumns && !question.blockedRow">
      <SvComponent
        v-for="item in question.bodyItems"
        :key="item.value"
        :name="getItemValueComponentName(item)"
        v-bind="getItemValueComponentData(item)"
      ></SvComponent>
    </template>
    <div :class="question.cssClasses.rootRow" v-if="question.blockedRow">
      <template v-if="!question.hasColumns && question.blockedRow">
        <SvComponent
          v-for="item in question.dataChoices"
          :key="item.value"
          :name="getItemValueComponentName(item)"
          v-bind="getItemValueComponentData(item)"
        ></SvComponent>
      </template>
    </div>
    <div
      v-if="question.hasColumns"
      :class="question.cssClasses.rootMultiColumn"
    >
      <template v-if="question.hasColumns">
        <div
          v-for="(column, index) in question.columns"
          :key="index"
          :class="question.getColumnClass()"
          role="presentation"
        >
          <SvComponent
            v-for="item in column"
            :key="item.value"
            :name="getItemValueComponentName(item)"
            v-bind="getItemValueComponentData(item)"
          ></SvComponent>
        </div>
      </template>
    </div>
    <template v-if="question.hasFootItems">
      <SvComponent
        v-for="item in question.footItems"
        :key="item.value"
        :name="getItemValueComponentName(item)"
        v-bind="getItemValueComponentData(item)"
      ></SvComponent>
    </template>
    <SvComponent
      :name="'survey-other-choice'"
      v-if="question.renderedValue && question.isOtherSelected"
      :question="question"
    />
    <div v-if="question.showClearButtonInContent">
      <input
        type="button"
        :class="question.cssClasses.clearButton"
        v-on:click="
          () => {
            question.clearValue(true);
          }
        "
        :value="question.clearButtonCaption"
      />
    </div>
  </fieldset>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type {
  ItemValue,
  QuestionCheckboxModel,
  QuestionRadiogroupModel,
} from "survey-core";
import { useQuestion } from "./base";
import { ref } from "vue";
defineOptions({
  inheritAttrs: false,
});
const props = defineProps<{
  question: QuestionRadiogroupModel | QuestionCheckboxModel;
  showLegend?: boolean;
}>();
const root = ref(null);
useQuestion(props, root);

const getItemValueComponentName = (item: ItemValue) => {
  return (
    props.question.getItemValueWrapperComponentName(item) ||
    props.question.itemComponent
  );
};

const getItemValueComponentData = (item: ItemValue) => {
  return {
    componentName: props.question.itemComponent,
    componentData: {
      question: props.question,
      item,
      data: props.question.getItemValueWrapperComponentData(item),
    },
  };
};
</script>
