// packages/survey-angular-ui/src/questions/text.component.ts
import { Component, Input } from "@angular/core";
import { QuestionAngular } from "../question";
import { QuestionTextModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-text-question",
  templateUrl: "./text.component.html",
  styleUrls: ["./text.component.scss"]
})
export class TextQuestionComponent extends QuestionAngular<QuestionTextModel> {
  keyup(event: any) {
    if (this.model.isInputTextUpdate) {
      this.model.value = event.target.value;
    }
  }
  onChange(event: any) {
    if(!this.model.isInputTextUpdate) {
      this.model.value = event.target.value;
    }
  }
}

AngularComponentFactory.Instance.registerComponent("text-question", TextQuestionComponent);
  <input *ngIf="!model.dataListId && !model.isInputTextUpdate && !model.isReadOnlyRenderDiv()"
    [disabled]="model.isInputReadOnly" [style]="model.inputStyle" [class]="model.getControlClass()"
    [(value)]="model.value" [type]="model.inputType" [id]="model.inputId" [placeholder]="model.renderedPlaceHolder"
    data-bind="attr: {size: question.renderedInputSize, maxLength: question.getMaxLength(), min: question.renderedMin, max: question.renderedMax, step: question.renderedStep, 'aria-required': question.ariaRequired, 'aria-label': question.ariaLabel, 'aria-invalid': question.ariaInvalid, 'aria-describedby': question.ariaDescribedBy, autoComplete: question.autoComplete, list:question.dataListId}"
  />
  <input *ngIf="!model.dataListId && model.isInputTextUpdate && !model.isReadOnlyRenderDiv()"
    [disabled]="model.isInputReadOnly" [style]="model.inputStyle" [class]="model.getControlClass()"
    [(value)]="model.value" [type]="model.inputType" [id]="model.inputId" [placeholder]="model.renderedPlaceHolder"
    data-bind="attr: {size: question.renderedInputSize, maxLength: question.getMaxLength(), min: question.renderedMin, max: question.renderedMax, step: question.renderedStep, 'aria-required': question.ariaRequired, 'aria-label': question.ariaLabel, 'aria-invalid': question.ariaInvalid, 'aria-describedby': question.ariaDescribedBy, autoComplete: question.autoComplete, list:question.dataListId}"
  />
  <div *ngIf="model.dataListId && !model.isReadOnlyRenderDiv()">
    <input *ngIf="!model.isInputTextUpdate"
      [disabled]="model.isInputReadOnly" [style]="model.inputStyle" [class]="model.getControlClass()"
      [(value)]="model.value" [type]="model.inputType" [id]="model.inputId" [placeholder]="model.renderedPlaceHolder"
      data-bind="attr: {size: question.renderedInputSize, maxLength: question.getMaxLength(), min: question.renderedMin, max: question.renderedMax, step: question.renderedStep, 'aria-required': question.ariaRequired, 'aria-label': question.ariaLabel, 'aria-invalid': question.ariaInvalid, 'aria-describedby': question.ariaDescribedBy, autoComplete: question.autoComplete, list:question.dataListId}"
    />
    <input *ngIf="model.isInputTextUpdate"
      [disabled]="model.isInputReadOnly" [style]="model.inputStyle" [class]="model.getControlClass()"
      [(value)]="model.value" [type]="model.inputType" [id]="model.inputId" [placeholder]="model.renderedPlaceHolder"
      data-bind="attr: {size: question.renderedInputSize, maxLength: question.getMaxLength(), min: question.renderedMin, max: question.renderedMax, step: question.renderedStep, 'aria-required': question.ariaRequired, 'aria-label': question.ariaLabel, 'aria-invalid': question.ariaInvalid, 'aria-describedby': question.ariaDescribedBy, autoComplete: question.autoComplete, list:question.dataListId}"
    />
    <datalist [id]="model.dataListId">
      <option *ngFor="let dataListItem of model.dataList" [value]="dataListItem"></option>
    </datalist>
  </div>
  <div *ngIf="model.isReadOnlyRenderDiv()">{{ model.value }}</div>

// packages/survey-vue3-ui/src/Text.vue
<template>
  <div :class="question.getRootClass()" @click="question.onContainerClick($event)" ref="root">
    <div v-if="question.isReadOnlyRenderDiv()">
      {{ question.value }}
    </div>
    <template v-else>
      <input
        :disabled="question.isDisabledAttr"
        :readonly="question.isReadOnlyAttr"
        :class="question.getControlClass()"
        :type="question.inputType"
        :maxlength="question.getMaxLength()"
        :min="question.renderedMin"
        :max="question.renderedMax"
        :step="question.renderedStep"
        :size="question.renderedInputSize"
        :style="inputStyle"
        :id="question.inputId"
        :list="question.dataListId"
        :placeholder="question.renderedPlaceholder"
        :autocomplete="question.autocomplete"
        :value="question.inputValue"
        @change="question.onChange"
        @click="question.readOnlyBlocker"
        @pointerdown="question.readOnlyBlocker"
        @keyup="question.onKeyUp"
        @keydown="question.onKeyDown"
        @composition-update="question.onCompositionUpdate"
        @blur="question.onBlur"
        @focus="question.onFocus"
        :aria-required="question.a11y_input_ariaRequired"
        :aria-label="question.a11y_input_ariaLabel"
        :aria-labelledby="question.a11y_input_ariaLabelledBy"
        :aria-describedby="question.a11y_input_ariaDescribedBy"
        :aria-invalid="question.a11y_input_ariaInvalid"
        :aria-errormessage="question.a11y_input_ariaErrormessage"
      />
      <datalist v-if="question.dataListId" :id="question.dataListId">
        <option v-for="(item, index) in question.dataList" :key="index" :value="item"></option>
      </datalist>
      <SvComponent v-if="question.hasVisibleInputActions" :is="'sv-action-bar'" :model="question.inputActionsContainer"></SvComponent>
    </template>
  </div>
</template>

<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { QuestionTextModel } from "survey-core";
import { useQuestion } from "./base";
import { computed, ref } from "vue";
const props = defineProps<{ question: QuestionTextModel }>();
const root = ref<HTMLElement>(null as any);
defineOptions({
  inheritAttrs: false,
});
useQuestion<QuestionTextModel>(props, root);
const inputStyle = computed(() => props.question.inputStyle);
</script>
