// packages/survey-angular-ui/src/questions/ranking.component.ts
import { Component } from "@angular/core";
import { QuestionAngular } from "../question";
import { ItemValue, QuestionRankingModel } from "survey-core";
import { AngularComponentFactory } from "../component-factory";

@Component({
  selector: "sv-ng-ranking-question",
  templateUrl: "./ranking.component.html",
})
export class RankingQuestionComponent extends QuestionAngular<QuestionRankingModel> {
  trackItemBy = (index: number, item: ItemValue): string => {
    return item.value + "-" + index + "-item";
  }
}

AngularComponentFactory.Instance.registerComponent("ranking-question", RankingQuestionComponent);
<div *ngIf="!model.selectToRankEnabled" [class]="model.rootClass" #contentElement>
  <ng-container *ngFor="let item of model.renderedRankingChoices; index as index; trackBy: trackItemBy">
    <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item, index) }"></ng-template>
  </ng-container>
</div>

<div *ngIf="model.selectToRankEnabled" [class]="model.rootClass" #contentElement>
  <div [class]='model.getContainerClasses("from")' data-ranking="from-container">
    <ng-container *ngFor="let item of model.renderedUnRankingChoices; index as index; trackBy: trackItemBy">
      <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item, index, true) }"></ng-template>
    </ng-container>

    <div *ngIf="model.renderedUnRankingChoices.length === 0" [class]="model.cssClasses.containerPlaceholder" [model]="$any(model).locSelectToRankEmptyRankedAreaText" sv-ng-string></div>
  </div>

  <div [class]="model.cssClasses.containersDivider"></div>

  <div [class]='model.getContainerClasses("to")' data-ranking="to-container">
    <ng-container *ngFor="let item of model.renderedRankingChoices; index as index; trackBy: trackItemBy">
      <ng-template [component]="{ name: getItemValueComponentName(item), data: getItemValueComponentData(item, index) }"></ng-template>
    </ng-container>

    <div *ngIf="model.renderedRankingChoices.length === 0" [class]="model.cssClasses.containerPlaceholder" [model]="$any(model).locSelectToRankEmptyUnrankedAreaText" sv-ng-string></div>
  </div>
</div>

// src/vue/ranking/ranking.vue
<template>
  <div :class="question.rootClass">
    <survey-ranking-item v-if="!question.selectToRankEnabled" v-for="(item, index) in (question.renderedRankingChoices)"
      :key="item.value + '-' + index + '-item'" :class="question.getItemClass(item)" :text="item.locText" :index="index"
      :indexText="getNumberByIndex(index)" :cssClasses="question.cssClasses" :question="question"
      :item="item"></survey-ranking-item>

    <div v-if="question.selectToRankEnabled" :class='question.getContainerClasses("from")' data-ranking="from-container">
      <survey-ranking-item v-for="(item, index) in (question.renderedUnRankingChoices)" :key="item.value + '-' + index + '-item'"
        :class="question.getItemClass(item)" :text="item.locText" :index="index" :indexText="getNumberByIndex(index)"
        :cssClasses="question.cssClasses" :question="question" :item="item" :unrankedItem=true></survey-ranking-item>

      <div v-if="question.renderedUnRankingChoices.length === 0" :class="question.cssClasses.containerPlaceholder">
        <survey-string :locString="question.locSelectToRankEmptyRankedAreaText"></survey-string>
      </div>
    </div>

    <div v-if="question.selectToRankEnabled" :class="question.cssClasses.containersDivider"></div>

    <div v-if="question.selectToRankEnabled" :class='question.getContainerClasses("to")' data-ranking="to-container">
      <survey-ranking-item v-for="(item, index) in (question.renderedRankingChoices)" :key="item.value + '-' + index + '-item'"
        :class="question.getItemClass(item)" :text="item.locText" :index="index" :indexText="getNumberByIndex(index)"
        :cssClasses="question.cssClasses" :question="question" :item="item"></survey-ranking-item>

      <div v-if="question.renderedRankingChoices.length === 0" :class="question.cssClasses.containerPlaceholder">
        <survey-string :locString="question.locSelectToRankEmptyUnrankedAreaText"></survey-string>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import { Component } from "vue-property-decorator";
import { default as QuestionVue } from "../question";
import { QuestionRankingModel } from "survey-core";

@Component
export class Ranking extends QuestionVue<QuestionRankingModel> {
  getNumberByIndex(index: any) {
    return this.question.getNumberByIndex(index);
  }
}

Vue.component("survey-ranking", Ranking);
export default Ranking;
</script>
