// packages/survey-angular-ui/src/components/popup/popup-close-button.component.ts
import { Component, Input } from "@angular/core";
import { BaseAngular } from "../../base-angular";
import { PopupBaseViewModel } from "survey-core";
import { AngularComponentFactory } from "../../component-factory";

@Component({
  selector: "sv-ng-popup-close-button, '[sv-ng-popup-close-button]'",
  templateUrl: "./popup-close-button.component.html"
})

export class PopupCloseButtonComponent extends BaseAngular<PopupBaseViewModel> {
  @Input() model!: PopupBaseViewModel;

  get popupModel(): PopupBaseViewModel {
    return this.model as PopupBaseViewModel;
  }

  protected getModel(): PopupBaseViewModel {
    return this.model;
  }
}
AngularComponentFactory.Instance.registerComponent("popup-close-button", PopupCloseButtonComponent);
<button tabindex="-1" class="sv-popup__close-button sd-action sd-action--icon" (click)="popupModel.clickClose()">
  <svg class="sv-popup__close-button-icon" [iconName]="'icon-close-24x24'" [size]="'auto'" sv-ng-svg-icon></svg>
</button>

// packages/survey-vue3-ui/src/components/popup/PopupCloseButton.vue
<template>
  <button tabindex="-1" class="sv-popup__close-button sd-action sd-action--icon" @click="model.clickClose()">
    <SvComponent class="sv-popup__close-button-icon" :is="'sv-svg-icon'" iconName="icon-close-24x24" size="auto"/>
  </button>
</template>
<script lang="ts" setup>
import SvComponent from "@/SvComponent.vue";
import type { PopupBaseViewModel } from "survey-core";

defineProps<{
  model: PopupBaseViewModel;
}>();
</script>
