// packages/survey-react-ui/src/progress.tsx
import * as React from "react";
import { SurveyProgressModel, Base } from "survey-core";
import { SurveyNavigationBase } from "./reactSurveyNavigationBase";
import { ReactElementFactory } from "./element-factory";

export class SurveyProgress extends SurveyNavigationBase {
  constructor(props: any) {
    super(props);
  }
  protected get isTop(): boolean {
    return this.props.isTop;
  }
  protected get model(): any {
    return this.props.model;
  }
  protected getStateElement(): Base | null {
    return this.model;
  }
  protected get progress(): number {
    return this.model.progressValue;
  }
  protected get progressText(): string {
    return this.model.progressText;
  }
  protected get progressBarAriaLabel(): string {
    return this.model.progressBarAriaLabel;
  }
  render(): React.JSX.Element {
    var progressStyle = {
      width: this.progress + "%",
    };
    return (
      <div className={this.model.getProgressCssClasses(this.props.container)}>
        <div
          style={progressStyle}
          className={this.model.css.progressBar}
          role="progressbar"
          aria-valuemin={0}
          aria-valuemax={100}
          aria-label={this.progressBarAriaLabel}
        >
          <span
            className={SurveyProgressModel.getProgressTextInBarCss(this.model.css)}
          >
            {this.progressText}
          </span>
        </div>
        <span
          className={SurveyProgressModel.getProgressTextUnderBarCss(this.model.css)}
        >
          {this.progressText}
        </span>
      </div>
    );
  }
}

ReactElementFactory.Instance.registerElement("sv-progress-pages", props => {
  return React.createElement(SurveyProgress, props);
});
ReactElementFactory.Instance.registerElement("sv-progress-questions", props => {
  return React.createElement(SurveyProgress, props);
});
ReactElementFactory.Instance.registerElement(
  "sv-progress-correctquestions",
  props => {
    return React.createElement(SurveyProgress, props);
  }
);
ReactElementFactory.Instance.registerElement(
  "sv-progress-requiredquestions",
  props => {
    return React.createElement(SurveyProgress, props);
  }
);

// packages/survey-angular-ui/src/components/progress/default/progress.component.ts
import { ChangeDetectorRef, Component, Input, ViewContainerRef } from "@angular/core";
import { AngularComponentFactory } from "../../../component-factory";
import { SurveyProgressModel } from "survey-core";
import { BaseAngular } from "../../../base-angular";

@Component({
  selector: "sv-ng-progress-default",
  templateUrl: "./progress.component.html"
})
export class ProgressDefaultComponent extends BaseAngular {
  @Input() container?: string;
  @Input() model: any;
  constructor(changeDetectorRef: ChangeDetectorRef, viewContainerRef?: ViewContainerRef) {
    super(changeDetectorRef, viewContainerRef);
  }
  protected getModel() {
    return this.model;
  }
  getProgressTextInBarCss(css: any): string {
    return SurveyProgressModel.getProgressTextInBarCss(css);
  }
  getProgressTextUnderBarCss(css: any): string {
    return SurveyProgressModel.getProgressTextUnderBarCss(css);
  }
}
AngularComponentFactory.Instance.registerComponent("sv-progress-progress", ProgressDefaultComponent);
AngularComponentFactory.Instance.registerComponent("sv-progress-pages", ProgressDefaultComponent);
AngularComponentFactory.Instance.registerComponent("sv-progress-questions", ProgressDefaultComponent);
AngularComponentFactory.Instance.registerComponent("sv-progress-correctquestions", ProgressDefaultComponent);
AngularComponentFactory.Instance.registerComponent("sv-progress-requiredquestions", ProgressDefaultComponent);
<ng-template #template>
  <div [class]="model.getProgressCssClasses(container)">
    <div [class]="model.css.progressBar" [style.width]="model.progressValue + '%'"
        role="progressbar" aria-valuemin="0" aria-valuemax="100" [attr.aria-label]="model.progressBarAriaLabel">
        <span [class]="getProgressTextInBarCss(model.css)">
          {{ model.progressText }}
        </span>
    </div>
    <span [class]="getProgressTextUnderBarCss(model.css)"> {{  model.progressText }} </span>
  </div>
</ng-template>
